import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));const root=path.resolve(here,'..');
const html=fs.readFileSync(path.join(root,'prototype','index.html'),'utf8');
const js=fs.readFileSync(path.join(root,'prototype','app.js'),'utf8');
const ui=fs.readFileSync(path.join(root,'prototype','phase31-ui.js'),'utf8');
const css=fs.readFileSync(path.join(root,'prototype','maintenance-v1.css'),'utf8');
const simple=fs.readFileSync(path.join(root,'prototype','maintenance-v1.4-simple.css'),'utf8');
const sw=fs.readFileSync(path.join(root,'prototype','sw.js'),'utf8');
const failures=[];
for(const token of ['maintenance-v1.css','id="processGateBox"','id="preStepBox"','id="choiceGate"','id="wrongCard"'])if(!html.includes(token))failures.push(`index missing ${token}`);
if(!js.includes("$('processGateBox')?.classList.remove('hidden')"))failures.push('process gate is not opened in question card');
if(js.includes("function startProcessGate(){processGateDone=false;stepIndex=0;$('stepBox')"))failures.push('legacy hidden-parent process gate bug remains');
for(const token of ['@media (max-width:699px)','@media (min-width:700px) and (max-width:1099px)','@media (min-width:1400px)','.choiceGate','.processGateBox'])if(!css.includes(token))failures.push(`responsive css missing ${token}`);
for(const token of ['maintenance-v1.4-simple.css','compactDecisionSteps','one-core-check','확인문제 풀기'])if(!ui.includes(token))failures.push(`simple UI logic missing ${token}`);
for(const token of ['#wrongCard.hidden','one screen, one question, one current action','grid-template-columns:minmax(0,1fr) minmax(0,.92fr)','jkResultCorrect','jkResultWrong'])if(!simple.includes(token))failures.push(`simple CSS missing ${token}`);
if(!sw.includes("VERSION='maintenance-v1.4.0'"))failures.push('service worker cache version is not v1.4.0');
console.log(JSON.stringify({status:failures.length?'FAIL':'PASS',checks:18,failures},null,2));if(failures.length)process.exit(1);
