(async()=>{'use strict';
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 try{await JK_AUTH.requireRole('admin')}catch(e){console.warn(e);return}
 await JK_STORAGE.init();const seed=JK_PHASE26_DATA.approvalSeed,manifest=JK_DATA.bankManifest||{bankVersion:'26.0',learnerQuestionRecordCount:4951,allFamilyCount:1438};
 let approvals=await JK_STORAGE.listQualityApprovals(),draft=approvals[0]?.payload||JK_PHASE26.seedDraft(seed),baseline=null,difficultySet=null,syntheticPreview=false;
 const actionLabel={keep_representative:'대표 가족 유지',intentional_repeat:'의도적 반복 유지',review_only:'복습·처방 전용',disable:'학습자 출제 비활성화',approve:'제안 승인',reject:'제안 반려',hold:'보류'};
 function metric(label,value){return `<div class="metric"><b>${esc(value)}</b><span>${esc(label)}</span></div>`}
 async function saveDraft(message='검토안을 저장했습니다.'){
   draft.updatedAt=new Date().toISOString();const saved=await JK_STORAGE.saveQualityApproval({approvalId:draft.draftId,status:draft.status,payload:draft,createdAt:draft.createdAt,updatedAt:draft.updatedAt});
   $('applyStatus').textContent=message;return saved;
 }
 function renderTop(){const p=JK_PHASE26.reviewProgress(draft,seed);$('metrics').innerHTML=[metric('중복 결정',`${p.duplicateDone}/${p.duplicateTotal}`),metric('개념 결정',`${p.conceptDone}/${p.conceptTotal}`),metric('전체 진행',`${p.totalDone}/${p.total}`),metric('스냅샷',(window._snapshots||[]).length),metric('기준선',baseline?.status||'NOT_COLLECTED'),metric('실측 데이터',baseline?.actualLearnerDataUsed?'있음':'없음')].join('');$('reviewBar').style.width=`${p.total?100*p.totalDone/p.total:0}%`;$('reviewStatus').textContent=p.complete?'모든 관리자 결정을 완료했습니다. 최종 적용 전에 스냅샷이 생성됩니다.':`남은 결정 ${p.total-p.totalDone}건 · 출제 정책에는 아직 반영되지 않습니다.`;$('applyPolicy').disabled=!p.complete}
 function renderDuplicates(){
  $('duplicates').innerHTML=seed.duplicateReviewFamilies.map(x=>{const d=draft.duplicateDecisions[x.familyId]||{};return `<div class="item"><div class="itemTop"><div><h3>${esc(x.familyId)} · ${esc(x.conceptId)}</h3><span class="pill ${d.status==='decided'?'ok':'warn'}">${d.status==='decided'?'결정됨':'승인 대기'}</span></div><select data-dup="${esc(x.familyId)}"><option value="">조치 선택</option>${x.allowedActions.map(a=>`<option value="${a}" ${d.action===a?'selected':''}>${actionLabel[a]}</option>`).join('')}</select></div><p>${esc(x.stem||'(원문 없음)')}</p><small>${esc((x.riskIds||[]).join(', '))}</small></div>`}).join('');
  document.querySelectorAll('[data-dup]').forEach(el=>el.onchange=()=>{if(!el.value)return;draft=JK_PHASE26.updateDuplicateDecision(draft,el.dataset.dup,el.value);renderAll()})
 }
 function renderConcepts(){
  $('concepts').innerHTML=seed.conceptBalanceProposals.map(x=>{const d=draft.conceptDecisions[x.conceptId]||{};return `<div class="item"><div class="itemTop"><div><h3>${esc(x.conceptName)}</h3><span class="pill ${x.representationStatus==='underrepresented'?'warn':'bad'}">${x.representationStatus==='underrepresented'?'과소대표':'과대표'} · ${x.coreFamilyCount}가족</span></div><select data-concept="${esc(x.conceptId)}"><option value="">결정 선택</option>${x.allowedActions.map(a=>`<option value="${a}" ${d.action===a?'selected':''}>${actionLabel[a]}</option>`).join('')}</select></div><p>${esc(x.rationale)} · 제안 가중치 ${x.proposedWeight}</p></div>`}).join('');
  document.querySelectorAll('[data-concept]').forEach(el=>el.onchange=()=>{if(!el.value)return;draft=JK_PHASE26.updateConceptDecision(draft,el.dataset.concept,el.value);renderAll()})
 }
 function renderSnapshots(){const rows=window._snapshots||[];$('snapshots').innerHTML=rows.length?`<table class="table"><thead><tr><th>생성</th><th>종류</th><th>ID</th></tr></thead><tbody>${rows.slice(0,8).map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString('ko-KR')}</td><td>${esc(x.kind)}</td><td>${esc(x.snapshotId)}</td></tr>`).join('')}</tbody></table>`:'<p class="note">저장된 스냅샷이 없습니다.</p>';const policy=JK_PHASE26.activePolicy();const count=Object.keys(policy.familyPolicies||{}).length+Object.keys(policy.conceptWeights||{}).length;$('policyStatus').textContent=count?`활성 정책 ${count}건`:'미적용';$('policyStatus').className=`pill ${count?'ok':''}`}
 function badgeClass(status){return ['READY_FOR_REVIEW','APPROVED_PERSONAL'].includes(status)?'ok':status==='PAUSED_INSUFFICIENT'?'bad':'warn'}
 function renderBaseline(){const b=baseline||{status:'NOT_COLLECTED',sufficientDays:0,requiredDays:7,progressPercent:0,observedDays:0,deduplication:{removed:0},days:[]};$('baselineBadge').textContent=b.status;$('baselineBadge').className=`pill ${badgeClass(b.status)}`;$('baselineBar').style.width=`${b.progressPercent||0}%`;$('baselineMetrics').innerHTML=[metric('충분한 Day',`${b.sufficientDays||0}/${b.requiredDays||7}`),metric('관찰 Day',b.observedDays||0),metric('진행률',`${b.progressPercent||0}%`),metric('중복 제거',b.deduplication?.removed||0),metric('기간',b.calendarSpanDays?`${b.calendarSpanDays}일`:'-'),metric('데이터 충분성',b.dataSufficient?'충분':'대기')].join('');$('baselineStatus').textContent=b.status==='NOT_COLLECTED'?'실제 학습 기록이 아직 없습니다. 초기 시뮬레이션 난이도를 유지합니다.':b.status==='READY_FOR_REVIEW'?'실제 7일 데이터가 충분합니다. 관리자가 기준선을 승인하면 개인 난이도 제안을 생성합니다.':b.status==='VALIDATION_ONLY_SYNTHETIC'?'검증용 합성 데이터 미리보기입니다. 실제 기준선으로 저장하거나 적용하지 않습니다.':b.status==='PAUSED_INSUFFICIENT'?'7일 이상 관찰되었으나 표본 또는 학습시간이 부족합니다. 부족 Day를 보완해야 합니다.':'기준선 수집 중입니다.';$('baselineDays').innerHTML=(b.days||[]).slice(-7).map(d=>`<div class="day ${d.sufficient?'good':'bad'}"><b>${esc(d.date)}</b><small>시도 ${d.attempts}</small><small>정확 ${Math.round(d.answerAccuracy)}% · 과정 ${Math.round(d.processPassRate)}%</small><small>${d.activeMinutes}분 · ${d.sufficient?'충분':'부족'}</small></div>`).join('')||'<p class="note">표시할 Day가 없습니다.</p>';$('approveBaseline').disabled=b.status!=='READY_FOR_REVIEW'||!b.actualLearnerDataUsed}
 function renderDifficulty(){const set=difficultySet?.payload||difficultySet||{proposals:[],status:'NOT_COLLECTED'},rows=set.proposals||[];const c=JK_PHASE26.expectedComparison(rows);$('comparison').innerHTML=[metric('제안 문항',c.proposalCount),metric('변경 전',c.averageBeforeSeconds?`${c.averageBeforeSeconds}초`:'-'),metric('변경 후',c.averageAfterSeconds?`${c.averageAfterSeconds}초`:'-'),metric('평균 변화',c.proposalCount?`${c.averageChangePercent}%`:'-'),metric('시간 단축',c.reducedCount),metric('시간 완화',c.increasedCount)].join('');$('difficultyRows').innerHTML=rows.length?rows.slice(0,80).map(p=>`<div class="item"><div class="itemTop"><div><h3>${esc(p.questionId)}</h3><span class="pill ${p.timeReductionAllowed?'ok':'warn'}">정확 ${p.answerAccuracy}% · 과정 ${p.processPassRate}%</span></div><select data-pd="${esc(p.proposalId)}"><option value="pending_admin" ${p.status==='pending_admin'?'selected':''}>승인 대기</option><option value="approved" ${p.status==='approved'?'selected':''}>승인</option><option value="rejected" ${p.status==='rejected'?'selected':''}>반려</option><option value="hold" ${p.status==='hold'?'selected':''}>보류</option></select></div><p>${p.before.targetSeconds}초 → ${p.proposed.targetSeconds}초 · ${esc(p.reason)}</p></div>`).join(''):'<p class="note">실제 7일 기준선 완료 전에는 제안이 없습니다.</p>';document.querySelectorAll('[data-pd]').forEach(el=>el.onchange=()=>{const p=rows.find(x=>x.proposalId===el.dataset.pd);if(p)p.status=el.value});$('approveDifficulty').disabled=!rows.length;$('difficultyStatus').textContent=set.status||'NOT_COLLECTED'}
 async function renderAudit(){const rows=await JK_STORAGE.listApprovalAudit();$('auditRows').innerHTML=rows.slice(0,40).map(x=>`<tr><td>${new Date(x.at).toLocaleString('ko-KR')}</td><td>${esc(x.type)}</td><td>${esc(x.entityId)}</td><td>${esc(x.payload?.note||x.payload?.status||'')}</td></tr>`).join('')||'<tr><td colspan="4">감사 이력이 없습니다.</td></tr>'}
 function renderAll(){renderTop();renderDuplicates();renderConcepts();renderSnapshots();renderBaseline();renderDifficulty()}
 async function analyzeActual(){const bundle=await JK_STORAGE.getDiagnosticBundle();syntheticPreview=false;baseline=JK_PHASE26.baselineState({events:bundle.events,sessions:bundle.sessions,reports:bundle.dailyReports,questions:JK_DATA.questions,actualLearnerData:true});await JK_STORAGE.saveBaselineRun({baselineId:baseline.baselineId,status:baseline.status,actualLearnerDataUsed:baseline.actualLearnerDataUsed,payload:baseline,updatedAt:new Date().toISOString()});renderAll()}
 function syntheticBundle(){const events=[],sessions=[],reports=[];for(let d=1;d<=7;d++){const date=`2026-08-${String(d).padStart(2,'0')}`,dayId=`DAY-${date}`,sid=`SYN-${d}`;sessions.push({sessionId:sid,dayId,deviceId:d%2?'tablet':'pc',startedAt:`${date}T09:00:00Z`,endedAt:`${date}T09:40:00Z`,totalActiveMs:2400000});reports.push({dayId,date,completedAt:`${date}T09:40:00Z`,activeMinutes:40,grammarMinutes:21,readingMinutes:18});for(let i=0;i<16;i++){const q=JK_DATA.questions[(d*17+i)%JK_DATA.questions.length];const event={eventId:`SYN-${d}-${i}`,sessionId:sid,dayId,deviceId:d%2?'tablet':'pc',type:'grading_result',questionId:q.id,conceptId:q.conceptId,answerCorrect:i%5!==0,methodScore:i%4===0?68:82,payload:{attemptNo:1,methodPass:i%4!==0,targetSeconds:60,elapsedSeconds:i%3===0?68:52,module:String(q.part).includes('READ')?'reading':'grammar'},timestamp:`${date}T09:${String(5+Math.floor(i/2)).padStart(2,'0')}:00Z`};events.push(event);if(i===0)events.push({...event,eventId:event.eventId,deviceId:'phone'})}events.push({eventId:`DONE-${d}`,sessionId:sid,dayId,type:'day_completed',timestamp:`${date}T09:40:00Z`,payload:{}})}return{events,sessions,reports}}
 $('saveDraft').onclick=async()=>{await saveDraft();await renderAudit()};$('snapshotNow').onclick=async()=>{const snap=JK_PHASE26.createSnapshot({draft,activePolicy:JK_PHASE26.activePolicy(),bankManifest:manifest,kind:'manual_pre_apply'});await JK_STORAGE.saveBankSnapshot(snap);await JK_STORAGE.appendApprovalAudit({type:'bank_snapshot_created',entityId:snap.snapshotId,payload:{note:'관리자 수동 스냅샷'}});window._snapshots=await JK_STORAGE.listBankSnapshots();renderAll();await renderAudit()};
 $('applyPolicy').onclick=async()=>{try{const pre=JK_PHASE26.createSnapshot({draft,activePolicy:JK_PHASE26.activePolicy(),bankManifest:manifest,kind:'pre_apply'});await JK_STORAGE.saveBankSnapshot(pre);const result=JK_PHASE26.applyApprovedDraft({draft,bankManifest:manifest,adminConfirmed:true});draft=result.draft;JK_PHASE26.saveActivePolicy(result.policy);await JK_STORAGE.saveBankSnapshot(result.snapshot);await saveDraft('정책을 적용했습니다. 자동 적용이 아니라 관리자 최종 승인으로 기록되었습니다.');await JK_STORAGE.appendApprovalAudit({type:'quality_policy_applied',entityId:'question-bank',payload:{status:'applied',note:`가족 정책 ${Object.keys(result.policy.familyPolicies).length}, 개념 가중치 ${Object.keys(result.policy.conceptWeights).length}`}});window._snapshots=await JK_STORAGE.listBankSnapshots();renderAll();await renderAudit()}catch(e){$('applyStatus').textContent=e.message}}
 $('rollbackLatest').onclick=async()=>{const rows=await JK_STORAGE.listBankSnapshots();const target=rows.find(x=>x.payload?.rollbackSupported||x.rollbackSupported);if(!target)return $('applyStatus').textContent='롤백할 스냅샷이 없습니다.';const source=target.payload||target;const restored=JK_PHASE26.rollbackSnapshot(source,true);draft=restored.draft||draft;JK_PHASE26.saveActivePolicy(restored.policy||{});await saveDraft(`스냅샷 ${target.snapshotId} 상태로 롤백했습니다.`);await JK_STORAGE.appendApprovalAudit({type:'bank_snapshot_rolled_back',entityId:target.snapshotId,payload:{note:'관리자 확인 롤백'}});renderAll();await renderAudit()};
 $('refreshBaseline').onclick=analyzeActual;$('previewSynthetic').onclick=()=>{const x=syntheticBundle();syntheticPreview=true;baseline=JK_PHASE26.baselineState({...x,questions:JK_DATA.questions,actualLearnerData:false});renderAll()};
 $('approveBaseline').onclick=async()=>{if(baseline.status!=='READY_FOR_REVIEW'||!baseline.actualLearnerDataUsed)return;baseline={...baseline,status:'APPROVED_PERSONAL',approvedAt:new Date().toISOString()};await JK_STORAGE.saveBaselineRun({baselineId:baseline.baselineId,status:baseline.status,actualLearnerDataUsed:true,payload:baseline});const bundle=await JK_STORAGE.getDiagnosticBundle();const proposals=JK_PHASE26.generateDifficultyProposals({baseline:{...baseline,status:'READY_FOR_REVIEW'},events:bundle.events,questions:JK_DATA.questions,adminApprovedBaseline:true});difficultySet=await JK_STORAGE.saveDifficultyProposalSet({proposalSetId:`PDSET-${Date.now()}`,status:proposals.status,actualLearnerDataUsed:true,payload:proposals});await JK_STORAGE.appendApprovalAudit({type:'baseline_approved',entityId:baseline.baselineId,payload:{status:'APPROVED_PERSONAL',note:`실제 ${baseline.sufficientDays}일 기준선 승인`}});renderAll();await renderAudit()};
 $('approveDifficulty').onclick=async()=>{const set=difficultySet?.payload||difficultySet;if(!set?.proposals?.length)return;const approved=set.proposals.filter(x=>x.status==='approved');for(const p of approved)if(p.proposed.targetSeconds<p.before.targetSeconds&&!p.timeReductionAllowed){p.status='rejected';p.guardrailViolation='accuracy_or_process_threshold'}set.status='ADMIN_REVIEWED';set.reviewedAt=new Date().toISOString();difficultySet=await JK_STORAGE.saveDifficultyProposalSet({proposalSetId:difficultySet.proposalSetId||`PDSET-${Date.now()}`,status:set.status,actualLearnerDataUsed:true,payload:set});await JK_STORAGE.appendApprovalAudit({type:'difficulty_proposals_reviewed',entityId:difficultySet.proposalSetId,payload:{status:set.status,note:`승인 ${set.proposals.filter(x=>x.status==='approved').length}건`}});renderAll();await renderAudit()};
 window._snapshots=await JK_STORAGE.listBankSnapshots();const savedBaseline=await JK_STORAGE.getBaselineRun();if(savedBaseline)baseline=savedBaseline.payload;const sets=await JK_STORAGE.listDifficultyProposalSets();if(sets.length)difficultySet=sets[0];if(!baseline)await analyzeActual();else renderAll();await renderAudit();
})();
