(async()=>{
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,deployChecks=[],qaRuns=[],recoveryRuns=[],baseline=null,defects=[];const matrix=JK_PHASE28_DATA.qaMatrix;
function unwrap(row){return row?.payload&&typeof row.payload==='object'?row.payload:row}
async function audits(){return (await JK_STORAGE.listApprovalAudit()).sort((a,b)=>Date.parse(b.at||b.createdAt)-Date.parse(a.at||a.createdAt))}
function status(el,value){if(!el)return;el.textContent=value;el.className=`status ${value}`}
function latestBy(rows,key){const map=new Map();for(const row of rows){const k=row?.[key];if(k&&!map.has(k))map.set(k,row)}return [...map.values()]}
function qaSummary(){return JK_PHASE28.summarizeQa(matrix,qaRuns)}
function blockerSummary(){return JK_PHASE32.summarizeBlockers(defects)}
function rehearsalSummary(){const qa=qaSummary(),rec=recoveryRuns[0]||{status:'RECOVERY_DRILL_NOT_RUN'},dep=deployChecks[0]||{status:'DEPLOYMENT_NOT_RUN'};return JK_PHASE32.rehearsalSummary({rehearsalPackage:JK_PHASE32_DATA.state.gates.rehearsalPackage,learningRegression:JK_PHASE32_DATA.state.gates.learningRegression,featureFreeze:JK_PHASE32_DATA.state.featureFreeze,deployment:dep.status,deviceQa:qa.status,recoveryDrill:rec.status,pwaExternalInstall:JK_PHASE32_DATA.state.gates.pwaExternalInstall,assistiveTechnology:JK_PHASE32_DATA.state.gates.assistiveTechnology,performanceDevice:JK_PHASE32_DATA.state.gates.performanceDevice,defects})}
function renderTop(){const qa=qaSummary();const rec=recoveryRuns[0]||{status:'RECOVERY_DRILL_NOT_RUN'};const dep=deployChecks[0]||{status:'DEPLOYMENT_NOT_RUN'};status($('deployBadge'),dep.status);status($('qaBadge'),qa.status);status($('recoveryBadge'),rec.status);status($('baselineBadge'),baseline?.status||'NOT_COLLECTED');$('deployTop').textContent=dep.status==='PASS'?'PASS':'대기';$('qaTop').textContent=`${qa.completed}/${qa.total}`;$('recoveryTop').textContent=rec.status==='PASS'?'PASS':'대기';$('baselineTop').textContent=baseline?.status==='READY_FOR_REVIEW'?'검토 가능':`${baseline?.sufficientDays||0}/5`;}
function renderRehearsal(){const summary=rehearsalSummary(),qa=qaSummary(),rec=recoveryRuns[0]||{status:'RECOVERY_DRILL_NOT_RUN'},dep=deployChecks[0]||{status:'DEPLOYMENT_NOT_RUN'},block=blockerSummary();const map={preflight:dep.status==='DEPLOYMENT_NOT_RUN'?'NOT_RUN':dep.status,backup:rec.backupId?'IN_PROGRESS':'NOT_RUN',deploy:dep.status,'device-qa':qa.status,restore:rec.status,gate:block.releaseBlocking?'BLOCKED':summary.allExternalPass?'PASS':'NOT_RUN'};status($('rehearsalBadge'),summary.status);$('rehearsalSteps').innerHTML=JK_PHASE32_DATA.policy.singlePath.map(step=>`<div class="stepRow"><span class="stepNo">${step.order}</span><div><strong>${esc(step.label)}</strong><div class="note">증거: ${esc(step.requiredEvidence.join(' · '))}</div></div><span class="status ${esc(map[step.id]||step.status)}">${esc(map[step.id]||step.status)}</span></div>`).join('');$('rehearsalMessage').textContent=summary.status==='READY_FOR_EXTERNAL_REHEARSAL'?'실행 패키지는 준비되었습니다. 외부 증거가 수집될 때까지 생산 승인 상태가 아닙니다.':summary.status==='BLOCKED'?'P0·P1 차단 결함을 먼저 해결해야 합니다.':summary.status;}
function renderDeploy(){const dep=deployChecks[0]||JK_PHASE28_DATA.initialState.deployment;$('baseUrl').value=dep.baseUrl||state.settings.cloudEndpoint||'';$('deployMessage').textContent=dep.status==='PASS'?'외부 도메인 검증이 통과했습니다.':dep.status==='FAIL'?'일부 필수 검증이 실패했습니다.':'외부 URL과 실제 운영 맥락이 없어 DEPLOYMENT_NOT_RUN입니다.';$('deployChecks').innerHTML=(dep.checks||[]).map(c=>`<div class="check ${c.ok?'ok':'bad'}"><span>${esc(c.id)}<br><small>${esc(c.detail)}</small></span><b>${c.ok?'PASS':'FAIL'}</b></div>`).join('')||'<div class="check"><span>실행 기록 없음</span><b>NOT_RUN</b></div>'}
function renderBaseline(){baseline=baseline||JK_PHASE28.evaluateBaselineReadiness(Object.values(state.dailyReports||{}));$('observedDays').textContent=baseline.calendarDaysObserved||0;$('sufficientDays').textContent=baseline.sufficientDays||0;$('baselineProgress').style.width=`${Math.min(100,(baseline.sufficientDays||0)/5*100)}%`;$('baselineDays').innerHTML=(baseline.days||[]).map(d=>`<div class="day ${d.sufficient?'good':''}"><b>${esc(d.date.slice(5))}</b><span>${d.sufficient?'충분':'부족'}<br>${d.activeMinutes}분 · ${d.attempts}문항</span></div>`).join('')||'<div class="note">실제 일일 결과가 없습니다.</div>';$('baselineAlerts').innerHTML=(baseline.alerts||[]).map(a=>`<div class="alert"><b>${esc(a.code)}</b><br>${esc(a.message)}</div>`).join('')||'<div class="note">현재 자료 충분성 알림이 없습니다.</div>'}
function recommendedEvidenceName(){const value=$('qaCell').value||'';const [platformId,scenarioId]=value.split('::');return JK_PHASE32.evidenceFileName({date:new Date().toISOString(),platformId,scenarioId,sequence:1,extension:'png'})}
function refreshEvidencePreview(){if($('evidenceNamePreview'))$('evidenceNamePreview').value=recommendedEvidenceName()}
function renderQa(){const sum=qaSummary();$('qaCompleted').textContent=`${sum.completed}/${sum.total}`;$('qaPass').textContent=sum.counts.PASS||0;$('qaFail').textContent=sum.counts.FAIL||0;$('qaCritical').textContent=sum.allCriticalPass?'PASS':'미완료';const p=Object.fromEntries(matrix.platforms.map(x=>[x.id,x])),s=Object.fromEntries(matrix.scenarios.map(x=>[x.id,x]));$('qaRows').innerHTML=sum.cells.map(c=>`<tr><td>${esc(p[c.platformId]?.label||c.platformId)}</td><td><button class="cellBtn" data-cell="${esc(c.cellId)}"><strong>${esc(s[c.scenarioId]?.title||c.scenarioId)}</strong><small>${esc(c.scenarioId)}</small></button></td><td>${esc(s[c.scenarioId]?.priority||'')}</td><td><span class="status ${esc(c.status)}">${esc(c.status)}</span></td><td>${c.executedAt?`${esc(c.deviceModel)} · ${esc(c.osVersion)}<br><small>${esc(c.tester)} · ${esc(c.executedAt)}</small>`:'<small>실행 기록 없음</small>'}</td></tr>`).join('');$('qaCell').innerHTML=sum.cells.map(c=>`<option value="${esc(c.cellId)}">${esc(p[c.platformId]?.label)} · ${esc(s[c.scenarioId]?.title)}</option>`).join('');document.querySelectorAll('.cellBtn').forEach(b=>b.onclick=()=>{$('qaCell').value=b.dataset.cell;loadQaCell(b.dataset.cell)});loadQaCell($('qaCell').value)}
function loadQaCell(cellId){const latest=qaSummary().cells.find(x=>x.cellId===cellId)||{};$('qaStatus').value=['PASS','FAIL','BLOCKED','NOT_RUN'].includes(latest.status)?latest.status:'NOT_RUN';$('deviceModel').value=latest.deviceModel||'';$('osVersion').value=latest.osVersion||'';$('browserVersion').value=latest.browserVersion||'';$('tester').value=latest.tester||'';$('executedAt').value=(latest.executedAt||'').slice(0,16);$('physicalDevice').value=String(Boolean(latest.physicalDeviceUsed));$('stylusUsed').value=String(Boolean(latest.stylusUsed));$('observedResult').value=latest.observedResult||'';$('qaEvidence').value=(latest.evidence||[]).join('\n');refreshEvidencePreview()}
function renderRecovery(){const r=recoveryRuns[0]||{status:'RECOVERY_DRILL_NOT_RUN'};$('recoveryMessage').textContent=r.status==='PASS'?`복원 훈련 통과 · RTO ${r.rtoMinutes?.toFixed?.(1)||r.rtoMinutes}분`:r.status==='FAIL'?`복원 훈련 실패 · 누락: ${(r.missingEvidence||[]).join(', ')}`:'실제 백업으로 복원 훈련을 수행하지 않았습니다.'}
function renderBlockers(){const sum=blockerSummary();status($('blockerBadge'),sum.status);$('defectTotal').textContent=sum.total;$('defectOpen').textContent=sum.open;$('defectBlocking').textContent=sum.releaseBlocking;$('defectP2').textContent=sum.unresolvedP2;const selected=$('defectRecord').value;$('defectRecord').innerHTML='<option value="">새 결함</option>'+sum.rows.map(d=>`<option value="${esc(d.defectId)}">${esc(d.defectId)} · ${esc(d.severity)} · ${esc(d.status)}</option>`).join('');if(selected&&sum.rows.some(d=>d.defectId===selected))$('defectRecord').value=selected;$('defectList').innerHTML=sum.rows.map(d=>`<div class="defect"><div class="defectTop"><strong>${esc(d.defectId)} · ${esc(d.title||'제목 없음')}</strong><span class="status ${esc(d.status)}">${esc(d.severity)} · ${esc(d.status)}</span></div><div class="note">${esc(d.platformId||'-')} / ${esc(d.scenarioId||'-')} · 담당 ${esc(d.owner||'-')}</div></div>`).join('')||'<div class="note">등록된 결함이 없습니다.</div>'}
function clearDefectForm(){for(const id of ['defectId','defectScenario','defectPlatform','defectOwner','defectTitle','defectReproduction','defectFixRef','defectReverifyEvidence','defectReverifiedBy','defectNotes'])$(id).value='';$('defectSeverity').value='P2';$('defectStatus').value='OPEN';$('defectAcceptedRisk').value='false';$('defectReverifiedAt').value='';$('defectMessage').textContent=''}
function loadDefect(id){if(!id){clearDefectForm();return}const d=defects.find(x=>x.defectId===id);if(!d)return;$('defectId').value=d.defectId;$('defectSeverity').value=d.severity;$('defectStatus').value=d.status;$('defectScenario').value=d.scenarioId||'';$('defectPlatform').value=d.platformId||'';$('defectOwner').value=d.owner||'';$('defectAcceptedRisk').value=String(Boolean(d.acceptedRisk));$('defectTitle').value=d.title||'';$('defectReproduction').value=d.reproduction||'';$('defectFixRef').value=d.fixReference||'';$('defectReverifyEvidence').value=(d.reverifyEvidence||[]).join('\n');$('defectReverifiedBy').value=d.reverifiedBy||'';$('defectReverifiedAt').value=(d.reverifiedAt||'').slice(0,16);$('defectNotes').value=d.notes||'';$('defectMessage').textContent=`현재 상태: ${d.status}`}
async function load(){state=JK_STORAGE.getSnapshot();const rows=await audits();deployChecks=rows.filter(x=>x.type==='deployment_check_saved').map(unwrap);qaRuns=rows.filter(x=>x.type==='device_qa_result_saved').map(unwrap);recoveryRuns=rows.filter(x=>x.type==='recovery_drill_saved').map(unwrap);defects=latestBy(rows.filter(x=>x.type==='phase32_defect_saved').map(unwrap),'defectId');const br=(await JK_STORAGE.listBaselineRuns()).map(unwrap).find(x=>x.format==='JK_ENG_PHASE28_BASELINE_READINESS');baseline=br||JK_PHASE28.evaluateBaselineReadiness(Object.values(state.dailyReports||{}));renderTop();renderRehearsal();renderDeploy();renderBaseline();renderQa();renderRecovery();renderBlockers()}
async function remoteVerify(){const base=$('baseUrl').value.trim().replace(/\/$/,'');if(!base){$('deployMessage').textContent='운영 URL이 없어 DEPLOYMENT_NOT_RUN을 유지합니다.';return}let health={},integrity={},headers={},pwa={};try{const h=await fetch(`${base}/health`,{cache:'no-store'});headers=Object.fromEntries([...h.headers.entries()]);health=await h.json();const i=await fetch(`${base}/integrity`,{cache:'no-store'});integrity=await i.json();const [m,sw,a]=await Promise.all([fetch(`${base}/manifest.webmanifest`,{cache:'no-store'}),fetch(`${base}/sw.js`,{cache:'no-store'}),fetch(`${base}/asset-integrity-manifest-v50.json`,{cache:'no-store'})]);pwa={manifestOk:m.ok&&(await m.clone().json()).version==='50.0',manifestStatus:m.status,serviceWorkerOk:sw.ok&&/VERSION='50\.0'/.test(await sw.text()),serviceWorkerStatus:sw.status,assetManifestOk:a.ok&&(await a.json()).version==='50.0',assetManifestStatus:a.status}}catch(e){$('deployMessage').textContent=`원격 요청 실패: ${e.message}`}
const result=JK_PHASE32.evaluateDeploymentEvidence({baseUrl:base,health,integrity,headers,pwa,requiredSecurityHeaders:JK_PHASE28.policy.deployment?.requiredSecurityHeaders||{},externalNetworkUsed:$('externalNetwork').value==='true',actualCredentialsUsed:$('actualCredentials').value==='true',expectedManifestVersion:'50.0'});await JK_STORAGE.appendApprovalAudit({type:'deployment_check_saved',entityId:result.checkId,payload:result});await load()}
async function saveQa(){const [platformId,scenarioId]=$('qaCell').value.split('::');const raw={cellId:$('qaCell').value,platformId,scenarioId,status:$('qaStatus').value,deviceModel:$('deviceModel').value,osVersion:$('osVersion').value,browserVersion:$('browserVersion').value,tester:$('tester').value,executedAt:$('executedAt').value?new Date($('executedAt').value).toISOString():null,observedResult:$('observedResult').value,evidence:$('qaEvidence').value,physicalDeviceUsed:$('physicalDevice').value==='true',stylusUsed:$('stylusUsed').value==='true'};const evidence=JK_PHASE32.normalizeEvidenceRun(raw);const run=JK_PHASE28.normalizeQaRun({...raw,status:evidence.status});run.phase32Evidence=evidence;await JK_STORAGE.appendApprovalAudit({type:'device_qa_result_saved',entityId:run.cellId,payload:run});const missing=[...(evidence.missingEvidence||[]),...(evidence.invalidEvidenceNames||[]).map(x=>`명명규칙:${x}`)];$('qaMessage').textContent=evidence.status==='INCOMPLETE_EVIDENCE'?`PASS로 저장하지 않았습니다. 누락/오류: ${missing.join(', ')||'물리 기기 또는 스타일러스 증거'}`:'저장했습니다.';await load()}
async function saveRecovery(){const r=JK_PHASE28.evaluateRecoveryDrill({backupId:$('backupId').value,tester:$('recoveryTester').value,restoreStartedAt:$('restoreStarted').value?new Date($('restoreStarted').value).toISOString():null,restoreFinishedAt:$('restoreFinished').value?new Date($('restoreFinished').value).toISOString():null,sha256Verified:$('shaOk').value==='true',quickCheckOk:$('quickOk').value==='true',requiredTablesOk:$('tablesOk').value==='true',actualBackupUsed:$('actualBackup').value==='true',evidence:$('recoveryEvidence').value,notes:$('recoveryNotes').value});await JK_STORAGE.appendApprovalAudit({type:'recovery_drill_saved',entityId:r.drillId,payload:r});await load()}
async function refreshBaseline(){baseline=JK_PHASE28.evaluateBaselineReadiness(Object.values(state.dailyReports||{}));await JK_STORAGE.saveBaselineRun(baseline);await JK_STORAGE.appendApprovalAudit({type:'baseline_readiness_changed',entityId:baseline.baselineId,payload:{status:baseline.status,sufficientDays:baseline.sufficientDays,calendarDaysObserved:baseline.calendarDaysObserved,actualLearnerDataUsed:baseline.actualLearnerDataUsed,automaticDifficultyApplication:false}});await load()}
async function saveDefect(){const selected=$('defectRecord').value,target=$('defectStatus').value;const patch={defectId:$('defectId').value,severity:$('defectSeverity').value,title:$('defectTitle').value,scenarioId:$('defectScenario').value,platformId:$('defectPlatform').value,reproduction:$('defectReproduction').value,owner:$('defectOwner').value,fixReference:$('defectFixRef').value,reverifyEvidence:$('defectReverifyEvidence').value,reverifiedBy:$('defectReverifiedBy').value,reverifiedAt:$('defectReverifiedAt').value?new Date($('defectReverifiedAt').value).toISOString():null,acceptedRisk:$('defectAcceptedRisk').value==='true',notes:$('defectNotes').value};let record;if(!selected){if(target!=='OPEN'){$('defectMessage').textContent='새 결함은 OPEN으로 등록해야 합니다.';return}record=JK_PHASE32.normalizeDefect({...patch,status:'OPEN'})}else{const existing=defects.find(x=>x.defectId===selected);if(!existing){$('defectMessage').textContent='선택 결함을 찾지 못했습니다.';return}if(target===existing.status)record=JK_PHASE32.normalizeDefect({...existing,...patch,status:existing.status,createdAt:existing.createdAt});else{record=JK_PHASE32.transitionDefect(existing,target,patch);if(record.transitionError){$('defectMessage').textContent=`상태 변경 불가: ${record.transitionError}${record.missing?.length?' · '+record.missing.join(', '):''}`;return}}}await JK_STORAGE.appendApprovalAudit({type:'phase32_defect_saved',entityId:record.defectId,payload:record});$('defectMessage').textContent=`저장: ${record.defectId} · ${record.status}`;await load();$('defectRecord').value=record.defectId;loadDefect(record.defectId)}
function buildExport(){const dep=deployChecks[0]||JK_PHASE28_DATA.initialState.deployment,qa=qaSummary(),rec=recoveryRuns[0]||JK_PHASE28_DATA.initialState.recovery;return JK_PHASE32.exportPackage({deployment:dep,deviceQa:qa,recovery:rec,blockers:defects,baseline})}
function downloadJson(payload,name){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportOps(){downloadJson(buildExport(),`JK_ENG_RC2_Phase32_Rehearsal_${new Date().toISOString().slice(0,10)}.json`)}
async function copyEvidenceName(){const value=recommendedEvidenceName();try{await navigator.clipboard.writeText(value);$('qaMessage').textContent=`복사됨: ${value}`}catch(_){$('evidenceNamePreview').select();document.execCommand?.('copy');$('qaMessage').textContent=`권장 파일명: ${value}`}}
await JK_AUTH.requireRole('admin');state=await JK_STORAGE.init();$('runRemote').onclick=remoteVerify;$('saveQa').onclick=saveQa;$('qaCell').onchange=()=>loadQaCell($('qaCell').value);$('copyEvidenceName').onclick=copyEvidenceName;$('saveRecovery').onclick=saveRecovery;$('refreshBaseline').onclick=refreshBaseline;$('exportOps').onclick=exportOps;$('exportRehearsal').onclick=exportOps;$('saveDefect').onclick=saveDefect;$('defectRecord').onchange=()=>loadDefect($('defectRecord').value);await load();
})().catch(e=>{console.error(e);document.body.insertAdjacentHTML('beforeend',`<pre style="color:#b00;padding:20px">${String(e.message||e)}</pre>`)})
