(async function(){
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={snapshot:null,audits:[],importRecord:null,verification:null,executions:[],smokes:[],ops:[],incidents:[],evaluations:[],decisions:[]};
const sorted=rows=>(rows||[]).slice().sort((a,b)=>Date.parse(b.at||b.decidedAt||b.evaluatedAt||b.testedAt||b.executedAt||b.verifiedAt||b.recordedAt||0)-Date.parse(a.at||a.decidedAt||a.evaluatedAt||a.testedAt||a.executedAt||a.verifiedAt||a.recordedAt||0));
const rowsByType=type=>sorted(state.audits.filter(x=>x.type===type).map(x=>x.payload));const latest=rows=>rows?.[0]||null;
async function hashFile(file){const b=await file.arrayBuffer(),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function badgeClass(s){s=String(s||'');return /PASS|EXECUTED|STABLE|RECORDED|APPROVED/.test(s)?'pass':/FAIL|BLOCKED|ROLLBACK/.test(s)?'fail':/HOLD|INSUFFICIENT|REVIEW_REQUIRED/.test(s)?'warn':''}
function buildTestRows(containerId,defs,prefix){const root=$(containerId);if(!root)return;root.innerHTML=(defs||[]).map(d=>`<div class="smokeRow"><div><strong>${esc(d.id)}</strong><div class="note">${esc(d.label)}</div></div><select id="${prefix}Status_${esc(d.id)}"><option>NOT_RUN</option><option>PASS</option><option>FAIL</option></select><input id="${prefix}Evidence_${esc(d.id)}" placeholder="evidence reference"></div>`).join('')}
function readTests(defs,prefix){const out={};for(const d of defs||[])out[d.id]={status:$(`${prefix}Status_${d.id}`).value,evidence:$(`${prefix}Evidence_${d.id}`).value};return out}
function referenceMetricsFromHistory(){for(const type of ['phase39_confirmation30_saved','phase38_stabilization_saved','phase37_monthly_review_saved']){for(const row of rowsByType(type)){const m=row?.currentMetrics;if(m&&['answerAccuracy','processPassRate','recoveryRate','paceStability'].every(k=>Number.isFinite(Number(m[k]))))return m}}return null}
function setReferenceInputs(m){if(!m)return;for(const [id,k] of [['phase42RefAccuracy','answerAccuracy'],['phase42RefProcess','processPassRate'],['phase42RefRecovery','recoveryRate'],['phase42RefPace','paceStability']])if($(id)&&!$(id).value)$(id).value=Number(m[k])}
function getReferenceInputs(){return {answerAccuracy:Number($('phase42RefAccuracy').value),processPassRate:Number($('phase42RefProcess').value),recoveryRate:Number($('phase42RefRecovery').value),paceStability:Number($('phase42RefPace').value)}}
function render(){const v=state.verification||{status:'NOT_IMPORTED'},e=latest(state.executions)||{status:'V102_RELEASE_NOT_RUN'},s=latest(state.smokes)||{status:'V102_SMOKE_NOT_RUN'},z=latest(state.evaluations)||{status:'NOT_COLLECTED'},d=latest(state.decisions)||{status:'NOT_RECORDED'};for(const [id,val] of [['phase42InputBadge',v.status],['phase42RcBadge',v.rcGate?.status||'NOT_VERIFIED'],['phase42ReleaseBadge',e.status],['phase42SmokeBadge',s.status],['phase42StabilizationBadge',z.status],['phase42DecisionBadge',d.status]])if($(id)){ $(id).textContent=val;$(id).className=`status ${badgeClass(val)}` }
 if($('phase42SourceSha'))$('phase42SourceSha').textContent=v.bundleSha256||'-';if($('phase42PlanId'))$('phase42PlanId').textContent=v.rcGate?.planId||'-';if($('phase42StagingRunId'))$('phase42StagingRunId').textContent=v.candidateStaging?.runId||'-';if($('phase42CandidateIdentity'))$('phase42CandidateIdentity').textContent=v.candidateArtifactSha256||'-';if($('phase42ManifestIdentity'))$('phase42ManifestIdentity').textContent=v.assetManifestVersion?`${v.assetManifestVersion} / ${v.assetManifestSha256}`:'-';
 if(v.status==='PASS'){if($('phase42CandidateSha')&&!$('phase42CandidateSha').value)$('phase42CandidateSha').value=v.candidateArtifactSha256||'';if($('phase42ManifestVersion')&&!$('phase42ManifestVersion').value)$('phase42ManifestVersion').value=v.assetManifestVersion||'';if($('phase42ManifestSha')&&!$('phase42ManifestSha').value)$('phase42ManifestSha').value=v.assetManifestSha256||''}
 setReferenceInputs(referenceMetricsFromHistory());if($('phase42EvaluationResult'))$('phase42EvaluationResult').innerHTML=z?.evaluationId?`<div class="issue"><strong>${esc(z.status)}</strong><div class="note">learning ${esc(z.sufficientLearningDays||0)}d / ops ${esc(z.operationsDays||0)}d / P0·P1 ${esc(z.openP0P1||0)} / content mismatch ${esc(z.contentMismatchDays||0)} / asset fail ${esc(z.assetIdentityFailureDays||0)} / ${esc(z.recommendation||'')}</div></div>`:'<div class="note">실제 v1.0.2 출시·스모크·14일 실사용 증거가 있어야 평가됩니다.</div>';
 if($('phase42History'))$('phase42History').innerHTML=[...state.executions.slice(0,2),...state.evaluations.slice(0,2),...state.decisions.slice(0,2)].map(x=>`<div class="decisionRow"><div><strong>${esc(x.status||x.action)}</strong><div class="note">${esc(x.targetUrl||x.recommendation||x.reason||'')}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status||x.action)}</span></div>`).join('')||'<div class="note">No Phase 42 external record.</div>';if($('phase42Export'))$('phase42Export').disabled=!state.importRecord;
}
async function load(){state.snapshot=JK_STORAGE.getSnapshot();state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase42_phase41_rc_audit_import_saved')[0]||null;state.verification=state.importRecord?.verification||null;state.executions=rowsByType('phase42_v102_release_execution_saved');state.smokes=rowsByType('phase42_post_release_smoke_saved');state.ops=rowsByType('phase42_ops_snapshot_saved');state.incidents=rowsByType('phase42_incident_saved');state.evaluations=rowsByType('phase42_stabilization_saved');state.decisions=rowsByType('phase42_followup_decision_saved');render()}
async function verifyBundle(){const file=$('phase42BundleFile').files?.[0];if(!file){$('phase42ImportMessage').textContent='Phase 41 audit JSON을 선택하세요.';return}try{const bundle=JSON.parse(await file.text()),sha=await hashFile(file),verification=JK_PHASE42.verifyPhase41RcAuditBundle(bundle,{computedSha256:sha,expectedSha256:$('phase42ExpectedSha').value}),record={format:'JK_ENG_PHASE42_PHASE41_RC_AUDIT_IMPORT',version:'42.0',importId:verification.verificationId,phase41Bundle:bundle,phase41BundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:sha,expectedSha256:JK_PHASE42.normalizeHash($('phase42ExpectedSha').value)||null},verification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase42_phase41_rc_audit_import_saved',entityId:record.importId,payload:record});$('phase42ImportMessage').textContent=verification.status==='PASS'?'RC_APPROVED + STAGING_PASS + ROLLBACK_REHEARSAL_PASS 검증 완료.':'검증 실패: '+verification.errors.join(', ');await load()}catch(e){$('phase42ImportMessage').textContent='Import failed: '+(e.message||e)}}
async function executeRelease(){const file=$('phase42ExecutionBundleFile').files?.[0];if(!file||!state.verification){$('phase42ReleaseMessage').textContent='검증된 Phase 41 감사 번들을 동일 파일로 다시 선택하세요.';return}const sha=await hashFile(file),rec=JK_PHASE42.createExternalReleaseExecution({rehashedSha256:sha,targetUrl:$('phase42TargetUrl').value,operator:$('phase42ReleaseOperator').value,evidence:$('phase42ReleaseEvidence').value,actualExternalContext:$('phase42ReleaseExternal').checked,confirmationPhrase:$('phase42ReleaseConfirm').value,deployedCandidateSha256:$('phase42CandidateSha').value,deployedAssetManifestVersion:$('phase42ManifestVersion').value,deployedAssetManifestSha256:$('phase42ManifestSha').value},state.verification);await JK_STORAGE.appendApprovalAudit({type:'phase42_v102_release_execution_saved',entityId:rec.executionId,payload:rec});$('phase42ReleaseMessage').textContent=`${rec.status}: ${(rec.errors||[]).join(', ')||'recorded'}`;await load()}
async function runSmoke(){const exec=latest(state.executions),cfg=JK_PHASE42_DATA.policy.externalRelease,rec=JK_PHASE42.evaluatePostReleaseSmoke({actualExternalContext:$('phase42SmokeExternal').checked,operator:$('phase42SmokeOperator').value,tests:readTests(cfg.smokeTests,'phase42Smoke')},exec||{},state.verification||{});await JK_STORAGE.appendApprovalAudit({type:'phase42_post_release_smoke_saved',entityId:rec.runId,payload:rec});$('phase42SmokeMessage').textContent=`${rec.status}: ${(rec.errors||[]).join(', ')||'all pass'}`;await load()}
async function saveOps(){const rec=JK_PHASE42.createOpsSnapshot({date:$('phase42OpsDate').value,syncStatus:$('phase42SyncStatus').value,backupStatus:$('phase42BackupStatus').value,recoveryStatus:$('phase42RecoveryStatus').value,contentIdentityStatus:$('phase42ContentIdentityStatus').value,assetIdentityStatus:$('phase42AssetIdentityStatus').value,operator:$('phase42OpsOperator').value,evidence:$('phase42OpsEvidence').value,actualExternalContext:$('phase42OpsExternal').checked},latest(state.executions)||{});if(!rec.accepted){$('phase42OpsMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase42_ops_snapshot_saved',entityId:rec.snapshotId,payload:rec});$('phase42OpsMessage').textContent='운영 스냅샷 기록 완료.';await load()}
async function saveIncident(){const rec=JK_PHASE42.normalizeIncident({severity:$('phase42IncidentSeverity').value,status:$('phase42IncidentStatus').value,category:$('phase42IncidentCategory').value,title:$('phase42IncidentTitle').value,detail:$('phase42IncidentDetail').value,evidence:$('phase42IncidentEvidence').value,at:new Date().toISOString()});await JK_STORAGE.appendApprovalAudit({type:'phase42_incident_saved',entityId:rec.incidentId,payload:rec});$('phase42IncidentMessage').textContent='Incident recorded.';await load()}
async function evaluate14(){const rec=JK_PHASE42.evaluateStabilization14({execution:latest(state.executions)||{},smoke:latest(state.smokes)||{},asOf:$('phase42AsOf').value,actualLearnerDataUsed:$('phase42LearnerData').checked,dailyReports:Object.values(state.snapshot?.dailyReports||{}),opsSnapshots:state.ops,incidents:state.incidents,referenceMetrics:getReferenceInputs()});await JK_STORAGE.appendApprovalAudit({type:'phase42_stabilization_saved',entityId:rec.evaluationId,payload:rec});$('phase42EvaluationMessage').textContent=`${rec.status} / ${rec.recommendation}`;await load()}
async function decide(){const ev=latest(state.evaluations);if(!ev){$('phase42DecisionMessage').textContent='14-day evaluation is required.';return}const rec=JK_PHASE42.makeFollowupDecision({action:$('phase42DecisionAction').value,reviewer:$('phase42DecisionReviewer').value,reason:$('phase42DecisionReason').value,confirmationPhrase:$('phase42RollbackConfirm').value},ev);if(!rec.accepted){$('phase42DecisionMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase42_followup_decision_saved',entityId:rec.decisionId,payload:rec});$('phase42DecisionMessage').textContent=`${rec.status}. Automatic rollback was not performed.`;await load()}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE42.buildPhase42AuditBundle({phase41BundleMeta:state.importRecord?.phase41BundleMeta||null,phase41RcAuditVerification:state.verification,releaseExecutions:state.executions,smokeRuns:state.smokes,opsSnapshots:state.ops,incidents:state.incidents,stabilizationEvaluations:state.evaluations,followupDecisions:state.decisions}),`JK_ENG_Phase42_v102_Release_Stabilization_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();buildTestRows('phase42SmokeTests',JK_PHASE42_DATA.policy.externalRelease.smokeTests,'phase42Smoke');$('phase42OpsDate').value=new Date().toISOString().slice(0,10);$('phase42AsOf').value=new Date().toISOString().slice(0,10);$('phase42VerifyBundle').onclick=verifyBundle;$('phase42ExecuteRelease').onclick=executeRelease;$('phase42RunSmoke').onclick=runSmoke;$('phase42OpsSave').onclick=saveOps;$('phase42IncidentSave').onclick=saveIncident;$('phase42Evaluate14').onclick=evaluate14;$('phase42DecisionSave').onclick=decide;$('phase42Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase42ImportMessage');if(el)el.textContent=String(e.message||e)});
