(function(global){
'use strict';
const VERSION='38.0';
const text=v=>String(v==null?'':v).trim();
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const nowIso=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
const policy=()=>global.JK_PHASE38_DATA?.policy||{};
const normalizeHash=v=>text(v).toLowerCase().replace(/^sha256:/,'').trim();
const dateOnly=v=>{const source=(typeof v==='string'||typeof v==='number')?v:(v?.date||v?.dayId||v?.executedAt||v?.testedAt||v?.evaluatedAt||v?.recordedAt||v?.updatedAt||v?.at||v);const raw=text(source).replace(/^DAY-/,'');const m=raw.match(/(\d{4}-\d{2}-\d{2})/);return m?m[1]:''};
const addDays=(date,n)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+Number(n||0));return d.toISOString().slice(0,10)};
const avg=values=>{const rows=(values||[]).map(Number).filter(Number.isFinite);return rows.length?Math.round(rows.reduce((a,b)=>a+b,0)*10/rows.length)/10:null};
const latest=(rows=[],field)=>((Array.isArray(rows)?rows:[]).slice().sort((a,b)=>Date.parse(b?.[field]||b?.authorizedAt||b?.verifiedAt||b?.reviewedAt||b?.requestedAt||b?.evaluatedAt||b?.testedAt||b?.executedAt||b?.recordedAt||b?.at||0)-Date.parse(a?.[field]||a?.authorizedAt||a?.verifiedAt||a?.reviewedAt||a?.requestedAt||a?.evaluatedAt||a?.testedAt||a?.executedAt||a?.recordedAt||a?.at||0))[0]||null);
function findBy(rows=[],idField,id){return (Array.isArray(rows)?rows:[]).find(x=>text(x?.[idField])===text(id))||null}
function verifyPhase37AuthorizedBundle(bundle={},options={},p=policy()){
 const cfg=p.acceptedPhase37Bundle||{},checks=[],errors=[];const add=(id,ok,detail='')=>{checks.push({id,ok:Boolean(ok),detail:text(detail)});if(!ok)errors.push(id)};
 const computed=normalizeHash(options.computedSha256),expected=normalizeHash(options.expectedSha256),auth=latest(bundle?.releaseAuthorizations||[],'authorizedAt');
 const regression=auth?findBy(bundle?.regressionVerifications,'verificationId',auth.regressionVerificationId):latest(bundle?.regressionVerifications||[],'verifiedAt');
 const request=auth?findBy(bundle?.changeRequests,'requestId',auth.requestId):null; const review=auth?findBy(bundle?.changeReviews,'reviewId',auth.reviewId):null;
 add('BUNDLE_FORMAT',bundle?.format===cfg.format,bundle?.format||'missing'); add('BUNDLE_VERSION',bundle?.version===cfg.version,bundle?.version||'missing'); add('MAINTENANCE_TARGET',bundle?.maintenanceTarget===cfg.maintenanceTarget,bundle?.maintenanceTarget||'missing');
 add('SOURCE_SHA256_COMPUTED',/^[a-f0-9]{64}$/.test(computed),computed||'missing'); if(expected)add('SOURCE_SHA256_MATCH',computed===expected,computed===expected?'match':'mismatch');
 add('LATEST_AUTHORIZATION_AUTHORIZED',auth?.status===cfg.latestAuthorizationStatus&&auth?.accepted===cfg.latestAuthorizationAccepted,auth?.status||'missing');
 add('LINKED_REGRESSION_PASS',regression?.status===cfg.requiredRegressionStatus&&regression?.pass===true,regression?.status||'missing');
 add('AUTH_REGRESSION_LINK',Boolean(auth&&regression&&text(auth.regressionVerificationId)===text(regression.verificationId)),auth?.regressionVerificationId||'missing');
 add('AUTHORIZED_REQUEST_VALID',request?.status==='REQUESTED'&&request?.accepted===true,request?.status||'missing'); add('AUTHORIZED_REVIEW_APPROVED',review?.status==='APPROVED'&&review?.accepted===true,review?.status||'missing');
 if(request?.contentBankChange)add('CONTENT_APPROVAL_BOUNDARY',Boolean(request?.contentApprovalRef)&&regression?.contentApprovalRef===request.contentApprovalRef,request?.contentApprovalRef||'missing'); else add('CONTENT_APPROVAL_BOUNDARY',true,'content bank unchanged');
 const pass=errors.length===0;return {format:'JK_ENG_PHASE38_PHASE37_AUTHORIZED_INPUT_VERIFICATION',version:VERSION,verificationId:text(options.verificationId)||uid('v101-input'),status:pass?'PASS':'FAIL',approvedForStaging:pass,bundleSha256:computed,expectedSha256:expected||null,authorization:clone(auth),regressionVerification:clone(regression),changeRequest:clone(request),changeReview:clone(review),checks,errors,verifiedAt:nowIso(),automaticDeployment:false,automaticRollback:false,automaticContentApply:false};
}
function normalizeTests(defs=[],provided={}){return (defs||[]).map(d=>{const row=provided?.[d.id]||{};const status=text(row.status||'NOT_RUN').toUpperCase(),evidence=text(row.evidence);return {id:d.id,label:d.label,status,evidence,pass:status==='PASS'&&Boolean(evidence)}})}
function evaluateStagingVerification(input={},verification={},p=policy()){
 const cfg=p.stagingVerification||{},sourceHash=normalizeHash(verification?.bundleSha256),rehash=normalizeHash(input.rehashedSha256),url=text(input.stagingUrl),operator=text(input.operator),evidence=text(input.evidence),actual=Boolean(input.actualStagingContext),tests=normalizeTests(cfg.tests||[],input.tests||{}),errors=[];
 if(verification?.status!=='PASS'||verification?.approvedForStaging!==true)errors.push('AUTHORIZED_PACKAGE_VERIFICATION_REQUIRED'); if(!/^[a-f0-9]{64}$/.test(rehash))errors.push('STAGING_REHASH_REQUIRED'); else if(rehash!==sourceHash)errors.push('STAGING_REHASH_MISMATCH'); if(cfg.actualStagingContextRequired!==false&&!actual)errors.push('ACTUAL_STAGING_CONTEXT_REQUIRED'); if(cfg.httpsRequired!==false&&!/^https:\/\//i.test(url))errors.push('HTTPS_STAGING_URL_REQUIRED'); if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED'); if(cfg.evidenceRequired!==false&&!evidence)errors.push('EVIDENCE_REQUIRED'); for(const t of tests)if(!t.pass)errors.push(`STAGING_${t.id}_PASS_REQUIRED`);
 const pass=errors.length===0;return {format:'JK_ENG_PHASE38_STAGING_VERIFICATION',version:VERSION,runId:text(input.runId)||uid('v101-staging'),status:pass?'STAGING_PASS':'STAGING_FAIL',pass,eligibleForExternalExecution:pass,errors,authorizedBundleSha256:sourceHash||null,stagingRehashSha256:rehash||null,stagingUrl:url||null,actualStagingContext:actual,operator,evidence,tests,verifiedAt:input.verifiedAt||nowIso(),automaticPromotion:false,automaticDeployment:false};
}
function createExternalReleaseExecution(input={},verification={},staging={},p=policy()){
 const cfg=p.externalRelease||{},sourceHash=normalizeHash(verification?.bundleSha256),rehash=normalizeHash(input.rehashedSha256),targetUrl=text(input.targetUrl),operator=text(input.operator),evidence=text(input.evidence),confirmation=text(input.confirmationPhrase),actual=Boolean(input.actualExternalContext),errors=[];
 if(verification?.status!=='PASS'||verification?.approvedForStaging!==true)errors.push('AUTHORIZED_PACKAGE_VERIFICATION_REQUIRED'); if(staging?.status!=='STAGING_PASS'||staging?.eligibleForExternalExecution!==true)errors.push('STAGING_PASS_REQUIRED'); if(!/^[a-f0-9]{64}$/.test(rehash))errors.push('EXECUTION_REHASH_REQUIRED'); else if(rehash!==sourceHash)errors.push('EXECUTION_REHASH_MISMATCH'); if(cfg.actualExternalContextRequired!==false&&!actual)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED'); if(cfg.httpsRequired!==false&&!/^https:\/\//i.test(targetUrl))errors.push('HTTPS_TARGET_REQUIRED'); if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED'); if(cfg.evidenceRequired!==false&&!evidence)errors.push('EVIDENCE_REQUIRED'); if(confirmation!==cfg.confirmationPhrase)errors.push('RELEASE_CONFIRMATION_MISMATCH');
 const accepted=errors.length===0;return {format:'JK_ENG_PHASE38_V101_RELEASE_EXECUTION',version:VERSION,executionId:text(input.executionId)||uid('v101-release'),status:accepted?'V101_RELEASE_EXECUTED':'V101_RELEASE_BLOCKED',accepted,errors,releaseTarget:p.releaseTarget||'JK English v1.0.1',rollbackTarget:p.rollbackTarget||'JK English v1.0',targetUrl:targetUrl||null,actualExternalContext:actual,operator,evidence,authorizedBundleSha256:sourceHash||null,executionRehashSha256:rehash||null,stagingRunId:staging?.runId||null,executedAt:input.executedAt||nowIso(),automaticRelease:false,automaticRollback:false};
}
function evaluatePostReleaseSmoke(input={},execution={},p=policy()){
 const defs=p.externalRelease?.smokeTests||[],tests=normalizeTests(defs,input.tests||{}),actual=Boolean(input.actualExternalContext),operator=text(input.operator),errors=[];
 if(execution?.status!=='V101_RELEASE_EXECUTED'||execution?.accepted!==true)return {format:'JK_ENG_PHASE38_V101_POST_RELEASE_SMOKE',version:VERSION,runId:text(input.runId)||uid('v101-smoke'),status:'V101_SMOKE_NOT_RUN',tests:defs.map(d=>({id:d.id,label:d.label,status:'NOT_RUN',evidence:'',pass:false})),actualExternalContext:false,errors:['V101_RELEASE_NOT_EXECUTED'],testedAt:null,automaticPass:false};
 if(p.externalRelease?.actualExternalContextRequired!==false&&!actual)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED'); if(!operator)errors.push('OPERATOR_REQUIRED'); for(const t of tests)if(!t.pass)errors.push(`SMOKE_${t.id}_PASS_REQUIRED`); const pass=errors.length===0;
 return {format:'JK_ENG_PHASE38_V101_POST_RELEASE_SMOKE',version:VERSION,runId:text(input.runId)||uid('v101-smoke'),status:pass?'V101_SMOKE_PASS':'V101_SMOKE_FAIL',pass,tests,actualExternalContext:actual,operator,targetUrl:execution.targetUrl||null,errors,testedAt:input.testedAt||nowIso(),automaticPass:false};
}
function createOpsSnapshot(input={},execution={},p=policy()){
 const cfg=p.followupOperations||{},date=dateOnly(input.date),sync=text(input.syncStatus).toUpperCase(),backup=text(input.backupStatus).toUpperCase(),recovery=text(input.recoveryStatus).toUpperCase(),operator=text(input.operator),evidence=text(input.evidence),actual=Boolean(input.actualExternalContext),errors=[];
 if(execution?.status!=='V101_RELEASE_EXECUTED'||execution?.accepted!==true)errors.push('V101_RELEASE_NOT_EXECUTED'); if(!date)errors.push('DATE_REQUIRED'); if(!(cfg.syncStatuses||[]).includes(sync))errors.push('SYNC_STATUS_INVALID'); if(!(cfg.backupStatuses||[]).includes(backup))errors.push('BACKUP_STATUS_INVALID'); if(!(cfg.recoveryStatuses||[]).includes(recovery))errors.push('RECOVERY_STATUS_INVALID'); if(cfg.actualExternalContextRequired!==false&&!actual)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED'); if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED'); if(cfg.evidenceRequired!==false&&!evidence)errors.push('EVIDENCE_REQUIRED'); const accepted=errors.length===0;
 return {format:'JK_ENG_PHASE38_V101_OPERATIONS_SNAPSHOT',version:VERSION,snapshotId:text(input.snapshotId)||uid('v101-ops'),date,status:accepted?'RECORDED':'REJECTED',accepted,errors,syncStatus:sync||'CLEAR',backupStatus:backup||'NOT_VERIFIED',recoveryStatus:recovery||'NOT_VERIFIED',actualExternalContext:actual,operator,evidence,recordedAt:input.recordedAt||nowIso(),immutable:true};
}
function normalizeIncident(input={}){const severity=text(input.severity||'P2').toUpperCase(),status=text(input.status||'OPEN').toUpperCase();return {format:'JK_ENG_PHASE38_V101_INCIDENT',version:VERSION,incidentId:text(input.incidentId)||uid('v101-incident'),severity:['P0','P1','P2'].includes(severity)?severity:'P2',status:['OPEN','MITIGATED','CLOSED'].includes(status)?status:'OPEN',title:text(input.title),detail:text(input.detail),evidence:text(input.evidence),at:input.at||nowIso(),updatedAt:input.updatedAt||nowIso()}}
function sufficientReport(r={},cfg={}){return Boolean(r?.completedAt)&&Number(r?.attempts||0)>=Number(cfg.minimumAttempts||12)&&Number(r?.activeMinutes||0)>=Number(cfg.minimumActiveMinutes||25)&&Number(r?.grammarMinutes||0)>=Number(cfg.minimumGrammarMinutes||12)&&Number(r?.readingMinutes||0)>=Number(cfg.minimumReadingMinutes||10)}
function referenceMetricsFromBundle(bundle={}){const rows=(bundle?.monthlyReviews||[]).filter(x=>x?.status==='STABLE'&&x?.actualLearnerDataUsed===true);const row=latest(rows,'evaluatedAt');return clone(row?.currentMetrics||{})}
function evaluateStabilization14(input={},p=policy()){
 const cfg=p.stabilization14||{},execution=input.execution||{},smoke=input.smoke||{},releaseDate=dateOnly(execution?.executedAt),asOf=dateOnly(input.asOf||nowIso()),dueDate=releaseDate?addDays(releaseDate,Number(cfg.days||14)-1):'',base={format:'JK_ENG_PHASE38_V101_STABILIZATION_14',version:VERSION,evaluationId:text(input.evaluationId)||uid('v101-stabilization14'),days:Number(cfg.days||14),releaseDate:releaseDate||null,dueDate:dueDate||null,asOf:asOf||null,automaticRollback:false,automaticPersonalizationThresholdChange:false};
 if(execution?.status!=='V101_RELEASE_EXECUTED'||execution?.accepted!==true||smoke?.status!=='V101_SMOKE_PASS')return {...base,status:'NOT_COLLECTED',recommendation:'HOLD',errors:['RELEASE_AND_SMOKE_PASS_REQUIRED'],actualLearnerDataUsed:false}; if(!releaseDate||!asOf||asOf<dueDate)return {...base,status:'NOT_COLLECTED',recommendation:'HOLD',errors:['DAY14_NOT_REACHED'],actualLearnerDataUsed:false};
 const end=dueDate,reports=(input.dailyReports||[]).filter(r=>{const d=dateOnly(r);return d>=releaseDate&&d<=end}),sufficient=reports.filter(r=>sufficientReport(r,cfg.sufficientLearningDay||{})),ops=(input.opsSnapshots||[]).filter(x=>x?.accepted===true&&x.date>=releaseDate&&x.date<=end),incidents=(input.incidents||[]).map(normalizeIncident).filter(x=>{const d=dateOnly(x.at||x.updatedAt);return d>=releaseDate&&d<=end});
 const actualLearnerDataUsed=Boolean(input.actualLearnerDataUsed),current={learningContinuityRate:reports.length?Math.round(reports.filter(r=>r?.completedAt).length/reports.length*1000)/10:null,answerAccuracy:avg(sufficient.map(r=>r.answerAccuracy)),processPassRate:avg(sufficient.map(r=>r.processPassRate)),recoveryRate:avg(sufficient.map(r=>r.recoveryRate)),paceStability:avg(sufficient.map(r=>r?.axes?.paceStability))},reference=clone(input.referenceMetrics||{}),drops={}; for(const k of ['learningContinuityRate','answerAccuracy','processPassRate','recoveryRate','paceStability'])drops[k]=(Number.isFinite(Number(reference?.[k]))&&current[k]!=null)?Math.round((Number(reference[k])-current[k])*10)/10:null;
 const syncFailureDays=ops.filter(x=>x.syncStatus==='FAILED').length,backupFailureDays=ops.filter(x=>x.backupStatus==='FAIL').length,recoveryFailureDays=ops.filter(x=>['FAILED','DEGRADED'].includes(x.recoveryStatus)).length,openP0P1=incidents.filter(x=>['P0','P1'].includes(x.severity)&&x.status!=='CLOSED').length,openP2=incidents.filter(x=>x.severity==='P2'&&x.status!=='CLOSED').length,errors=[];
 if(!actualLearnerDataUsed)errors.push('ACTUAL_LEARNER_DATA_REQUIRED'); if(sufficient.length<Number(cfg.minimumSufficientLearningDays||9))errors.push('INSUFFICIENT_LEARNING_DAYS'); if(ops.length<Number(cfg.minimumOperationsDays||9))errors.push('INSUFFICIENT_OPERATIONS_DAYS'); if(errors.length)return {...base,status:'INSUFFICIENT',recommendation:'HOLD',errors,actualLearnerDataUsed,sufficientLearningDays:sufficient.length,operationsDays:ops.length,currentMetrics:current,referenceMetrics:reference,drops,syncFailureDays,backupFailureDays,recoveryFailureDays,openP0P1,openP2,evaluatedAt:nowIso()};
 const th=cfg.regressionThresholds||{},hold=[]; if((drops.answerAccuracy??0)>=Number(th.answerAccuracyDropPoints||8))hold.push('answerAccuracy'); if((drops.processPassRate??0)>=Number(th.processPassDropPoints||8))hold.push('processPassRate'); if((drops.recoveryRate??0)>=Number(th.recoveryDropPoints||10))hold.push('recoveryRate'); if((drops.paceStability??0)>=Number(th.paceStabilityDropPoints||12))hold.push('paceStability');
 const severe=[]; if((drops.answerAccuracy??0)>=Number(th.severeAnswerOrProcessDropPoints||12))severe.push('answerAccuracy'); if((drops.processPassRate??0)>=Number(th.severeAnswerOrProcessDropPoints||12))severe.push('processPassRate'); if((drops.recoveryRate??0)>=Number(th.severeRecoveryDropPoints||15))severe.push('recoveryRate'); if((drops.paceStability??0)>=Number(th.severePaceStabilityDropPoints||20))severe.push('paceStability');
 let status='STABLE',recommendation='CONTINUE'; if(openP0P1>0||severe.length){status='ROLLBACK_REVIEW_REQUIRED';recommendation='MANUAL_ROLLBACK_REVIEW'} else if(hold.length>=Number(th.minimumTriggersForHoldReview||2)||syncFailureDays>1||backupFailureDays>0||recoveryFailureDays>0||openP2>0){status='HOLD_REVIEW_REQUIRED';recommendation='MANUAL_HOLD_REVIEW'};
 return {...base,status,recommendation,errors:[],actualLearnerDataUsed,sufficientLearningDays:sufficient.length,operationsDays:ops.length,currentMetrics:current,referenceMetrics:reference,drops,holdMetrics:hold,severeMetrics:severe,syncFailureDays,backupFailureDays,recoveryFailureDays,openP0P1,openP2,sourceDates:sufficient.map(dateOnly),evaluatedAt:input.evaluatedAt||nowIso(),thresholdsChanged:false};
}
function makeFollowupDecision(input={},evaluation={},p=policy()){
 const cfg=p.followupDecision||{},action=text(input.action).toUpperCase(),reviewer=text(input.reviewer),reason=text(input.reason),confirmation=text(input.confirmationPhrase),errors=[]; if(!(cfg.allowedActions||[]).includes(action))errors.push('ACTION_INVALID'); if(cfg.reviewerRequired!==false&&!reviewer)errors.push('REVIEWER_REQUIRED'); if(cfg.reasonRequired!==false&&!reason)errors.push('REASON_REQUIRED'); if(Number(evaluation?.days)!==14||!['STABLE','HOLD_REVIEW_REQUIRED','ROLLBACK_REVIEW_REQUIRED'].includes(evaluation?.status))errors.push('DAY14_EVALUATION_REQUIRED'); if(action==='CONTINUE'&&evaluation?.status!=='STABLE')errors.push('CONTINUE_REQUIRES_STABLE'); if(action==='ROLLBACK_REQUEST'&&evaluation?.status!=='ROLLBACK_REVIEW_REQUIRED')errors.push('ROLLBACK_REVIEW_REQUIRED'); if(action==='ROLLBACK_REQUEST'&&confirmation!==cfg.rollbackConfirmationPhrase)errors.push('ROLLBACK_CONFIRMATION_MISMATCH'); const accepted=errors.length===0;
 return {format:'JK_ENG_PHASE38_V101_FOLLOWUP_DECISION',version:VERSION,decisionId:text(input.decisionId)||uid('v101-followup'),evaluationId:evaluation?.evaluationId||null,evaluationStatus:evaluation?.status||'NOT_COLLECTED',action,status:accepted?(action==='ROLLBACK_REQUEST'?'ROLLBACK_REQUESTED':'RECORDED'):'REJECTED',accepted,errors,reviewer,reason,confirmationMatched:action!=='ROLLBACK_REQUEST'||!errors.includes('ROLLBACK_CONFIRMATION_MISMATCH'),decidedAt:input.decidedAt||nowIso(),immutable:true,automaticRollback:false,externalRollbackExecution:cfg.externalRollbackExecution||'NOT_VERIFIED'};
}
function buildExecutionAuditBundle(input={},p=policy()){
 return {format:'JK_ENG_PHASE38_V101_EXECUTION_STABILIZATION_AUDIT_BUNDLE',version:VERSION,releaseTarget:p.releaseTarget||'JK English v1.0.1',rollbackTarget:p.rollbackTarget||'JK English v1.0',exportedAt:nowIso(),policy:clone(p),state:clone(global.JK_PHASE38_DATA?.state||{}),phase37BundleMeta:clone(input.phase37BundleMeta||null),authorizedInputVerification:clone(input.authorizedInputVerification||null),stagingVerifications:clone(input.stagingVerifications||[]),releaseExecutions:clone(input.releaseExecutions||[]),postReleaseSmokeRuns:clone(input.smokeRuns||[]),operationsSnapshots:clone(input.opsSnapshots||[]),incidents:clone(input.incidents||[]),stabilizationEvaluations:clone(input.stabilizationEvaluations||[]),followupDecisions:clone(input.followupDecisions||[]),truthfulBoundary:{stagingIsNotExternalRelease:true,externalReleaseRequiresExplicitExecution:true,rollbackRequestIsNotExternalRollbackExecution:true,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false,localOrSyntheticCannotPromoteExternalState:true}};
}
const api={VERSION,normalizeHash,dateOnly,addDays,latest,verifyPhase37AuthorizedBundle,evaluateStagingVerification,createExternalReleaseExecution,evaluatePostReleaseSmoke,createOpsSnapshot,normalizeIncident,sufficientReport,referenceMetricsFromBundle,evaluateStabilization14,makeFollowupDecision,buildExecutionAuditBundle};
if(typeof module!=='undefined'&&module.exports)module.exports=api;global.JK_PHASE38=api;
})(typeof window!=='undefined'?window:globalThis);
