(function(global){
'use strict';
const VERSION='49.0';
const text=v=>String(v==null?'':v).trim();
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const nowIso=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
const policy=()=>global.JK_PHASE49_DATA?.policy||{};
const normalizeHash=v=>text(v).toLowerCase().replace(/^sha256:/,'').trim();
const latest=(rows=[],field)=>((Array.isArray(rows)?rows:[]).slice().sort((a,b)=>Date.parse(b?.[field]||b?.approvedAt||b?.testedAt||b?.recordedAt||b?.reviewedAt||b?.at||0)-Date.parse(a?.[field]||a?.approvedAt||a?.testedAt||a?.recordedAt||a?.reviewedAt||a?.at||0))[0]||null);
const validHash=v=>/^[a-f0-9]{64}$/.test(normalizeHash(v));
function verifyPhase48AuditBundle(bundle={},options={},p=policy()){
 const cfg=p.acceptedPhase48Bundle||{},checks=[],errors=[];const add=(id,ok,detail='')=>{checks.push({id,ok:Boolean(ok),detail:text(detail)});if(!ok)errors.push(id)};
 const computed=normalizeHash(options.computedSha256),expected=normalizeHash(options.expectedSha256),plan=latest(bundle?.controlledChangePlans||[],'approvedAt'),guardrail=latest(bundle?.learnerImpactGuardrails||[],'assessedAt'),staging=latest(bundle?.stagingValidations||[],'testedAt'),reviews=(bundle?.requestReviews||[]).filter(x=>x?.accepted===true);
 add('BUNDLE_FORMAT',bundle?.format===cfg.format,bundle?.format||'missing');add('BUNDLE_VERSION',bundle?.version===cfg.version,bundle?.version||'missing');add('CHANGE_TARGET',bundle?.changeTarget===cfg.changeTarget,bundle?.changeTarget||'missing');add('ROLLBACK_TARGET',bundle?.rollbackTarget===cfg.rollbackTarget,bundle?.rollbackTarget||'missing');add('SOURCE_SHA256_COMPUTED',validHash(computed),computed||'missing');if(expected)add('SOURCE_SHA256_MATCH',computed===expected,computed===expected?'match':'mismatch');
 add('PLAN_APPROVED',plan?.status===cfg.requiredPlanStatus&&plan?.accepted===true,plan?.status||'missing');add('GUARDRAIL_PASS',guardrail?.status===cfg.requiredGuardrailStatus&&guardrail?.accepted===true,guardrail?.status||'missing');add('STAGING_PASS',staging?.status===cfg.requiredStagingStatus&&staging?.accepted===true,staging?.status||'missing');add('ACTUAL_STAGING_CONTEXT',cfg.actualStagingContextRequired!==true||staging?.actualStagingContext===true,String(staging?.actualStagingContext));
 add('STAGING_PLAN_LINK',Boolean(plan&&staging&&text(staging.planId)===text(plan.planId)),staging?.planId||'missing');add('STAGING_GUARDRAIL_LINK',Boolean(guardrail&&staging&&text(staging.guardrailId)===text(guardrail.guardrailId)),staging?.guardrailId||'missing');for(const key of cfg.requiredGuardrailPreservations||[]){const value=guardrail?.preservations?.[key]===true||guardrail?.[key]===true;add(`GUARDRAIL_PRESERVATION_${key}`,value,String(value));}
 const planRequestIds=(plan?.requestIds||[]).map(text),byRequest=new Map(reviews.map(x=>[text(x.requestId),x]));for(const id of planRequestIds){const r=byRequest.get(id);add(`REQUEST_AUTHORIZED_${id}`,Boolean(r&&r.status==='AUTHORIZED'&&r.decision==='AUTHORIZE'),r?.status||'missing');if(r?.contentBankChange===true){add(`CONTENT_APPROVAL_${id}`,r.contentApprovalStatus==='APPROVED'&&Boolean(text(r.contentApprovalRef))&&Boolean(text(r.contentApprovalEvidence)),r.contentApprovalStatus||'missing')}}
 add('PLAN_REQUESTS_PRESENT',planRequestIds.length>0,String(planRequestIds.length));const pass=errors.length===0;return {format:'JK_ENG_PHASE49_PHASE48_AUDIT_VERIFICATION',version:VERSION,verificationId:text(options.verificationId)||uid('phase48-audit'),status:pass?'PASS':'FAIL',accepted:pass,eligibleForImplementationEvidence:pass,bundleSha256:computed,expectedSha256:expected||null,plan:clone(plan),guardrail:clone(guardrail),phase48Staging:clone(staging),authorizedReviews:clone(reviews.filter(x=>planRequestIds.includes(text(x.requestId)))),requestIds:planRequestIds,checks,errors,verifiedAt:nowIso(),automaticImplementation:false,automaticDeployment:false,automaticContentApply:false};
}
function recordImplementationEvidence(input={},verification={},p=policy()){
 const cfg=p.implementationEvidence||{},requestId=text(input.requestId),review=(verification?.authorizedReviews||[]).find(x=>text(x.requestId)===requestId),plan=verification?.plan||{},implementedBy=text(input.implementedBy),evidence=text(input.evidence),artifactRef=text(input.builtArtifactRef),artifactSha256=normalizeHash(input.builtArtifactSha256),errors=[];
 if(verification?.status!=='PASS'||verification?.eligibleForImplementationEvidence!==true)errors.push('PHASE48_APPROVED_CONTROL_AUDIT_REQUIRED');if(!(verification?.requestIds||[]).includes(requestId))errors.push('PLAN_REQUEST_NOT_FOUND');if(!review||review.status!=='AUTHORIZED'||review.decision!=='AUTHORIZE')errors.push('AUTHORIZED_REQUEST_REVIEW_REQUIRED');if(cfg.requestReviewPlanBindingRequired!==false&&text(review?.reviewId)&&!(plan?.reviewIds||[]).map(text).includes(text(review.reviewId)))errors.push('REQUEST_REVIEW_PLAN_LINK_MISMATCH');if(cfg.implementedByRequired!==false&&!implementedBy)errors.push('IMPLEMENTED_BY_REQUIRED');if(cfg.implementationEvidenceRequired!==false&&!evidence)errors.push('IMPLEMENTATION_EVIDENCE_REQUIRED');if(cfg.builtArtifactReferenceRequired!==false&&!artifactRef)errors.push('BUILT_ARTIFACT_REFERENCE_REQUIRED');if(cfg.builtArtifactSha256Required!==false&&!validHash(artifactSha256))errors.push('BUILT_ARTIFACT_SHA256_REQUIRED');
 if(review?.contentBankChange===true&&cfg.contentApprovalContinuityRequired!==false){if(review.contentApprovalStatus!=='APPROVED')errors.push('CONTENT_APPROVAL_NOT_APPROVED');if(!text(review.contentApprovalRef)||!text(review.contentApprovalEvidence))errors.push('CONTENT_APPROVAL_CONTINUITY_MISSING')}
 const accepted=errors.length===0;return {format:'JK_ENG_PHASE49_V104_IMPLEMENTATION_EVIDENCE',version:VERSION,evidenceId:text(input.evidenceId)||uid('v104-impl'),requestId,reviewId:review?.reviewId||null,planId:plan?.planId||null,status:accepted?'IMPLEMENTATION_EVIDENCE_RECORDED':'IMPLEMENTATION_EVIDENCE_REJECTED',accepted,errors,implementedBy,evidence,builtArtifactRef:artifactRef,builtArtifactSha256:artifactSha256||null,contentBankChange:Boolean(review?.contentBankChange),contentApprovalRef:review?.contentApprovalRef||null,contentApprovalStatus:review?.contentBankChange?review?.contentApprovalStatus||'NOT_VERIFIED':'NOT_REQUIRED',recordedAt:input.recordedAt||nowIso(),immutable:true,automaticImplementation:false,automaticContentApply:false};
}
function implementationCoverage(verification={},records=[]){const ids=(verification?.requestIds||[]).map(text),valid=(records||[]).filter(x=>x?.accepted===true&&x?.status==='IMPLEMENTATION_EVIDENCE_RECORDED'&&text(x.planId)===text(verification?.plan?.planId));const byId=new Map(valid.map(x=>[text(x.requestId),x]));const missing=ids.filter(id=>!byId.has(id));return {requestIds:ids,records:ids.map(id=>byId.get(id)).filter(Boolean),missing,complete:ids.length>0&&missing.length===0}}
function createCandidateStaging(input={},verification={},implementationRecords=[],p=policy()){
 const cfg=p.candidateStaging||{},coverage=implementationCoverage(verification,implementationRecords),actual=Boolean(input.actualStagingContext),url=text(input.stagingUrl),operator=text(input.operator),candidateSha=normalizeHash(input.candidateArtifactSha256),manifestFormat=text(input.assetManifestFormat),manifestVersion=text(input.assetManifestVersion),manifestSha=normalizeHash(input.assetManifestSha256),rows=Array.isArray(input.cases)?input.cases:[],byId=new Map(rows.map(x=>[text(x.id),x])),errors=[];
 if(verification?.status!=='PASS')errors.push('PHASE48_AUDIT_VERIFICATION_REQUIRED');if(!coverage.complete)errors.push('IMPLEMENTATION_EVIDENCE_INCOMPLETE');if(cfg.candidateArtifactMustMatchAllImplementationEvidence===true&&coverage.complete&&validHash(candidateSha)&&coverage.records.some(x=>normalizeHash(x.builtArtifactSha256)!==candidateSha))errors.push('CANDIDATE_ARTIFACT_IMPLEMENTATION_SHA_MISMATCH');if(cfg.actualStagingContextRequired!==false&&!actual)errors.push('ACTUAL_STAGING_CONTEXT_REQUIRED');if(cfg.httpsRequired!==false&&!/^https:\/\//i.test(url))errors.push('HTTPS_STAGING_URL_REQUIRED');if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');if(cfg.candidateArtifactSha256Required!==false&&!validHash(candidateSha))errors.push('CANDIDATE_ARTIFACT_SHA256_REQUIRED');if(manifestFormat!==cfg.assetManifestFormatRequired)errors.push('ASSET_MANIFEST_FORMAT_MISMATCH');if(manifestVersion!==cfg.assetManifestVersionRequired)errors.push('ASSET_MANIFEST_VERSION_MISMATCH');if(cfg.assetManifestSha256Required!==false&&!validHash(manifestSha))errors.push('ASSET_MANIFEST_SHA256_REQUIRED');
 const normalized=(cfg.cases||[]).map(c=>{const x=byId.get(c.id)||{},status=text(x.status||'NOT_RUN').toUpperCase(),evidence=text(x.evidence);if(!(cfg.allowedStatuses||[]).includes(status))errors.push(`STAGING_STATUS_INVALID_${c.id}`);if(status!=='NOT_RUN'&&cfg.evidenceRequiredPerCase!==false&&!evidence)errors.push(`STAGING_EVIDENCE_REQUIRED_${c.id}`);return {id:c.id,label:c.label,status:(cfg.allowedStatuses||[]).includes(status)?status:'NOT_RUN',evidence}});
 const assetRow=normalized.find(x=>x.id==='ASSET_INTEGRITY'),rollbackRow=normalized.find(x=>x.id==='ROLLBACK_READINESS');if(assetRow?.status!=='PASS')errors.push('ASSET_INTEGRITY_PASS_REQUIRED');const rbCfg=cfg.rollbackRehearsal||{},rb=input.rollbackRehearsal||{},rbActual=Boolean(rb.actualRehearsal),rbTarget=text(rb.target),rbResult=text(rb.result).toUpperCase(),rbOperator=text(rb.operator),rbEvidence=text(rb.evidence),rbRestore=text(rb.restoreCandidateEvidence);if(rbCfg.actualRehearsalRequired!==false&&!rbActual)errors.push('ACTUAL_ROLLBACK_REHEARSAL_REQUIRED');if(rbTarget!==rbCfg.targetRequired)errors.push('ROLLBACK_TARGET_MISMATCH');if(rbResult!==rbCfg.resultRequired)errors.push('ROLLBACK_REHEARSAL_PASS_REQUIRED');if(rbCfg.operatorRequired!==false&&!rbOperator)errors.push('ROLLBACK_OPERATOR_REQUIRED');if(rbCfg.evidenceRequired!==false&&!rbEvidence)errors.push('ROLLBACK_EVIDENCE_REQUIRED');if(rbCfg.restoreCandidateEvidenceRequired!==false&&!rbRestore)errors.push('ROLLBACK_RESTORE_CANDIDATE_EVIDENCE_REQUIRED');if(rollbackRow?.status!=='PASS')errors.push('ROLLBACK_STAGING_CASE_PASS_REQUIRED');
 const failed=normalized.some(x=>x.status==='FAIL'),allPass=normalized.length>0&&normalized.every(x=>x.status==='PASS');let status=cfg.incompleteStatus||'STAGING_INCOMPLETE';if(errors.length||failed)status=cfg.failStatus||'STAGING_FAIL';else if(allPass)status=cfg.passStatus||'STAGING_PASS';else if(normalized.every(x=>x.status==='NOT_RUN'))status=cfg.notRunStatus||'STAGING_NOT_RUN';const accepted=status==='STAGING_PASS'&&errors.length===0;
 return {format:'JK_ENG_PHASE49_V104_CANDIDATE_STAGING',version:VERSION,runId:text(input.runId)||uid('v104-candidate-stage'),status,accepted,errors,planId:verification?.plan?.planId||null,guardrailId:verification?.guardrail?.guardrailId||null,requestIds:coverage.requestIds,implementationEvidenceIds:coverage.records.map(x=>x.evidenceId),actualStagingContext:actual,stagingUrl:url||null,operator:operator||null,candidateArtifactSha256:candidateSha||null,assetManifestFormat:manifestFormat||null,assetManifestVersion:manifestVersion||null,assetManifestSha256:manifestSha||null,cases:normalized,rollbackRehearsal:{actualRehearsal:rbActual,target:rbTarget||null,result:rbResult||'NOT_RUN',operator:rbOperator||null,evidence:rbEvidence||null,restoreCandidateEvidence:rbRestore||null,status:rbActual&&rbResult==='PASS'&&rbTarget===rbCfg.targetRequired&&rbEvidence&&rbRestore?'ROLLBACK_REHEARSAL_PASS':'ROLLBACK_REHEARSAL_NOT_VERIFIED'},testedAt:input.testedAt||nowIso(),productionDeploymentAuthorization:'NOT_GRANTED',automaticDeployment:false,automaticRollback:false};
}
function recordDefect(input={},p=policy()){
 const cfg=p.defects||{},defectId=text(input.defectId)||uid('v104-defect'),severity=text(input.severity).toUpperCase(),status=text(input.status).toUpperCase(),summary=text(input.summary),evidence=text(input.evidence),errors=[];if(!(cfg.severity||[]).includes(severity))errors.push('DEFECT_SEVERITY_INVALID');if(!(cfg.status||[]).includes(status))errors.push('DEFECT_STATUS_INVALID');if(!summary)errors.push('DEFECT_SUMMARY_REQUIRED');if(!evidence)errors.push('DEFECT_EVIDENCE_REQUIRED');return {format:'JK_ENG_PHASE49_V104_DEFECT',version:VERSION,defectId,severity,status,summary,evidence,accepted:errors.length===0,errors,recordedAt:input.recordedAt||nowIso(),immutable:true};
}
function createRCGate(input={},verification={},implementationRecords=[],staging={},defects=[],p=policy()){
 const cfg=p.rcGate||{},coverage=implementationCoverage(verification,implementationRecords),operator=text(input.operator),evidence=text(input.evidence),confirmation=text(input.confirmationPhrase),preserve=input.preservations||{},impacts=input.impacts||{},errors=[];if(verification?.status!=='PASS')errors.push('PHASE48_AUDIT_VERIFICATION_REQUIRED');if(cfg.allImplementationEvidenceRequired!==false&&!coverage.complete)errors.push('IMPLEMENTATION_EVIDENCE_INCOMPLETE');if(cfg.candidateStagingPassRequired!==false&&(staging?.status!=='STAGING_PASS'||staging?.accepted!==true))errors.push('CANDIDATE_STAGING_PASS_REQUIRED');if(cfg.rollbackRehearsalPassRequired!==false&&staging?.rollbackRehearsal?.status!=='ROLLBACK_REHEARSAL_PASS')errors.push('ROLLBACK_REHEARSAL_PASS_REQUIRED');if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');if(cfg.evidenceRequired!==false&&!evidence)errors.push('RC_EVIDENCE_REQUIRED');
 const blocking=(defects||[]).filter(d=>(p.defects?.blockingSeverities||[]).includes(d?.severity)&&(p.defects?.blockingStatuses||[]).includes(d?.status));if(cfg.noUnresolvedP0P1!==false&&blocking.length)errors.push('UNRESOLVED_P0_P1_DEFECT');if(input.guardrailRegression===true&&cfg.guardrailRegressionForbidden!==false)errors.push('GUARDRAIL_REGRESSION');if(input.contentApprovalMismatch===true&&cfg.contentApprovalMismatchForbidden!==false)errors.push('CONTENT_APPROVAL_MISMATCH');if(input.learningLoopInvariantRegression===true&&cfg.learningLoopInvariantRegressionForbidden!==false)errors.push('LEARNING_LOOP_INVARIANT_REGRESSION');if(input.dailyStructureRegression===true&&cfg.dailyStructureRegressionForbidden!==false)errors.push('DAILY_STRUCTURE_REGRESSION');if(input.assetIdentityFailure===true&&cfg.assetIdentityFailureForbidden!==false)errors.push('ASSET_IDENTITY_FAILURE');for(const key of cfg.requiredPreservations||[])if(preserve[key]!==true)errors.push(`PRESERVATION_REQUIRED_${key.toUpperCase()}`);for(const key of cfg.forbiddenImpacts||[])if(impacts[key]===true)errors.push(`FORBIDDEN_IMPACT_${key.toUpperCase()}`);if(confirmation!==cfg.confirmationPhrase)errors.push('RC_CONFIRMATION_MISMATCH');const accepted=errors.length===0;
 return {format:'JK_ENG_PHASE49_V104_RC_GATE',version:VERSION,gateId:text(input.gateId)||uid('v104-rc'),status:accepted?'RC_APPROVED':'RC_BLOCKED',accepted,errors,planId:verification?.plan?.planId||null,guardrailId:verification?.guardrail?.guardrailId||null,stagingRunId:staging?.runId||null,requestIds:coverage.requestIds,implementationEvidenceIds:coverage.records.map(x=>x.evidenceId),blockingDefectIds:blocking.map(x=>x.defectId),operator,evidence,preservations:clone(preserve),impacts:clone(impacts),guardrailRegression:Boolean(input.guardrailRegression),contentApprovalMismatch:Boolean(input.contentApprovalMismatch),learningLoopInvariantRegression:Boolean(input.learningLoopInvariantRegression),dailyStructureRegression:Boolean(input.dailyStructureRegression),assetIdentityFailure:Boolean(input.assetIdentityFailure),confirmationMatched:confirmation===cfg.confirmationPhrase,approvedAt:accepted?(input.approvedAt||nowIso()):null,productionDeploymentAuthorization:cfg.productionDeploymentAuthorization||'NOT_GRANTED',externalV104Release:'NOT_RUN',automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false};
}
function buildPhase49AuditBundle(input={},p=policy()){
 return {format:'JK_ENG_PHASE49_V104_IMPLEMENTATION_STAGING_RC_AUDIT_BUNDLE',version:VERSION,changeTarget:p.changeTarget||'JK English v1.0.4',rollbackTarget:p.rollbackTarget||'JK English v1.0.3',exportedAt:nowIso(),policy:clone(p),state:clone(global.JK_PHASE49_DATA?.state||{}),phase48BundleMeta:clone(input.phase48BundleMeta||null),phase48AuditVerification:clone(input.phase48AuditVerification||null),implementationEvidence:clone(input.implementationEvidence||[]),candidateStagingRuns:clone(input.candidateStagingRuns||[]),defects:clone(input.defects||[]),rcGates:clone(input.rcGates||[]),truthfulBoundary:{implementationEvidenceDoesNotAutoApply:true,stagingPassIsNotProductionRelease:true,rcApprovalIsNotProductionDeployment:true,rollbackRehearsalIsNotProductionRollback:true,externalV104Release:'NOT_RUN',automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false,localOrSyntheticCannotPromoteExternalState:true}};
}
const api={VERSION,normalizeHash,latest,verifyPhase48AuditBundle,recordImplementationEvidence,implementationCoverage,createCandidateStaging,recordDefect,createRCGate,buildPhase49AuditBundle};global.JK_PHASE49=api;
})(typeof window!=='undefined'?window:globalThis);
