(function(global){
'use strict';
const VERSION='37.0';
const text=v=>String(v==null?'':v).trim();
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const nowIso=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
const policy=()=>global.JK_PHASE37_DATA?.policy||{};
const normalizeHash=v=>text(v).toLowerCase().replace(/^sha256:/,'').trim();
const dateOnly=v=>{const raw=text(v?.date||v?.dayId||v).replace(/^DAY-/,'');const m=raw.match(/(\d{4}-\d{2}-\d{2})/);return m?m[1]:''};
const monthOnly=v=>{const raw=text(v);const m=raw.match(/^(\d{4}-\d{2})/);return m?m[1]:''};
const avg=values=>{const rows=values.map(Number).filter(Number.isFinite);return rows.length?Math.round(rows.reduce((a,b)=>a+b,0)*10/rows.length)/10:null};
const latest=(rows=[],field='at')=>(Array.isArray(rows)?rows:[]).slice().sort((a,b)=>Date.parse(b?.[field]||b?.decidedAt||b?.evaluatedAt||b?.testedAt||b?.executedAt||0)-Date.parse(a?.[field]||a?.decidedAt||a?.evaluatedAt||a?.testedAt||a?.executedAt||0))[0]||null;
function latestCheckpoint(bundle={},days=30){return (bundle?.checkpointEvaluations||[]).filter(x=>Number(x?.days)===Number(days)).slice().sort((a,b)=>Date.parse(b?.evaluatedAt||0)-Date.parse(a?.evaluatedAt||0))[0]||null}
function latestDecision(bundle={},days=30){return (bundle?.followupDecisions||[]).filter(x=>Number(x?.checkpointDays)===Number(days)).slice().sort((a,b)=>Date.parse(b?.decidedAt||0)-Date.parse(a?.decidedAt||0))[0]||null}
function verifyPhase36LongTermBundle(bundle={},options={},p=policy()){
 const cfg=p.acceptedPhase36Bundle||{},checks=[],errors=[];const add=(id,ok,detail='')=>{checks.push({id,ok:Boolean(ok),detail:text(detail)});if(!ok)errors.push(id)};
 const computed=normalizeHash(options.computedSha256),expected=normalizeHash(options.expectedSha256),execution=latest(bundle?.releaseExecutions||[],'executedAt'),smoke=latest(bundle?.postReleaseSmokeRuns||[],'testedAt'),checkpoint=latestCheckpoint(bundle,cfg.checkpointDays||30),decision=latestDecision(bundle,cfg.checkpointDays||30);
 add('BUNDLE_FORMAT',bundle?.format===cfg.format,bundle?.format||'missing');
 add('BUNDLE_VERSION',bundle?.version===cfg.version,bundle?.version||'missing');
 add('RELEASE_TARGET',bundle?.releaseTarget===cfg.releaseTarget,bundle?.releaseTarget||'missing');
 add('SOURCE_SHA256_COMPUTED',/^[a-f0-9]{64}$/.test(computed),computed||'missing');
 if(expected)add('SOURCE_SHA256_MATCH',computed===expected,computed===expected?'match':'mismatch');
 add('V1_RELEASE_EXECUTED',execution?.status===cfg.releaseExecutionStatus&&execution?.accepted===true,execution?.status||'missing');
 add('POST_RELEASE_SMOKE_PASS',smoke?.status===cfg.postReleaseSmokeStatus&&smoke?.actualExternalContext===true,smoke?.status||'missing');
 add('CHECKPOINT_30_STABLE',Number(checkpoint?.days)===Number(cfg.checkpointDays)&&checkpoint?.status===cfg.checkpointStatus,checkpoint?.status||'missing');
 add('CHECKPOINT_30_ACTUAL_LEARNER_DATA',checkpoint?.actualLearnerDataUsed===cfg.actualLearnerDataRequired,String(checkpoint?.actualLearnerDataUsed));
 add('CHECKPOINT_30_SUFFICIENT_DAYS',Number(checkpoint?.sufficientLearningDays||0)>=18&&Number(checkpoint?.operationsDays||0)>=18,`${checkpoint?.sufficientLearningDays||0}/${checkpoint?.operationsDays||0}`);
 add('FOLLOWUP_CONTINUE',decision?.action===cfg.latestFollowupAction&&decision?.accepted===cfg.latestFollowupAccepted,decision?.action||'missing');
 const pass=errors.length===0;
 return {format:'JK_ENG_PHASE37_PHASE36_LONGTERM_INPUT_VERIFICATION',version:VERSION,verificationId:text(options.verificationId)||uid('maintenance-input'),status:pass?'PASS':'FAIL',approvedForLongTermOperations:pass,bundleSha256:computed,expectedSha256:expected||null,releaseExecution:clone(execution),postReleaseSmoke:clone(smoke),checkpoint30:clone(checkpoint),followupDecision:clone(decision),checks,errors,verifiedAt:nowIso(),automaticDeployment:false,automaticRollback:false};
}
function sufficientReport(r={},cfg={}){return Boolean(r?.completedAt)&&Number(r?.attempts||0)>=Number(cfg.minimumAttempts||12)&&Number(r?.activeMinutes||0)>=Number(cfg.minimumActiveMinutes||25)&&Number(r?.grammarMinutes||0)>=Number(cfg.minimumGrammarMinutes||12)&&Number(r?.readingMinutes||0)>=Number(cfg.minimumReadingMinutes||10)}
function normalizeRetentionEvidence(input={},p=policy()){
 const cfg=p.retentionEvidence||{},month=monthOnly(input.month),ret=text(input.retentionStatus).toUpperCase(),backup=text(input.backupStatus).toUpperCase(),recovery=text(input.recoveryStatus).toUpperCase(),operator=text(input.operator),evidence=text(input.evidence),errors=[];
 if(!month)errors.push('MONTH_REQUIRED');if(!(cfg.retentionStatuses||[]).includes(ret))errors.push('RETENTION_STATUS_INVALID');if(!(cfg.backupStatuses||[]).includes(backup))errors.push('BACKUP_STATUS_INVALID');if(!(cfg.recoveryStatuses||[]).includes(recovery))errors.push('RECOVERY_STATUS_INVALID');if(cfg.actualExternalContextRequired!==false&&!input.actualExternalContext)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED');if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');if(cfg.evidenceRequired!==false&&!evidence)errors.push('EVIDENCE_REQUIRED');
 const accepted=errors.length===0;return {format:'JK_ENG_PHASE37_RETENTION_BACKUP_RECOVERY_EVIDENCE',version:VERSION,evidenceId:text(input.evidenceId)||uid('retention-evidence'),month,status:accepted?'RECORDED':'REJECTED',accepted,errors,actualExternalContext:Boolean(input.actualExternalContext),retentionStatus:ret||'NOT_VERIFIED',backupStatus:backup||'NOT_VERIFIED',recoveryStatus:recovery||'NOT_VERIFIED',operator,evidence,recordedAt:input.recordedAt||nowIso(),immutable:true,automaticPass:false};
}
function buildMonthlyEffectReview(input={},verification={},p=policy()){
 const cfg=p.monthlyReview||{},month=monthOnly(input.month),base={format:'JK_ENG_PHASE37_MONTHLY_EFFECT_REVIEW',version:VERSION,reviewId:text(input.reviewId)||uid(`monthly-${month||'unknown'}`),month,minimumSufficientLearningDays:Number(cfg.minimumSufficientLearningDays||18),minimumOperationsDays:Number(cfg.minimumOperationsDays||18),minimumRetentionEvidence:Number(cfg.minimumRetentionEvidence||1),automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false};
 if(verification?.status!=='PASS'||verification?.approvedForLongTermOperations!==true)return {...base,status:'NOT_COLLECTED',recommendation:'HOLD',errors:['PHASE36_30DAY_STABLE_INPUT_REQUIRED'],actualLearnerDataUsed:false};
 if(!month)return {...base,status:'NOT_COLLECTED',recommendation:'HOLD',errors:['MONTH_REQUIRED'],actualLearnerDataUsed:false};
 if(cfg.actualExternalContextRequired!==false&&!input.actualExternalContext)return {...base,status:'NOT_COLLECTED',recommendation:'HOLD',errors:['ACTUAL_EXTERNAL_CONTEXT_REQUIRED'],actualLearnerDataUsed:false};
 const reports=(input.dailyReports||[]).filter(r=>dateOnly(r).startsWith(month)),sufficient=reports.filter(r=>sufficientReport(r,cfg.sufficientLearningDay||{}));
 const ops=(input.opsSnapshots||[]).filter(x=>x?.accepted!==false&&dateOnly(x).startsWith(month));
 const retention=(input.retentionEvidence||[]).filter(x=>x?.accepted===true&&x?.month===month);
 const incidents=(input.incidents||[]).filter(x=>dateOnly(x?.at||x?.updatedAt).startsWith(month));
 const actualLearnerDataUsed=Boolean(input.actualLearnerDataUsed);
 const continuity=reports.length?Math.round((reports.filter(r=>r?.completedAt).length/reports.length)*1000)/10:null;
 const current={learningContinuityRate:continuity,answerAccuracy:avg(sufficient.map(r=>r.answerAccuracy)),processPassRate:avg(sufficient.map(r=>r.processPassRate)),recoveryRate:avg(sufficient.map(r=>r.recoveryRate)),paceStability:avg(sufficient.map(r=>r?.axes?.paceStability))};
 const ref=verification?.checkpoint30?.currentMetrics||{};const reference={learningContinuityRate:Number(verification?.checkpoint30?.learningContinuityRate||0)||null,answerAccuracy:Number(ref.answerAccuracy||0)||null,processPassRate:Number(ref.processPassRate||0)||null,recoveryRate:Number(ref.recoveryRate||0)||null,paceStability:Number(ref.paceStability||0)||null};
 const drops={};for(const k of ['learningContinuityRate','answerAccuracy','processPassRate','recoveryRate','paceStability'])drops[k]=(reference[k]!=null&&current[k]!=null)?Math.round((reference[k]-current[k])*10)/10:null;
 const syncFailureDays=ops.filter(x=>['FAILED'].includes(String(x.syncStatus))).length,backupFailureDays=ops.filter(x=>x.backupStatus==='FAIL').length,recoveryFailureDays=ops.filter(x=>['FAILED','DEGRADED'].includes(String(x.recoveryStatus))).length,openP0P1=incidents.filter(x=>['P0','P1'].includes(String(x.severity))&&String(x.status)!=='CLOSED').length,openP2=incidents.filter(x=>String(x.severity)==='P2'&&String(x.status)!=='CLOSED').length;
 const errors=[];if(!actualLearnerDataUsed)errors.push('ACTUAL_LEARNER_DATA_REQUIRED');if(sufficient.length<base.minimumSufficientLearningDays)errors.push('INSUFFICIENT_LEARNING_DAYS');if(ops.length<base.minimumOperationsDays)errors.push('INSUFFICIENT_OPERATIONS_DAYS');if(retention.length<base.minimumRetentionEvidence)errors.push('RETENTION_EVIDENCE_REQUIRED');
 if(errors.length)return {...base,status:'INSUFFICIENT',recommendation:'HOLD',errors,actualLearnerDataUsed,sufficientLearningDays:sufficient.length,operationsDays:ops.length,retentionEvidenceCount:retention.length,currentMetrics:current,referenceMetrics:reference,drops,syncFailureDays,backupFailureDays,recoveryFailureDays,openP0P1,openP2,evaluatedAt:nowIso()};
 const bands=cfg.trendBands||{},criticalKeys=Object.entries(drops).filter(([,v])=>v!=null&&v>=Number(bands.criticalDropPoints||15)).map(([k])=>k),watchKeys=Object.entries(drops).filter(([,v])=>v!=null&&v>=Number(bands.watchDropPoints||10)).map(([k])=>k);
 let status='STABLE',recommendation='CONTINUE';if(openP0P1>0||criticalKeys.length||recoveryFailureDays>2||backupFailureDays>2){status='CRITICAL_REVIEW';recommendation='CHANGE_REVIEW_REQUIRED'}else if(watchKeys.length||syncFailureDays>2||recoveryFailureDays>0||backupFailureDays>0||openP2>0){status='WATCH';recommendation='MAINTENANCE_REVIEW'}
 return {...base,status,recommendation,errors:[],actualLearnerDataUsed,sufficientLearningDays:sufficient.length,operationsDays:ops.length,retentionEvidenceCount:retention.length,currentMetrics:current,referenceMetrics:reference,drops,watchMetrics:watchKeys,criticalMetrics:criticalKeys,syncFailureDays,backupFailureDays,recoveryFailureDays,openP0P1,openP2,sourceDates:sufficient.map(dateOnly),evaluatedAt:nowIso(),thresholdsChanged:false};
}
function createChangeRequest(input={},p=policy()){
 const cfg=p.changeControl||{},changeType=text(input.changeType).toUpperCase(),severity=text(input.severity).toUpperCase(),title=text(input.title),summary=text(input.summary),requestedBy=text(input.requestedBy),incidentRef=text(input.incidentRef),contentApprovalRef=text(input.contentApprovalRef),contentBankChange=Boolean(input.contentBankChange),errors=[];
 if(!(cfg.changeTypes||[]).includes(changeType))errors.push('CHANGE_TYPE_INVALID');if(!(cfg.severities||[]).includes(severity))errors.push('SEVERITY_INVALID');if(!title)errors.push('TITLE_REQUIRED');if(!summary)errors.push('SUMMARY_REQUIRED');if(!requestedBy)errors.push('REQUESTER_REQUIRED');if(changeType==='HOTFIX'&&!(cfg.hotfixSeverities||[]).includes(severity))errors.push('HOTFIX_REQUIRES_P0_P1');if(changeType==='HOTFIX'&&cfg.hotfixIncidentReferenceRequired!==false&&!incidentRef)errors.push('HOTFIX_INCIDENT_REFERENCE_REQUIRED');if(contentBankChange&&cfg.contentBankChangeRequiresSeparateApproval!==false&&!contentApprovalRef)errors.push('CONTENT_APPROVAL_REFERENCE_REQUIRED');
 const accepted=errors.length===0;return {format:'JK_ENG_PHASE37_CHANGE_REQUEST',version:VERSION,requestId:text(input.requestId)||uid('change-request'),maintenanceTarget:p.maintenanceTarget||'JK English v1.0.1',changeType,severity,title,summary,requestedBy,incidentRef:incidentRef||null,contentBankChange,contentApprovalRef:contentApprovalRef||null,status:accepted?'REQUESTED':'REJECTED',accepted,errors,requestedAt:input.requestedAt||nowIso(),automaticContentApply:false,automaticDeployment:false,immutable:true};
}
function reviewChangeRequest(input={},request={},p=policy()){
 const cfg=p.changeControl||{},decision=text(input.decision).toUpperCase(),reviewer=text(input.reviewer),reason=text(input.reason),checklist={};for(const key of cfg.requiredInvariantChecklist||[])checklist[key]=Boolean(input.checklist?.[key]);const missing=(cfg.requiredInvariantChecklist||[]).filter(k=>!checklist[k]),errors=[];
 if(request?.status!=='REQUESTED'||request?.accepted!==true)errors.push('VALID_REQUEST_REQUIRED');if(!(cfg.allowedDecisions||[]).includes(decision))errors.push('DECISION_INVALID');if(cfg.reviewerRequired!==false&&!reviewer)errors.push('REVIEWER_REQUIRED');if(cfg.reasonRequired!==false&&!reason)errors.push('REASON_REQUIRED');if(decision==='APPROVE'&&missing.length)errors.push('INVARIANT_CHECKLIST_INCOMPLETE');if(decision==='APPROVE'&&request?.contentBankChange&&!request?.contentApprovalRef)errors.push('CONTENT_APPROVAL_REFERENCE_REQUIRED');
 const accepted=errors.length===0,status=accepted?(decision==='APPROVE'?'APPROVED':'REJECTED'):'REVIEW_REJECTED';return {format:'JK_ENG_PHASE37_CHANGE_REVIEW',version:VERSION,reviewId:text(input.reviewId)||uid('change-review'),requestId:request?.requestId||null,changeType:request?.changeType||null,severity:request?.severity||null,decision,status,accepted,errors,checklist,missingInvariantChecks:missing,reviewer,reason,reviewedAt:input.reviewedAt||nowIso(),automaticDeployment:false,automaticContentApply:false,immutable:true};
}
function recordRegressionVerification(input={},request={},review={},p=policy()){
 const cfg=p.regressionContract||{},tests={};for(const id of cfg.requiredTests||[]){const row=input.tests?.[id]||{};tests[id]={status:text(row.status||'NOT_RUN').toUpperCase(),evidence:text(row.evidence)}}const errors=[];if(request?.status!=='REQUESTED'||request?.accepted!==true)errors.push('VALID_REQUEST_REQUIRED');if(review?.status!=='APPROVED'||review?.accepted!==true)errors.push('APPROVED_REVIEW_REQUIRED');for(const id of cfg.requiredTests||[]){if(tests[id].status!=='PASS')errors.push(`TEST_${id}_PASS_REQUIRED`);if(!tests[id].evidence)errors.push(`TEST_${id}_EVIDENCE_REQUIRED`)}
 const observed=input.observed||{};if(Number(observed.questionCount)!==Number(cfg.expectedQuestionCount))errors.push('QUESTION_COUNT_INVARIANT_FAILED');if(Number(observed.coreFamilyCount)!==Number(cfg.expectedCoreFamilyCount))errors.push('CORE_FAMILY_COUNT_INVARIANT_FAILED');if(Number(observed.allFamilyCount)!==Number(cfg.expectedAllFamilyCount))errors.push('ALL_FAMILY_COUNT_INVARIANT_FAILED');if(Number(observed.grammarMinutes)!==Number(cfg.expectedGrammarMinutes)||Number(observed.readingMinutes)!==Number(cfg.expectedReadingMinutes)||Number(observed.resultMinutes)!==Number(cfg.expectedResultMinutes))errors.push('DAILY_TIMING_INVARIANT_FAILED');if(request?.contentBankChange&&!request?.contentApprovalRef)errors.push('CONTENT_APPROVAL_REFERENCE_REQUIRED');
 const pass=errors.length===0;return {format:'JK_ENG_PHASE37_REGRESSION_VERIFICATION',version:VERSION,verificationId:text(input.verificationId)||uid('v101-regression'),requestId:request?.requestId||null,reviewId:review?.reviewId||null,status:pass?'REGRESSION_PASS':'REGRESSION_FAIL',pass,eligibleForV101Authorization:pass,errors,tests,observed:{questionCount:Number(observed.questionCount||0),coreFamilyCount:Number(observed.coreFamilyCount||0),allFamilyCount:Number(observed.allFamilyCount||0),grammarMinutes:Number(observed.grammarMinutes||0),readingMinutes:Number(observed.readingMinutes||0),resultMinutes:Number(observed.resultMinutes||0)},contentBankChange:Boolean(request?.contentBankChange),contentApprovalRef:request?.contentApprovalRef||null,verifiedBy:text(input.verifiedBy),verifiedAt:input.verifiedAt||nowIso(),automaticDeployment:false,automaticRollback:false};
}
function authorizeV101Release(input={},request={},review={},regression={},monthlyReview={},p=policy()){
 const cfg=p.changeControl||{},reviewer=text(input.reviewer),reason=text(input.reason),confirmation=text(input.confirmationPhrase),errors=[];if(request?.status!=='REQUESTED'||!request?.accepted)errors.push('VALID_REQUEST_REQUIRED');if(review?.status!=='APPROVED'||!review?.accepted)errors.push('APPROVED_REVIEW_REQUIRED');if(regression?.status!=='REGRESSION_PASS'||regression?.eligibleForV101Authorization!==true)errors.push('REGRESSION_PASS_REQUIRED');if(request?.changeType!=='HOTFIX'&&monthlyReview?.status!=='STABLE')errors.push('STABLE_MONTHLY_REVIEW_REQUIRED');if(cfg.reviewerRequired!==false&&!reviewer)errors.push('REVIEWER_REQUIRED');if(cfg.reasonRequired!==false&&!reason)errors.push('REASON_REQUIRED');if(confirmation!==cfg.v101ReleaseConfirmationPhrase)errors.push('V101_CONFIRMATION_MISMATCH');const accepted=errors.length===0;return {format:'JK_ENG_PHASE37_V101_RELEASE_AUTHORIZATION',version:VERSION,authorizationId:text(input.authorizationId)||uid('v101-authorization'),maintenanceTarget:p.maintenanceTarget||'JK English v1.0.1',requestId:request?.requestId||null,reviewId:review?.reviewId||null,regressionVerificationId:regression?.verificationId||null,monthlyReviewId:monthlyReview?.reviewId||null,status:accepted?'AUTHORIZED':'REJECTED',accepted,errors,reviewer,reason,confirmationMatched:!errors.includes('V101_CONFIRMATION_MISMATCH'),authorizedAt:input.authorizedAt||nowIso(),externalReleaseExecution:'NOT_RUN',automaticDeployment:false,automaticRollback:false,immutable:true};
}
function buildMonthlyAuditBundle(input={},p=policy()){
 return {format:'JK_ENG_PHASE37_MONTHLY_MAINTENANCE_AUDIT_BUNDLE',version:VERSION,releaseTarget:p.releaseTarget||'JK English v1.0',maintenanceTarget:p.maintenanceTarget||'JK English v1.0.1',exportedAt:nowIso(),policy:clone(p),state:clone(global.JK_PHASE37_DATA?.state||{}),phase36BundleMeta:clone(input.phase36BundleMeta||null),phase36Verification:clone(input.phase36Verification||null),monthlyReviews:clone(input.monthlyReviews||[]),retentionEvidence:clone(input.retentionEvidence||[]),changeRequests:clone(input.changeRequests||[]),changeReviews:clone(input.changeReviews||[]),regressionVerifications:clone(input.regressionVerifications||[]),releaseAuthorizations:clone(input.releaseAuthorizations||[]),truthfulBoundary:{externalV101Release:'NOT_RUN',automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false,localOrSyntheticCannotPromoteExternalState:true}};
}
const api={VERSION,normalizeHash,dateOnly,monthOnly,latestCheckpoint,latestDecision,verifyPhase36LongTermBundle,normalizeRetentionEvidence,buildMonthlyEffectReview,createChangeRequest,reviewChangeRequest,recordRegressionVerification,authorizeV101Release,buildMonthlyAuditBundle};
if(typeof module!=='undefined'&&module.exports)module.exports=api;global.JK_PHASE37=api;
})(typeof window!=='undefined'?window:globalThis);
