(async function(){
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={snapshot:null,audits:[],importRecord:null,verification:null,executions:[],smokes:[],ops:[],incidents:[],evaluations:[],decisions:[],rollbackExecutions:[]};
const sorted=rows=>(rows||[]).slice().sort((a,b)=>Date.parse(b.at||b.decidedAt||b.evaluatedAt||b.testedAt||b.executedAt||b.verifiedAt||b.recordedAt||0)-Date.parse(a.at||a.decidedAt||a.evaluatedAt||a.testedAt||a.executedAt||a.verifiedAt||a.recordedAt||0));
const rowsByType=type=>sorted(state.audits.filter(x=>x.type===type).map(x=>x.payload));const latest=rows=>rows?.[0]||null;
async function hashFile(file){const b=await file.arrayBuffer(),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function badgeClass(s){s=String(s||'');return /PASS|EXECUTED|STABLE|RECORDED|APPROVED/.test(s)?'pass':/FAIL|BLOCKED|ROLLBACK/.test(s)?'fail':/HOLD|INSUFFICIENT|REVIEW_REQUIRED/.test(s)?'warn':''}
function buildTestRows(containerId,defs,prefix){const root=$(containerId);if(!root)return;root.innerHTML=(defs||[]).map(d=>`<div class="smokeRow"><div><strong>${esc(d.id)}</strong><div class="note">${esc(d.label)}</div></div><select id="${prefix}Status_${esc(d.id)}"><option>NOT_RUN</option><option>PASS</option><option>FAIL</option></select><input id="${prefix}Evidence_${esc(d.id)}" placeholder="evidence reference"></div>`).join('')}
function readTests(defs,prefix){const out={};for(const d of defs||[])out[d.id]={status:$(`${prefix}Status_${d.id}`).value,evidence:$(`${prefix}Evidence_${d.id}`).value};return out}
function referenceMetricsFromHistory(){for(const type of ['phase47_confirmation30_saved','phase46_stabilization_saved','phase43_confirmation30_saved','phase42_stabilization_saved','phase39_confirmation30_saved']){for(const row of rowsByType(type)){const m=row?.currentMetrics;if(m&&['answerAccuracy','processPassRate','recoveryRate','paceStability'].every(k=>Number.isFinite(Number(m[k]))))return m}}return null}
function setReferenceInputs(m){if(!m)return;for(const [id,k] of [['phase50RefAccuracy','answerAccuracy'],['phase50RefProcess','processPassRate'],['phase50RefRecovery','recoveryRate'],['phase50RefPace','paceStability']])if($(id)&&!$(id).value)$(id).value=Number(m[k])}
function getReferenceInputs(){return {answerAccuracy:Number($('phase50RefAccuracy').value),processPassRate:Number($('phase50RefProcess').value),recoveryRate:Number($('phase50RefRecovery').value),paceStability:Number($('phase50RefPace').value)}}
function render(){const v=state.verification||{status:'NOT_IMPORTED'},e=latest(state.executions)||{status:'V104_RELEASE_NOT_RUN'},s=latest(state.smokes)||{status:'V104_SMOKE_NOT_RUN'},z=latest(state.evaluations)||{status:'NOT_COLLECTED'},d=latest(state.decisions)||{status:'NOT_RECORDED'};for(const [id,val] of [['phase50InputBadge',v.status],['phase50RcBadge',v.rcGate?.status||'NOT_VERIFIED'],['phase50ReleaseBadge',e.status],['phase50SmokeBadge',s.status],['phase50StabilizationBadge',z.status],['phase50DecisionBadge',d.status]])if($(id)){ $(id).textContent=val;$(id).className=`status ${badgeClass(val)}` }
 if($('phase50SourceSha'))$('phase50SourceSha').textContent=v.bundleSha256||'-';if($('phase50PlanId'))$('phase50PlanId').textContent=v.rcGate?.planId||'-';if($('phase50StagingRunId'))$('phase50StagingRunId').textContent=v.candidateStaging?.runId||'-';if($('phase50CandidateIdentity'))$('phase50CandidateIdentity').textContent=v.candidateArtifactSha256||'-';if($('phase50ManifestIdentity'))$('phase50ManifestIdentity').textContent=v.assetManifestVersion?`${v.assetManifestVersion} / ${v.assetManifestSha256}`:'-';
 if(v.status==='PASS'){if($('phase50CandidateSha')&&!$('phase50CandidateSha').value)$('phase50CandidateSha').value=v.candidateArtifactSha256||'';if($('phase50ManifestVersion')&&!$('phase50ManifestVersion').value)$('phase50ManifestVersion').value=v.assetManifestVersion||'';if($('phase50ManifestSha')&&!$('phase50ManifestSha').value)$('phase50ManifestSha').value=v.assetManifestSha256||''}
 setReferenceInputs(referenceMetricsFromHistory());if($('phase50EvaluationResult'))$('phase50EvaluationResult').innerHTML=z?.evaluationId?`<div class="issue"><strong>${esc(z.status)}</strong><div class="note">learning ${esc(z.sufficientLearningDays||0)}d / ops ${esc(z.operationsDays||0)}d / P0·P1 ${esc(z.openP0P1||0)} / Daily regression ${esc(z.dailyStructureRegressionDays||0)} / content mismatch ${esc(z.contentMismatchDays||0)} / asset fail ${esc(z.assetIdentityFailureDays||0)} / ${esc(z.recommendation||'')}</div></div>`:'<div class="note">실제 v1.0.4 출시·스모크·14일 실사용 증거가 있어야 평가됩니다.</div>';
 if($('phase50History'))$('phase50History').innerHTML=[...state.executions.slice(0,2),...state.evaluations.slice(0,2),...state.decisions.slice(0,2),...state.rollbackExecutions.slice(0,2)].map(x=>`<div class="decisionRow"><div><strong>${esc(x.status||x.action)}</strong><div class="note">${esc(x.targetUrl||x.recommendation||x.reason||'')}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status||x.action)}</span></div>`).join('')||'<div class="note">No Phase 50 external record.</div>';if($('phase50Export'))$('phase50Export').disabled=!state.importRecord;
}
async function load(){state.snapshot=JK_STORAGE.getSnapshot();state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase50_phase49_rc_audit_import_saved')[0]||null;state.verification=state.importRecord?.verification||null;state.executions=rowsByType('phase50_v104_release_execution_saved');state.smokes=rowsByType('phase50_post_release_smoke_saved');state.ops=rowsByType('phase50_ops_snapshot_saved');state.incidents=rowsByType('phase50_incident_saved');state.evaluations=rowsByType('phase50_stabilization_saved');state.decisions=rowsByType('phase50_followup_decision_saved');state.rollbackExecutions=rowsByType('phase50_v103_rollback_execution_saved');render()}
async function verifyBundle(){const file=$('phase50BundleFile').files?.[0];if(!file){$('phase50ImportMessage').textContent='Phase 49 audit JSON을 선택하세요.';return}try{const bundle=JSON.parse(await file.text()),sha=await hashFile(file),verification=JK_PHASE50.verifyPhase49RcAuditBundle(bundle,{computedSha256:sha,expectedSha256:$('phase50ExpectedSha').value}),record={format:'JK_ENG_PHASE50_PHASE49_RC_AUDIT_IMPORT',version:'50.0',importId:verification.verificationId,phase49Bundle:bundle,phase49BundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:sha,expectedSha256:JK_PHASE50.normalizeHash($('phase50ExpectedSha').value)||null},verification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase50_phase49_rc_audit_import_saved',entityId:record.importId,payload:record});$('phase50ImportMessage').textContent=verification.status==='PASS'?'RC_APPROVED + STAGING_PASS + ROLLBACK_REHEARSAL_PASS 검증 완료.':'검증 실패: '+verification.errors.join(', ');await load()}catch(e){$('phase50ImportMessage').textContent='Import failed: '+(e.message||e)}}
async function executeRelease(){const file=$('phase50ExecutionBundleFile').files?.[0];if(!file||!state.verification){$('phase50ReleaseMessage').textContent='검증된 Phase 49 감사 번들을 동일 파일로 다시 선택하세요.';return}const sha=await hashFile(file),rec=JK_PHASE50.createExternalReleaseExecution({rehashedSha256:sha,targetUrl:$('phase50TargetUrl').value,operator:$('phase50ReleaseOperator').value,evidence:$('phase50ReleaseEvidence').value,actualExternalContext:$('phase50ReleaseExternal').checked,confirmationPhrase:$('phase50ReleaseConfirm').value,deployedCandidateSha256:$('phase50CandidateSha').value,deployedAssetManifestVersion:$('phase50ManifestVersion').value,deployedAssetManifestSha256:$('phase50ManifestSha').value},state.verification);await JK_STORAGE.appendApprovalAudit({type:'phase50_v104_release_execution_saved',entityId:rec.executionId,payload:rec});$('phase50ReleaseMessage').textContent=`${rec.status}: ${(rec.errors||[]).join(', ')||'recorded'}`;await load()}
async function runSmoke(){const exec=latest(state.executions),cfg=JK_PHASE50_DATA.policy.externalRelease,rec=JK_PHASE50.evaluatePostReleaseSmoke({actualExternalContext:$('phase50SmokeExternal').checked,operator:$('phase50SmokeOperator').value,tests:readTests(cfg.smokeTests,'phase50Smoke')},exec||{},state.verification||{});await JK_STORAGE.appendApprovalAudit({type:'phase50_post_release_smoke_saved',entityId:rec.runId,payload:rec});$('phase50SmokeMessage').textContent=`${rec.status}: ${(rec.errors||[]).join(', ')||'all pass'}`;await load()}
async function saveOps(){const rec=JK_PHASE50.createOpsSnapshot({date:$('phase50OpsDate').value,syncStatus:$('phase50SyncStatus').value,backupStatus:$('phase50BackupStatus').value,recoveryStatus:$('phase50RecoveryStatus').value,contentIdentityStatus:$('phase50ContentIdentityStatus').value,assetIdentityStatus:$('phase50AssetIdentityStatus').value,dailyStructureStatus:$('phase50DailyStructureStatus').value,operator:$('phase50OpsOperator').value,evidence:$('phase50OpsEvidence').value,actualExternalContext:$('phase50OpsExternal').checked},latest(state.executions)||{});if(!rec.accepted){$('phase50OpsMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase50_ops_snapshot_saved',entityId:rec.snapshotId,payload:rec});$('phase50OpsMessage').textContent='운영 스냅샷 기록 완료.';await load()}
async function saveIncident(){const rec=JK_PHASE50.normalizeIncident({severity:$('phase50IncidentSeverity').value,status:$('phase50IncidentStatus').value,category:$('phase50IncidentCategory').value,title:$('phase50IncidentTitle').value,detail:$('phase50IncidentDetail').value,evidence:$('phase50IncidentEvidence').value,at:new Date().toISOString()});await JK_STORAGE.appendApprovalAudit({type:'phase50_incident_saved',entityId:rec.incidentId,payload:rec});$('phase50IncidentMessage').textContent='Incident recorded.';await load()}
async function evaluate14(){const rec=JK_PHASE50.evaluateStabilization14({execution:latest(state.executions)||{},smoke:latest(state.smokes)||{},asOf:$('phase50AsOf').value,actualLearnerDataUsed:$('phase50LearnerData').checked,dailyReports:Object.values(state.snapshot?.dailyReports||{}),opsSnapshots:state.ops,incidents:state.incidents,referenceMetrics:getReferenceInputs()});await JK_STORAGE.appendApprovalAudit({type:'phase50_stabilization_saved',entityId:rec.evaluationId,payload:rec});$('phase50EvaluationMessage').textContent=`${rec.status} / ${rec.recommendation}`;await load()}
async function executeRollback(){const decision=latest(state.decisions),evaluation=latest(state.evaluations),execution=latest(state.executions);if(!decision||!evaluation||!execution){$('phase50RollbackExecutionMessage').textContent='Rollback request decision, Day-14 evaluation, and v1.0.4 release execution are required.';return}const rec=JK_PHASE50.recordExternalRollbackExecution({actualExternalContext:$('phase50RollbackExecutionExternal').checked,targetUrl:$('phase50RollbackExecutionUrl').value,target:$('phase50RollbackExecutionTarget').value,operator:$('phase50RollbackExecutionOperator').value,evidence:$('phase50RollbackExecutionEvidence').value,confirmationPhrase:$('phase50RollbackExecutionConfirm').value},decision,evaluation,execution);if(!rec.accepted){$('phase50RollbackExecutionMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase50_v103_rollback_execution_saved',entityId:rec.rollbackExecutionId,payload:rec});$('phase50RollbackExecutionMessage').textContent=rec.status;await load()}
async function decide(){const ev=latest(state.evaluations);if(!ev){$('phase50DecisionMessage').textContent='14-day evaluation is required.';return}const rec=JK_PHASE50.makeFollowupDecision({action:$('phase50DecisionAction').value,reviewer:$('phase50DecisionReviewer').value,reason:$('phase50DecisionReason').value,confirmationPhrase:$('phase50RollbackConfirm').value},ev);if(!rec.accepted){$('phase50DecisionMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase50_followup_decision_saved',entityId:rec.decisionId,payload:rec});$('phase50DecisionMessage').textContent=`${rec.status}. Automatic rollback was not performed.`;await load()}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE50.buildPhase50AuditBundle({phase49BundleMeta:state.importRecord?.phase49BundleMeta||null,phase49RcAuditVerification:state.verification,releaseExecutions:state.executions,smokeRuns:state.smokes,opsSnapshots:state.ops,incidents:state.incidents,stabilizationEvaluations:state.evaluations,followupDecisions:state.decisions}),`JK_ENG_Phase46_v104_Release_Stabilization_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();buildTestRows('phase50SmokeTests',JK_PHASE50_DATA.policy.externalRelease.smokeTests,'phase50Smoke');$('phase50OpsDate').value=new Date().toISOString().slice(0,10);$('phase50AsOf').value=new Date().toISOString().slice(0,10);$('phase50VerifyBundle').onclick=verifyBundle;$('phase50ExecuteRelease').onclick=executeRelease;$('phase50RunSmoke').onclick=runSmoke;$('phase50OpsSave').onclick=saveOps;$('phase50IncidentSave').onclick=saveIncident;$('phase50Evaluate14').onclick=evaluate14;$('phase50DecisionSave').onclick=decide;$('phase50RollbackExecutionSave').onclick=executeRollback;$('phase50Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase50ImportMessage');if(el)el.textContent=String(e.message||e)});
