(async function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={snapshot:null,audits:[],importRecord:null,verification:null,ops:[],newIncidents:[],incidentCloseouts:[],evaluations:[],maintenanceCloseouts:[],requests:[],windows:[]};
const sorted=rows=>(rows||[]).slice().sort((a,b)=>Date.parse(b.at||b.openedAt||b.requestedAt||b.closedAt||b.evaluatedAt||b.recordedAt||0)-Date.parse(a.at||a.openedAt||a.requestedAt||a.closedAt||a.evaluatedAt||a.recordedAt||0));
const rowsByType=type=>sorted(state.audits.filter(x=>x.type===type).map(x=>x.payload));
const latest=rows=>rows?.[0]||null;
async function hashFile(file){const b=await file.arrayBuffer(),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function badgeClass(s){s=String(s||'');return /PASS|STABLE|CLOSED|OPEN|RECORDED|REQUESTED/.test(s)?'pass':/FAIL|BLOCKED|ROLLBACK|REJECTED/.test(s)?'fail':/HOLD|INSUFFICIENT|NOT_/.test(s)?'warn':''}
function sourceIncidents(){return state.importRecord?.phase42Bundle?.incidents||[]}
function render(){
 const imp=state.verification||{status:'NOT_IMPORTED'},dec=imp.manualDecision||{action:'NOT_VERIFIED'},ev=latest(state.evaluations)||{status:'NOT_COLLECTED'},cl=latest(state.maintenanceCloseouts)||{status:'NOT_RECORDED'},win=latest(state.windows)||{status:'NOT_OPEN'};
 for(const [id,val] of [['phase43InputBadge',imp.status],['phase43DecisionBadge',dec.action],['phase43Day30Badge',ev.status],['phase43CloseoutBadge',cl.status],['phase43V103Badge',win.status]])if($(id)){$(id).textContent=val;$(id).className=`status ${badgeClass(val)}`}
 if($('phase43SourceSha'))$('phase43SourceSha').textContent=imp.bundleSha256||'-';
 if($('phase43ReleaseStatus'))$('phase43ReleaseStatus').textContent=imp.releaseExecution?.status||'NOT_VERIFIED';
 if($('phase43SmokeStatus'))$('phase43SmokeStatus').textContent=imp.postReleaseSmoke?.status||'NOT_VERIFIED';
 if($('phase43CandidateIdentity'))$('phase43CandidateIdentity').textContent=imp.releaseExecution?.deployedCandidateSha256||'-';
 if($('phase43AssetIdentity'))$('phase43AssetIdentity').textContent=imp.releaseExecution?.deployedAssetManifestVersion?`${imp.releaseExecution.deployedAssetManifestVersion} / ${imp.releaseExecution.deployedAssetManifestSha256||'-'}`:'-';
 if($('phase43EvaluationResult'))$('phase43EvaluationResult').innerHTML=ev?.evaluationId?`<div class="issue"><strong>${esc(ev.status)}</strong><div class="note">learning ${esc(ev.sufficientLearningDays||0)}d / ops ${esc(ev.operationsDays||0)}d / P0-P1 ${esc(ev.openP0P1||0)} / content mismatch ${esc(ev.contentMismatchDays||0)} / asset fail ${esc(ev.assetIdentityFailureDays||0)} / ${esc(ev.recommendation||'')}</div></div>`:'<div class="note">Actual CONTINUE handoff and Day-30 evidence are required.</div>';
 if($('phase43History'))$('phase43History').innerHTML=[...state.maintenanceCloseouts.slice(0,2),...state.requests.slice(0,2),...state.windows.slice(0,2)].map(x=>`<div class="decisionRow"><div><strong>${esc(x.status)}</strong><div class="note">${esc(x.title||x.reason||x.closeoutId||'')}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status)}</span></div>`).join('')||'<div class="note">No Phase 43 closeout/change-window record.</div>';
 if($('phase43Export'))$('phase43Export').disabled=!state.importRecord;
}
async function load(){
 state.snapshot=JK_STORAGE.getSnapshot();state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase43_phase42_audit_import_saved')[0]||null;state.verification=state.importRecord?.verification||null;state.ops=rowsByType('phase43_ops_snapshot_saved');state.newIncidents=rowsByType('phase43_incident_saved');state.incidentCloseouts=rowsByType('phase43_incident_closeout_saved');state.evaluations=rowsByType('phase43_confirmation30_saved');state.maintenanceCloseouts=rowsByType('phase43_maintenance_closeout_saved');state.requests=rowsByType('phase43_v103_change_request_saved');state.windows=rowsByType('phase43_v103_change_window_saved');render();
}
async function verifyBundle(){
 const file=$('phase43BundleFile').files?.[0];if(!file){$('phase43ImportMessage').textContent='Select a Phase 42 audit JSON.';return}
 try{const bundle=JSON.parse(await file.text()),sha=await hashFile(file),verification=JK_PHASE43.verifyPhase42AuditBundle(bundle,{computedSha256:sha,expectedSha256:$('phase43ExpectedSha').value}),record={format:'JK_ENG_PHASE43_PHASE42_AUDIT_IMPORT',version:'43.0',importId:verification.verificationId,phase42Bundle:bundle,phase42BundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:sha,expectedSha256:JK_PHASE43.normalizeHash($('phase43ExpectedSha').value)||null},verification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase43_phase42_audit_import_saved',entityId:record.importId,payload:record});$('phase43ImportMessage').textContent=verification.status==='PASS'?`Phase 42 audit verified / decision ${verification.manualDecision?.action}.`:'Verification failed: '+verification.errors.join(', ');await load()}catch(e){$('phase43ImportMessage').textContent='Import failed: '+(e.message||e)}
}
async function saveOps(){
 const rec=JK_PHASE43.createOpsSnapshot({date:$('phase43OpsDate').value,syncStatus:$('phase43SyncStatus').value,backupStatus:$('phase43BackupStatus').value,recoveryStatus:$('phase43RecoveryStatus').value,contentIdentityStatus:$('phase43ContentIdentityStatus').value,assetIdentityStatus:$('phase43AssetIdentityStatus').value,operator:$('phase43OpsOperator').value,evidence:$('phase43OpsEvidence').value,actualExternalContext:$('phase43OpsExternal').checked},state.verification||{});if(!rec.accepted){$('phase43OpsMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase43_ops_snapshot_saved',entityId:rec.snapshotId,payload:rec});$('phase43OpsMessage').textContent='Day-30 operations evidence recorded.';await load();
}
async function saveIncident(){
 const rec=JK_PHASE43.normalizeIncident({severity:$('phase43IncidentSeverity').value,status:$('phase43IncidentStatus').value,category:$('phase43IncidentCategory').value,title:$('phase43IncidentTitle').value,detail:$('phase43IncidentDetail').value,evidence:$('phase43IncidentEvidence').value,at:new Date().toISOString()});await JK_STORAGE.appendApprovalAudit({type:'phase43_incident_saved',entityId:rec.incidentId,payload:rec});$('phase43IncidentMessage').textContent=`Incident ${rec.incidentId} recorded.`;await load();
}
async function closeIncident(){
 const sources=[...sourceIncidents(),...state.newIncidents];const rec=JK_PHASE43.createIncidentCloseout({incidentId:$('phase43CloseIncidentId').value,reviewer:$('phase43CloseIncidentReviewer').value,resolution:$('phase43CloseIncidentResolution').value,evidence:$('phase43CloseIncidentEvidence').value},sources);if(!rec.accepted){$('phase43CloseIncidentMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase43_incident_closeout_saved',entityId:rec.closeoutId,payload:rec});$('phase43CloseIncidentMessage').textContent='Incident closeout recorded.';await load();
}
async function evaluate30(){
 const rec=JK_PHASE43.evaluateConfirmation30({asOf:$('phase43AsOf').value,actualLearnerDataUsed:$('phase43LearnerData').checked,dailyReports:Object.values(state.snapshot?.dailyReports||{}),opsSnapshots:state.ops,sourceIncidents:sourceIncidents(),newIncidents:state.newIncidents,incidentCloseouts:state.incidentCloseouts},state.verification||{});await JK_STORAGE.appendApprovalAudit({type:'phase43_confirmation30_saved',entityId:rec.evaluationId,payload:rec});$('phase43EvaluationMessage').textContent=`${rec.status} / ${rec.recommendation}`;await load();
}
async function closeMaintenance(){
 const rec=JK_PHASE43.createMaintenanceCloseout({operator:$('phase43CloseoutOperator').value,backupEvidence:$('phase43BackupEvidence').value,recoveryEvidence:$('phase43RecoveryEvidence').value,rollbackReadinessEvidence:$('phase43RollbackEvidence').value,contentIdentityEvidence:$('phase43ContentEvidence').value,assetIdentityEvidence:$('phase43AssetEvidence').value,actualExternalContext:$('phase43CloseoutExternal').checked,confirmationPhrase:$('phase43CloseoutConfirm').value},state.verification||{},latest(state.evaluations)||{},sourceIncidents(),state.newIncidents,state.incidentCloseouts,state.ops);if(!rec.accepted){$('phase43CloseoutMessage').textContent='Blocked: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase43_maintenance_closeout_saved',entityId:rec.closeoutId,payload:rec});$('phase43CloseoutMessage').textContent='v1.0.2 maintenance closed. v1.0.3 change window remains separate.';await load();
}
async function requestV103(){
 const impacts={questionBankShapeChange:$('phase43QuestionShapeChange').checked,dailyTimingChange:$('phase43DailyTimingChange').checked,stagedLearningLoopChange:$('phase43LoopChange').checked,automaticBehaviorChange:$('phase43AutoChange').checked};const rec=JK_PHASE43.createV103ChangeRequest({type:$('phase43RequestType').value,title:$('phase43RequestTitle').value,description:$('phase43RequestDescription').value,risk:$('phase43RequestRisk').value,contentBankChange:$('phase43ContentBankChange').checked,contentApprovalRef:$('phase43ContentApprovalRef').value,invariantImpacts:impacts,requestedBy:$('phase43RequestedBy').value},latest(state.maintenanceCloseouts)||{});if(!rec.accepted){$('phase43RequestMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase43_v103_change_request_saved',entityId:rec.requestId,payload:rec});$('phase43RequestMessage').textContent='v1.0.3 request recorded; no implementation, content, or deployment applied.';await load();
}
async function openWindow(){
 const rec=JK_PHASE43.openV103ChangeWindow({operator:$('phase43WindowOperator').value,reason:$('phase43WindowReason').value,confirmationPhrase:$('phase43WindowConfirm').value},latest(state.maintenanceCloseouts)||{},state.requests);if(!rec.accepted){$('phase43WindowMessage').textContent='Blocked: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase43_v103_change_window_saved',entityId:rec.windowId,payload:rec});$('phase43WindowMessage').textContent='v1.0.3 change window opened. This is not implementation or deployment authorization.';await load();
}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE43.buildCloseoutAuditBundle({phase42BundleMeta:state.importRecord?.phase42BundleMeta||null,phase42AuditVerification:state.verification,opsSnapshots:state.ops,newIncidents:state.newIncidents,incidentCloseouts:state.incidentCloseouts,confirmation30Evaluations:state.evaluations,maintenanceCloseouts:state.maintenanceCloseouts,v103ChangeRequests:state.requests,v103ChangeWindows:state.windows}),`JK_ENG_Phase43_v102_Closeout_v103_Window_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();$('phase43OpsDate').value=new Date().toISOString().slice(0,10);$('phase43AsOf').value=new Date().toISOString().slice(0,10);$('phase43VerifyBundle').onclick=verifyBundle;$('phase43OpsSave').onclick=saveOps;$('phase43IncidentSave').onclick=saveIncident;$('phase43CloseIncident').onclick=closeIncident;$('phase43Evaluate30').onclick=evaluate30;$('phase43MaintenanceClose').onclick=closeMaintenance;$('phase43RequestSave').onclick=requestV103;$('phase43WindowOpen').onclick=openWindow;$('phase43Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase43ImportMessage');if(el)el.textContent=String(e.message||e)});
