(async()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unwrap=row=>row?.payload&&typeof row.payload==='object'?row.payload:row;
let state={snapshot:null,audits:[],importRecord:null,verification:null,retention:[],monthly:[],requests:[],reviews:[],regressions:[],authorizations:[]};
function sorted(rows){return [...rows].sort((a,b)=>Date.parse(b.at||b.createdAt||b.recordedAt||b.reviewedAt||b.requestedAt||b.verifiedAt||b.authorizedAt||0)-Date.parse(a.at||a.createdAt||a.recordedAt||a.reviewedAt||a.requestedAt||a.verifiedAt||a.authorizedAt||0))}
function rowsByType(type){return state.audits.filter(x=>x.type===type).map(unwrap)}
async function hashFile(file){const digest=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function badgeClass(value){return ['PASS','STABLE','RECORDED','REQUESTED','APPROVED','REGRESSION_PASS','AUTHORIZED'].includes(value)?'PASS':['WATCH','INSUFFICIENT'].includes(value)?'OBSERVING':['CRITICAL_REVIEW','REJECTED','REGRESSION_FAIL','FAIL'].includes(value)?'FAIL':'NOT_RUN'}
function latestMonthly(){return state.monthly[0]||null}function latestRequest(){return state.requests[0]||null}function latestReview(){return state.reviews.find(x=>x.requestId===latestRequest()?.requestId)||state.reviews[0]||null}function latestRegression(){return state.regressions.find(x=>x.requestId===latestRequest()?.requestId)||state.regressions[0]||null}
function buildInvariantChecklist(){const box=$('phase37InvariantChecklist');if(!box)return;box.innerHTML=(JK_PHASE37_DATA.policy.changeControl?.requiredInvariantChecklist||[]).map(k=>`<label><input type="checkbox" id="phase37Inv_${esc(k)}">${esc(k)}</label>`).join('')}
function buildRegressionRows(){const box=$('phase37RegressionRows');if(!box)return;box.innerHTML=(JK_PHASE37_DATA.policy.regressionContract?.requiredTests||[]).map(id=>`<div class="smokeRow"><strong>${esc(id)}</strong><select id="phase37TestStatus_${esc(id)}"><option>NOT_RUN</option><option>PASS</option><option>FAIL</option></select><input id="phase37TestEvidence_${esc(id)}" placeholder="evidence file or log"></div>`).join('')}
function render(){
 const imp=state.verification||{status:'NOT_IMPORTED'},monthly=latestMonthly()||{status:'NOT_COLLECTED'},req=latestRequest()||{status:'NOT_RECORDED'},review=latestReview()||{status:'NOT_RECORDED'},reg=latestRegression()||{status:'NOT_RUN'},auth=state.authorizations[0]||{status:'NOT_RECORDED'};
 for(const [id,val] of [['phase37InputBadge',imp.status],['phase37MonthBadge',monthly.status],['phase37RequestBadge',req.status],['phase37ReviewBadge',review.status],['phase37RegressionBadge',reg.status],['phase37AuthBadge',auth.status]]){const el=$(id);if(el){el.textContent=val;el.className=`status ${badgeClass(val)}`}}
 if($('phase37SourceSha'))$('phase37SourceSha').textContent=imp.bundleSha256?`${imp.bundleSha256.slice(0,12)}...`:'-';
 if($('phase37Checkpoint30'))$('phase37Checkpoint30').textContent=imp.checkpoint30?.status||'NOT_COLLECTED';
 if($('phase37MonthResult'))$('phase37MonthResult').innerHTML=monthly.reviewId?`<strong>${esc(monthly.month)} ${esc(monthly.status)}</strong><div class="note">learning ${monthly.sufficientLearningDays||0}d / operations ${monthly.operationsDays||0}d / retention ${monthly.retentionEvidenceCount||0}; process ${monthly.currentMetrics?.processPassRate??'-'}; recovery ${monthly.currentMetrics?.recoveryRate??'-'}; pace ${monthly.currentMetrics?.paceStability??'-'}; sync failures ${monthly.syncFailureDays||0}; open P0/P1 ${monthly.openP0P1||0}</div>`:'No monthly review recorded.';
 if($('phase37RequestHistory'))$('phase37RequestHistory').innerHTML=state.requests.slice(0,6).map(x=>`<div class="decisionRow"><div><strong>${esc(x.changeType)} ${esc(x.severity)} - ${esc(x.title)}</strong><div class="note">${esc(x.summary)} | content bank ${x.contentBankChange?'CHANGE':'UNCHANGED'}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status)}</span></div>`).join('')||'<div class="note">No change request recorded.</div>';
 if($('phase37ReviewHistory'))$('phase37ReviewHistory').innerHTML=state.reviews.slice(0,6).map(x=>`<div class="decisionRow"><div><strong>${esc(x.decision)} - ${esc(x.reviewer)}</strong><div class="note">${esc(x.reason)}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status)}</span></div>`).join('')||'<div class="note">No review recorded.</div>';
 if($('phase37RegressionHistory'))$('phase37RegressionHistory').innerHTML=state.regressions.slice(0,6).map(x=>`<div class="decisionRow"><div><strong>${esc(x.status)}</strong><div class="note">${esc((x.errors||[]).join(', ')||'all invariant tests passed')}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status)}</span></div>`).join('')||'<div class="note">No regression verification recorded.</div>';
 if($('phase37ImportMessage'))$('phase37ImportMessage').textContent=imp.status==='PASS'?'Phase 36 30-day stable followup bundle verified.':'A real Phase 36 followup audit bundle with stable 30-day evidence is required.';
 if($('phase37Export'))$('phase37Export').disabled=!state.importRecord;
}
async function load(){state.snapshot=JK_STORAGE.getSnapshot();state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase37_phase36_bundle_import_saved')[0]||null;state.verification=state.importRecord?.verification||null;state.retention=rowsByType('phase37_retention_evidence_saved');state.monthly=rowsByType('phase37_monthly_review_saved');state.requests=rowsByType('phase37_change_request_saved');state.reviews=rowsByType('phase37_change_review_saved');state.regressions=rowsByType('phase37_regression_verification_saved');state.authorizations=rowsByType('phase37_v101_authorization_saved');render()}
async function verifyBundle(){const file=$('phase37BundleFile').files?.[0];if(!file){$('phase37ImportMessage').textContent='Select a Phase 36 followup audit JSON.';return}try{const bundle=JSON.parse(await file.text()),computedSha256=await hashFile(file),expectedSha256=$('phase37ExpectedSha').value,verification=JK_PHASE37.verifyPhase36LongTermBundle(bundle,{computedSha256,expectedSha256}),record={format:'JK_ENG_PHASE37_PHASE36_BUNDLE_IMPORT',version:'37.0',importId:verification.verificationId,approvedBundle:bundle,approvedBundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:computedSha256,expectedSha256:JK_PHASE37.normalizeHash(expectedSha256)||null},verification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase37_phase36_bundle_import_saved',entityId:record.importId,payload:record});await load();$('phase37ImportMessage').textContent=verification.status==='PASS'?'Verification PASS. Long-term monthly review is unlocked.':`Verification FAIL: ${verification.errors.join(', ')}`}catch(e){console.error(e);$('phase37ImportMessage').textContent=`Import failed: ${e.message||e}`}}
async function saveRetention(){const record=JK_PHASE37.normalizeRetentionEvidence({month:$('phase37RetentionMonth').value,retentionStatus:$('phase37RetentionStatus').value,backupStatus:$('phase37BackupStatus').value,recoveryStatus:$('phase37RecoveryStatus').value,operator:$('phase37RetentionOperator').value,evidence:$('phase37RetentionEvidence').value,actualExternalContext:$('phase37RetentionExternal').checked});if(!record.accepted){$('phase37RetentionMessage').textContent=`Record rejected: ${record.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase37_retention_evidence_saved',entityId:record.evidenceId,payload:record});$('phase37RetentionMessage').textContent='Retention/backup/recovery evidence recorded.';await load()}
async function evaluateMonth(){const month=$('phase37ReviewMonth').value,bundle=state.importRecord?.approvedBundle||{},localOps=rowsByType('phase36_followup_ops_snapshot_saved'),localIncidents=rowsByType('phase36_release_incident_saved'),reportRows=Object.values(state.snapshot?.dailyReports||{}),review=JK_PHASE37.buildMonthlyEffectReview({month,actualExternalContext:$('phase37ReviewExternal').checked,actualLearnerDataUsed:$('phase37ReviewLearnerData').checked,dailyReports:reportRows,opsSnapshots:[...(bundle.followupOperationsSnapshots||[]),...localOps],incidents:[...(bundle.releaseIncidents||[]),...localIncidents],retentionEvidence:state.retention},state.verification||{});await JK_STORAGE.appendApprovalAudit({type:'phase37_monthly_review_saved',entityId:review.reviewId,payload:review});$('phase37ReviewMessage').textContent=`Monthly review: ${review.status} / ${review.recommendation}`;await load()}
async function saveRequest(){const record=JK_PHASE37.createChangeRequest({changeType:$('phase37ChangeType').value,severity:$('phase37Severity').value,title:$('phase37ChangeTitle').value,summary:$('phase37ChangeSummary').value,requestedBy:$('phase37RequestedBy').value,incidentRef:$('phase37IncidentRef').value,contentBankChange:$('phase37ContentChange').checked,contentApprovalRef:$('phase37ContentApprovalRef').value});if(!record.accepted){$('phase37RequestMessage').textContent=`Request rejected: ${record.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase37_change_request_saved',entityId:record.requestId,payload:record});$('phase37RequestMessage').textContent='Change request recorded. No deployment or content apply was performed.';await load()}
async function saveReview(){const request=latestRequest();if(!request){$('phase37ReviewDecisionMessage').textContent='A valid change request is required.';return}const checklist={};for(const key of JK_PHASE37_DATA.policy.changeControl?.requiredInvariantChecklist||[])checklist[key]=$(`phase37Inv_${key}`).checked;const record=JK_PHASE37.reviewChangeRequest({decision:$('phase37ReviewDecision').value,reviewer:$('phase37Reviewer').value,reason:$('phase37ReviewReason').value,checklist},request);if(!record.accepted){$('phase37ReviewDecisionMessage').textContent=`Review rejected: ${record.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase37_change_review_saved',entityId:record.reviewId,payload:record});$('phase37ReviewDecisionMessage').textContent=`Review ${record.status}.`;await load()}
async function saveRegression(){const request=latestRequest(),review=latestReview();if(!request||!review){$('phase37RegressionMessage').textContent='An approved review is required.';return}const tests={};for(const id of JK_PHASE37_DATA.policy.regressionContract?.requiredTests||[])tests[id]={status:$(`phase37TestStatus_${id}`).value,evidence:$(`phase37TestEvidence_${id}`).value};const record=JK_PHASE37.recordRegressionVerification({tests,observed:{questionCount:$('phase37QuestionCount').value,coreFamilyCount:$('phase37CoreFamilyCount').value,allFamilyCount:$('phase37AllFamilyCount').value,grammarMinutes:$('phase37GrammarMinutes').value,readingMinutes:$('phase37ReadingMinutes').value,resultMinutes:$('phase37ResultMinutes').value},verifiedBy:$('phase37RegressionVerifier').value},request,review);await JK_STORAGE.appendApprovalAudit({type:'phase37_regression_verification_saved',entityId:record.verificationId,payload:record});$('phase37RegressionMessage').textContent=`Regression ${record.status}: ${(record.errors||[]).join(', ')||'all pass'}`;await load()}
async function authorize(){const request=latestRequest(),review=latestReview(),regression=latestRegression(),monthly=latestMonthly();const record=JK_PHASE37.authorizeV101Release({reviewer:$('phase37AuthReviewer').value,reason:$('phase37AuthReason').value,confirmationPhrase:$('phase37AuthConfirm').value},request||{},review||{},regression||{},monthly||{});if(!record.accepted){$('phase37AuthMessage').textContent=`Authorization rejected: ${record.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase37_v101_authorization_saved',entityId:record.authorizationId,payload:record});$('phase37AuthMessage').textContent='v1.0.1 release authorization recorded. External release remains NOT_RUN.';await load()}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE37.buildMonthlyAuditBundle({phase36BundleMeta:state.importRecord?.approvedBundleMeta||null,phase36Verification:state.verification,monthlyReviews:state.monthly,retentionEvidence:state.retention,changeRequests:state.requests,changeReviews:state.reviews,regressionVerifications:state.regressions,releaseAuthorizations:state.authorizations}),`JK_ENG_Phase37_Monthly_Maintenance_Audit_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();buildInvariantChecklist();buildRegressionRows();const month=new Date().toISOString().slice(0,7);$('phase37RetentionMonth').value=month;$('phase37ReviewMonth').value=month;const rc=JK_PHASE37_DATA.policy.regressionContract||{};$('phase37QuestionCount').value=rc.expectedQuestionCount;$('phase37CoreFamilyCount').value=rc.expectedCoreFamilyCount;$('phase37AllFamilyCount').value=rc.expectedAllFamilyCount;$('phase37GrammarMinutes').value=rc.expectedGrammarMinutes;$('phase37ReadingMinutes').value=rc.expectedReadingMinutes;$('phase37ResultMinutes').value=rc.expectedResultMinutes;$('phase37VerifyBundle').onclick=verifyBundle;$('phase37RetentionSave').onclick=saveRetention;$('phase37ReviewEvaluate').onclick=evaluateMonth;$('phase37RequestSave').onclick=saveRequest;$('phase37ReviewSave').onclick=saveReview;$('phase37RegressionSave').onclick=saveRegression;$('phase37AuthSave').onclick=authorize;$('phase37Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase37ImportMessage');if(el)el.textContent=String(e.message||e)});
