(function(global){
'use strict';
const VERSION='48.0';
const text=v=>String(v==null?'':v).trim();
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const nowIso=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
const policy=()=>global.JK_PHASE48_DATA?.policy||{};
const normalizeHash=v=>text(v).toLowerCase().replace(/^sha256:/,'').trim();
const latest=(rows=[],field)=>((Array.isArray(rows)?rows:[]).slice().sort((a,b)=>Date.parse(b?.[field]||b?.approvedAt||b?.testedAt||b?.reviewedAt||b?.openedAt||b?.closedAt||b?.requestedAt||b?.at||0)-Date.parse(a?.[field]||a?.approvedAt||a?.testedAt||a?.reviewedAt||a?.openedAt||a?.closedAt||a?.requestedAt||a?.at||0))[0]||null);
function verifyPhase47AuditBundle(bundle={},options={},p=policy()){
 const cfg=p.acceptedPhase47Bundle||{},checks=[],errors=[];const add=(id,ok,detail='')=>{checks.push({id,ok:Boolean(ok),detail:text(detail)});if(!ok)errors.push(id)};
 const computed=normalizeHash(options.computedSha256),expected=normalizeHash(options.expectedSha256),closeout=latest(bundle?.maintenanceCloseouts||[],'closedAt'),windowRec=latest(bundle?.v104ChangeWindows||[],'openedAt'),requests=(bundle?.v104ChangeRequests||[]).filter(x=>x?.accepted===true&&x?.status===cfg.acceptedRequestStatus);
 add('BUNDLE_FORMAT',bundle?.format===cfg.format,bundle?.format||'missing');add('BUNDLE_VERSION',bundle?.version===cfg.version,bundle?.version||'missing');add('MAINTENANCE_TARGET',bundle?.maintenanceTarget===cfg.maintenanceTarget,bundle?.maintenanceTarget||'missing');add('NEXT_CHANGE_TARGET',bundle?.nextChangeTarget===cfg.nextChangeTarget,bundle?.nextChangeTarget||'missing');add('SOURCE_SHA256_COMPUTED',/^[a-f0-9]{64}$/.test(computed),computed||'missing');if(expected)add('SOURCE_SHA256_MATCH',computed===expected,computed===expected?'match':'mismatch');
 add('V103_MAINTENANCE_CLOSED',closeout?.status===cfg.requiredMaintenanceStatus&&closeout?.accepted===true&&(!cfg.actualExternalCloseoutRequired||closeout?.actualExternalContext===true),closeout?.status||'missing');add('V104_CHANGE_WINDOW_OPEN',windowRec?.status===cfg.requiredWindowStatus&&windowRec?.accepted===true,windowRec?.status||'missing');add('WINDOW_CLOSEOUT_LINK',Boolean(closeout&&windowRec&&text(windowRec.maintenanceCloseoutId)===text(closeout.closeoutId)),windowRec?.maintenanceCloseoutId||'missing');add('WINDOW_REQUESTS_PRESENT',Array.isArray(windowRec?.requestIds)&&windowRec.requestIds.length>0,String(windowRec?.requestIds?.length||0));
 const requestIds=new Set(requests.map(x=>text(x.requestId)));const missingWindowRequests=(windowRec?.requestIds||[]).filter(id=>!requestIds.has(text(id)));add('WINDOW_REQUESTS_RESOLVED',missingWindowRequests.length===0,missingWindowRequests.join(','));
 const linked=requests.filter(x=>(windowRec?.requestIds||[]).map(text).includes(text(x.requestId)));const pass=errors.length===0;return {format:'JK_ENG_PHASE48_PHASE47_AUDIT_VERIFICATION',version:VERSION,verificationId:text(options.verificationId)||uid('phase47-audit'),status:pass?'PASS':'FAIL',accepted:pass,eligibleForReview:pass,bundleSha256:computed,expectedSha256:expected||null,maintenanceCloseout:clone(closeout),changeWindow:clone(windowRec),acceptedRequests:clone(linked),checks,errors,verifiedAt:nowIso(),automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false};
}
function reviewV104Request(input={},verification={},p=policy()){
 const cfg=p.requestReview||{},requestId=text(input.requestId),request=(verification?.acceptedRequests||[]).find(x=>text(x.requestId)===requestId),decision=text(input.decision).toUpperCase(),riskLevel=text(input.riskLevel).toUpperCase(),reviewer=text(input.reviewer),scope=text(input.scopeAssessment),risk=text(input.riskAssessment),rollback=text(input.rollbackPlan),errors=[];
 if(verification?.status!=='PASS'||verification?.eligibleForReview!==true)errors.push('PHASE47_OPEN_CHANGE_WINDOW_AUDIT_REQUIRED');if(!request)errors.push('WINDOW_REQUEST_NOT_FOUND');if(!(cfg.decisions||[]).includes(decision))errors.push('DECISION_INVALID');if(!(cfg.riskLevels||[]).includes(riskLevel))errors.push('RISK_LEVEL_INVALID');if(cfg.reviewerRequired!==false&&!reviewer)errors.push('REVIEWER_REQUIRED');if(cfg.scopeAssessmentRequired!==false&&!scope)errors.push('SCOPE_ASSESSMENT_REQUIRED');if(cfg.riskAssessmentRequired!==false&&!risk)errors.push('RISK_ASSESSMENT_REQUIRED');if(cfg.rollbackPlanRequired!==false&&!rollback)errors.push('ROLLBACK_PLAN_REQUIRED');
 const invariantMap=request?.invariantImpacts||request?.invariants||{};if(Object.values(invariantMap).some(Boolean))errors.push('PROTECTED_LEARNING_INVARIANT_MUTATION');
 const contentChange=Boolean(request?.contentBankChange)||request?.type==='CONTENT',approvalRef=text(input.contentApprovalRef),approvalStatus=text(input.contentApprovalStatus).toUpperCase(),approvalEvidence=text(input.contentApprovalEvidence);if(contentChange&&cfg.contentBankChangeRequiresSeparateApproval!==false){if(!text(request?.contentApprovalRef))errors.push('SOURCE_CONTENT_APPROVAL_REF_MISSING');if(!approvalRef||approvalRef!==text(request?.contentApprovalRef))errors.push('CONTENT_APPROVAL_REF_MISMATCH');if(approvalStatus!==cfg.contentApprovalStatusRequired)errors.push('CONTENT_APPROVAL_NOT_APPROVED');if(cfg.contentApprovalEvidenceRequired!==false&&!approvalEvidence)errors.push('CONTENT_APPROVAL_EVIDENCE_REQUIRED')}
 const accepted=errors.length===0;return {format:'JK_ENG_PHASE48_V104_REQUEST_REVIEW',version:VERSION,reviewId:text(input.reviewId)||uid('v104-review'),requestId,status:accepted?(decision==='AUTHORIZE'?'AUTHORIZED':decision==='HOLD'?'HELD':'REJECTED'):'REVIEW_REJECTED',accepted,errors,decision,riskLevel,reviewer,scopeAssessment:scope,riskAssessment:risk,rollbackPlan:rollback,contentBankChange:contentChange,contentApprovalRef:approvalRef||request?.contentApprovalRef||null,contentApprovalStatus:contentChange?approvalStatus||'NOT_VERIFIED':'NOT_REQUIRED',contentApprovalEvidence:approvalEvidence||null,reviewedAt:input.reviewedAt||nowIso(),immutable:true,automaticImplementation:false,automaticContentApply:false};
}
function assessLearnerImpact(input={},verification={},reviews=[],p=policy()){
 const cfg=p.learnerImpactGuardrail||{},reviewer=text(input.reviewer),evidence=text(input.evidence),impacts=input.impacts||{},preserve=input.preservations||{},errors=[];if(verification?.status!=='PASS')errors.push('PHASE47_AUDIT_REQUIRED');const requestIds=(verification?.changeWindow?.requestIds||[]).map(text);const reviewed=new Set((reviews||[]).filter(x=>x?.accepted===true).map(x=>text(x.requestId)));for(const id of requestIds)if(!reviewed.has(id))errors.push(`REQUEST_REVIEW_MISSING_${id}`);if(cfg.reviewerRequired!==false&&!reviewer)errors.push('REVIEWER_REQUIRED');if(cfg.evidenceRequired!==false&&!evidence)errors.push('EVIDENCE_REQUIRED');for(const key of cfg.requiredPreservations||[])if(preserve[key]!==true)errors.push(`PRESERVATION_REQUIRED_${key.toUpperCase()}`);for(const key of cfg.forbiddenImpacts||[])if(impacts[key]===true)errors.push(`FORBIDDEN_IMPACT_${key.toUpperCase()}`);const pass=errors.length===0;return {format:'JK_ENG_PHASE48_V104_LEARNER_IMPACT_GUARDRAIL',version:VERSION,guardrailId:text(input.guardrailId)||uid('v104-guardrail'),status:pass?'GUARDRAIL_PASS':'GUARDRAIL_BLOCKED',accepted:pass,errors,requestIds,reviewer,evidence,preservations:clone(preserve),impacts:clone(impacts),numericCountdownVisible:Boolean(impacts.numericCountdownVisible),processScoringPreserved:preserve.processScoringPreserved===true,textbookReturnLoopPreserved:preserve.textbookReturnLoopPreserved===true,dailyStructurePreserved:preserve.dailyStructurePreserved===true,grammarMinutes:p.learningInvariants?.grammarMinutes||21,readingMinutes:p.learningInvariants?.readingMinutes||18,resultMinutes:p.learningInvariants?.resultMinutes||1,assessedAt:input.assessedAt||nowIso(),immutable:true};
}
function createControlledChangePlan(input={},verification={},reviews=[],guardrail={},p=policy()){
 const cfg=p.controlledChangePlan||{},operator=text(input.operator),owner=text(input.owner),scopeSummary=text(input.scopeSummary),rollbackPlan=text(input.rollbackPlan),confirmation=text(input.confirmationPhrase),errors=[];if(verification?.status!=='PASS'||verification?.eligibleForReview!==true)errors.push('PHASE47_OPEN_CHANGE_WINDOW_AUDIT_REQUIRED');const ids=(verification?.changeWindow?.requestIds||[]).map(text),validReviews=(reviews||[]).filter(x=>x?.accepted===true),byId=new Map(validReviews.map(x=>[text(x.requestId),x]));if(cfg.allWindowRequestsReviewed!==false)for(const id of ids)if(!byId.has(id))errors.push(`REQUEST_REVIEW_MISSING_${id}`);if(cfg.allWindowRequestsAuthorized!==false)for(const id of ids)if(byId.get(id)?.decision!=='AUTHORIZE')errors.push(`REQUEST_NOT_AUTHORIZED_${id}`);if(cfg.guardrailPassRequired!==false&&guardrail?.status!=='GUARDRAIL_PASS')errors.push('LEARNER_IMPACT_GUARDRAIL_PASS_REQUIRED');if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');if(cfg.ownerRequired!==false&&!owner)errors.push('OWNER_REQUIRED');if(cfg.scopeSummaryRequired!==false&&!scopeSummary)errors.push('SCOPE_SUMMARY_REQUIRED');if(cfg.rollbackPlanRequired!==false&&!rollbackPlan)errors.push('ROLLBACK_PLAN_REQUIRED');if(confirmation!==cfg.confirmationPhrase)errors.push('CHANGE_PLAN_CONFIRMATION_MISMATCH');const approved=errors.length===0;return {format:'JK_ENG_PHASE48_V104_CONTROLLED_CHANGE_PLAN',version:VERSION,planId:text(input.planId)||uid('v104-plan'),target:'JK English v1.0.4',rollbackTarget:p.rollbackTarget||'JK English v1.0.3',status:approved?'PLAN_APPROVED':'PLAN_BLOCKED',accepted:approved,errors,requestIds:ids,reviewIds:ids.map(id=>byId.get(id)?.reviewId).filter(Boolean),guardrailId:guardrail?.guardrailId||null,operator,owner,scopeSummary,rollbackPlan,confirmationMatched:confirmation===cfg.confirmationPhrase,approvedAt:approved?(input.approvedAt||nowIso()):null,implementationAuthorization:approved?'MANUAL_IMPLEMENTATION_AUTHORIZED':'NOT_RECORDED',automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false};
}
function createStagingValidation(input={},plan={},guardrail={},p=policy()){
 const cfg=p.stagingMatrix||{},actual=Boolean(input.actualStagingContext),url=text(input.stagingUrl),operator=text(input.operator),rows=Array.isArray(input.cases)?input.cases:[],byId=new Map(rows.map(x=>[text(x.id),x])),errors=[];if(plan?.status!=='PLAN_APPROVED'||plan?.accepted!==true)errors.push('APPROVED_CHANGE_PLAN_REQUIRED');if(guardrail?.status!=='GUARDRAIL_PASS')errors.push('GUARDRAIL_PASS_REQUIRED');const normalized=(cfg.cases||[]).map(c=>{const x=byId.get(c.id)||{},status=text(x.status||'NOT_RUN').toUpperCase(),evidence=text(x.evidence);if(!(cfg.allowedStatuses||[]).includes(status))errors.push(`STAGING_STATUS_INVALID_${c.id}`);if(status!=='NOT_RUN'&&cfg.evidenceRequiredPerCase!==false&&!evidence)errors.push(`STAGING_EVIDENCE_REQUIRED_${c.id}`);return {id:c.id,label:c.label,status:(cfg.allowedStatuses||[]).includes(status)?status:'NOT_RUN',evidence}});const anyRun=normalized.some(x=>x.status!=='NOT_RUN');if(anyRun&&cfg.actualStagingContextRequired!==false&&!actual)errors.push('ACTUAL_STAGING_CONTEXT_REQUIRED');if(anyRun&&cfg.httpsRequired!==false&&!/^https:\/\//i.test(url))errors.push('HTTPS_STAGING_URL_REQUIRED');if(anyRun&&cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');const failed=normalized.some(x=>x.status==='FAIL'),allPass=normalized.length>0&&normalized.every(x=>x.status==='PASS'),allNotRun=normalized.every(x=>x.status==='NOT_RUN');let status=cfg.incompleteStatus||'STAGING_INCOMPLETE';if(errors.length&&anyRun)status=cfg.failStatus||'STAGING_FAIL';else if(failed)status=cfg.failStatus||'STAGING_FAIL';else if(allPass&&actual&&/^https:\/\//i.test(url)&&operator)status=cfg.passStatus||'STAGING_PASS';else if(allNotRun)status=cfg.notRunStatus||'STAGING_NOT_RUN';const accepted=status==='STAGING_PASS'&&errors.length===0;return {format:'JK_ENG_PHASE48_V104_STAGING_VALIDATION',version:VERSION,runId:text(input.runId)||uid('v104-staging'),status,accepted,errors,planId:plan?.planId||null,guardrailId:guardrail?.guardrailId||null,actualStagingContext:actual,stagingUrl:url||null,operator:operator||null,cases:normalized,testedAt:input.testedAt||nowIso(),deploymentAuthorization:'NOT_GRANTED',automaticDeployment:false,automaticRollback:false};
}
function buildPhase48AuditBundle(input={},p=policy()){
 return {format:'JK_ENG_PHASE48_V104_CHANGE_PLAN_STAGING_AUDIT_BUNDLE',version:VERSION,changeTarget:p.changeTarget||'JK English v1.0.4',rollbackTarget:p.rollbackTarget||'JK English v1.0.3',exportedAt:nowIso(),policy:clone(p),state:clone(global.JK_PHASE48_DATA?.state||{}),phase47BundleMeta:clone(input.phase47BundleMeta||null),phase47AuditVerification:clone(input.phase47AuditVerification||null),requestReviews:clone(input.requestReviews||[]),learnerImpactGuardrails:clone(input.learnerImpactGuardrails||[]),controlledChangePlans:clone(input.controlledChangePlans||[]),stagingValidations:clone(input.stagingValidations||[]),truthfulBoundary:{changeWindowIsNotImplementationAuthorization:true,planApprovalIsNotDeployment:true,stagingPassIsNotProductionRelease:true,contentWindowIsNotContentApproval:true,automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false,localOrSyntheticCannotPromoteExternalState:true}};
}
const api={VERSION,normalizeHash,latest,verifyPhase47AuditBundle,reviewV104Request,assessLearnerImpact,createControlledChangePlan,createStagingValidation,buildPhase48AuditBundle};global.JK_PHASE48=api;
})(typeof window!=='undefined'?window:globalThis);
