(async function(){
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={audits:[],importRecord:null,verification:null,reviews:[],guardrails:[],plans:[],staging:[]};
const sorted=a=>(a||[]).slice().sort((x,y)=>Date.parse(y?.at||y?.payload?.testedAt||y?.payload?.approvedAt||y?.payload?.reviewedAt||0)-Date.parse(x?.at||x?.payload?.testedAt||x?.payload?.approvedAt||x?.payload?.reviewedAt||0));
const rowsByType=t=>state.audits.filter(x=>x?.type===t).map(x=>x.payload||x).filter(Boolean);
const latest=rows=>JK_PHASE48.latest(rows);
const hashFile=async f=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',await f.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');
function badgeClass(v){return ['PASS','AUTHORIZED','GUARDRAIL_PASS','PLAN_APPROVED','STAGING_PASS','MAINTENANCE_CLOSED','V104_CHANGE_WINDOW_OPEN'].includes(v)?'PASS':['FAIL','REJECTED','REVIEW_REJECTED','GUARDRAIL_BLOCKED','PLAN_BLOCKED','STAGING_FAIL'].includes(v)?'FAIL':'NOT_RUN'}
function render(){const v=state.verification||{status:'NOT_IMPORTED'},g=latest(state.guardrails)||{status:'NOT_RECORDED'},p=latest(state.plans)||{status:'NOT_RECORDED'},s=latest(state.staging)||{status:'NOT_RUN'};for(const [id,val] of [['phase48InputBadge',v.status],['phase48CloseoutBadge',v.maintenanceCloseout?.status||'NOT_VERIFIED'],['phase48WindowBadge',v.changeWindow?.status||'NOT_VERIFIED'],['phase48GuardrailBadge',g.status],['phase48PlanBadge',p.status],['phase48StagingBadge',s.status]])if($(id)){$(id).textContent=val;$(id).className=`status ${badgeClass(val)}`};if($('phase48SourceSha'))$('phase48SourceSha').textContent=v.bundleSha256||'-';if($('phase48RequestList'))$('phase48RequestList').innerHTML=(v.acceptedRequests||[]).map(r=>`<div class="decisionRow"><div><strong>${esc(r.requestId)}</strong><div class="note">${esc(r.type)} / ${esc(r.title)} / content approval ${esc(r.contentApprovalRef||'not required')}</div></div><span class="status ${badgeClass((state.reviews.find(x=>x.requestId===r.requestId)||{}).status||'NOT_RECORDED')}">${esc((state.reviews.find(x=>x.requestId===r.requestId)||{}).status||'NOT_RECORDED')}</span></div>`).join('')||'<div class="note">No verified Phase 47 requests.</div>';if($('phase48RequestId')){$('phase48RequestId').innerHTML='<option value="">Select request</option>'+(v.acceptedRequests||[]).map(r=>`<option value="${esc(r.requestId)}">${esc(r.requestId)} - ${esc(r.title)}</option>`).join('')};if($('phase48History'))$('phase48History').innerHTML=[...state.reviews.slice(0,3),...state.guardrails.slice(0,1),...state.plans.slice(0,1),...state.staging.slice(0,1)].map(x=>`<div class="decisionRow"><div><strong>${esc(x.status)}</strong><div class="note">${esc(x.requestId||x.planId||x.guardrailId||x.runId||'')}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status)}</span></div>`).join('')||'<div class="note">No Phase 48 records.</div>';if($('phase48Export'))$('phase48Export').disabled=!state.importRecord;}
async function load(){state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase48_phase47_audit_import_saved')[0]||null;state.verification=state.importRecord?.verification||null;state.reviews=rowsByType('phase48_request_review_saved');state.guardrails=rowsByType('phase48_guardrail_saved');state.plans=rowsByType('phase48_change_plan_saved');state.staging=rowsByType('phase48_staging_run_saved');render()}
async function verifyBundle(){const file=$('phase48BundleFile').files?.[0];if(!file){$('phase48ImportMessage').textContent='Select a Phase 47 audit JSON.';return}try{const bundle=JSON.parse(await file.text()),sha=await hashFile(file),verification=JK_PHASE48.verifyPhase47AuditBundle(bundle,{computedSha256:sha,expectedSha256:$('phase48ExpectedSha').value}),record={format:'JK_ENG_PHASE48_PHASE47_AUDIT_IMPORT',version:'48.0',importId:verification.verificationId,phase47Bundle:bundle,phase47BundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:sha,expectedSha256:JK_PHASE48.normalizeHash($('phase48ExpectedSha').value)||null},verification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase48_phase47_audit_import_saved',entityId:record.importId,payload:record});$('phase48ImportMessage').textContent=verification.status==='PASS'?'Phase 47 maintenance closeout and v1.0.4 open window verified.':'Verification failed: '+verification.errors.join(', ');await load()}catch(e){$('phase48ImportMessage').textContent='Import failed: '+(e.message||e)}}
async function saveReview(){const rec=JK_PHASE48.reviewV104Request({requestId:$('phase48RequestId').value,decision:$('phase48ReviewDecision').value,riskLevel:$('phase48RiskLevel').value,reviewer:$('phase48Reviewer').value,scopeAssessment:$('phase48ScopeAssessment').value,riskAssessment:$('phase48RiskAssessment').value,rollbackPlan:$('phase48ReviewRollback').value,contentApprovalRef:$('phase48ContentApprovalRef').value,contentApprovalStatus:$('phase48ContentApprovalStatus').value,contentApprovalEvidence:$('phase48ContentApprovalEvidence').value},state.verification||{});if(!rec.accepted){$('phase48ReviewMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase48_request_review_saved',entityId:rec.reviewId,payload:rec});$('phase48ReviewMessage').textContent=`${rec.status}; no implementation was applied.`;await load()}
async function saveGuardrail(){const preservations={processScoringPreserved:$('phase48PreserveProcess').checked,textbookReturnLoopPreserved:$('phase48PreserveTextbook').checked,evidenceMarkingPreserved:$('phase48PreserveEvidence').checked,originalRetryPreserved:$('phase48PreserveRetry').checked,nonAnxietyPacingPreserved:$('phase48PreservePacing').checked,dailyStructurePreserved:$('phase48PreserveDaily').checked};const impacts={numericCountdownVisible:$('phase48ImpactCountdown').checked,bypassProcessScoring:$('phase48ImpactProcessBypass').checked,bypassTextbookReturn:$('phase48ImpactTextbookBypass').checked,bypassEvidenceMarking:$('phase48ImpactEvidenceBypass').checked,bypassOriginalRetry:$('phase48ImpactRetryBypass').checked,dailyTimingMutation:$('phase48ImpactDailyTiming').checked,automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false};const rec=JK_PHASE48.assessLearnerImpact({reviewer:$('phase48GuardrailReviewer').value,evidence:$('phase48GuardrailEvidence').value,preservations,impacts},state.verification||{},state.reviews);await JK_STORAGE.appendApprovalAudit({type:'phase48_guardrail_saved',entityId:rec.guardrailId,payload:rec});$('phase48GuardrailMessage').textContent=`${rec.status}${rec.errors.length?': '+rec.errors.join(', '):''}`;await load()}
async function approvePlan(){const rec=JK_PHASE48.createControlledChangePlan({operator:$('phase48PlanOperator').value,owner:$('phase48PlanOwner').value,scopeSummary:$('phase48PlanScope').value,rollbackPlan:$('phase48PlanRollback').value,confirmationPhrase:$('phase48PlanConfirm').value},state.verification||{},state.reviews,latest(state.guardrails)||{});if(!rec.accepted){$('phase48PlanMessage').textContent='Blocked: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase48_change_plan_saved',entityId:rec.planId,payload:rec});$('phase48PlanMessage').textContent='Controlled plan approved. Deployment remains manual and separate.';await load()}
async function saveStaging(){const ids=['AUTH','DAILY_LOOP','MULTI_DEVICE_RESUME','OFFLINE_RECOVERY','ADMIN_RECOVERY','ASSET_INTEGRITY','ROLLBACK_READINESS'],cases=ids.map(id=>({id,status:$(`phase48Stage${id}Status`).value,evidence:$(`phase48Stage${id}Evidence`).value}));const rec=JK_PHASE48.createStagingValidation({actualStagingContext:$('phase48StagingActual').checked,stagingUrl:$('phase48StagingUrl').value,operator:$('phase48StagingOperator').value,cases},latest(state.plans)||{},latest(state.guardrails)||{});await JK_STORAGE.appendApprovalAudit({type:'phase48_staging_run_saved',entityId:rec.runId,payload:rec});$('phase48StagingMessage').textContent=`${rec.status}${rec.errors.length?': '+rec.errors.join(', '):''}. Production release is not authorized here.`;await load()}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE48.buildPhase48AuditBundle({phase47BundleMeta:state.importRecord?.phase47BundleMeta||null,phase47AuditVerification:state.verification,requestReviews:state.reviews,learnerImpactGuardrails:state.guardrails,controlledChangePlans:state.plans,stagingValidations:state.staging}),`JK_ENG_Phase48_v104_ChangePlan_Staging_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();$('phase48VerifyBundle').onclick=verifyBundle;$('phase48ReviewSave').onclick=saveReview;$('phase48GuardrailSave').onclick=saveGuardrail;$('phase48PlanApprove').onclick=approvePlan;$('phase48StagingSave').onclick=saveStaging;$('phase48Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase48ImportMessage');if(el)el.textContent=String(e.message||e)});
