(async function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={snapshot:null,audits:[],importRecord:null,verification:null,ops:[],newIncidents:[],incidentCloseouts:[],evaluations:[],maintenanceCloseouts:[],requests:[],windows:[]};
const sorted=rows=>(rows||[]).slice().sort((a,b)=>Date.parse(b.at||b.openedAt||b.requestedAt||b.closedAt||b.evaluatedAt||b.recordedAt||0)-Date.parse(a.at||a.openedAt||a.requestedAt||a.closedAt||a.evaluatedAt||a.recordedAt||0));
const rowsByType=type=>sorted(state.audits.filter(x=>x.type===type).map(x=>x.payload));
const latest=rows=>rows?.[0]||null;
async function hashFile(file){const b=await file.arrayBuffer(),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function badgeClass(s){s=String(s||'');return /PASS|STABLE|CLOSED|OPEN|RECORDED|REQUESTED/.test(s)?'pass':/FAIL|BLOCKED|ROLLBACK|REJECTED/.test(s)?'fail':/HOLD|INSUFFICIENT|NOT_/.test(s)?'warn':''}
function sourceIncidents(){return state.importRecord?.phase46Bundle?.incidents||[]}
function render(){
 const imp=state.verification||{status:'NOT_IMPORTED'},dec=imp.manualDecision||{action:'NOT_VERIFIED'},ev=latest(state.evaluations)||{status:'NOT_COLLECTED'},cl=latest(state.maintenanceCloseouts)||{status:'NOT_RECORDED'},win=latest(state.windows)||{status:'NOT_OPEN'};
 for(const [id,val] of [['phase47InputBadge',imp.status],['phase47DecisionBadge',dec.action],['phase47Day30Badge',ev.status],['phase47CloseoutBadge',cl.status],['phase47V104Badge',win.status]])if($(id)){$(id).textContent=val;$(id).className=`status ${badgeClass(val)}`}
 if($('phase47SourceSha'))$('phase47SourceSha').textContent=imp.bundleSha256||'-';
 if($('phase47ReleaseStatus'))$('phase47ReleaseStatus').textContent=imp.releaseExecution?.status||'NOT_VERIFIED';
 if($('phase47SmokeStatus'))$('phase47SmokeStatus').textContent=imp.postReleaseSmoke?.status||'NOT_VERIFIED';
 if($('phase47CandidateIdentity'))$('phase47CandidateIdentity').textContent=imp.releaseExecution?.deployedCandidateSha256||'-';
 if($('phase47AssetIdentity'))$('phase47AssetIdentity').textContent=imp.releaseExecution?.deployedAssetManifestVersion?`${imp.releaseExecution.deployedAssetManifestVersion} / ${imp.releaseExecution.deployedAssetManifestSha256||'-'}`:'-';
 if($('phase47EvaluationResult'))$('phase47EvaluationResult').innerHTML=ev?.evaluationId?`<div class="issue"><strong>${esc(ev.status)}</strong><div class="note">learning ${esc(ev.sufficientLearningDays||0)}d / ops ${esc(ev.operationsDays||0)}d / P0-P1 ${esc(ev.openP0P1||0)} / content mismatch ${esc(ev.contentMismatchDays||0)} / asset fail ${esc(ev.assetIdentityFailureDays||0)} / ${esc(ev.recommendation||'')}</div></div>`:'<div class="note">Actual CONTINUE handoff and Day-30 evidence are required.</div>';
 if($('phase47History'))$('phase47History').innerHTML=[...state.maintenanceCloseouts.slice(0,2),...state.requests.slice(0,2),...state.windows.slice(0,2)].map(x=>`<div class="decisionRow"><div><strong>${esc(x.status)}</strong><div class="note">${esc(x.title||x.reason||x.closeoutId||'')}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status)}</span></div>`).join('')||'<div class="note">No Phase 47 closeout/change-window record.</div>';
 if($('phase47Export'))$('phase47Export').disabled=!state.importRecord;
}
async function load(){
 state.snapshot=JK_STORAGE.getSnapshot();state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase47_phase46_audit_import_saved')[0]||null;state.verification=state.importRecord?.verification||null;state.ops=rowsByType('phase47_ops_snapshot_saved');state.newIncidents=rowsByType('phase47_incident_saved');state.incidentCloseouts=rowsByType('phase47_incident_closeout_saved');state.evaluations=rowsByType('phase47_confirmation30_saved');state.maintenanceCloseouts=rowsByType('phase47_maintenance_closeout_saved');state.requests=rowsByType('phase47_v104_change_request_saved');state.windows=rowsByType('phase47_v104_change_window_saved');render();
}
async function verifyBundle(){
 const file=$('phase47BundleFile').files?.[0];if(!file){$('phase47ImportMessage').textContent='Select a Phase 46 audit JSON.';return}
 try{const bundle=JSON.parse(await file.text()),sha=await hashFile(file),verification=JK_PHASE47.verifyPhase46AuditBundle(bundle,{computedSha256:sha,expectedSha256:$('phase47ExpectedSha').value}),record={format:'JK_ENG_PHASE47_PHASE46_AUDIT_IMPORT',version:'47.0',importId:verification.verificationId,phase46Bundle:bundle,phase46BundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:sha,expectedSha256:JK_PHASE47.normalizeHash($('phase47ExpectedSha').value)||null},verification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase47_phase46_audit_import_saved',entityId:record.importId,payload:record});$('phase47ImportMessage').textContent=verification.status==='PASS'?`Phase 46 audit verified / decision ${verification.manualDecision?.action}.`:'Verification failed: '+verification.errors.join(', ');await load()}catch(e){$('phase47ImportMessage').textContent='Import failed: '+(e.message||e)}
}
async function saveOps(){
 const rec=JK_PHASE47.createOpsSnapshot({date:$('phase47OpsDate').value,syncStatus:$('phase47SyncStatus').value,backupStatus:$('phase47BackupStatus').value,recoveryStatus:$('phase47RecoveryStatus').value,contentIdentityStatus:$('phase47ContentIdentityStatus').value,assetIdentityStatus:$('phase47AssetIdentityStatus').value,operator:$('phase47OpsOperator').value,evidence:$('phase47OpsEvidence').value,actualExternalContext:$('phase47OpsExternal').checked},state.verification||{});if(!rec.accepted){$('phase47OpsMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase47_ops_snapshot_saved',entityId:rec.snapshotId,payload:rec});$('phase47OpsMessage').textContent='Day-30 operations evidence recorded.';await load();
}
async function saveIncident(){
 const rec=JK_PHASE47.normalizeIncident({severity:$('phase47IncidentSeverity').value,status:$('phase47IncidentStatus').value,category:$('phase47IncidentCategory').value,title:$('phase47IncidentTitle').value,detail:$('phase47IncidentDetail').value,evidence:$('phase47IncidentEvidence').value,at:new Date().toISOString()});await JK_STORAGE.appendApprovalAudit({type:'phase47_incident_saved',entityId:rec.incidentId,payload:rec});$('phase47IncidentMessage').textContent=`Incident ${rec.incidentId} recorded.`;await load();
}
async function closeIncident(){
 const sources=[...sourceIncidents(),...state.newIncidents];const rec=JK_PHASE47.createIncidentCloseout({incidentId:$('phase47CloseIncidentId').value,reviewer:$('phase47CloseIncidentReviewer').value,resolution:$('phase47CloseIncidentResolution').value,evidence:$('phase47CloseIncidentEvidence').value},sources);if(!rec.accepted){$('phase47CloseIncidentMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase47_incident_closeout_saved',entityId:rec.closeoutId,payload:rec});$('phase47CloseIncidentMessage').textContent='Incident closeout recorded.';await load();
}
async function evaluate30(){
 const rec=JK_PHASE47.evaluateConfirmation30({asOf:$('phase47AsOf').value,actualLearnerDataUsed:$('phase47LearnerData').checked,dailyReports:Object.values(state.snapshot?.dailyReports||{}),opsSnapshots:state.ops,sourceIncidents:sourceIncidents(),newIncidents:state.newIncidents,incidentCloseouts:state.incidentCloseouts},state.verification||{});await JK_STORAGE.appendApprovalAudit({type:'phase47_confirmation30_saved',entityId:rec.evaluationId,payload:rec});$('phase47EvaluationMessage').textContent=`${rec.status} / ${rec.recommendation}`;await load();
}
async function closeMaintenance(){
 const rec=JK_PHASE47.createMaintenanceCloseout({operator:$('phase47CloseoutOperator').value,backupEvidence:$('phase47BackupEvidence').value,recoveryEvidence:$('phase47RecoveryEvidence').value,rollbackReadinessEvidence:$('phase47RollbackEvidence').value,contentIdentityEvidence:$('phase47ContentEvidence').value,assetIdentityEvidence:$('phase47AssetEvidence').value,actualExternalContext:$('phase47CloseoutExternal').checked,confirmationPhrase:$('phase47CloseoutConfirm').value},state.verification||{},latest(state.evaluations)||{},sourceIncidents(),state.newIncidents,state.incidentCloseouts,state.ops);if(!rec.accepted){$('phase47CloseoutMessage').textContent='Blocked: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase47_maintenance_closeout_saved',entityId:rec.closeoutId,payload:rec});$('phase47CloseoutMessage').textContent='v1.0.3 maintenance closed. v1.0.4 change window remains separate.';await load();
}
async function requestV104(){
 const impacts={questionBankShapeChange:$('phase47QuestionShapeChange').checked,dailyTimingChange:$('phase47DailyTimingChange').checked,stagedLearningLoopChange:$('phase47LoopChange').checked,automaticBehaviorChange:$('phase47AutoChange').checked};const rec=JK_PHASE47.createV104ChangeRequest({type:$('phase47RequestType').value,title:$('phase47RequestTitle').value,description:$('phase47RequestDescription').value,risk:$('phase47RequestRisk').value,contentBankChange:$('phase47ContentBankChange').checked,contentApprovalRef:$('phase47ContentApprovalRef').value,invariantImpacts:impacts,requestedBy:$('phase47RequestedBy').value},latest(state.maintenanceCloseouts)||{});if(!rec.accepted){$('phase47RequestMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase47_v104_change_request_saved',entityId:rec.requestId,payload:rec});$('phase47RequestMessage').textContent='v1.0.4 request recorded; no implementation, content, or deployment applied.';await load();
}
async function openWindow(){
 const rec=JK_PHASE47.openV104ChangeWindow({operator:$('phase47WindowOperator').value,reason:$('phase47WindowReason').value,confirmationPhrase:$('phase47WindowConfirm').value},latest(state.maintenanceCloseouts)||{},state.requests);if(!rec.accepted){$('phase47WindowMessage').textContent='Blocked: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase47_v104_change_window_saved',entityId:rec.windowId,payload:rec});$('phase47WindowMessage').textContent='v1.0.4 change window opened. This is not implementation or deployment authorization.';await load();
}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE47.buildCloseoutAuditBundle({phase46BundleMeta:state.importRecord?.phase46BundleMeta||null,phase46AuditVerification:state.verification,opsSnapshots:state.ops,newIncidents:state.newIncidents,incidentCloseouts:state.incidentCloseouts,confirmation30Evaluations:state.evaluations,maintenanceCloseouts:state.maintenanceCloseouts,v104ChangeRequests:state.requests,v104ChangeWindows:state.windows}),`JK_ENG_Phase47_v103_Closeout_v104_Window_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();$('phase47OpsDate').value=new Date().toISOString().slice(0,10);$('phase47AsOf').value=new Date().toISOString().slice(0,10);$('phase47VerifyBundle').onclick=verifyBundle;$('phase47OpsSave').onclick=saveOps;$('phase47IncidentSave').onclick=saveIncident;$('phase47CloseIncident').onclick=closeIncident;$('phase47Evaluate30').onclick=evaluate30;$('phase47MaintenanceClose').onclick=closeMaintenance;$('phase47RequestSave').onclick=requestV104;$('phase47WindowOpen').onclick=openWindow;$('phase47Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase47ImportMessage');if(el)el.textContent=String(e.message||e)});
