(async function(){
'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={snapshot:null,audits:[],importRecord:null,verification:null,stagings:[],executions:[],smokes:[],ops:[],incidents:[],evaluations:[],decisions:[]};
const sorted=rows=>(rows||[]).slice().sort((a,b)=>Date.parse(b.at||b.decidedAt||b.evaluatedAt||b.testedAt||b.executedAt||b.verifiedAt||b.recordedAt||0)-Date.parse(a.at||a.decidedAt||a.evaluatedAt||a.testedAt||a.executedAt||a.verifiedAt||a.recordedAt||0));
const rowsByType=type=>sorted(state.audits.filter(x=>x.type===type).map(x=>x.payload)); const latest=rows=>rows?.[0]||null;
async function hashFile(file){const b=await file.arrayBuffer(),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function badgeClass(s){s=String(s||'');return /PASS|EXECUTED|STABLE|RECORDED|AUTHORIZED/.test(s)?'pass':/FAIL|BLOCKED|ROLLBACK/.test(s)?'fail':/HOLD|INSUFFICIENT|WATCH/.test(s)?'warn':''}
function buildTestRows(containerId,defs,prefix){const root=$(containerId);if(!root)return;root.innerHTML=(defs||[]).map(d=>`<div class="smokeRow"><div><strong>${esc(d.id)}</strong><div class="note">${esc(d.label)}</div></div><select id="${prefix}Status_${esc(d.id)}"><option>NOT_RUN</option><option>PASS</option><option>FAIL</option></select><input id="${prefix}Evidence_${esc(d.id)}" placeholder="evidence reference"></div>`).join('')}
function readTests(defs,prefix){const out={};for(const d of defs||[])out[d.id]={status:$(`${prefix}Status_${d.id}`).value,evidence:$(`${prefix}Evidence_${d.id}`).value};return out}
function render(){const imp=state.verification||{status:'NOT_IMPORTED'},stage=latest(state.stagings)||{status:'STAGING_NOT_RUN'},exec=latest(state.executions)||{status:'V101_RELEASE_NOT_RUN'},smoke=latest(state.smokes)||{status:'V101_SMOKE_NOT_RUN'},ev=latest(state.evaluations)||{status:'NOT_COLLECTED'},dec=latest(state.decisions)||{status:'NOT_RECORDED'};
 for(const [id,val] of [['phase38InputBadge',imp.status],['phase38StagingBadge',stage.status],['phase38ReleaseBadge',exec.status],['phase38SmokeBadge',smoke.status],['phase38StabilizationBadge',ev.status],['phase38DecisionBadge',dec.status]]){if($(id)){$(id).textContent=val;$(id).className=`status ${badgeClass(val)}`}}
 if($('phase38SourceSha'))$('phase38SourceSha').textContent=imp.bundleSha256||'-'; if($('phase38AuthStatus'))$('phase38AuthStatus').textContent=imp.authorization?.status||'NOT_IMPORTED'; if($('phase38RegressionStatus'))$('phase38RegressionStatus').textContent=imp.regressionVerification?.status||'NOT_RUN';
 if($('phase38EvaluationResult'))$('phase38EvaluationResult').innerHTML=ev?.evaluationId?`<div class="issue"><strong>${esc(ev.status)}</strong><div class="note">learning ${esc(ev.sufficientLearningDays||0)}d / ops ${esc(ev.operationsDays||0)}d / P0·P1 ${esc(ev.openP0P1||0)} / recommendation ${esc(ev.recommendation||'')}</div></div>`:'<div class="note">실제 v1.0.1 출시·스모크·14일 데이터가 있어야 평가됩니다.</div>';
 if($('phase38History'))$('phase38History').innerHTML=[...state.executions.slice(0,2),...state.evaluations.slice(0,2),...state.decisions.slice(0,2)].map(x=>`<div class="decisionRow"><div><strong>${esc(x.status||x.action)}</strong><div class="note">${esc(x.targetUrl||x.recommendation||x.reason||'')}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status||x.action)}</span></div>`).join('')||'<div class="note">No Phase 38 execution record.</div>';
 if($('phase38Export'))$('phase38Export').disabled=!state.importRecord;
}
async function load(){state.snapshot=JK_STORAGE.getSnapshot();state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase38_authorized_bundle_import_saved')[0]||null;state.verification=state.importRecord?.verification||null;state.stagings=rowsByType('phase38_staging_verification_saved');state.executions=rowsByType('phase38_v101_release_execution_saved');state.smokes=rowsByType('phase38_post_release_smoke_saved');state.ops=rowsByType('phase38_ops_snapshot_saved');state.incidents=rowsByType('phase38_incident_saved');state.evaluations=rowsByType('phase38_stabilization_saved');state.decisions=rowsByType('phase38_followup_decision_saved');render()}
async function verifyBundle(){const file=$('phase38BundleFile').files?.[0];if(!file){$('phase38ImportMessage').textContent='Phase 37 audit JSON을 선택하세요.';return}try{const bundle=JSON.parse(await file.text()),sha=await hashFile(file),verification=JK_PHASE38.verifyPhase37AuthorizedBundle(bundle,{computedSha256:sha,expectedSha256:$('phase38ExpectedSha').value}),record={format:'JK_ENG_PHASE38_PHASE37_AUTHORIZED_BUNDLE_IMPORT',version:'38.0',importId:verification.verificationId,authorizedBundle:bundle,authorizedBundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:sha,expectedSha256:JK_PHASE38.normalizeHash($('phase38ExpectedSha').value)||null},verification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase38_authorized_bundle_import_saved',entityId:record.importId,payload:record});$('phase38ImportMessage').textContent=verification.status==='PASS'?'AUTHORIZED + REGRESSION_PASS 패키지 검증 완료.':'검증 실패: '+verification.errors.join(', ');await load()}catch(e){$('phase38ImportMessage').textContent='Import failed: '+(e.message||e)}}
async function runStaging(){const file=$('phase38StagingBundleFile').files?.[0];if(!file||!state.verification){$('phase38StagingMessage').textContent='검증된 Phase 37 패키지를 동일 파일로 다시 선택하세요.';return}const sha=await hashFile(file),cfg=JK_PHASE38_DATA.policy.stagingVerification,rec=JK_PHASE38.evaluateStagingVerification({rehashedSha256:sha,stagingUrl:$('phase38StagingUrl').value,operator:$('phase38StagingOperator').value,evidence:$('phase38StagingEvidence').value,actualStagingContext:$('phase38StagingExternal').checked,tests:readTests(cfg.tests,'phase38Stage')},state.verification);await JK_STORAGE.appendApprovalAudit({type:'phase38_staging_verification_saved',entityId:rec.runId,payload:rec});$('phase38StagingMessage').textContent=`${rec.status}: ${(rec.errors||[]).join(', ')||'all pass'}`;await load()}
async function executeRelease(){const file=$('phase38ExecutionBundleFile').files?.[0],stage=latest(state.stagings);if(!file||!stage){$('phase38ReleaseMessage').textContent='STAGING_PASS와 동일 패키지 재선택이 필요합니다.';return}const sha=await hashFile(file),rec=JK_PHASE38.createExternalReleaseExecution({rehashedSha256:sha,targetUrl:$('phase38TargetUrl').value,operator:$('phase38ReleaseOperator').value,evidence:$('phase38ReleaseEvidence').value,actualExternalContext:$('phase38ReleaseExternal').checked,confirmationPhrase:$('phase38ReleaseConfirm').value},state.verification,stage);await JK_STORAGE.appendApprovalAudit({type:'phase38_v101_release_execution_saved',entityId:rec.executionId,payload:rec});$('phase38ReleaseMessage').textContent=`${rec.status}: ${(rec.errors||[]).join(', ')||'recorded'}`;await load()}
async function runSmoke(){const exec=latest(state.executions),cfg=JK_PHASE38_DATA.policy.externalRelease,rec=JK_PHASE38.evaluatePostReleaseSmoke({actualExternalContext:$('phase38SmokeExternal').checked,operator:$('phase38SmokeOperator').value,tests:readTests(cfg.smokeTests,'phase38Smoke')},exec||{});await JK_STORAGE.appendApprovalAudit({type:'phase38_post_release_smoke_saved',entityId:rec.runId,payload:rec});$('phase38SmokeMessage').textContent=`${rec.status}: ${(rec.errors||[]).join(', ')||'all pass'}`;await load()}
async function saveOps(){const rec=JK_PHASE38.createOpsSnapshot({date:$('phase38OpsDate').value,syncStatus:$('phase38SyncStatus').value,backupStatus:$('phase38BackupStatus').value,recoveryStatus:$('phase38RecoveryStatus').value,operator:$('phase38OpsOperator').value,evidence:$('phase38OpsEvidence').value,actualExternalContext:$('phase38OpsExternal').checked},latest(state.executions)||{});if(!rec.accepted){$('phase38OpsMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase38_ops_snapshot_saved',entityId:rec.snapshotId,payload:rec});$('phase38OpsMessage').textContent='운영 스냅샷 기록 완료.';await load()}
async function saveIncident(){const rec=JK_PHASE38.normalizeIncident({severity:$('phase38IncidentSeverity').value,status:$('phase38IncidentStatus').value,title:$('phase38IncidentTitle').value,detail:$('phase38IncidentDetail').value,evidence:$('phase38IncidentEvidence').value,at:new Date().toISOString()});await JK_STORAGE.appendApprovalAudit({type:'phase38_incident_saved',entityId:rec.incidentId,payload:rec});$('phase38IncidentMessage').textContent='Incident recorded.';await load()}
async function evaluate14(){const bundle=state.importRecord?.authorizedBundle||{},rec=JK_PHASE38.evaluateStabilization14({execution:latest(state.executions)||{},smoke:latest(state.smokes)||{},asOf:$('phase38AsOf').value,actualLearnerDataUsed:$('phase38LearnerData').checked,dailyReports:Object.values(state.snapshot?.dailyReports||{}),opsSnapshots:state.ops,incidents:state.incidents,referenceMetrics:JK_PHASE38.referenceMetricsFromBundle(bundle)});await JK_STORAGE.appendApprovalAudit({type:'phase38_stabilization_saved',entityId:rec.evaluationId,payload:rec});$('phase38EvaluationMessage').textContent=`${rec.status} / ${rec.recommendation}`;await load()}
async function decide(){const ev=latest(state.evaluations);if(!ev){$('phase38DecisionMessage').textContent='14-day evaluation is required.';return}const rec=JK_PHASE38.makeFollowupDecision({action:$('phase38DecisionAction').value,reviewer:$('phase38DecisionReviewer').value,reason:$('phase38DecisionReason').value,confirmationPhrase:$('phase38RollbackConfirm').value},ev);if(!rec.accepted){$('phase38DecisionMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase38_followup_decision_saved',entityId:rec.decisionId,payload:rec});$('phase38DecisionMessage').textContent=`${rec.status}. Automatic rollback was not performed.`;await load()}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE38.buildExecutionAuditBundle({phase37BundleMeta:state.importRecord?.authorizedBundleMeta||null,authorizedInputVerification:state.verification,stagingVerifications:state.stagings,releaseExecutions:state.executions,smokeRuns:state.smokes,opsSnapshots:state.ops,incidents:state.incidents,stabilizationEvaluations:state.evaluations,followupDecisions:state.decisions}),`JK_ENG_Phase38_v101_Execution_Audit_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();buildTestRows('phase38StagingTests',JK_PHASE38_DATA.policy.stagingVerification.tests,'phase38Stage');buildTestRows('phase38SmokeTests',JK_PHASE38_DATA.policy.externalRelease.smokeTests,'phase38Smoke');$('phase38OpsDate').value=new Date().toISOString().slice(0,10);$('phase38AsOf').value=new Date().toISOString().slice(0,10);$('phase38VerifyBundle').onclick=verifyBundle;$('phase38RunStaging').onclick=runStaging;$('phase38ExecuteRelease').onclick=executeRelease;$('phase38RunSmoke').onclick=runSmoke;$('phase38OpsSave').onclick=saveOps;$('phase38IncidentSave').onclick=saveIncident;$('phase38Evaluate14').onclick=evaluate14;$('phase38DecisionSave').onclick=decide;$('phase38Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase38ImportMessage');if(el)el.textContent=String(e.message||e)});
