(async function(){
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={snapshot:null,audits:[],importRecord:null,verification:null,ops:[],newIncidents:[],incidentCloseouts:[],evaluations:[],maintenanceCloseouts:[],requests:[],windows:[]};
const sorted=rows=>(rows||[]).slice().sort((a,b)=>Date.parse(b.at||b.openedAt||b.requestedAt||b.closedAt||b.evaluatedAt||b.recordedAt||0)-Date.parse(a.at||a.openedAt||a.requestedAt||a.closedAt||a.evaluatedAt||a.recordedAt||0));
const rowsByType=type=>sorted(state.audits.filter(x=>x.type===type).map(x=>x.payload));const latest=rows=>rows?.[0]||null;
async function hashFile(file){const b=await file.arrayBuffer(),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function badgeClass(s){s=String(s||'');return /PASS|STABLE|CLOSED|OPEN|RECORDED|REQUESTED/.test(s)?'pass':/FAIL|BLOCKED|ROLLBACK|REJECTED/.test(s)?'fail':/HOLD|INSUFFICIENT|NOT_/.test(s)?'warn':''}
function sourceIncidents(){return state.importRecord?.phase38Bundle?.incidents||[]}
function render(){const imp=state.verification||{status:'NOT_IMPORTED'},dec=imp.manualDecision||{action:'NOT_VERIFIED'},ev=latest(state.evaluations)||{status:'NOT_COLLECTED'},cl=latest(state.maintenanceCloseouts)||{status:'NOT_RECORDED'},win=latest(state.windows)||{status:'NOT_OPEN'};for(const [id,val] of [['phase39InputBadge',imp.status],['phase39DecisionBadge',dec.action],['phase39Day30Badge',ev.status],['phase39CloseoutBadge',cl.status],['phase39V102Badge',win.status]]){if($(id)){$(id).textContent=val;$(id).className=`status ${badgeClass(val)}`}}if($('phase39SourceSha'))$('phase39SourceSha').textContent=imp.bundleSha256||'-';if($('phase39ReleaseStatus'))$('phase39ReleaseStatus').textContent=imp.releaseExecution?.status||'NOT_VERIFIED';if($('phase39SmokeStatus'))$('phase39SmokeStatus').textContent=imp.postReleaseSmoke?.status||'NOT_VERIFIED';if($('phase39EvaluationResult'))$('phase39EvaluationResult').innerHTML=ev?.evaluationId?`<div class="issue"><strong>${esc(ev.status)}</strong><div class="note">learning ${esc(ev.sufficientLearningDays||0)}d / ops ${esc(ev.operationsDays||0)}d / P0·P1 ${esc(ev.openP0P1||0)} / ${esc(ev.recommendation||'')}</div></div>`:'<div class="note">실제 CONTINUE 인계와 30일 데이터가 있어야 평가됩니다.</div>';if($('phase39History'))$('phase39History').innerHTML=[...state.maintenanceCloseouts.slice(0,2),...state.requests.slice(0,2),...state.windows.slice(0,2)].map(x=>`<div class="decisionRow"><div><strong>${esc(x.status)}</strong><div class="note">${esc(x.title||x.reason||x.closeoutId||'')}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status)}</span></div>`).join('')||'<div class="note">No Phase 39 closeout/change-window record.</div>';if($('phase39Export'))$('phase39Export').disabled=!state.importRecord;}
async function load(){state.snapshot=JK_STORAGE.getSnapshot();state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase39_phase38_audit_import_saved')[0]||null;state.verification=state.importRecord?.verification||null;state.ops=rowsByType('phase39_ops_snapshot_saved');state.newIncidents=rowsByType('phase39_incident_saved');state.incidentCloseouts=rowsByType('phase39_incident_closeout_saved');state.evaluations=rowsByType('phase39_confirmation30_saved');state.maintenanceCloseouts=rowsByType('phase39_maintenance_closeout_saved');state.requests=rowsByType('phase39_v102_change_request_saved');state.windows=rowsByType('phase39_v102_change_window_saved');render()}
async function verifyBundle(){const file=$('phase39BundleFile').files?.[0];if(!file){$('phase39ImportMessage').textContent='Phase 38 audit JSON을 선택하세요.';return}try{const bundle=JSON.parse(await file.text()),sha=await hashFile(file),verification=JK_PHASE39.verifyPhase38AuditBundle(bundle,{computedSha256:sha,expectedSha256:$('phase39ExpectedSha').value}),record={format:'JK_ENG_PHASE39_PHASE38_AUDIT_IMPORT',version:'39.0',importId:verification.verificationId,phase38Bundle:bundle,phase38BundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:sha,expectedSha256:JK_PHASE39.normalizeHash($('phase39ExpectedSha').value)||null},verification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase39_phase38_audit_import_saved',entityId:record.importId,payload:record});$('phase39ImportMessage').textContent=verification.status==='PASS'?`Phase 38 audit verified / decision ${verification.manualDecision?.action}.`:'검증 실패: '+verification.errors.join(', ');await load()}catch(e){$('phase39ImportMessage').textContent='Import failed: '+(e.message||e)}}
async function saveOps(){const rec=JK_PHASE39.createOpsSnapshot({date:$('phase39OpsDate').value,syncStatus:$('phase39SyncStatus').value,backupStatus:$('phase39BackupStatus').value,recoveryStatus:$('phase39RecoveryStatus').value,operator:$('phase39OpsOperator').value,evidence:$('phase39OpsEvidence').value,actualExternalContext:$('phase39OpsExternal').checked},state.verification||{});if(!rec.accepted){$('phase39OpsMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase39_ops_snapshot_saved',entityId:rec.snapshotId,payload:rec});$('phase39OpsMessage').textContent='30일 운영 증거 기록 완료.';await load()}
async function saveIncident(){const rec=JK_PHASE39.normalizeIncident({severity:$('phase39IncidentSeverity').value,status:$('phase39IncidentStatus').value,title:$('phase39IncidentTitle').value,detail:$('phase39IncidentDetail').value,evidence:$('phase39IncidentEvidence').value,at:new Date().toISOString()});await JK_STORAGE.appendApprovalAudit({type:'phase39_incident_saved',entityId:rec.incidentId,payload:rec});$('phase39IncidentMessage').textContent=`Incident ${rec.incidentId} recorded.`;await load()}
async function closeIncident(){const sources=[...sourceIncidents(),...state.newIncidents];const rec=JK_PHASE39.createIncidentCloseout({incidentId:$('phase39CloseIncidentId').value,reviewer:$('phase39CloseIncidentReviewer').value,resolution:$('phase39CloseIncidentResolution').value,evidence:$('phase39CloseIncidentEvidence').value},sources);if(!rec.accepted){$('phase39CloseIncidentMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase39_incident_closeout_saved',entityId:rec.closeoutId,payload:rec});$('phase39CloseIncidentMessage').textContent='Incident closeout recorded.';await load()}
async function evaluate30(){const rec=JK_PHASE39.evaluateConfirmation30({asOf:$('phase39AsOf').value,actualLearnerDataUsed:$('phase39LearnerData').checked,dailyReports:Object.values(state.snapshot?.dailyReports||{}),opsSnapshots:state.ops,sourceIncidents:sourceIncidents(),newIncidents:state.newIncidents,incidentCloseouts:state.incidentCloseouts},state.verification||{});await JK_STORAGE.appendApprovalAudit({type:'phase39_confirmation30_saved',entityId:rec.evaluationId,payload:rec});$('phase39EvaluationMessage').textContent=`${rec.status} / ${rec.recommendation}`;await load()}
async function closeMaintenance(){const rec=JK_PHASE39.createMaintenanceCloseout({operator:$('phase39CloseoutOperator').value,backupEvidence:$('phase39BackupEvidence').value,recoveryEvidence:$('phase39RecoveryEvidence').value,rollbackReadinessEvidence:$('phase39RollbackEvidence').value,actualExternalContext:$('phase39CloseoutExternal').checked,confirmationPhrase:$('phase39CloseoutConfirm').value},state.verification||{},latest(state.evaluations)||{},sourceIncidents(),state.newIncidents,state.incidentCloseouts,state.ops);if(!rec.accepted){$('phase39CloseoutMessage').textContent='Blocked: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase39_maintenance_closeout_saved',entityId:rec.closeoutId,payload:rec});$('phase39CloseoutMessage').textContent='v1.0.1 maintenance closed. v1.0.2 window is still separate.';await load()}
async function requestV102(){const impacts={questionBankShapeChange:$('phase39QuestionShapeChange').checked,dailyTimingChange:$('phase39DailyTimingChange').checked,stagedLearningLoopChange:$('phase39LoopChange').checked,automaticBehaviorChange:$('phase39AutoChange').checked};const rec=JK_PHASE39.createV102ChangeRequest({type:$('phase39RequestType').value,title:$('phase39RequestTitle').value,description:$('phase39RequestDescription').value,risk:$('phase39RequestRisk').value,contentBankChange:$('phase39ContentBankChange').checked,contentApprovalRef:$('phase39ContentApprovalRef').value,invariantImpacts:impacts,requestedBy:$('phase39RequestedBy').value},latest(state.maintenanceCloseouts)||{});if(!rec.accepted){$('phase39RequestMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase39_v102_change_request_saved',entityId:rec.requestId,payload:rec});$('phase39RequestMessage').textContent='v1.0.2 request recorded; no content or deployment applied.';await load()}
async function openWindow(){const rec=JK_PHASE39.openV102ChangeWindow({operator:$('phase39WindowOperator').value,reason:$('phase39WindowReason').value,confirmationPhrase:$('phase39WindowConfirm').value},latest(state.maintenanceCloseouts)||{},state.requests);if(!rec.accepted){$('phase39WindowMessage').textContent='Blocked: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase39_v102_change_window_saved',entityId:rec.windowId,payload:rec});$('phase39WindowMessage').textContent='v1.0.2 change window opened. This is not deployment authorization.';await load()}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE39.buildCloseoutAuditBundle({phase38BundleMeta:state.importRecord?.phase38BundleMeta||null,phase38AuditVerification:state.verification,opsSnapshots:state.ops,newIncidents:state.newIncidents,incidentCloseouts:state.incidentCloseouts,confirmation30Evaluations:state.evaluations,maintenanceCloseouts:state.maintenanceCloseouts,v102ChangeRequests:state.requests,v102ChangeWindows:state.windows}),`JK_ENG_Phase39_v101_Closeout_v102_Window_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();$('phase39OpsDate').value=new Date().toISOString().slice(0,10);$('phase39AsOf').value=new Date().toISOString().slice(0,10);$('phase39VerifyBundle').onclick=verifyBundle;$('phase39OpsSave').onclick=saveOps;$('phase39IncidentSave').onclick=saveIncident;$('phase39CloseIncident').onclick=closeIncident;$('phase39Evaluate30').onclick=evaluate30;$('phase39MaintenanceClose').onclick=closeMaintenance;$('phase39RequestSave').onclick=requestV102;$('phase39WindowOpen').onclick=openWindow;$('phase39Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase39ImportMessage');if(el)el.textContent=String(e.message||e)});
