(async function(){
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={audits:[],importRecord:null,verification:null,reviews:[],guardrails:[],plans:[],staging:[]};
const sorted=a=>(a||[]).slice().sort((x,y)=>Date.parse(y?.at||y?.payload?.testedAt||y?.payload?.approvedAt||y?.payload?.reviewedAt||0)-Date.parse(x?.at||x?.payload?.testedAt||x?.payload?.approvedAt||x?.payload?.reviewedAt||0));
const rowsByType=t=>state.audits.filter(x=>x?.type===t).map(x=>x.payload||x).filter(Boolean);
const latest=rows=>JK_PHASE44.latest(rows);
const hashFile=async f=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',await f.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');
function badgeClass(v){return ['PASS','AUTHORIZED','GUARDRAIL_PASS','PLAN_APPROVED','STAGING_PASS','MAINTENANCE_CLOSED','V103_CHANGE_WINDOW_OPEN'].includes(v)?'PASS':['FAIL','REJECTED','REVIEW_REJECTED','GUARDRAIL_BLOCKED','PLAN_BLOCKED','STAGING_FAIL'].includes(v)?'FAIL':'NOT_RUN'}
function render(){const v=state.verification||{status:'NOT_IMPORTED'},g=latest(state.guardrails)||{status:'NOT_RECORDED'},p=latest(state.plans)||{status:'NOT_RECORDED'},s=latest(state.staging)||{status:'NOT_RUN'};for(const [id,val] of [['phase44InputBadge',v.status],['phase44CloseoutBadge',v.maintenanceCloseout?.status||'NOT_VERIFIED'],['phase44WindowBadge',v.changeWindow?.status||'NOT_VERIFIED'],['phase44GuardrailBadge',g.status],['phase44PlanBadge',p.status],['phase44StagingBadge',s.status]])if($(id)){$(id).textContent=val;$(id).className=`status ${badgeClass(val)}`};if($('phase44SourceSha'))$('phase44SourceSha').textContent=v.bundleSha256||'-';if($('phase44RequestList'))$('phase44RequestList').innerHTML=(v.acceptedRequests||[]).map(r=>`<div class="decisionRow"><div><strong>${esc(r.requestId)}</strong><div class="note">${esc(r.type)} / ${esc(r.title)} / content approval ${esc(r.contentApprovalRef||'not required')}</div></div><span class="status ${badgeClass((state.reviews.find(x=>x.requestId===r.requestId)||{}).status||'NOT_RECORDED')}">${esc((state.reviews.find(x=>x.requestId===r.requestId)||{}).status||'NOT_RECORDED')}</span></div>`).join('')||'<div class="note">No verified Phase 43 requests.</div>';if($('phase44RequestId')){$('phase44RequestId').innerHTML='<option value="">Select request</option>'+(v.acceptedRequests||[]).map(r=>`<option value="${esc(r.requestId)}">${esc(r.requestId)} - ${esc(r.title)}</option>`).join('')};if($('phase44History'))$('phase44History').innerHTML=[...state.reviews.slice(0,3),...state.guardrails.slice(0,1),...state.plans.slice(0,1),...state.staging.slice(0,1)].map(x=>`<div class="decisionRow"><div><strong>${esc(x.status)}</strong><div class="note">${esc(x.requestId||x.planId||x.guardrailId||x.runId||'')}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status)}</span></div>`).join('')||'<div class="note">No Phase 44 records.</div>';if($('phase44Export'))$('phase44Export').disabled=!state.importRecord;}
async function load(){state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase44_phase43_audit_import_saved')[0]||null;state.verification=state.importRecord?.verification||null;state.reviews=rowsByType('phase44_request_review_saved');state.guardrails=rowsByType('phase44_guardrail_saved');state.plans=rowsByType('phase44_change_plan_saved');state.staging=rowsByType('phase44_staging_run_saved');render()}
async function verifyBundle(){const file=$('phase44BundleFile').files?.[0];if(!file){$('phase44ImportMessage').textContent='Select a Phase 43 audit JSON.';return}try{const bundle=JSON.parse(await file.text()),sha=await hashFile(file),verification=JK_PHASE44.verifyPhase43AuditBundle(bundle,{computedSha256:sha,expectedSha256:$('phase44ExpectedSha').value}),record={format:'JK_ENG_PHASE44_PHASE43_AUDIT_IMPORT',version:'44.0',importId:verification.verificationId,phase43Bundle:bundle,phase43BundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:sha,expectedSha256:JK_PHASE44.normalizeHash($('phase44ExpectedSha').value)||null},verification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase44_phase43_audit_import_saved',entityId:record.importId,payload:record});$('phase44ImportMessage').textContent=verification.status==='PASS'?'Phase 43 maintenance closeout and v1.0.3 open window verified.':'Verification failed: '+verification.errors.join(', ');await load()}catch(e){$('phase44ImportMessage').textContent='Import failed: '+(e.message||e)}}
async function saveReview(){const rec=JK_PHASE44.reviewV103Request({requestId:$('phase44RequestId').value,decision:$('phase44ReviewDecision').value,riskLevel:$('phase44RiskLevel').value,reviewer:$('phase44Reviewer').value,scopeAssessment:$('phase44ScopeAssessment').value,riskAssessment:$('phase44RiskAssessment').value,rollbackPlan:$('phase44ReviewRollback').value,contentApprovalRef:$('phase44ContentApprovalRef').value,contentApprovalStatus:$('phase44ContentApprovalStatus').value,contentApprovalEvidence:$('phase44ContentApprovalEvidence').value},state.verification||{});if(!rec.accepted){$('phase44ReviewMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase44_request_review_saved',entityId:rec.reviewId,payload:rec});$('phase44ReviewMessage').textContent=`${rec.status}; no implementation was applied.`;await load()}
async function saveGuardrail(){const preservations={processScoringPreserved:$('phase44PreserveProcess').checked,textbookReturnLoopPreserved:$('phase44PreserveTextbook').checked,evidenceMarkingPreserved:$('phase44PreserveEvidence').checked,originalRetryPreserved:$('phase44PreserveRetry').checked,nonAnxietyPacingPreserved:$('phase44PreservePacing').checked,dailyStructurePreserved:$('phase44PreserveDaily').checked};const impacts={numericCountdownVisible:$('phase44ImpactCountdown').checked,bypassProcessScoring:$('phase44ImpactProcessBypass').checked,bypassTextbookReturn:$('phase44ImpactTextbookBypass').checked,bypassEvidenceMarking:$('phase44ImpactEvidenceBypass').checked,bypassOriginalRetry:$('phase44ImpactRetryBypass').checked,dailyTimingMutation:$('phase44ImpactDailyTiming').checked,automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false};const rec=JK_PHASE44.assessLearnerImpact({reviewer:$('phase44GuardrailReviewer').value,evidence:$('phase44GuardrailEvidence').value,preservations,impacts},state.verification||{},state.reviews);await JK_STORAGE.appendApprovalAudit({type:'phase44_guardrail_saved',entityId:rec.guardrailId,payload:rec});$('phase44GuardrailMessage').textContent=`${rec.status}${rec.errors.length?': '+rec.errors.join(', '):''}`;await load()}
async function approvePlan(){const rec=JK_PHASE44.createControlledChangePlan({operator:$('phase44PlanOperator').value,owner:$('phase44PlanOwner').value,scopeSummary:$('phase44PlanScope').value,rollbackPlan:$('phase44PlanRollback').value,confirmationPhrase:$('phase44PlanConfirm').value},state.verification||{},state.reviews,latest(state.guardrails)||{});if(!rec.accepted){$('phase44PlanMessage').textContent='Blocked: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase44_change_plan_saved',entityId:rec.planId,payload:rec});$('phase44PlanMessage').textContent='Controlled plan approved. Deployment remains manual and separate.';await load()}
async function saveStaging(){const ids=['AUTH','DAILY_LOOP','MULTI_DEVICE_RESUME','OFFLINE_RECOVERY','ADMIN_RECOVERY','ASSET_INTEGRITY','ROLLBACK_READINESS'],cases=ids.map(id=>({id,status:$(`phase44Stage${id}Status`).value,evidence:$(`phase44Stage${id}Evidence`).value}));const rec=JK_PHASE44.createStagingValidation({actualStagingContext:$('phase44StagingActual').checked,stagingUrl:$('phase44StagingUrl').value,operator:$('phase44StagingOperator').value,cases},latest(state.plans)||{},latest(state.guardrails)||{});await JK_STORAGE.appendApprovalAudit({type:'phase44_staging_run_saved',entityId:rec.runId,payload:rec});$('phase44StagingMessage').textContent=`${rec.status}${rec.errors.length?': '+rec.errors.join(', '):''}. Production release is not authorized here.`;await load()}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE44.buildPhase44AuditBundle({phase43BundleMeta:state.importRecord?.phase43BundleMeta||null,phase43AuditVerification:state.verification,requestReviews:state.reviews,learnerImpactGuardrails:state.guardrails,controlledChangePlans:state.plans,stagingValidations:state.staging}),`JK_ENG_Phase44_v103_ChangePlan_Staging_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();$('phase44VerifyBundle').onclick=verifyBundle;$('phase44ReviewSave').onclick=saveReview;$('phase44GuardrailSave').onclick=saveGuardrail;$('phase44PlanApprove').onclick=approvePlan;$('phase44StagingSave').onclick=saveStaging;$('phase44Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase44ImportMessage');if(el)el.textContent=String(e.message||e)});
