(function(global){
'use strict';
const VERSION='36.0';
const text=value=>String(value==null?'':value).trim();
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
const nowIso=()=>new Date().toISOString();
const uid=prefix=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
const policy=()=>global.JK_PHASE36_DATA?.policy||{};
const normalizeHash=value=>text(value).toLowerCase().replace(/^sha256:/,'').trim();
const dateOnly=value=>{const raw=text(value?.date||value?.dayId||value).replace(/^DAY-/,'');const m=raw.match(/(\d{4}-\d{2}-\d{2})/);return m?m[1]:''};
const addDays=(value,days)=>{const d=new Date(`${dateOnly(value)}T00:00:00.000Z`);if(!Number.isFinite(d.getTime()))return'';d.setUTCDate(d.getUTCDate()+Number(days||0));return d.toISOString().slice(0,10)};
const avg=values=>{const rows=values.map(Number).filter(Number.isFinite);return rows.length?Math.round(rows.reduce((a,b)=>a+b,0)*10/rows.length)/10:null};
const sortedUnique=rows=>[...new Map((rows||[]).map(x=>[dateOnly(x),x]).filter(([k])=>k)).values()].sort((a,b)=>dateOnly(a).localeCompare(dateOnly(b)));
function latestDecision(decisions=[]){return (Array.isArray(decisions)?decisions:[]).slice().sort((a,b)=>Date.parse(b?.decidedAt||0)-Date.parse(a?.decidedAt||0))[0]||null}
function verifyPhase35ReleaseBundle(bundle={},options={},p=policy()){
  const cfg=p.acceptedPhase35Bundle||{},checks=[],errors=[];const add=(id,ok,detail='')=>{checks.push({id,ok:Boolean(ok),detail:text(detail)});if(!ok)errors.push(id)};
  const computed=normalizeHash(options.computedSha256),expected=normalizeHash(options.expectedSha256),decision=latestDecision(bundle?.releaseDecisions||[]),evaluation=bundle?.releaseEvaluation||{},baseline=bundle?.baselineEvaluation||{},operations=bundle?.operationsSummary||{},observation=bundle?.phase34ObservationInput||{},hex=bundle?.sevenDayHex||{};
  add('BUNDLE_FORMAT',bundle?.format===cfg.format,bundle?.format||'missing');
  add('BUNDLE_VERSION',bundle?.version===cfg.version,bundle?.version||'missing');
  add('RELEASE_TARGET',bundle?.releaseTarget===cfg.releaseTarget,bundle?.releaseTarget||'missing');
  add('SOURCE_SHA256_COMPUTED',/^[a-f0-9]{64}$/.test(computed),computed||'missing');
  if(expected)add('SOURCE_SHA256_MATCH',computed===expected,computed===expected?'match':'mismatch');
  add('FINAL_DECISION_EXISTS',Boolean(decision),decision?.decisionId||'missing');
  add('FINAL_DECISION_RELEASE',decision?.action===cfg.latestDecisionAction,decision?.action||'missing');
  add('FINAL_DECISION_ACCEPTED',decision?.accepted===cfg.latestDecisionAccepted,String(decision?.accepted));
  add('FINAL_DECISION_IMMUTABLE',decision?.immutable===true,String(decision?.immutable));
  add('RELEASE_EVALUATION_READY',evaluation?.status===cfg.releaseEvaluationStatus&&evaluation?.readyForManualRelease===true,evaluation?.status||'missing');
  add('SEVEN_DAY_BASELINE_READY',baseline?.status===cfg.baselineStatus&&baseline?.actualLearnerDataUsed===true&&Number(baseline?.sufficientDays||0)>=7,`${baseline?.status||'missing'} ${baseline?.sufficientDays||0}/7`);
  add('SEVEN_DAY_OPERATIONS_READY',operations?.status===cfg.operationsStatus&&operations?.ready===true&&Number(operations?.openP0P1||0)===0&&Number(operations?.unresolvedP2||0)===0,operations?.status||'missing');
  add('PHASE34_EXTERNAL_OBSERVATION_PASS',observation?.status==='PASS'&&observation?.actualExternalContext===true,observation?.status||'missing');
  add('SEVEN_DAY_HEX_READY',hex?.status==='READY'&&hex?.personalizationChanged===false,hex?.status||'missing');
  const pass=errors.length===0;
  return {format:'JK_ENG_PHASE36_PHASE35_RELEASE_INPUT_VERIFICATION',version:VERSION,verificationId:text(options.verificationId)||uid('v1-release-input'),status:pass?'PASS':'FAIL',approvedForReleaseExecution:pass,bundleSha256:computed,expectedSha256:expected||null,latestDecision:clone(decision),baselineSummary:{status:baseline?.status||'NOT_COLLECTED',sufficientDays:Number(baseline?.sufficientDays||0),averages:clone(baseline?.averages||{})},operationsSummary:{status:operations?.status||'OPERATIONS_INCOMPLETE',openP0P1:Number(operations?.openP0P1||0),unresolvedP2:Number(operations?.unresolvedP2||0)},checks,errors,verifiedAt:nowIso(),automaticRelease:false};
}
function normalizeChecklist(input={},p=policy()){const required=p.releaseLock?.requiredChecklist||[];const values={};for(const key of required)values[key]=Boolean(input?.[key]);return {required,values,missing:required.filter(k=>!values[k]),complete:required.every(k=>values[k])}}
function createReleaseLock(input={},verification={},p=policy()){
  const checklist=normalizeChecklist(input.checklist||{},p),operator=text(input.operator),reason=text(input.reason),errors=[];
  if(verification?.status!=='PASS'||verification?.approvedForReleaseExecution!==true)errors.push('PHASE35_RELEASE_AUDIT_REQUIRED');
  if(!/^[a-f0-9]{64}$/.test(normalizeHash(verification?.bundleSha256)))errors.push('SOURCE_BUNDLE_SHA256_REQUIRED');
  if(!checklist.complete)errors.push('CHECKLIST_INCOMPLETE');if(p.releaseLock?.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');if(p.releaseLock?.reasonRequired!==false&&!reason)errors.push('REASON_REQUIRED');
  const accepted=errors.length===0;return {format:'JK_ENG_PHASE36_RELEASE_LOCK',version:VERSION,lockId:text(input.lockId)||uid('v1-release-lock'),status:accepted?'LOCKED':'LOCK_REJECTED',accepted,errors,checklist,operator,reason,bundleSha256:normalizeHash(verification?.bundleSha256),verificationId:verification?.verificationId||null,lockedAt:input.lockedAt||nowIso(),immutable:true,automaticRelease:false};
}
function createReleaseExecution(input={},lock={},p=policy()){
  const targetUrl=text(input.targetUrl).replace(/\/$/,'');let parsed=null;try{parsed=new URL(targetUrl)}catch(_){ }
  const rehash=normalizeHash(input.reverifiedSha256),phrase=text(input.confirmationPhrase),operator=text(input.operator),evidence=text(input.evidence),errors=[];
  if(lock?.status!=='LOCKED'||lock?.accepted!==true)errors.push('RELEASE_LOCK_REQUIRED');
  if(p.releaseExecution?.httpsRequired!==false&&(!parsed||parsed.protocol!=='https:'))errors.push('HTTPS_TARGET_REQUIRED');
  if(p.releaseExecution?.actualExternalContextRequired===true&&input.actualExternalContext!==true)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED');
  if(phrase!==(p.releaseLock?.confirmationPhrase||'EXECUTE JK ENGLISH V1.0 RELEASE'))errors.push('CONFIRMATION_PHRASE_MISMATCH');
  if(!rehash||rehash!==normalizeHash(lock?.bundleSha256))errors.push('PREEXECUTION_REHASH_MISMATCH');
  if(!operator)errors.push('OPERATOR_REQUIRED');if(p.releaseExecution?.evidenceRequired!==false&&!evidence)errors.push('EVIDENCE_REQUIRED');
  const accepted=errors.length===0;return {format:'JK_ENG_PHASE36_V1_RELEASE_EXECUTION',version:VERSION,executionId:text(input.executionId)||uid('v1-release-execution'),status:accepted?'RELEASE_EXECUTED':'RELEASE_BLOCKED',accepted,errors,releaseTarget:p.releaseTarget||'JK English v1.0',rollbackTarget:p.releaseExecution?.rollbackTarget||'JK English v1.0 RC2',targetUrl:targetUrl||null,actualExternalContext:Boolean(input.actualExternalContext),operator,evidence,bundleSha256:rehash||null,lockId:lock?.lockId||null,executedAt:input.executedAt||nowIso(),automaticRelease:false};
}
function evaluatePostReleaseSmoke(input={},execution={},p=policy()){
  const defs=p.releaseExecution?.smokeTests||[],provided=input.tests||{},actual=Boolean(input.actualExternalContext),operator=text(input.operator);
  if(execution?.status!=='RELEASE_EXECUTED'||execution?.accepted!==true)return {format:'JK_ENG_PHASE36_POST_RELEASE_SMOKE',version:VERSION,runId:text(input.runId)||uid('v1-release-smoke'),status:'RELEASE_SMOKE_NOT_RUN',tests:defs.map(d=>({id:d.id,label:d.label,status:'NOT_RUN',evidence:'',pass:false})),actualExternalContext:false,errors:['RELEASE_NOT_EXECUTED'],testedAt:null,automaticPass:false};
  const rows=defs.map(def=>{const raw=provided[def.id]||{},status=text(raw.status||'NOT_RUN').toUpperCase(),evidence=text(raw.evidence);let final=status;if(status==='PASS'&&(!actual||!evidence))final='INCOMPLETE_EVIDENCE';return{id:def.id,label:def.label,status:final,evidence,pass:final==='PASS'}});
  const failed=rows.some(r=>r.status==='FAIL'),allPass=rows.length>0&&rows.every(r=>r.pass),status=!actual?'RELEASE_SMOKE_INCOMPLETE':failed?'RELEASE_SMOKE_FAIL':allPass?'RELEASE_SMOKE_PASS':'RELEASE_SMOKE_INCOMPLETE',errors=[];if(!actual)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED');if(!operator)errors.push('OPERATOR_REQUIRED');
  return {format:'JK_ENG_PHASE36_POST_RELEASE_SMOKE',version:VERSION,runId:text(input.runId)||uid('v1-release-smoke'),status,tests:rows,actualExternalContext:actual,operator,targetUrl:execution.targetUrl||null,errors,testedAt:input.testedAt||nowIso(),automaticPass:false};
}
function createFollowupOpsSnapshot(input={},execution={},p=policy()){
  const cfg=p.followupOperations||{},date=dateOnly(input.date),releaseDate=dateOnly(execution?.executedAt),sync=text(input.syncStatus).toUpperCase(),backup=text(input.backupStatus).toUpperCase(),recovery=text(input.recoveryStatus).toUpperCase(),review=text(input.incidentReviewStatus).toUpperCase(),operator=text(input.operator),evidence=text(input.evidence),errors=[];
  if(execution?.status!=='RELEASE_EXECUTED')errors.push('RELEASE_EXECUTION_REQUIRED');if(!date)errors.push('DATE_REQUIRED');if(releaseDate&&date<releaseDate)errors.push('DATE_BEFORE_RELEASE');if(cfg.actualExternalContextRequired===true&&input.actualExternalContext!==true)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED');if(!(cfg.syncStatuses||[]).includes(sync))errors.push('SYNC_STATUS_INVALID');if(!(cfg.backupStatuses||[]).includes(backup))errors.push('BACKUP_STATUS_INVALID');if(!(cfg.recoveryStatuses||[]).includes(recovery))errors.push('RECOVERY_STATUS_INVALID');if(!(cfg.incidentReviewStatuses||[]).includes(review))errors.push('INCIDENT_REVIEW_STATUS_INVALID');if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');if(cfg.evidenceRequired!==false&&!evidence)errors.push('EVIDENCE_REQUIRED');
  const accepted=errors.length===0;return {format:'JK_ENG_PHASE36_FOLLOWUP_OPERATIONS_SNAPSHOT',version:VERSION,snapshotId:text(input.snapshotId)||uid(`v1-ops-${date||'day'}`),date,status:accepted?'RECORDED':'REJECTED',accepted,errors,actualExternalContext:Boolean(input.actualExternalContext),syncStatus:sync||'NOT_VERIFIED',backupStatus:backup||'NOT_VERIFIED',recoveryStatus:recovery||'NOT_VERIFIED',incidentReviewStatus:review||'INCOMPLETE',queuedSync:Math.max(0,Number(input.queuedSync||0)),failedSync:Math.max(0,Number(input.failedSync||0)),operator,evidence,recordedAt:input.recordedAt||nowIso(),immutable:true,automaticPass:false};
}
function normalizeIncident(input={}){const severity=text(input.severity||'P2').toUpperCase(),status=text(input.status||'OPEN').toUpperCase();return {format:'JK_ENG_PHASE36_RELEASE_INCIDENT',version:VERSION,incidentId:text(input.incidentId)||uid('v1-incident'),severity:['P0','P1','P2'].includes(severity)?severity:'P2',status:['OPEN','MITIGATED','CLOSED'].includes(status)?status:'OPEN',title:text(input.title),detail:text(input.detail),evidence:text(input.evidence),at:input.at||nowIso(),updatedAt:nowIso()}}
function sufficientReport(r={},cfg={}){return Boolean(r?.completedAt)&&Number(r?.attempts||0)>=Number(cfg.minimumAttempts||12)&&Number(r?.activeMinutes||0)>=Number(cfg.minimumActiveMinutes||25)&&Number(r?.grammarMinutes||0)>=Number(cfg.minimumGrammarMinutes||12)&&Number(r?.readingMinutes||0)>=Number(cfg.minimumReadingMinutes||10)}
function evaluateCheckpoint(input={},p=policy()){
  const days=Number(input.days||0),cfg=(p.checkpoints||[]).find(x=>Number(x.days)===days),execution=input.execution||{},smoke=input.smoke||{},baseline=input.baseline||{},asOf=dateOnly(input.asOf||nowIso()),releaseDate=dateOnly(execution?.executedAt),dueDate=cfg&&releaseDate?addDays(releaseDate,days-1):'',allReports=sortedUnique(input.dailyReports||[]),allOps=sortedUnique((input.opsSnapshots||[]).filter(x=>x?.accepted===true)),incidents=(input.incidents||[]).map(x=>normalizeIncident(x));
  if(!cfg)return {format:'JK_ENG_PHASE36_CHECKPOINT_EVALUATION',version:VERSION,days,status:'CHECKPOINT_INVALID',errors:['CHECKPOINT_INVALID'],automaticRollback:false,automaticPersonalizationChange:false};
  const base={format:'JK_ENG_PHASE36_CHECKPOINT_EVALUATION',version:VERSION,days,releaseDate,dueDate,asOf,minimumSufficientLearningDays:Number(cfg.minimumSufficientLearningDays||0),minimumOperationsDays:Number(cfg.minimumOperationsDays||0),automaticRollback:false,automaticPersonalizationChange:false};
  if(execution?.status!=='RELEASE_EXECUTED'||execution?.accepted!==true||smoke?.status!=='RELEASE_SMOKE_PASS')return {...base,status:'NOT_COLLECTED',recommendation:'HOLD',errors:['RELEASE_AND_SMOKE_PASS_REQUIRED'],actualLearnerDataUsed:false};
  const inWindow=r=>{const d=dateOnly(r);return d&&d>=releaseDate&&d<=dueDate};const reports=allReports.filter(inWindow),sufficient=reports.filter(r=>sufficientReport(r,p.sufficientLearningDay||{})),ops=allOps.filter(inWindow),opsMap=new Map(ops.map(o=>[dateOnly(o),o]));
  const current={activeMinutes:avg(sufficient.map(r=>r.activeMinutes)),answerAccuracy:avg(sufficient.map(r=>r.answerAccuracy)),processPassRate:avg(sufficient.map(r=>r.processPassRate)),recoveryRate:avg(sufficient.map(r=>r.recoveryRate)),paceStability:avg(sufficient.map(r=>r.axes?.paceStability))};
  const reference=clone(baseline?.averages||{}),threshold=p.regressionThresholds||{},drops={answerAccuracy:reference.answerAccuracy!=null&&current.answerAccuracy!=null?Math.round((Number(reference.answerAccuracy)-Number(current.answerAccuracy))*10)/10:null,processPassRate:reference.processPassRate!=null&&current.processPassRate!=null?Math.round((Number(reference.processPassRate)-Number(current.processPassRate))*10)/10:null,recoveryRate:reference.recoveryRate!=null&&current.recoveryRate!=null?Math.round((Number(reference.recoveryRate)-Number(current.recoveryRate))*10)/10:null,paceStability:reference.paceStability!=null&&current.paceStability!=null?Math.round((Number(reference.paceStability)-Number(current.paceStability))*10)/10:null};
  const triggers=[];if(drops.answerAccuracy!=null&&drops.answerAccuracy>=Number(threshold.answerAccuracyDropPoints||8))triggers.push('ANSWER_ACCURACY_REGRESSION');if(drops.processPassRate!=null&&drops.processPassRate>=Number(threshold.processPassDropPoints||8))triggers.push('PROCESS_PASS_REGRESSION');if(drops.recoveryRate!=null&&drops.recoveryRate>=Number(threshold.recoveryDropPoints||10))triggers.push('RECOVERY_REGRESSION');if(drops.paceStability!=null&&drops.paceStability>=Number(threshold.paceStabilityDropPoints||12))triggers.push('PACE_STABILITY_REGRESSION');
  const severe=(drops.answerAccuracy!=null&&drops.answerAccuracy>=Number(threshold.severeAnswerOrProcessDropPoints||12))||(drops.processPassRate!=null&&drops.processPassRate>=Number(threshold.severeAnswerOrProcessDropPoints||12))||(drops.recoveryRate!=null&&drops.recoveryRate>=Number(threshold.severeRecoveryDropPoints||15))||(drops.paceStability!=null&&drops.paceStability>=Number(threshold.severePaceStabilityDropPoints||20));
  const openCritical=incidents.filter(i=>['P0','P1'].includes(i.severity)&&i.status!=='CLOSED'&&dateOnly(i.at)>=releaseDate&&dateOnly(i.at)<=dueDate),opsFailures=ops.filter(o=>o.syncStatus==='FAILED'||Number(o.failedSync||0)>0||o.backupStatus==='FAIL'||['FAILED','DEGRADED'].includes(o.recoveryStatus)||o.incidentReviewStatus!=='COMPLETE');
  const dueReached=Boolean(asOf&&dueDate&&asOf>=dueDate),learningReady=sufficient.length>=Number(cfg.minimumSufficientLearningDays||0),opsReady=ops.length>=Number(cfg.minimumOperationsDays||0),actualLearnerDataUsed=Boolean(input.actualLearnerDataUsed===true&&learningReady),meaningful=triggers.length>=Number(threshold.minimumTriggersForHoldReview||2),continuityRate=days?Math.round(reports.filter(r=>r?.completedAt).length*1000/days)/10:0;
  let status='OBSERVING',recommendation='CONTINUE';const errors=[];if(!dueReached){status='OBSERVING'}else if(!learningReady||!opsReady||!actualLearnerDataUsed){status='CHECKPOINT_INCOMPLETE';recommendation='HOLD';if(!learningReady)errors.push('INSUFFICIENT_LEARNING_DAYS');if(!opsReady)errors.push('INSUFFICIENT_OPERATIONS_DAYS');if(!actualLearnerDataUsed)errors.push('ACTUAL_LEARNER_DATA_REQUIRED')}else if(openCritical.length||severe){status='ROLLBACK_REVIEW_REQUIRED';recommendation='ROLLBACK_REVIEW'}else if(meaningful||opsFailures.length){status='HOLD_REVIEW_REQUIRED';recommendation='HOLD'}else{status='STABLE';recommendation='CONTINUE'}
  return {...base,status,recommendation,errors,actualLearnerDataUsed,sufficientLearningDays:sufficient.length,operationsDays:ops.length,completedLearningDays:reports.filter(r=>r?.completedAt).length,learningContinuityRate:continuityRate,currentMetrics:current,baselineMetrics:reference,drops,regressionTriggers:triggers,severeRegression:severe,openP0P1:openCritical.length,operationsFailureDays:opsFailures.map(dateOnly),sourceDates:sufficient.map(dateOnly),operationsDates:ops.map(dateOnly),evaluatedAt:nowIso(),thresholdsChanged:false};
}
function makeFollowupDecision(input={},checkpoint={},p=policy()){
  const cfg=p.followupDecision||{},action=text(input.action||'HOLD').toUpperCase(),reviewer=text(input.reviewer),reason=text(input.reason),confirmation=text(input.confirmationPhrase),errors=[];
  if(!(cfg.allowedActions||[]).includes(action))errors.push('ACTION_INVALID');if(cfg.reviewerRequired!==false&&!reviewer)errors.push('REVIEWER_REQUIRED');if(cfg.reasonRequired!==false&&!reason)errors.push('REASON_REQUIRED');if(![14,30].includes(Number(checkpoint?.days)))errors.push('CHECKPOINT_REQUIRED');if(action==='CONTINUE'&&checkpoint?.status!=='STABLE')errors.push('CONTINUE_REQUIRES_STABLE');if(action==='ROLLBACK_REQUEST'&&checkpoint?.status!=='ROLLBACK_REVIEW_REQUIRED'&&Number(checkpoint?.openP0P1||0)===0)errors.push('ROLLBACK_REVIEW_NOT_REQUIRED');if(action==='ROLLBACK_REQUEST'&&confirmation!==(cfg.rollbackConfirmationPhrase||'REQUEST JK ENGLISH V1.0 ROLLBACK'))errors.push('ROLLBACK_CONFIRMATION_MISMATCH');
  const accepted=errors.length===0;return {format:'JK_ENG_PHASE36_FOLLOWUP_DECISION',version:VERSION,decisionId:text(input.decisionId)||uid('v1-followup-decision'),checkpointDays:Number(checkpoint?.days||0),checkpointStatus:checkpoint?.status||'NOT_COLLECTED',action,status:accepted?(action==='ROLLBACK_REQUEST'?'ROLLBACK_REQUESTED':'RECORDED'):'REJECTED',accepted,errors,reviewer,reason,confirmationMatched:action!=='ROLLBACK_REQUEST'||!errors.includes('ROLLBACK_CONFIRMATION_MISMATCH'),decidedAt:input.decidedAt||nowIso(),immutable:true,automaticRollback:false,externalRollbackExecution:cfg.externalRollbackExecution||'NOT_VERIFIED'};
}
function createPersonalizationReview(input={},checkpoint={},p=policy()){
  const cfg=p.personalizationReview||{},action=text(input.action||'KEEP_CURRENT').toUpperCase(),reviewer=text(input.reviewer),reason=text(input.reason),errors=[];
  if(!(cfg.allowedActions||[]).includes(action))errors.push('ACTION_INVALID');if(![14,30].includes(Number(checkpoint?.days)))errors.push('CHECKPOINT_REQUIRED');if(!(cfg.checkpointStatuses||['STABLE']).includes(checkpoint?.status))errors.push('STABLE_CHECKPOINT_REQUIRED');if(checkpoint?.actualLearnerDataUsed!==true)errors.push('ACTUAL_LEARNER_DATA_REQUIRED');if(cfg.adminApprovalRequired!==false&&input.adminApproved!==true)errors.push('ADMIN_APPROVAL_REQUIRED');if(cfg.reviewerRequired!==false&&!reviewer)errors.push('REVIEWER_REQUIRED');if(cfg.reasonRequired!==false&&!reason)errors.push('REASON_REQUIRED');
  const accepted=errors.length===0;return {format:'JK_ENG_PHASE36_PERSONALIZATION_REVIEW',version:VERSION,reviewId:text(input.reviewId)||uid('personalization-review'),checkpointDays:Number(checkpoint?.days||0),checkpointStatus:checkpoint?.status||'NOT_COLLECTED',action,status:accepted?'RECORDED':'REJECTED',accepted,errors,reviewer,reason,adminApproved:Boolean(input.adminApproved),reviewedAt:input.reviewedAt||nowIso(),thresholdsChanged:false,automaticThresholdChange:false,manualChangeExecutionIncluded:false,immutable:true};
}
function buildFollowupAuditBundle(input={},p=policy()){
  return {format:'JK_ENG_PHASE36_V1_RELEASE_FOLLOWUP_AUDIT_BUNDLE',version:VERSION,releaseTarget:p.releaseTarget||'JK English v1.0',exportedAt:nowIso(),policy:clone(p),state:clone(global.JK_PHASE36_DATA?.state||{}),phase35BundleMeta:clone(input.phase35BundleMeta||null),preReleaseVerification:clone(input.preReleaseVerification||null),releaseLocks:clone(input.releaseLocks||[]),releaseExecutions:clone(input.releaseExecutions||[]),postReleaseSmokeRuns:clone(input.smokeRuns||[]),followupOperationsSnapshots:clone(input.opsSnapshots||[]),releaseIncidents:clone(input.incidents||[]),checkpointEvaluations:clone(input.checkpoints||[]),followupDecisions:clone(input.followupDecisions||[]),personalizationReviews:clone(input.personalizationReviews||[]),truthfulBoundary:{releaseDecisionIsNotExternalExecution:true,localOrSyntheticCannotPromoteRelease:true,automaticRelease:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,rollbackRequestIsNotExternalRollbackExecution:true}};
}
const api={VERSION,normalizeHash,dateOnly,addDays,latestDecision,verifyPhase35ReleaseBundle,normalizeChecklist,createReleaseLock,createReleaseExecution,evaluatePostReleaseSmoke,createFollowupOpsSnapshot,normalizeIncident,sufficientReport,evaluateCheckpoint,makeFollowupDecision,createPersonalizationReview,buildFollowupAuditBundle};
if(typeof module!=='undefined'&&module.exports)module.exports=api;global.JK_PHASE36=api;
})(typeof globalThis!=='undefined'?globalThis:this);
