(function(global){
'use strict';
const VERSION='42.0';
const text=v=>String(v==null?'':v).trim();
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const nowIso=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
const policy=()=>global.JK_PHASE42_DATA?.policy||{};
const normalizeHash=v=>text(v).toLowerCase().replace(/^sha256:/,'').trim();
const validHash=v=>/^[a-f0-9]{64}$/.test(normalizeHash(v));
const dateOnly=v=>{const source=(typeof v==='string'||typeof v==='number')?v:(v?.date||v?.dayId||v?.executedAt||v?.testedAt||v?.evaluatedAt||v?.recordedAt||v?.updatedAt||v?.at||v);const raw=text(source).replace(/^DAY-/,'');const m=raw.match(/(\d{4}-\d{2}-\d{2})/);return m?m[1]:''};
const addDays=(date,n)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+Number(n||0));return d.toISOString().slice(0,10)};
const avg=values=>{const rows=(values||[]).map(Number).filter(Number.isFinite);return rows.length?Math.round(rows.reduce((a,b)=>a+b,0)*10/rows.length)/10:null};
const latest=(rows=[],field)=>((Array.isArray(rows)?rows:[]).slice().sort((a,b)=>Date.parse(b?.[field]||b?.approvedAt||b?.testedAt||b?.executedAt||b?.evaluatedAt||b?.recordedAt||b?.updatedAt||b?.at||0)-Date.parse(a?.[field]||a?.approvedAt||a?.testedAt||a?.executedAt||a?.evaluatedAt||a?.recordedAt||a?.updatedAt||a?.at||0))[0]||null);
function findBy(rows=[],idField,id){return (Array.isArray(rows)?rows:[]).find(x=>text(x?.[idField])===text(id))||null}
function implementationCoverage(bundle={},gate={}){const ids=(gate?.implementationEvidenceIds||[]).map(text),records=(bundle?.implementationEvidence||[]).filter(x=>x?.accepted===true&&x?.status==='IMPLEMENTATION_EVIDENCE_RECORDED'),byId=new Map(records.map(x=>[text(x.evidenceId),x])),missing=ids.filter(id=>!byId.has(id));return {requiredIds:ids,records:ids.map(id=>byId.get(id)).filter(Boolean),missing,complete:ids.length>0&&missing.length===0}}
function unresolvedP0P1(bundle={},p=policy()){const sev=p.acceptedPhase41Bundle?.noUnresolvedP0P1===true,defs=bundle?.policy?.defects||{},blockingSev=defs.blockingSeverities||['P0','P1'],blockingStatus=defs.blockingStatuses||['OPEN','TRIAGED','FIXED','REVERIFY_REQUIRED'];const rows=(bundle?.defects||[]).filter(d=>blockingSev.includes(d?.severity)&&blockingStatus.includes(d?.status));return sev?rows:[]}
function verifyPhase41RcAuditBundle(bundle={},options={},p=policy()){
 const cfg=p.acceptedPhase41Bundle||{},checks=[],errors=[];const add=(id,ok,detail='')=>{checks.push({id,ok:Boolean(ok),detail:text(detail)});if(!ok)errors.push(id)};
 const computed=normalizeHash(options.computedSha256),expected=normalizeHash(options.expectedSha256),gate=latest(bundle?.rcGates||[],'approvedAt'),staging=gate?findBy(bundle?.candidateStagingRuns,'runId',gate.stagingRunId):latest(bundle?.candidateStagingRuns||[],'testedAt'),coverage=implementationCoverage(bundle,gate),blocking=unresolvedP0P1(bundle,p),phase40=bundle?.phase40AuditVerification||{};
 add('BUNDLE_FORMAT',bundle?.format===cfg.format,bundle?.format||'missing');add('BUNDLE_VERSION',bundle?.version===cfg.version,bundle?.version||'missing');add('CHANGE_TARGET',bundle?.changeTarget===cfg.changeTarget,bundle?.changeTarget||'missing');add('ROLLBACK_TARGET',bundle?.rollbackTarget===cfg.rollbackTarget,bundle?.rollbackTarget||'missing');add('SOURCE_SHA256_COMPUTED',validHash(computed),computed||'missing');if(expected)add('SOURCE_SHA256_MATCH',computed===expected,computed===expected?'match':'mismatch');
 add('RC_APPROVED',gate?.status===cfg.requiredRcStatus&&gate?.accepted===cfg.requiredRcAccepted,gate?.status||'missing');add('RC_EXTERNAL_RELEASE_STILL_NOT_RUN',gate?.externalV102Release==='NOT_RUN',gate?.externalV102Release||'missing');add('RC_NOT_PRODUCTION_DEPLOYMENT_AUTH',gate?.productionDeploymentAuthorization==='NOT_GRANTED',gate?.productionDeploymentAuthorization||'missing');
 add('STAGING_PASS',staging?.status===cfg.requiredCandidateStagingStatus&&staging?.accepted===cfg.requiredCandidateStagingAccepted,staging?.status||'missing');add('ACTUAL_STAGING_CONTEXT',cfg.actualStagingContextRequired!==true||staging?.actualStagingContext===true,String(staging?.actualStagingContext));add('RC_STAGING_LINK',Boolean(gate&&staging&&text(gate.stagingRunId)===text(staging.runId)),gate?.stagingRunId||'missing');
 add('ROLLBACK_REHEARSAL_PASS',staging?.rollbackRehearsal?.status===cfg.requiredRollbackRehearsalStatus,staging?.rollbackRehearsal?.status||'missing');add('IMPLEMENTATION_EVIDENCE_COMPLETE',cfg.completeImplementationEvidenceRequired!==true||coverage.complete,coverage.complete?'complete':coverage.missing.join(','));
 add('PLAN_LINK',Boolean(gate&&phase40?.plan&&text(gate.planId)===text(phase40.plan.planId)),gate?.planId||'missing');add('GUARDRAIL_LINK',Boolean(gate&&phase40?.guardrail&&text(gate.guardrailId)===text(phase40.guardrail.guardrailId)),gate?.guardrailId||'missing');
 add('CANDIDATE_ARTIFACT_SHA256',cfg.candidateArtifactSha256Required!==true||validHash(staging?.candidateArtifactSha256),staging?.candidateArtifactSha256||'missing');add('ASSET_MANIFEST_IDENTITY',cfg.assetManifestIdentityRequired!==true||(Boolean(text(staging?.assetManifestVersion))&&validHash(staging?.assetManifestSha256)),`${staging?.assetManifestVersion||'missing'} / ${staging?.assetManifestSha256||'missing'}`);
 add('NO_UNRESOLVED_P0P1',cfg.noUnresolvedP0P1!==true||blocking.length===0,String(blocking.length));add('NO_GUARDRAIL_REGRESSION',cfg.guardrailRegressionForbidden!==true||gate?.guardrailRegression!==true,String(gate?.guardrailRegression));add('NO_CONTENT_APPROVAL_MISMATCH',cfg.contentApprovalMismatchForbidden!==true||gate?.contentApprovalMismatch!==true,String(gate?.contentApprovalMismatch));add('NO_LEARNING_LOOP_REGRESSION',cfg.learningLoopInvariantRegressionForbidden!==true||gate?.learningLoopInvariantRegression!==true,String(gate?.learningLoopInvariantRegression));
 const pass=errors.length===0;return {format:'JK_ENG_PHASE42_PHASE41_RC_AUDIT_VERIFICATION',version:VERSION,verificationId:text(options.verificationId)||uid('phase41-rc-audit'),status:pass?'PASS':'FAIL',accepted:pass,eligibleForExternalRelease:pass,bundleSha256:computed,expectedSha256:expected||null,rcGate:clone(gate),candidateStaging:clone(staging),implementationCoverage:clone(coverage),blockingDefects:clone(blocking),plan:clone(phase40?.plan||null),guardrail:clone(phase40?.guardrail||null),candidateArtifactSha256:normalizeHash(staging?.candidateArtifactSha256)||null,assetManifestVersion:text(staging?.assetManifestVersion)||null,assetManifestSha256:normalizeHash(staging?.assetManifestSha256)||null,checks,errors,verifiedAt:nowIso(),automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false};
}
function normalizeTests(defs=[],provided={}){return (defs||[]).map(d=>{const row=provided?.[d.id]||{};const status=text(row.status||'NOT_RUN').toUpperCase(),evidence=text(row.evidence);return {id:d.id,label:d.label,status,evidence,pass:status==='PASS'&&Boolean(evidence)}})}
function createExternalReleaseExecution(input={},verification={},p=policy()){
 const cfg=p.externalRelease||{},sourceHash=normalizeHash(verification?.bundleSha256),rehash=normalizeHash(input.rehashedSha256),targetUrl=text(input.targetUrl),operator=text(input.operator),evidence=text(input.evidence),confirmation=text(input.confirmationPhrase),actual=Boolean(input.actualExternalContext),deployedCandidateSha=normalizeHash(input.deployedCandidateSha256),deployedManifestVersion=text(input.deployedAssetManifestVersion),deployedManifestSha=normalizeHash(input.deployedAssetManifestSha256),errors=[];
 if(verification?.status!=='PASS'||verification?.eligibleForExternalRelease!==true)errors.push('PHASE41_RC_APPROVED_AUDIT_REQUIRED');if(!validHash(rehash))errors.push('RELEASE_REHASH_REQUIRED');else if(rehash!==sourceHash)errors.push('RELEASE_REHASH_MISMATCH');if(cfg.actualExternalContextRequired!==false&&!actual)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED');if(cfg.httpsRequired!==false&&!/^https:\/\//i.test(targetUrl))errors.push('HTTPS_TARGET_REQUIRED');if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');if(cfg.evidenceRequired!==false&&!evidence)errors.push('EVIDENCE_REQUIRED');if(confirmation!==cfg.confirmationPhrase)errors.push('RELEASE_CONFIRMATION_MISMATCH');if(cfg.deployedCandidateIdentityRequired!==false){if(!validHash(deployedCandidateSha)||deployedCandidateSha!==normalizeHash(verification?.candidateArtifactSha256))errors.push('DEPLOYED_CANDIDATE_IDENTITY_MISMATCH');if(deployedManifestVersion!==text(verification?.assetManifestVersion))errors.push('DEPLOYED_ASSET_MANIFEST_VERSION_MISMATCH');if(!validHash(deployedManifestSha)||deployedManifestSha!==normalizeHash(verification?.assetManifestSha256))errors.push('DEPLOYED_ASSET_MANIFEST_SHA256_MISMATCH')}
 const accepted=errors.length===0;return {format:'JK_ENG_PHASE42_V102_RELEASE_EXECUTION',version:VERSION,executionId:text(input.executionId)||uid('v102-release'),status:accepted?'V102_RELEASE_EXECUTED':'V102_RELEASE_BLOCKED',accepted,errors,releaseTarget:p.releaseTarget||'JK English v1.0.2',rollbackTarget:p.rollbackTarget||'JK English v1.0.1',targetUrl:targetUrl||null,actualExternalContext:actual,operator,evidence,phase41BundleSha256:sourceHash||null,executionRehashSha256:rehash||null,rcGateId:verification?.rcGate?.gateId||null,planId:verification?.rcGate?.planId||verification?.plan?.planId||null,stagingRunId:verification?.candidateStaging?.runId||null,candidateArtifactSha256:verification?.candidateArtifactSha256||null,deployedCandidateSha256:deployedCandidateSha||null,deployedAssetManifestVersion:deployedManifestVersion||null,deployedAssetManifestSha256:deployedManifestSha||null,executedAt:accepted?(input.executedAt||nowIso()):null,automaticRelease:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false};
}
function evaluatePostReleaseSmoke(input={},execution={},verification={},p=policy()){
 const defs=p.externalRelease?.smokeTests||[],tests=normalizeTests(defs,input.tests||{}),actual=Boolean(input.actualExternalContext),operator=text(input.operator),errors=[];
 if(execution?.status!=='V102_RELEASE_EXECUTED'||execution?.accepted!==true)return {format:'JK_ENG_PHASE42_V102_POST_RELEASE_SMOKE',version:VERSION,runId:text(input.runId)||uid('v102-smoke'),status:'V102_SMOKE_NOT_RUN',tests:defs.map(d=>({id:d.id,label:d.label,status:'NOT_RUN',evidence:'',pass:false})),actualExternalContext:false,errors:['V102_RELEASE_NOT_EXECUTED'],testedAt:null,automaticPass:false};
 if(p.externalRelease?.actualExternalContextRequired!==false&&!actual)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED');if(!operator)errors.push('OPERATOR_REQUIRED');for(const t of tests)if(!t.pass)errors.push(`SMOKE_${t.id}_PASS_REQUIRED`);if(normalizeHash(execution.deployedCandidateSha256)!==normalizeHash(verification?.candidateArtifactSha256))errors.push('SMOKE_CANDIDATE_IDENTITY_MISMATCH');if(execution.deployedAssetManifestVersion!==verification?.assetManifestVersion||normalizeHash(execution.deployedAssetManifestSha256)!==normalizeHash(verification?.assetManifestSha256))errors.push('SMOKE_ASSET_IDENTITY_MISMATCH');const pass=errors.length===0;
 return {format:'JK_ENG_PHASE42_V102_POST_RELEASE_SMOKE',version:VERSION,runId:text(input.runId)||uid('v102-smoke'),status:pass?'V102_SMOKE_PASS':'V102_SMOKE_FAIL',pass,tests,actualExternalContext:actual,operator,targetUrl:execution.targetUrl||null,errors,testedAt:input.testedAt||nowIso(),automaticPass:false};
}
function createOpsSnapshot(input={},execution={},p=policy()){
 const cfg=p.followupOperations||{},date=dateOnly(input.date),sync=text(input.syncStatus).toUpperCase(),backup=text(input.backupStatus).toUpperCase(),recovery=text(input.recoveryStatus).toUpperCase(),content=text(input.contentIdentityStatus).toUpperCase(),asset=text(input.assetIdentityStatus).toUpperCase(),operator=text(input.operator),evidence=text(input.evidence),actual=Boolean(input.actualExternalContext),errors=[];
 if(execution?.status!=='V102_RELEASE_EXECUTED'||execution?.accepted!==true)errors.push('V102_RELEASE_NOT_EXECUTED');if(!date)errors.push('DATE_REQUIRED');if(!(cfg.syncStatuses||[]).includes(sync))errors.push('SYNC_STATUS_INVALID');if(!(cfg.backupStatuses||[]).includes(backup))errors.push('BACKUP_STATUS_INVALID');if(!(cfg.recoveryStatuses||[]).includes(recovery))errors.push('RECOVERY_STATUS_INVALID');if(!(cfg.contentIdentityStatuses||[]).includes(content))errors.push('CONTENT_IDENTITY_STATUS_INVALID');if(!(cfg.assetIdentityStatuses||[]).includes(asset))errors.push('ASSET_IDENTITY_STATUS_INVALID');if(cfg.actualExternalContextRequired!==false&&!actual)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED');if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');if(cfg.evidenceRequired!==false&&!evidence)errors.push('EVIDENCE_REQUIRED');const accepted=errors.length===0;
 return {format:'JK_ENG_PHASE42_V102_OPERATIONS_SNAPSHOT',version:VERSION,snapshotId:text(input.snapshotId)||uid('v102-ops'),date,status:accepted?'RECORDED':'REJECTED',accepted,errors,syncStatus:sync||'CLEAR',backupStatus:backup||'NOT_VERIFIED',recoveryStatus:recovery||'NOT_VERIFIED',contentIdentityStatus:content||'NOT_VERIFIED',assetIdentityStatus:asset||'NOT_VERIFIED',actualExternalContext:actual,operator,evidence,recordedAt:input.recordedAt||nowIso(),immutable:true};
}
function normalizeIncident(input={}){const severity=text(input.severity||'P2').toUpperCase(),status=text(input.status||'OPEN').toUpperCase(),category=text(input.category||'GENERAL').toUpperCase();return {format:'JK_ENG_PHASE42_V102_INCIDENT',version:VERSION,incidentId:text(input.incidentId)||uid('v102-incident'),severity:['P0','P1','P2'].includes(severity)?severity:'P2',status:['OPEN','MITIGATED','CLOSED'].includes(status)?status:'OPEN',category:['GENERAL','LEARNER_IMPACT','CONTENT_MISMATCH','ASSET_IDENTITY'].includes(category)?category:'GENERAL',title:text(input.title),detail:text(input.detail),evidence:text(input.evidence),at:input.at||nowIso(),updatedAt:input.updatedAt||nowIso()}}
function sufficientReport(r={},cfg={}){return Boolean(r?.completedAt)&&Number(r?.attempts||0)>=Number(cfg.minimumAttempts||12)&&Number(r?.activeMinutes||0)>=Number(cfg.minimumActiveMinutes||25)&&Number(r?.grammarMinutes||0)>=Number(cfg.minimumGrammarMinutes||12)&&Number(r?.readingMinutes||0)>=Number(cfg.minimumReadingMinutes||10)}
function referenceMetricsValid(ref={}){return ['answerAccuracy','processPassRate','recoveryRate','paceStability'].every(k=>Number.isFinite(Number(ref?.[k])))}
function evaluateStabilization14(input={},p=policy()){
 const cfg=p.stabilization14||{},execution=input.execution||{},smoke=input.smoke||{},releaseDate=dateOnly(execution?.executedAt),asOf=dateOnly(input.asOf||nowIso()),dueDate=releaseDate?addDays(releaseDate,Number(cfg.days||14)-1):'',base={format:'JK_ENG_PHASE42_V102_STABILIZATION_14',version:VERSION,evaluationId:text(input.evaluationId)||uid('v102-stabilization14'),days:Number(cfg.days||14),releaseDate:releaseDate||null,dueDate:dueDate||null,asOf:asOf||null,automaticRollback:false,automaticPersonalizationThresholdChange:false};
 if(execution?.status!=='V102_RELEASE_EXECUTED'||execution?.accepted!==true||smoke?.status!=='V102_SMOKE_PASS')return {...base,status:'NOT_COLLECTED',recommendation:'HOLD',errors:['RELEASE_AND_SMOKE_PASS_REQUIRED'],actualLearnerDataUsed:false};if(!releaseDate||!asOf||asOf<dueDate)return {...base,status:'NOT_COLLECTED',recommendation:'HOLD',errors:['DAY14_NOT_REACHED'],actualLearnerDataUsed:false};
 const reports=(input.dailyReports||[]).filter(r=>{const d=dateOnly(r);return d>=releaseDate&&d<=dueDate}),sufficient=reports.filter(r=>sufficientReport(r,cfg.sufficientLearningDay||{})),ops=(input.opsSnapshots||[]).filter(x=>x?.accepted===true&&x.date>=releaseDate&&x.date<=dueDate),incidents=(input.incidents||[]).map(normalizeIncident).filter(x=>{const d=dateOnly(x.at||x.updatedAt);return d>=releaseDate&&d<=dueDate}),actualLearnerDataUsed=Boolean(input.actualLearnerDataUsed),reference=clone(input.referenceMetrics||{});
 const current={learningContinuityRate:reports.length?Math.round(reports.filter(r=>r?.completedAt).length/reports.length*1000)/10:null,answerAccuracy:avg(sufficient.map(r=>r.answerAccuracy)),processPassRate:avg(sufficient.map(r=>r.processPassRate)),recoveryRate:avg(sufficient.map(r=>r.recoveryRate)),paceStability:avg(sufficient.map(r=>r?.axes?.paceStability))},drops={};for(const k of ['learningContinuityRate','answerAccuracy','processPassRate','recoveryRate','paceStability'])drops[k]=(Number.isFinite(Number(reference?.[k]))&&current[k]!=null)?Math.round((Number(reference[k])-current[k])*10)/10:null;
 const syncFailureDays=ops.filter(x=>x.syncStatus==='FAILED').length,backupFailureDays=ops.filter(x=>x.backupStatus==='FAIL').length,recoveryFailureDays=ops.filter(x=>['FAILED','DEGRADED'].includes(x.recoveryStatus)).length,contentMismatchDays=ops.filter(x=>x.contentIdentityStatus==='MISMATCH').length,assetIdentityFailureDays=ops.filter(x=>x.assetIdentityStatus==='FAIL').length,openP0P1=incidents.filter(x=>['P0','P1'].includes(x.severity)&&x.status!=='CLOSED').length,openP2=incidents.filter(x=>x.severity==='P2'&&x.status!=='CLOSED').length,contentMismatchIncidents=incidents.filter(x=>x.category==='CONTENT_MISMATCH'&&x.status!=='CLOSED').length,assetIdentityIncidents=incidents.filter(x=>x.category==='ASSET_IDENTITY'&&x.status!=='CLOSED').length,errors=[];
 if(!actualLearnerDataUsed)errors.push('ACTUAL_LEARNER_DATA_REQUIRED');if(cfg.referenceMetricsRequired!==false&&!referenceMetricsValid(reference))errors.push('REFERENCE_METRICS_REQUIRED');if(sufficient.length<Number(cfg.minimumSufficientLearningDays||9))errors.push('INSUFFICIENT_LEARNING_DAYS');if(ops.length<Number(cfg.minimumOperationsDays||9))errors.push('INSUFFICIENT_OPERATIONS_DAYS');if(errors.length)return {...base,status:'INSUFFICIENT',recommendation:'HOLD',errors,actualLearnerDataUsed,sufficientLearningDays:sufficient.length,operationsDays:ops.length,currentMetrics:current,referenceMetrics:reference,drops,syncFailureDays,backupFailureDays,recoveryFailureDays,contentMismatchDays,assetIdentityFailureDays,openP0P1,openP2,evaluatedAt:nowIso()};
 const th=cfg.regressionThresholds||{},hold=[];if((drops.answerAccuracy??0)>=Number(th.answerAccuracyDropPoints||8))hold.push('answerAccuracy');if((drops.processPassRate??0)>=Number(th.processPassDropPoints||8))hold.push('processPassRate');if((drops.recoveryRate??0)>=Number(th.recoveryDropPoints||10))hold.push('recoveryRate');if((drops.paceStability??0)>=Number(th.paceStabilityDropPoints||12))hold.push('paceStability');const severe=[];if((drops.answerAccuracy??0)>=Number(th.severeAnswerOrProcessDropPoints||12))severe.push('answerAccuracy');if((drops.processPassRate??0)>=Number(th.severeAnswerOrProcessDropPoints||12))severe.push('processPassRate');if((drops.recoveryRate??0)>=Number(th.severeRecoveryDropPoints||15))severe.push('recoveryRate');if((drops.paceStability??0)>=Number(th.severePaceStabilityDropPoints||20))severe.push('paceStability');let status='STABLE',recommendation='CONTINUE';const rollbackTriggers=[];if(openP0P1>0)rollbackTriggers.push('OPEN_P0_P1');if(severe.length)rollbackTriggers.push('SERIOUS_LEARNER_IMPACT_REGRESSION');if(contentMismatchDays>0||contentMismatchIncidents>0)rollbackTriggers.push('CONTENT_IDENTITY_MISMATCH');if(assetIdentityFailureDays>0||assetIdentityIncidents>0)rollbackTriggers.push('ASSET_IDENTITY_FAILURE');if(rollbackTriggers.length){status='ROLLBACK_REVIEW_REQUIRED';recommendation='MANUAL_ROLLBACK_REVIEW'}else if(hold.length>=Number(th.minimumTriggersForHoldReview||2)||syncFailureDays>1||backupFailureDays>0||recoveryFailureDays>0||openP2>0){status='HOLD_REVIEW_REQUIRED';recommendation='MANUAL_HOLD_REVIEW'};
 return {...base,status,recommendation,errors:[],actualLearnerDataUsed,sufficientLearningDays:sufficient.length,operationsDays:ops.length,currentMetrics:current,referenceMetrics:reference,drops,holdMetrics:hold,severeMetrics:severe,rollbackTriggers,syncFailureDays,backupFailureDays,recoveryFailureDays,contentMismatchDays,assetIdentityFailureDays,openP0P1,openP2,sourceDates:sufficient.map(dateOnly),evaluatedAt:input.evaluatedAt||nowIso(),thresholdsChanged:false};
}
function makeFollowupDecision(input={},evaluation={},p=policy()){
 const cfg=p.followupDecision||{},action=text(input.action).toUpperCase(),reviewer=text(input.reviewer),reason=text(input.reason),confirmation=text(input.confirmationPhrase),errors=[];if(!(cfg.allowedActions||[]).includes(action))errors.push('ACTION_INVALID');if(cfg.reviewerRequired!==false&&!reviewer)errors.push('REVIEWER_REQUIRED');if(cfg.reasonRequired!==false&&!reason)errors.push('REASON_REQUIRED');if(Number(evaluation?.days)!==14||!['STABLE','HOLD_REVIEW_REQUIRED','ROLLBACK_REVIEW_REQUIRED'].includes(evaluation?.status))errors.push('DAY14_EVALUATION_REQUIRED');if(action==='CONTINUE'&&evaluation?.status!=='STABLE')errors.push('CONTINUE_REQUIRES_STABLE');if(action==='ROLLBACK_REQUEST'&&evaluation?.status!=='ROLLBACK_REVIEW_REQUIRED')errors.push('ROLLBACK_REVIEW_REQUIRED');if(action==='ROLLBACK_REQUEST'&&confirmation!==cfg.rollbackConfirmationPhrase)errors.push('ROLLBACK_CONFIRMATION_MISMATCH');const accepted=errors.length===0;
 return {format:'JK_ENG_PHASE42_V102_FOLLOWUP_DECISION',version:VERSION,decisionId:text(input.decisionId)||uid('v102-followup'),evaluationId:evaluation?.evaluationId||null,evaluationStatus:evaluation?.status||'NOT_COLLECTED',action,status:accepted?(action==='ROLLBACK_REQUEST'?'ROLLBACK_REQUESTED':'RECORDED'):'REJECTED',accepted,errors,reviewer,reason,confirmationMatched:action!=='ROLLBACK_REQUEST'||!errors.includes('ROLLBACK_CONFIRMATION_MISMATCH'),decidedAt:input.decidedAt||nowIso(),immutable:true,automaticRollback:false,externalRollbackExecution:cfg.externalRollbackExecution||'NOT_VERIFIED'};
}
function buildPhase42AuditBundle(input={},p=policy()){
 return {format:'JK_ENG_PHASE42_V102_RELEASE_STABILIZATION_AUDIT_BUNDLE',version:VERSION,releaseTarget:p.releaseTarget||'JK English v1.0.2',rollbackTarget:p.rollbackTarget||'JK English v1.0.1',exportedAt:nowIso(),policy:clone(p),state:clone(global.JK_PHASE42_DATA?.state||{}),phase41BundleMeta:clone(input.phase41BundleMeta||null),phase41RcAuditVerification:clone(input.phase41RcAuditVerification||null),releaseExecutions:clone(input.releaseExecutions||[]),postReleaseSmokeRuns:clone(input.smokeRuns||[]),operationsSnapshots:clone(input.opsSnapshots||[]),incidents:clone(input.incidents||[]),stabilizationEvaluations:clone(input.stabilizationEvaluations||[]),followupDecisions:clone(input.followupDecisions||[]),truthfulBoundary:{rcApprovalIsNotProductionDeployment:true,externalReleaseRequiresExplicitExecution:true,releaseSmokePassStartsButDoesNotCompleteStabilization:true,rollbackRequestIsNotExternalRollbackExecution:true,automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false,localOrSyntheticCannotPromoteExternalState:true}};
}
const api={VERSION,normalizeHash,validHash,dateOnly,addDays,latest,implementationCoverage,verifyPhase41RcAuditBundle,createExternalReleaseExecution,evaluatePostReleaseSmoke,createOpsSnapshot,normalizeIncident,sufficientReport,referenceMetricsValid,evaluateStabilization14,makeFollowupDecision,buildPhase42AuditBundle};
if(typeof module!=='undefined'&&module.exports)module.exports=api;global.JK_PHASE42=api;
})(typeof window!=='undefined'?window:globalThis);
