(function(global){
'use strict';
const VERSION='47.0';
const text=v=>String(v==null?'':v).trim();
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const nowIso=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
const policy=()=>global.JK_PHASE47_DATA?.policy||{};
const normalizeHash=v=>text(v).toLowerCase().replace(/^sha256:/,'').trim();
const validHash=v=>/^[a-f0-9]{64}$/.test(normalizeHash(v));
const dateOnly=v=>{const source=(typeof v==='string'||typeof v==='number')?v:(v?.date||v?.dayId||v?.executedAt||v?.testedAt||v?.evaluatedAt||v?.decidedAt||v?.recordedAt||v?.updatedAt||v?.closedAt||v?.at||v);const raw=text(source).replace(/^DAY-/,'');const m=raw.match(/(\d{4}-\d{2}-\d{2})/);return m?m[1]:''};
const addDays=(date,n)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+Number(n||0));return d.toISOString().slice(0,10)};
const avg=values=>{const rows=(values||[]).map(Number).filter(Number.isFinite);return rows.length?Math.round(rows.reduce((a,b)=>a+b,0)*10/rows.length)/10:null};
const latest=(rows=[],field)=>((Array.isArray(rows)?rows:[]).slice().sort((a,b)=>Date.parse(b?.[field]||b?.closedAt||b?.openedAt||b?.requestedAt||b?.decidedAt||b?.evaluatedAt||b?.testedAt||b?.executedAt||b?.recordedAt||b?.updatedAt||b?.at||0)-Date.parse(a?.[field]||a?.closedAt||a?.openedAt||a?.requestedAt||a?.decidedAt||a?.evaluatedAt||a?.testedAt||a?.executedAt||a?.recordedAt||a?.updatedAt||a?.at||0))[0]||null);
function verifyPhase46AuditBundle(bundle={},options={},p=policy()){
 const cfg=p.acceptedPhase46Bundle||{},checks=[],errors=[];const add=(id,ok,detail='')=>{checks.push({id,ok:Boolean(ok),detail:text(detail)});if(!ok)errors.push(id)};
 const computed=normalizeHash(options.computedSha256),expected=normalizeHash(options.expectedSha256),execution=latest(bundle?.releaseExecutions||[],'executedAt'),smoke=latest(bundle?.postReleaseSmokeRuns||bundle?.smokeRuns||[],'testedAt'),evaluation=latest(bundle?.stabilizationEvaluations||[],'evaluatedAt'),decision=latest(bundle?.followupDecisions||[],'decidedAt');
 add('BUNDLE_FORMAT',bundle?.format===cfg.format,bundle?.format||'missing');add('BUNDLE_VERSION',bundle?.version===cfg.version,bundle?.version||'missing');add('RELEASE_TARGET',bundle?.releaseTarget===cfg.releaseTarget,bundle?.releaseTarget||'missing');add('SOURCE_SHA256_COMPUTED',validHash(computed),computed||'missing');if(expected)add('SOURCE_SHA256_MATCH',computed===expected,computed===expected?'match':'mismatch');
 add('ACTUAL_V103_RELEASE_EXECUTED',execution?.status===cfg.requiredReleaseStatus&&execution?.accepted===true&&execution?.actualExternalContext===true&&/^https:\/\//i.test(text(execution?.targetUrl))&&Boolean(text(execution?.operator))&&Boolean(text(execution?.evidence)),execution?.status||'missing');
 add('DEPLOYED_CANDIDATE_IDENTITY',validHash(execution?.deployedCandidateSha256),execution?.deployedCandidateSha256||'missing');add('DEPLOYED_ASSET_IDENTITY',Boolean(text(execution?.deployedAssetManifestVersion))&&validHash(execution?.deployedAssetManifestSha256),execution?.deployedAssetManifestVersion||'missing');
 add('V103_SMOKE_PASS',smoke?.status===cfg.requiredSmokeStatus&&smoke?.pass===true&&smoke?.actualExternalContext===true,smoke?.status||'missing');add('RELEASE_SMOKE_TARGET_LINK',Boolean(execution&&smoke&&text(smoke.targetUrl)===text(execution.targetUrl)),smoke?.targetUrl||'missing');
 if(execution&&smoke){add('SMOKE_CANDIDATE_IDENTITY_LINK',normalizeHash(smoke?.deployedCandidateSha256||smoke?.candidateArtifactSha256||execution.deployedCandidateSha256)===normalizeHash(execution.deployedCandidateSha256),'candidate identity');add('SMOKE_ASSET_IDENTITY_LINK',text(smoke?.deployedAssetManifestVersion||execution.deployedAssetManifestVersion)===text(execution.deployedAssetManifestVersion)&&normalizeHash(smoke?.deployedAssetManifestSha256||execution.deployedAssetManifestSha256)===normalizeHash(execution.deployedAssetManifestSha256),'asset identity')}
 add('DAY14_STABILIZATION_COMPLETED',Number(evaluation?.days)===14&&(cfg.allowedDay14Statuses||[]).includes(evaluation?.status)&&evaluation?.actualLearnerDataUsed===true&&Boolean(evaluation?.evaluatedAt),evaluation?.status||'missing');
 add('MANUAL_DECISION_VALID',decision?.accepted===true&&(cfg.allowedDecisionActions||[]).includes(decision?.action)&&['RECORDED','ROLLBACK_REQUESTED'].includes(decision?.status)&&Boolean(text(decision?.reviewer))&&Boolean(text(decision?.reason)),decision?.action||'missing');add('DECISION_EVALUATION_LINK',Boolean(decision&&evaluation&&text(decision.evaluationId)===text(evaluation.evaluationId)),decision?.evaluationId||'missing');
 if(decision?.action==='CONTINUE'&&cfg.continueRequiresStableDay14!==false)add('CONTINUE_REQUIRES_STABLE_DAY14',evaluation?.status==='STABLE',evaluation?.status||'missing');
 const pass=errors.length===0,eligible=pass&&decision?.action==='CONTINUE';return {format:'JK_ENG_PHASE47_PHASE46_AUDIT_VERIFICATION',version:VERSION,verificationId:text(options.verificationId)||uid('phase46-audit'),status:pass?'PASS':'FAIL',accepted:pass,eligibleFor30DayConfirmation:eligible,bundleSha256:computed,expectedSha256:expected||null,releaseExecution:clone(execution),postReleaseSmoke:clone(smoke),day14Evaluation:clone(evaluation),manualDecision:clone(decision),checks,errors,verifiedAt:nowIso(),automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false};
}
function sufficientReport(r={},cfg={}){return Boolean(r?.completedAt)&&Number(r?.attempts||0)>=Number(cfg.minimumAttempts||12)&&Number(r?.activeMinutes||0)>=Number(cfg.minimumActiveMinutes||25)&&Number(r?.grammarMinutes||0)>=Number(cfg.minimumGrammarMinutes||12)&&Number(r?.readingMinutes||0)>=Number(cfg.minimumReadingMinutes||10)}
function createOpsSnapshot(input={},verification={},p=policy()){
 const cfg=p.operations||{},date=dateOnly(input.date),sync=text(input.syncStatus).toUpperCase(),backup=text(input.backupStatus).toUpperCase(),recovery=text(input.recoveryStatus).toUpperCase(),content=text(input.contentIdentityStatus).toUpperCase(),asset=text(input.assetIdentityStatus).toUpperCase(),operator=text(input.operator),evidence=text(input.evidence),actual=Boolean(input.actualExternalContext),errors=[];
 if(verification?.status!=='PASS'||verification?.eligibleFor30DayConfirmation!==true)errors.push('PHASE46_CONTINUE_AUDIT_REQUIRED');if(!date)errors.push('DATE_REQUIRED');if(!(cfg.syncStatuses||[]).includes(sync))errors.push('SYNC_STATUS_INVALID');if(!(cfg.backupStatuses||[]).includes(backup))errors.push('BACKUP_STATUS_INVALID');if(!(cfg.recoveryStatuses||[]).includes(recovery))errors.push('RECOVERY_STATUS_INVALID');if(!(cfg.contentIdentityStatuses||[]).includes(content))errors.push('CONTENT_IDENTITY_STATUS_INVALID');if(!(cfg.assetIdentityStatuses||[]).includes(asset))errors.push('ASSET_IDENTITY_STATUS_INVALID');if(cfg.actualExternalContextRequired!==false&&!actual)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED');if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');if(cfg.evidenceRequired!==false&&!evidence)errors.push('EVIDENCE_REQUIRED');const accepted=errors.length===0;
 return {format:'JK_ENG_PHASE47_V103_DAY30_OPERATIONS_SNAPSHOT',version:VERSION,snapshotId:text(input.snapshotId)||uid('v103-day30-ops'),date,status:accepted?'RECORDED':'REJECTED',accepted,errors,syncStatus:sync||'CLEAR',backupStatus:backup||'NOT_VERIFIED',recoveryStatus:recovery||'NOT_VERIFIED',contentIdentityStatus:content||'NOT_VERIFIED',assetIdentityStatus:asset||'NOT_VERIFIED',actualExternalContext:actual,operator,evidence,recordedAt:input.recordedAt||nowIso(),immutable:true};
}
function normalizeIncident(input={}){const severity=text(input.severity||'P2').toUpperCase(),status=text(input.status||'OPEN').toUpperCase(),category=text(input.category||'GENERAL').toUpperCase();return {incidentId:text(input.incidentId)||uid('v103-incident'),severity:['P0','P1','P2'].includes(severity)?severity:'P2',status:['OPEN','MITIGATED','CLOSED'].includes(status)?status:'OPEN',category:['GENERAL','LEARNER_IMPACT','CONTENT_MISMATCH','ASSET_IDENTITY'].includes(category)?category:'GENERAL',title:text(input.title),detail:text(input.detail),evidence:text(input.evidence),at:input.at||nowIso(),updatedAt:input.updatedAt||input.at||nowIso()}}
function incidentStates(sourceIncidents=[],newIncidents=[],closeouts=[]){const map=new Map();for(const row of [...(sourceIncidents||[]),...(newIncidents||[])]){const x=normalizeIncident(row);map.set(x.incidentId,x)}for(const c of closeouts||[]){if(c?.accepted===true&&c?.finalStatus==='CLOSED'&&map.has(c.incidentId)){map.set(c.incidentId,{...map.get(c.incidentId),status:'CLOSED',resolution:c.resolution,closeoutEvidence:c.evidence,closedAt:c.closedAt})}}return [...map.values()]}
function evaluateConfirmation30(input={},verification={},p=policy()){
 const cfg=p.confirmation30||{},execution=verification?.releaseExecution||{},releaseDate=dateOnly(execution?.executedAt),asOf=dateOnly(input.asOf||nowIso()),dueDate=releaseDate?addDays(releaseDate,Number(cfg.days||30)-1):'',base={format:'JK_ENG_PHASE47_V103_CONFIRMATION_30',version:VERSION,evaluationId:text(input.evaluationId)||uid('v103-confirmation30'),days:Number(cfg.days||30),releaseDate:releaseDate||null,dueDate:dueDate||null,asOf:asOf||null,automaticRollback:false,automaticPersonalizationThresholdChange:false};
 if(verification?.status!=='PASS'||verification?.eligibleFor30DayConfirmation!==true)return {...base,status:'NOT_COLLECTED',recommendation:'HOLD',errors:['PHASE46_CONTINUE_AUDIT_REQUIRED'],actualLearnerDataUsed:false};if(!releaseDate||!asOf||asOf<dueDate)return {...base,status:'NOT_COLLECTED',recommendation:'HOLD',errors:['DAY30_NOT_REACHED'],actualLearnerDataUsed:false};
 const reports=(input.dailyReports||[]).filter(r=>{const d=dateOnly(r);return d>=releaseDate&&d<=dueDate}),sufficient=reports.filter(r=>sufficientReport(r,cfg.sufficientLearningDay||{})),ops=(input.opsSnapshots||[]).filter(x=>x?.accepted===true&&x.date>=releaseDate&&x.date<=dueDate),incidents=incidentStates(input.sourceIncidents||[],input.newIncidents||[],input.incidentCloseouts||[]).filter(x=>{const d=dateOnly(x.at||x.updatedAt||x.closedAt);return !d||(d>=releaseDate&&d<=dueDate)}),actualLearnerDataUsed=Boolean(input.actualLearnerDataUsed);
 const current={learningContinuityRate:reports.length?Math.round(reports.filter(r=>r?.completedAt).length/reports.length*1000)/10:null,answerAccuracy:avg(sufficient.map(r=>r.answerAccuracy)),processPassRate:avg(sufficient.map(r=>r.processPassRate)),recoveryRate:avg(sufficient.map(r=>r.recoveryRate)),paceStability:avg(sufficient.map(r=>r?.axes?.paceStability))},reference=clone(verification?.day14Evaluation?.currentMetrics||{}),drops={};for(const k of ['learningContinuityRate','answerAccuracy','processPassRate','recoveryRate','paceStability'])drops[k]=(Number.isFinite(Number(reference?.[k]))&&current[k]!=null)?Math.round((Number(reference[k])-current[k])*10)/10:null;
 const syncFailureDays=ops.filter(x=>x.syncStatus==='FAILED').length,backupFailureDays=ops.filter(x=>x.backupStatus==='FAIL').length,recoveryFailureDays=ops.filter(x=>['FAILED','DEGRADED'].includes(x.recoveryStatus)).length,contentMismatchDays=ops.filter(x=>x.contentIdentityStatus==='MISMATCH').length,assetIdentityFailureDays=ops.filter(x=>x.assetIdentityStatus==='FAIL').length,openP0P1=incidents.filter(x=>['P0','P1'].includes(x.severity)&&x.status!=='CLOSED').length,openP2=incidents.filter(x=>x.severity==='P2'&&x.status!=='CLOSED').length,errors=[];
 if(!actualLearnerDataUsed)errors.push('ACTUAL_LEARNER_DATA_REQUIRED');if(sufficient.length<Number(cfg.minimumSufficientLearningDays||18))errors.push('INSUFFICIENT_LEARNING_DAYS');if(ops.length<Number(cfg.minimumOperationsDays||18))errors.push('INSUFFICIENT_OPERATIONS_DAYS');if(errors.length)return {...base,status:'INSUFFICIENT',recommendation:'HOLD',errors,actualLearnerDataUsed,sufficientLearningDays:sufficient.length,operationsDays:ops.length,currentMetrics:current,referenceMetrics:reference,drops,syncFailureDays,backupFailureDays,recoveryFailureDays,contentMismatchDays,assetIdentityFailureDays,openP0P1,openP2,evaluatedAt:nowIso()};
 const th=cfg.regressionThresholds||{},hold=[];if((drops.answerAccuracy??0)>=Number(th.answerAccuracyDropPoints||8))hold.push('answerAccuracy');if((drops.processPassRate??0)>=Number(th.processPassDropPoints||8))hold.push('processPassRate');if((drops.recoveryRate??0)>=Number(th.recoveryDropPoints||10))hold.push('recoveryRate');if((drops.paceStability??0)>=Number(th.paceStabilityDropPoints||12))hold.push('paceStability');const severe=[];if((drops.answerAccuracy??0)>=Number(th.severeAnswerOrProcessDropPoints||12))severe.push('answerAccuracy');if((drops.processPassRate??0)>=Number(th.severeAnswerOrProcessDropPoints||12))severe.push('processPassRate');if((drops.recoveryRate??0)>=Number(th.severeRecoveryDropPoints||15))severe.push('recoveryRate');if((drops.paceStability??0)>=Number(th.severePaceStabilityDropPoints||20))severe.push('paceStability');let status='STABLE',recommendation='CLOSEOUT_READY',rollbackTriggers=[];if(openP0P1>0)rollbackTriggers.push('OPEN_P0_P1');if(severe.length)rollbackTriggers.push('SERIOUS_LEARNER_IMPACT_REGRESSION');if(contentMismatchDays>0)rollbackTriggers.push('CONTENT_IDENTITY_MISMATCH');if(assetIdentityFailureDays>0)rollbackTriggers.push('ASSET_IDENTITY_FAILURE');if(rollbackTriggers.length){status='ROLLBACK_REVIEW_REQUIRED';recommendation='MANUAL_ROLLBACK_REVIEW'}else if(hold.length>=Number(th.minimumTriggersForHoldReview||2)||syncFailureDays>1||backupFailureDays>0||recoveryFailureDays>0||openP2>0){status='HOLD_REVIEW_REQUIRED';recommendation='MANUAL_HOLD_REVIEW'}
 return {...base,status,recommendation,errors:[],actualLearnerDataUsed,sufficientLearningDays:sufficient.length,operationsDays:ops.length,currentMetrics:current,referenceMetrics:reference,drops,holdMetrics:hold,severeMetrics:severe,rollbackTriggers,syncFailureDays,backupFailureDays,recoveryFailureDays,contentMismatchDays,assetIdentityFailureDays,openP0P1,openP2,sourceDates:sufficient.map(dateOnly),evaluatedAt:input.evaluatedAt||nowIso(),thresholdsChanged:false};
}
function createIncidentCloseout(input={},sourceIncidents=[],p=policy()){
 const cfg=p.incidentCloseout||{},incidentId=text(input.incidentId),source=(sourceIncidents||[]).map(normalizeIncident).find(x=>x.incidentId===incidentId),reviewer=text(input.reviewer),resolution=text(input.resolution),evidence=text(input.evidence),errors=[];if(!source)errors.push('INCIDENT_NOT_FOUND');if(source?.status==='CLOSED')errors.push('INCIDENT_ALREADY_CLOSED');if(cfg.reviewerRequired!==false&&!reviewer)errors.push('REVIEWER_REQUIRED');if(cfg.resolutionRequired!==false&&!resolution)errors.push('RESOLUTION_REQUIRED');if(cfg.evidenceRequired!==false&&!evidence)errors.push('EVIDENCE_REQUIRED');const accepted=errors.length===0;return {format:'JK_ENG_PHASE47_V103_INCIDENT_CLOSEOUT',version:VERSION,closeoutId:text(input.closeoutId)||uid('v103-incident-closeout'),incidentId,sourceSeverity:source?.severity||null,sourceCategory:source?.category||null,finalStatus:accepted?(cfg.finalStatus||'CLOSED'):'NOT_RECORDED',status:accepted?'INCIDENT_CLOSED':'REJECTED',accepted,errors,reviewer,resolution,evidence,closedAt:input.closedAt||nowIso(),immutable:true};
}
function createMaintenanceCloseout(input={},verification={},evaluation30={},sourceIncidents=[],newIncidents=[],incidentCloseouts=[],opsSnapshots=[],p=policy()){
 const cfg=p.maintenanceCloseout||{},operator=text(input.operator),backupEvidence=text(input.backupEvidence),recoveryEvidence=text(input.recoveryEvidence),rollbackEvidence=text(input.rollbackReadinessEvidence),contentEvidence=text(input.contentIdentityEvidence),assetEvidence=text(input.assetIdentityEvidence),confirmation=text(input.confirmationPhrase),actual=Boolean(input.actualExternalContext),states=incidentStates(sourceIncidents,newIncidents,incidentCloseouts),unresolved=states.filter(x=>x.status!=='CLOSED'),unresolvedP0P1=unresolved.filter(x=>['P0','P1'].includes(x.severity)),validOps=(opsSnapshots||[]).filter(x=>x?.accepted===true),errors=[];
 if(verification?.status!=='PASS'||verification?.manualDecision?.action!=='CONTINUE')errors.push('PHASE46_CONTINUE_AUDIT_REQUIRED');if(evaluation30?.status!==cfg.allowedDay30Status)errors.push('STABLE_DAY30_REQUIRED');if(cfg.allV103IncidentsResolved!==false&&unresolved.length)errors.push('UNRESOLVED_V103_INCIDENTS');if(unresolvedP0P1.length)errors.push('UNRESOLVED_P0P1');if(!validOps.some(x=>x.backupStatus==='PASS'))errors.push('BACKUP_PASS_OPERATIONS_EVIDENCE_REQUIRED');if(!validOps.some(x=>x.recoveryStatus==='READY'))errors.push('RECOVERY_READY_OPERATIONS_EVIDENCE_REQUIRED');if(!validOps.some(x=>x.contentIdentityStatus==='MATCH'))errors.push('CONTENT_IDENTITY_MATCH_OPERATIONS_EVIDENCE_REQUIRED');if(!validOps.some(x=>x.assetIdentityStatus==='PASS'))errors.push('ASSET_IDENTITY_PASS_OPERATIONS_EVIDENCE_REQUIRED');if(cfg.actualExternalContextRequired!==false&&!actual)errors.push('ACTUAL_EXTERNAL_CONTEXT_REQUIRED');if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');if(cfg.backupEvidenceRequired!==false&&!backupEvidence)errors.push('BACKUP_EVIDENCE_REQUIRED');if(cfg.recoveryEvidenceRequired!==false&&!recoveryEvidence)errors.push('RECOVERY_EVIDENCE_REQUIRED');if(cfg.rollbackReadinessEvidenceRequired!==false&&!rollbackEvidence)errors.push('ROLLBACK_READINESS_EVIDENCE_REQUIRED');if(cfg.contentIdentityMatchEvidenceRequired!==false&&!contentEvidence)errors.push('CONTENT_IDENTITY_EVIDENCE_REQUIRED');if(cfg.assetIdentityPassEvidenceRequired!==false&&!assetEvidence)errors.push('ASSET_IDENTITY_EVIDENCE_REQUIRED');if(confirmation!==cfg.confirmationPhrase)errors.push('CLOSEOUT_CONFIRMATION_MISMATCH');const accepted=errors.length===0;
 return {format:'JK_ENG_PHASE47_V103_MAINTENANCE_CLOSEOUT',version:VERSION,closeoutId:text(input.closeoutId)||uid('v103-maintenance-closeout'),status:accepted?'MAINTENANCE_CLOSED':'CLOSEOUT_BLOCKED',accepted,errors,evaluationId:evaluation30?.evaluationId||null,phase46VerificationId:verification?.verificationId||null,incidentCount:states.length,resolvedIncidentCount:states.filter(x=>x.status==='CLOSED').length,unresolvedIncidentCount:unresolved.length,unresolvedP0P1:unresolvedP0P1.length,operator,backupEvidence,recoveryEvidence,rollbackReadinessEvidence:rollbackEvidence,contentIdentityEvidence:contentEvidence,assetIdentityEvidence:assetEvidence,actualExternalContext:actual,confirmationMatched:confirmation===cfg.confirmationPhrase,closedAt:accepted?(input.closedAt||nowIso()):null,immutable:true,rollbackReady:accepted,automaticCloseout:false,automaticRollback:false};
}
function createV104ChangeRequest(input={},maintenanceCloseout={},p=policy()){
 const cfg=p.v104ChangeWindow||{},type=text(input.type||'STANDARD').toUpperCase(),title=text(input.title),description=text(input.description),risk=text(input.risk),contentBankChange=Boolean(input.contentBankChange),contentApprovalRef=text(input.contentApprovalRef),impacts=input.invariantImpacts||{},errors=[];if(maintenanceCloseout?.status!=='MAINTENANCE_CLOSED'||maintenanceCloseout?.accepted!==true)errors.push('V103_MAINTENANCE_CLOSEOUT_REQUIRED');if(!(cfg.requestTypes||[]).includes(type))errors.push('REQUEST_TYPE_INVALID');if(!title)errors.push('TITLE_REQUIRED');if(!description)errors.push('DESCRIPTION_REQUIRED');if(!risk)errors.push('RISK_REQUIRED');if(contentBankChange&&cfg.contentBankChangeRequiresSeparateApproval!==false&&!contentApprovalRef)errors.push('CONTENT_APPROVAL_REQUIRED');for(const [k,v] of Object.entries(impacts))if(Boolean(v))errors.push(`LEARNING_INVARIANT_MUTATION_${String(k).toUpperCase()}`);const accepted=errors.length===0;return {format:'JK_ENG_PHASE47_V104_CHANGE_REQUEST',version:VERSION,requestId:text(input.requestId)||uid('v104-request'),target:'JK English v1.0.4',type,status:accepted?'REQUESTED':'REJECTED',accepted,errors,title,description,risk,contentBankChange,contentApprovalRef:contentApprovalRef||null,invariantImpacts:clone(impacts),requestedBy:text(input.requestedBy),requestedAt:input.requestedAt||nowIso(),automaticApply:false,automaticImplementation:false,automaticDeployment:false};
}
function openV104ChangeWindow(input={},maintenanceCloseout={},requests=[],p=policy()){
 const cfg=p.v104ChangeWindow||{},operator=text(input.operator),reason=text(input.reason),confirmation=text(input.confirmationPhrase),acceptedRequests=(requests||[]).filter(x=>x?.accepted===true&&x?.status==='REQUESTED'),errors=[];if(maintenanceCloseout?.status!=='MAINTENANCE_CLOSED'||maintenanceCloseout?.accepted!==true)errors.push('V103_MAINTENANCE_CLOSEOUT_REQUIRED');if(!acceptedRequests.length)errors.push('ACCEPTED_V104_REQUEST_REQUIRED');if(cfg.operatorRequired!==false&&!operator)errors.push('OPERATOR_REQUIRED');if(cfg.reasonRequired!==false&&!reason)errors.push('REASON_REQUIRED');if(confirmation!==cfg.confirmationPhrase)errors.push('CHANGE_WINDOW_CONFIRMATION_MISMATCH');const accepted=errors.length===0;return {format:'JK_ENG_PHASE47_V104_CHANGE_WINDOW',version:VERSION,windowId:text(input.windowId)||uid('v104-window'),target:'JK English v1.0.4',status:accepted?'V104_CHANGE_WINDOW_OPEN':'V104_CHANGE_WINDOW_BLOCKED',accepted,errors,maintenanceCloseoutId:maintenanceCloseout?.closeoutId||null,requestIds:acceptedRequests.map(x=>x.requestId),operator,reason,confirmationMatched:confirmation===cfg.confirmationPhrase,openedAt:accepted?(input.openedAt||nowIso()):null,automaticOpen:false,automaticImplementation:false,automaticDeployment:false,automaticContentApply:false};
}
function buildCloseoutAuditBundle(input={},p=policy()){
 return {format:'JK_ENG_PHASE47_V103_CLOSEOUT_V104_CHANGE_WINDOW_AUDIT_BUNDLE',version:VERSION,maintenanceTarget:p.maintenanceTarget||'JK English v1.0.3',nextChangeTarget:p.nextChangeTarget||'JK English v1.0.4',rollbackTarget:p.rollbackTarget||'JK English v1.0.2',exportedAt:nowIso(),policy:clone(p),state:clone(global.JK_PHASE47_DATA?.state||{}),phase46BundleMeta:clone(input.phase46BundleMeta||null),phase46AuditVerification:clone(input.phase46AuditVerification||null),operationsSnapshots:clone(input.opsSnapshots||[]),newIncidents:clone(input.newIncidents||[]),incidentCloseouts:clone(input.incidentCloseouts||[]),confirmation30Evaluations:clone(input.confirmation30Evaluations||[]),maintenanceCloseouts:clone(input.maintenanceCloseouts||[]),v104ChangeRequests:clone(input.v104ChangeRequests||[]),v104ChangeWindows:clone(input.v104ChangeWindows||[]),truthfulBoundary:{phase46DecisionIsNotPhase47Closeout:true,day14IsNotDay30Confirmation:true,maintenanceCloseoutIsNotV104ChangeWindow:true,v104ChangeWindowIsNotImplementationOrDeploymentAuthorization:true,automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false,localOrSyntheticCannotPromoteExternalState:true}};
}
const api={VERSION,normalizeHash,validHash,dateOnly,addDays,latest,verifyPhase46AuditBundle,sufficientReport,createOpsSnapshot,normalizeIncident,incidentStates,evaluateConfirmation30,createIncidentCloseout,createMaintenanceCloseout,createV104ChangeRequest,openV104ChangeWindow,buildCloseoutAuditBundle};
if(typeof module!=='undefined'&&module.exports)module.exports=api;global.JK_PHASE47=api;
})(typeof window!=='undefined'?window:globalThis);
