(async()=>{
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=s=>`<span class="status ${esc(s)}">${esc(s)}</span>`;
const unwrap=row=>row?.payload&&typeof row.payload==='object'?row.payload:row;
const dateOf=x=>String(x?.date||x?.dayId||'').replace(/^DAY-/,'').slice(0,10);
const nextLocalDate=iso=>{const d=new Date(iso);if(!Number.isFinite(d.getTime()))return'';d.setDate(d.getDate()+1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let state={snapshot:null,audits:[],execution:null,smoke:null,observation:null,incidents:[],rollbacks:[],observationEvaluation:null,observationInput:null,stabilizationStartDate:'',baseline:null,baselineEvaluation:null,hex:null,opsSnapshots:[],dispositions:[],operations:null,releaseEvaluation:null,releaseDecisions:[]};
function sortedAudits(rows){return [...rows].sort((a,b)=>Date.parse(b.at||b.createdAt||0)-Date.parse(a.at||a.createdAt||0))}
function rowsByType(type){return state.audits.filter(x=>x.type===type).map(unwrap)}
function reportMap(){return new Map(Object.values(state.snapshot?.dailyReports||{}).map(r=>[dateOf(r),r]))}
function dayKeyOfEvent(x){return String(x?.dayId||JK_STORAGE.localDateId(x?.timestamp||x?.startedAt||Date.now())).replace(/^DAY-/,'')}
function filteredBaselineBundle(){if(!state.stabilizationStartDate)return {events:[],sessions:[],reports:[]};const start=state.stabilizationStartDate,events=(state.snapshot?.events||[]).filter(e=>dayKeyOfEvent(e)>=start),sessions=Object.values(state.snapshot?.sessions||{}).filter(s=>dayKeyOfEvent(s)>=start),reports=Object.values(state.snapshot?.dailyReports||{}).filter(r=>dateOf(r)>=start);return {events,sessions,reports}}
function currentSyncCounts(){const rows=Object.values(state.snapshot?.syncQueue||{}),failed=rows.filter(x=>['failed','error'].includes(String(x.status).toLowerCase())).length,queued=rows.filter(x=>['queued','retry','pending'].includes(String(x.status).toLowerCase())).length;return {failed,queued}}
function incidentCounts(){return {P0:state.incidents.filter(x=>x.severity==='P0').length,P1:state.incidents.filter(x=>x.severity==='P1').length,P2:state.incidents.filter(x=>x.severity==='P2').length}}
function render(){
 const obs=state.observationInput||{status:'NOT_READY'},base=state.baselineEvaluation||{status:'NOT_COLLECTED',sufficientDays:0,averages:{}},ops=state.operations||{status:'OPERATIONS_INCOMPLETE',days:[],severityCounts:{},openP0P1:0,unresolvedP2:0},rel=state.releaseEvaluation||{status:'RELEASE_HOLD',reasons:[]},latest=state.releaseDecisions[0];
 $('phase35ObservationBadge').textContent=obs.status;$('phase35ObservationBadge').className=`status ${obs.status==='PASS'?'PASS':'NOT_RUN'}`;
 $('phase35BaselineBadge').textContent=base.status;$('phase35BaselineBadge').className=`status ${base.status==='BASELINE_READY'?'PASS':'NOT_RUN'}`;
 $('phase35OperationsBadge').textContent=ops.status;$('phase35OperationsBadge').className=`status ${ops.status==='OPERATIONS_READY'?'PASS':'NOT_RUN'}`;
 const releaseLabel=latest?.accepted?latest.action:rel.status;$('phase35ReleaseBadge').textContent=releaseLabel;$('phase35ReleaseBadge').className=`status ${releaseLabel==='RELEASE'?'PASS':releaseLabel==='READY_FOR_MANUAL_RELEASE'?'OBSERVING':'NOT_RUN'}`;
 $('phase35StartDate').textContent=state.stabilizationStartDate||'24시간 관측 완료 후 계산';$('phase35BaselineDays').textContent=`${base.sufficientDays||0}/7`;$('phase35ActiveAvg').textContent=base.averages?.activeMinutes!=null?`${base.averages.activeMinutes}분`:'-';$('phase35AccuracyAvg').textContent=base.averages?.answerAccuracy!=null?`${base.averages.answerAccuracy}%`:'-';$('phase35ProcessAvg').textContent=base.averages?.processPassRate!=null?`${base.averages.processPassRate}%`:'-';$('phase35RecoveryAvg').textContent=base.averages?.recoveryRate!=null?`${base.averages.recoveryRate}%`:'-';
 $('phase35BaselineMessage').textContent=obs.status!=='PASS'?'Phase 34의 실제 컷오버·스모크·24시간 관측 완료가 확인되어야 7일 수집 창이 시작됩니다.':base.status==='BASELINE_READY'?'실제 학습 7일 기준선이 충분합니다. 개인화 임계값은 자동 변경하지 않습니다.':`실제 완료 학습일 ${base.sufficientDays||0}/7 · 부족/누락 데이터는 RELEASE로 승격되지 않습니다.`;
 const axes=state.hex?.axes||{};$('phase35Radar').innerHTML=window.JK_DAILY?.radarSvg?JK_DAILY.radarSvg(axes,{size:300}):'';$('phase35AxisRows').innerHTML=(JK_PHASE35_DATA.policy.diagnosticAxes||[]).map(a=>`<div class="axisRow"><span>${esc(a.label)}</span><b>${Number(axes[a.id]||0).toFixed(1)}</b><small>근거 ${Number(state.hex?.evidence?.[a.id]||0)}</small></div>`).join('');
 const rmap=reportMap(),opMap=new Map((ops.days||[]).map(x=>[x.date,x])),dates=[...new Set([...(base.reportDates||[]),...(ops.days||[]).map(x=>x.date)])].sort();$('phase35DayRows').innerHTML=dates.map(d=>{const r=rmap.get(d),o=opMap.get(d);return `<tr><td>${esc(d)}</td><td>${r?`${Number(r.activeMinutes||0).toFixed(1)}분 · ${r.attempts||0}문항`:'-'}</td><td>${r?`${Number(r.answerAccuracy||0).toFixed(1)}% / ${Number(r.processPassRate||0).toFixed(1)}%`:'-'}</td><td>${r?`${Number(r.recoveryRate||0).toFixed(1)}% / ${Number(r.axes?.paceStability||0).toFixed(1)}`:'-'}</td><td>${o?`${badge(o.syncStatus)} ${badge(o.backupStatus)} ${badge(o.recoveryStatus)}`:'NOT_RECORDED'}</td><td>${o?badge(o.incidentReviewStatus):'-'}</td></tr>`}).join('')||'<tr><td colspan="6">수집된 안정화 일자가 없습니다.</td></tr>';
 $('phase35IncidentSummary').innerHTML=`<div class="metric"><span>P0</span><b>${ops.severityCounts?.P0||0}</b></div><div class="metric"><span>P1</span><b>${ops.severityCounts?.P1||0}</b></div><div class="metric"><span>P2</span><b>${ops.severityCounts?.P2||0}</b></div><div class="metric"><span>미해결 P0/P1</span><b>${ops.openP0P1||0}</b></div><div class="metric"><span>미처분 P2</span><b>${ops.unresolvedP2||0}</b></div><div class="metric"><span>운영 기록</span><b>${state.opsSnapshots.length}/7</b></div>`;
 $('phase35ReleaseReasons').innerHTML=(rel.reasons||[]).map(x=>`<div class="issue error">${esc(x)}</div>`).join('')||'<div class="issue">수동 RELEASE 판단을 기록할 수 있는 상태입니다. 자동 출시하지 않습니다.</div>';
 $('phase35DecisionHistory').innerHTML=state.releaseDecisions.map(d=>`<div class="decisionRow"><div><strong>${esc(d.action)} · ${esc(d.reviewer)}</strong><div class="note">${esc(d.reason)}<br>${new Date(d.decidedAt).toLocaleString()}</div></div>${badge(d.accepted?'RECORDED':'REJECTED')}</div>`).join('')||'<div class="note">v1.0 RELEASE/HOLD 결정 기록이 없습니다.</div>';
 $('phase35Export').disabled=!state.observationInput;$('phase35SaveOps').disabled=obs.status!=='PASS';
 const disposed=new Set(state.dispositions.filter(x=>x.accepted).map(x=>x.incidentId));const p2=state.incidents.filter(x=>x.severity==='P2'&&x.status==='OPEN'&&!disposed.has(x.incidentId));$('phase35P2Incident').innerHTML='<option value="">미처분 P2 선택</option>'+p2.map(i=>`<option value="${esc(i.incidentId)}">${esc(i.incidentId)} · ${esc(i.title||'')}</option>`).join('');$('phase35SaveDisposition').disabled=!p2.length;
}
async function load(){
 state.snapshot=JK_STORAGE.getSnapshot();state.audits=sortedAudits(await JK_STORAGE.listApprovalAudit());state.execution=rowsByType('phase34_cutover_execution_saved')[0]||null;state.smoke=rowsByType('phase34_smoke_run_saved')[0]||null;state.observation=rowsByType('phase34_observation_saved')[0]||null;state.incidents=rowsByType('phase34_incident_saved');state.rollbacks=rowsByType('phase34_rollback_saved');state.observationEvaluation=JK_PHASE34.evaluateObservation(state.observation||{},state.incidents,new Date().toISOString());state.observationInput=JK_PHASE35.verifyPhase34Completion({execution:state.execution||{},smoke:state.smoke||{},observation:state.observation||{},evaluation:state.observationEvaluation,rollbacks:state.rollbacks});state.stabilizationStartDate=state.observationInput.status==='PASS'?nextLocalDate(state.observationInput.observationEndedAt):'';
 const fb=filteredBaselineBundle();state.baseline=JK_PHASE26.baselineState({events:fb.events,sessions:fb.sessions,reports:fb.reports,questions:JK_DATA.questions||[],actualLearnerData:true});state.baselineEvaluation=JK_PHASE35.evaluateSevenDayBaseline({baseline:state.baseline,dailyReports:fb.reports,stabilizationStartDate:state.stabilizationStartDate});state.hex=JK_PHASE35.aggregateSevenDayHex({baselineEvaluation:state.baselineEvaluation,dailyReports:fb.reports});state.opsSnapshots=rowsByType('phase35_daily_ops_snapshot_saved');state.dispositions=rowsByType('phase35_p2_disposition_saved');state.operations=JK_PHASE35.summarizeOperations({dates:state.baselineEvaluation.reportDates||[],opsSnapshots:state.opsSnapshots,incidents:state.incidents,dispositions:state.dispositions});state.releaseEvaluation=JK_PHASE35.evaluateRelease({observationInput:state.observationInput,baselineEvaluation:state.baselineEvaluation,hex:state.hex,operations:state.operations});state.releaseDecisions=rowsByType('phase35_release_decision_saved');render();
}
async function refreshBaseline(){const fb=filteredBaselineBundle();const baseline=JK_PHASE26.baselineState({events:fb.events,sessions:fb.sessions,reports:fb.reports,questions:JK_DATA.questions||[],actualLearnerData:true});await JK_STORAGE.saveBaselineRun({...baseline,baselineId:'single-learner-release-stabilization-7-days'});await JK_STORAGE.appendApprovalAudit({type:'phase35_baseline_refreshed',entityId:'single-learner-release-stabilization-7-days',payload:{status:baseline.status,sufficientDays:baseline.sufficientDays,actualLearnerDataUsed:baseline.actualLearnerDataUsed,stabilizationStartDate:state.stabilizationStartDate,automaticPersonalizationChange:false}});$('phase35BaselineActionMessage').textContent='현재 실제 기록으로 7일 기준선을 다시 계산했습니다. 개인화 임계값은 변경하지 않았습니다.';await load()}
async function saveOpsSnapshot(){const sync=currentSyncCounts(),counts=incidentCounts(),record=JK_PHASE35.createDailyOpsSnapshot({date:$('phase35OpsDate').value,phase34Ready:state.observationInput?.status==='PASS',stabilizationStartDate:state.stabilizationStartDate,actualExternalContext:$('phase35OpsExternal').checked,syncStatus:$('phase35OpsSync').value,backupStatus:$('phase35OpsBackup').value,recoveryStatus:$('phase35OpsRecovery').value,incidentReviewStatus:$('phase35OpsIncidentReview').value,operator:$('phase35OpsOperator').value,evidence:$('phase35OpsEvidence').value,queuedSync:sync.queued,failedSync:sync.failed,incidentCounts:counts});if(!record.accepted){$('phase35OpsMessage').textContent=`저장 불가: ${record.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase35_daily_ops_snapshot_saved',entityId:record.snapshotId,payload:record});$('phase35OpsMessage').textContent=`${record.date} 운영 스냅샷을 불변 기록으로 저장했습니다.`;await load()}
async function saveDisposition(){const incident=state.incidents.find(x=>x.incidentId===$('phase35P2Incident').value);if(!incident){$('phase35DispositionMessage').textContent='미처분 P2 사고를 선택해야 합니다.';return}const record=JK_PHASE35.createP2Disposition({incident,action:$('phase35P2Action').value,operator:$('phase35P2Operator').value,reason:$('phase35P2Reason').value});if(!record.accepted){$('phase35DispositionMessage').textContent=`기록 불가: ${record.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase35_p2_disposition_saved',entityId:record.dispositionId,payload:record});$('phase35DispositionMessage').textContent=`${record.incidentId} P2 처리방침을 기록했습니다.`;await load()}
async function saveReleaseDecision(){const record=JK_PHASE35.makeReleaseDecision({action:$('phase35Decision').value,reviewer:$('phase35Reviewer').value,reason:$('phase35DecisionReason').value,confirmationPhrase:$('phase35ReleaseConfirm').value},state.releaseEvaluation);if(!record.accepted){$('phase35DecisionMessage').textContent=`결정 기록 불가: ${record.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase35_release_decision_saved',entityId:record.decisionId,payload:record});$('phase35DecisionMessage').textContent=`${record.action} 결정을 저장했습니다. 이 기록 자체가 외부 배포 실행을 의미하지는 않습니다.`;$('phase35DecisionReason').value='';$('phase35ReleaseConfirm').value='';await load()}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE35.buildReleaseAuditBundle({observationInput:state.observationInput,baselineEvaluation:state.baselineEvaluation,hex:state.hex,operations:state.operations,opsSnapshots:state.opsSnapshots,dispositions:state.dispositions,releaseEvaluation:state.releaseEvaluation,releaseDecisions:state.releaseDecisions}),`JK_ENG_v1_Phase35_Release_Audit_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();$('phase35OpsDate').value=new Date().toISOString().slice(0,10);$('phase35RefreshBaseline').onclick=refreshBaseline;$('phase35SaveOps').onclick=saveOpsSnapshot;$('phase35SaveDisposition').onclick=saveDisposition;$('phase35SaveDecision').onclick=saveReleaseDecision;$('phase35Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase35BaselineActionMessage');if(el)el.textContent=String(e.message||e)});
