(async()=>{
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=s=>`<span class="status ${esc(s)}">${esc(s)}</span>`;
const unwrap=row=>row?.payload&&typeof row.payload==='object'?row.payload:row;
const dateOf=x=>JK_PHASE36.dateOnly(x);
let state={snapshot:null,audits:[],importRecord:null,verification:null,locks:[],executions:[],smokeRuns:[],opsSnapshots:[],incidents:[],checkpointRecords:[],checkpointEvaluations:{14:null,30:null},decisions:[],personalizationReviews:[]};
function sorted(rows){return [...rows].sort((a,b)=>Date.parse(b.at||b.createdAt||b.recordedAt||b.decidedAt||0)-Date.parse(a.at||a.createdAt||a.recordedAt||a.decidedAt||0))}
function rowsByType(type){return state.audits.filter(x=>x.type===type).map(unwrap)}
async function hashFile(file){const digest=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function currentSyncCounts(){const rows=Object.values(state.snapshot?.syncQueue||{}),failed=rows.filter(x=>['failed','error'].includes(String(x.status).toLowerCase())).length,queued=rows.filter(x=>['queued','retry','pending'].includes(String(x.status).toLowerCase())).length;return {failed,queued}}
function latestCheckpoint(days){const rows=state.checkpointRecords.filter(x=>Number(x.days)===Number(days)).sort((a,b)=>Date.parse(b.evaluatedAt||0)-Date.parse(a.evaluatedAt||0));return rows[0]||state.checkpointEvaluations[days]||null}
function liveCheckpoint(days){const execution=state.executions[0]||{},smoke=state.smokeRuns[0]||{},baseline=state.importRecord?.approvedBundle?.baselineEvaluation||{},reports=Object.values(state.snapshot?.dailyReports||{});return JK_PHASE36.evaluateCheckpoint({days,execution,smoke,baseline,dailyReports:reports,opsSnapshots:state.opsSnapshots,incidents:state.incidents,actualLearnerDataUsed:Boolean(state.importRecord?.approvedBundle?.baselineEvaluation?.actualLearnerDataUsed),asOf:new Date().toISOString()})}
function buildSmokeRows(){const box=$('phase36SmokeRows');if(!box)return;box.innerHTML=(JK_PHASE36_DATA.policy.releaseExecution?.smokeTests||[]).map(d=>`<div class="smokeRow"><strong>${esc(d.label)}</strong><select id="phase36SmokeStatus_${esc(d.id)}"><option>NOT_RUN</option><option>PASS</option><option>FAIL</option></select><input id="phase36SmokeEvidence_${esc(d.id)}" placeholder="실기기·외부 운영 증거 파일명 또는 로그"></div>`).join('')}
function render(){
 const imp=state.verification||{status:'NOT_IMPORTED'},lock=state.locks[0]||{status:'UNLOCKED'},execution=state.executions[0]||{status:'RELEASE_NOT_RUN'},smoke=state.smokeRuns[0]||{status:'RELEASE_SMOKE_NOT_RUN'},c14=liveCheckpoint(14),c30=liveCheckpoint(30);
 state.checkpointEvaluations={14:c14,30:c30};
 for(const [id,val,good] of [['phase36InputBadge',imp.status,'PASS'],['phase36LockBadge',lock.status,'LOCKED'],['phase36ExecutionBadge',execution.status,'RELEASE_EXECUTED'],['phase36SmokeBadge',smoke.status,'RELEASE_SMOKE_PASS'],['phase36Day14Badge',c14.status,'STABLE'],['phase36Day30Badge',c30.status,'STABLE']]){const el=$(id);if(el){el.textContent=val;el.className=`status ${val===good?'PASS':(['OBSERVING','HOLD_REVIEW_REQUIRED','ROLLBACK_REVIEW_REQUIRED'].includes(val)?'OBSERVING':'NOT_RUN')}`}}
 $('phase36SourceSha').textContent=imp.bundleSha256?`${imp.bundleSha256.slice(0,12)}…`:'-';$('phase36ReleaseAt').textContent=execution.executedAt?new Date(execution.executedAt).toLocaleString():'-';$('phase36TargetUrlView').textContent=execution.targetUrl||'-';$('phase36RollbackTargetView').textContent=execution.rollbackTarget||JK_PHASE36_DATA.policy.releaseExecution?.rollbackTarget||'-';
 const rows=[c14,c30];$('phase36CheckpointRows').innerHTML=rows.map(c=>`<tr><td>${c.days}일</td><td>${badge(c.status)}</td><td>${c.sufficientLearningDays||0}/${c.minimumSufficientLearningDays||0}</td><td>${c.operationsDays||0}/${c.minimumOperationsDays||0}</td><td>${c.learningContinuityRate!=null?`${Number(c.learningContinuityRate).toFixed(1)}%`:'-'}</td><td>${c.currentMetrics?.processPassRate!=null?`${c.currentMetrics.processPassRate}%`:'-'}</td><td>${c.currentMetrics?.recoveryRate!=null?`${c.currentMetrics.recoveryRate}%`:'-'}</td><td>${c.currentMetrics?.paceStability!=null?`${c.currentMetrics.paceStability}%`:'-'}</td><td>${badge(c.recommendation||'HOLD')}</td></tr>`).join('');
 $('phase36RegressionRows').innerHTML=rows.map(c=>`<div class="issue ${c.status==='ROLLBACK_REVIEW_REQUIRED'?'error':c.status==='HOLD_REVIEW_REQUIRED'?'warning':''}"><strong>${c.days}일 · ${esc(c.status)}</strong> · 회귀 ${esc((c.regressionTriggers||[]).join(', ')||'없음')} · 미해결 P0/P1 ${Number(c.openP0P1||0)} · 운영 이상 ${Number(c.operationsFailureDays?.length||0)}일</div>`).join('');
 $('phase36DecisionHistory').innerHTML=state.decisions.map(d=>`<div class="decisionRow"><div><strong>${esc(d.checkpointDays)}일 · ${esc(d.action)} · ${esc(d.reviewer)}</strong><div class="note">${esc(d.reason)}<br>${d.decidedAt?new Date(d.decidedAt).toLocaleString():''}</div></div>${badge(d.status)}</div>`).join('')||'<div class="note">14/30일 후속 결정 기록이 없습니다.</div>';
 $('phase36PersonalHistory').innerHTML=state.personalizationReviews.map(r=>`<div class="decisionRow"><div><strong>${esc(r.checkpointDays)}일 · ${esc(r.action)} · ${esc(r.reviewer)}</strong><div class="note">${esc(r.reason)} · 임계값 변경 ${r.thresholdsChanged?'YES':'NO'}</div></div>${badge(r.status)}</div>`).join('')||'<div class="note">개인화 정책 재검토 기록이 없습니다.</div>';
 $('phase36ImportMessage').textContent=imp.status==='PASS'?'Phase 35 RELEASE 감사 번들이 검증되었습니다. 동일 파일 재해시 후 출시 잠금을 생성할 수 있습니다.':'실제 수동 RELEASE가 포함된 Phase 35 감사 번들이 없으면 출시 실행을 시작할 수 없습니다.';
 $('phase36OpsSave').disabled=execution.status!=='RELEASE_EXECUTED';$('phase36SmokeSave').disabled=execution.status!=='RELEASE_EXECUTED';$('phase36CheckpointEvaluate').disabled=smoke.status!=='RELEASE_SMOKE_PASS';$('phase36Export').disabled=!state.importRecord;
}
async function load(){
 state.snapshot=JK_STORAGE.getSnapshot();state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase36_release_bundle_import_saved')[0]||null;state.verification=state.importRecord?.preReleaseVerification||null;state.locks=rowsByType('phase36_release_lock_saved');state.executions=rowsByType('phase36_release_execution_saved');state.smokeRuns=rowsByType('phase36_post_release_smoke_saved');state.opsSnapshots=rowsByType('phase36_followup_ops_snapshot_saved');state.incidents=rowsByType('phase36_release_incident_saved');state.checkpointRecords=rowsByType('phase36_checkpoint_evaluation_saved');state.decisions=rowsByType('phase36_followup_decision_saved');state.personalizationReviews=rowsByType('phase36_personalization_review_saved');render();
}
async function verifyReleaseBundle(){const file=$('phase36BundleFile').files?.[0];if(!file){$('phase36ImportMessage').textContent='Phase 35 v1.0 RELEASE 감사 번들 JSON을 선택해야 합니다.';return}try{$('phase36ImportMessage').textContent='SHA-256, 최종 RELEASE 결정, 7일 기준선과 운영 게이트를 검증하고 있습니다.';const raw=await file.text(),bundle=JSON.parse(raw),computedSha256=await hashFile(file),expectedSha256=$('phase36ExpectedSha').value,preReleaseVerification=JK_PHASE36.verifyPhase35ReleaseBundle(bundle,{computedSha256,expectedSha256}),record={format:'JK_ENG_PHASE36_RELEASE_BUNDLE_IMPORT',version:'36.0',importId:preReleaseVerification.verificationId,approvedBundle:bundle,approvedBundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:computedSha256,expectedSha256:JK_PHASE36.normalizeHash(expectedSha256)||null},preReleaseVerification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase36_release_bundle_import_saved',entityId:record.importId,payload:record});await load();$('phase36ImportMessage').textContent=preReleaseVerification.status==='PASS'?'검증 PASS. 같은 파일을 유지한 채 출시 잠금을 생성하십시오.':`검증 FAIL: ${preReleaseVerification.errors.join(', ')}`}catch(e){console.error(e);$('phase36ImportMessage').textContent=`감사 번들 검증 실패: ${e.message||e}`}}
async function createLock(){if(!state.importRecord){$('phase36LockMessage').textContent='먼저 Phase 35 RELEASE 감사 번들을 검증해야 합니다.';return}const file=$('phase36BundleFile').files?.[0];if(!file){$('phase36LockMessage').textContent='잠금 직전 재해시를 위해 동일한 감사 번들 파일을 선택해야 합니다.';return}const computedSha256=await hashFile(file),verification=JK_PHASE36.verifyPhase35ReleaseBundle(state.importRecord.approvedBundle,{computedSha256,expectedSha256:state.importRecord.approvedBundleMeta?.sha256});const checklist={releaseDecisionConfirmed:$('phase36CheckRelease').checked,sourceBundleHashVerified:$('phase36CheckHash').checked,backupSnapshotReady:$('phase36CheckBackup').checked,rollbackTargetReady:$('phase36CheckRollback').checked,externalUrlConfirmed:$('phase36CheckUrl').checked},lock=JK_PHASE36.createReleaseLock({checklist,operator:$('phase36Operator').value,reason:$('phase36LockReason').value},verification);if(!lock.accepted){$('phase36LockMessage').textContent=`잠금 불가: ${lock.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase36_release_lock_saved',entityId:lock.lockId,payload:lock});$('phase36LockMessage').textContent='v1.0 출시 잠금을 불변 기록으로 저장했습니다.';await load()}
async function recordExecution(){const lock=state.locks[0],file=$('phase36BundleFile').files?.[0];if(!lock){$('phase36ExecutionMessage').textContent='출시 잠금이 필요합니다.';return}if(!file){$('phase36ExecutionMessage').textContent='실행 직전 재해시를 위해 동일한 감사 번들 파일을 선택해야 합니다.';return}const reverifiedSha256=await hashFile(file),execution=JK_PHASE36.createReleaseExecution({targetUrl:$('phase36TargetUrl').value,actualExternalContext:$('phase36ActualExternal').checked,confirmationPhrase:$('phase36ConfirmPhrase').value,reverifiedSha256,operator:$('phase36Operator').value,evidence:$('phase36ExecutionEvidence').value},lock);if(!execution.accepted){$('phase36ExecutionMessage').textContent=`출시 실행 기록 불가: ${execution.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase36_release_execution_saved',entityId:execution.executionId,payload:execution});$('phase36ExecutionMessage').textContent='실제 외부 v1.0 출시 실행을 기록했습니다. 이제 배포 직후 스모크를 수행하십시오.';await load()}
async function saveSmoke(){const tests={};for(const def of JK_PHASE36_DATA.policy.releaseExecution?.smokeTests||[])tests[def.id]={status:$(`phase36SmokeStatus_${def.id}`).value,evidence:$(`phase36SmokeEvidence_${def.id}`).value};const run=JK_PHASE36.evaluatePostReleaseSmoke({actualExternalContext:$('phase36SmokeExternal').checked,operator:$('phase36Operator').value,tests},state.executions[0]||{});await JK_STORAGE.appendApprovalAudit({type:'phase36_post_release_smoke_saved',entityId:run.runId,payload:run});$('phase36SmokeMessage').textContent=run.status==='RELEASE_SMOKE_PASS'?'배포 후 스모크 PASS를 기록했습니다. 14/30일 관측을 시작할 수 있습니다.':`스모크 상태: ${run.status}`;await load()}
async function saveOps(){const sync=currentSyncCounts(),record=JK_PHASE36.createFollowupOpsSnapshot({date:$('phase36OpsDate').value,actualExternalContext:$('phase36OpsExternal').checked,syncStatus:$('phase36OpsSync').value,backupStatus:$('phase36OpsBackup').value,recoveryStatus:$('phase36OpsRecovery').value,incidentReviewStatus:$('phase36OpsIncidentReview').value,operator:$('phase36OpsOperator').value,evidence:$('phase36OpsEvidence').value,queuedSync:sync.queued,failedSync:sync.failed},state.executions[0]||{});if(!record.accepted){$('phase36OpsMessage').textContent=`저장 불가: ${record.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase36_followup_ops_snapshot_saved',entityId:record.snapshotId,payload:record});$('phase36OpsMessage').textContent=`${record.date} 출시 후 운영 스냅샷을 저장했습니다.`;await load()}
async function saveIncident(){const record=JK_PHASE36.normalizeIncident({severity:$('phase36IncidentSeverity').value,status:$('phase36IncidentStatus').value,title:$('phase36IncidentTitle').value,detail:$('phase36IncidentDetail').value,evidence:$('phase36IncidentEvidence').value});if(!record.title){$('phase36IncidentMessage').textContent='사고 제목을 입력해야 합니다.';return}await JK_STORAGE.appendApprovalAudit({type:'phase36_release_incident_saved',entityId:record.incidentId,payload:record});$('phase36IncidentTitle').value='';$('phase36IncidentDetail').value='';$('phase36IncidentEvidence').value='';$('phase36IncidentMessage').textContent=`${record.severity} 사고를 기록했습니다.`;await load()}
async function evaluateCheckpoints(){for(const days of [14,30]){const evaluation=liveCheckpoint(days);await JK_STORAGE.appendApprovalAudit({type:'phase36_checkpoint_evaluation_saved',entityId:`checkpoint-${days}-${Date.now()}`,payload:evaluation})}$('phase36CheckpointMessage').textContent='현재 실제 기록으로 14일·30일 관측을 재평가했습니다. 자동 롤백·자동 개인화 변경은 수행하지 않았습니다.';await load()}
async function saveDecision(){const days=Number($('phase36DecisionCheckpoint').value),checkpoint=latestCheckpoint(days)||liveCheckpoint(days),record=JK_PHASE36.makeFollowupDecision({action:$('phase36DecisionAction').value,reviewer:$('phase36DecisionReviewer').value,reason:$('phase36DecisionReason').value,confirmationPhrase:$('phase36RollbackConfirm').value},checkpoint||{});if(!record.accepted){$('phase36DecisionMessage').textContent=`결정 기록 불가: ${record.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase36_followup_decision_saved',entityId:record.decisionId,payload:record});$('phase36DecisionMessage').textContent=record.action==='ROLLBACK_REQUEST'?'롤백 요청을 기록했습니다. 외부 롤백 실행은 별도 확인이 필요합니다.':'후속 운영 결정을 기록했습니다.';$('phase36DecisionReason').value='';$('phase36RollbackConfirm').value='';await load()}
async function savePersonalReview(){const days=Number($('phase36PersonalCheckpoint').value),checkpoint=latestCheckpoint(days)||liveCheckpoint(days),record=JK_PHASE36.createPersonalizationReview({action:$('phase36PersonalAction').value,reviewer:$('phase36PersonalReviewer').value,reason:$('phase36PersonalReason').value,adminApproved:$('phase36PersonalApproved').checked},checkpoint||{});if(!record.accepted){$('phase36PersonalMessage').textContent=`재검토 기록 불가: ${record.errors.join(', ')}`;return}await JK_STORAGE.appendApprovalAudit({type:'phase36_personalization_review_saved',entityId:record.reviewId,payload:record});$('phase36PersonalMessage').textContent='개인화 정책 재검토를 기록했습니다. 임계값은 변경하지 않았습니다.';$('phase36PersonalReason').value='';await load()}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE36.buildFollowupAuditBundle({phase35BundleMeta:state.importRecord?.approvedBundleMeta||null,preReleaseVerification:state.verification,releaseLocks:state.locks,releaseExecutions:state.executions,smokeRuns:state.smokeRuns,opsSnapshots:state.opsSnapshots,incidents:state.incidents,checkpoints:[latestCheckpoint(14),latestCheckpoint(30)].filter(Boolean),followupDecisions:state.decisions,personalizationReviews:state.personalizationReviews}),`JK_ENG_v1_Phase36_Followup_Audit_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();buildSmokeRows();$('phase36OpsDate').value=new Date().toISOString().slice(0,10);$('phase36VerifyBundle').onclick=verifyReleaseBundle;$('phase36CreateLock').onclick=createLock;$('phase36RecordExecution').onclick=recordExecution;$('phase36SmokeSave').onclick=saveSmoke;$('phase36OpsSave').onclick=saveOps;$('phase36IncidentSave').onclick=saveIncident;$('phase36CheckpointEvaluate').onclick=evaluateCheckpoints;$('phase36DecisionSave').onclick=saveDecision;$('phase36PersonalSave').onclick=savePersonalReview;$('phase36Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase36ImportMessage');if(el)el.textContent=String(e.message||e)});
