(async function(){
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={snapshot:null,audits:[],importRecord:null,verification:null,executions:[],smokes:[],ops:[],incidents:[],evaluations:[],decisions:[]};
const sorted=rows=>(rows||[]).slice().sort((a,b)=>Date.parse(b.at||b.decidedAt||b.evaluatedAt||b.testedAt||b.executedAt||b.verifiedAt||b.recordedAt||0)-Date.parse(a.at||a.decidedAt||a.evaluatedAt||a.testedAt||a.executedAt||a.verifiedAt||a.recordedAt||0));
const rowsByType=type=>sorted(state.audits.filter(x=>x.type===type).map(x=>x.payload));const latest=rows=>rows?.[0]||null;
async function hashFile(file){const b=await file.arrayBuffer(),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function badgeClass(s){s=String(s||'');return /PASS|EXECUTED|STABLE|RECORDED|APPROVED/.test(s)?'pass':/FAIL|BLOCKED|ROLLBACK/.test(s)?'fail':/HOLD|INSUFFICIENT|REVIEW_REQUIRED/.test(s)?'warn':''}
function buildTestRows(containerId,defs,prefix){const root=$(containerId);if(!root)return;root.innerHTML=(defs||[]).map(d=>`<div class="smokeRow"><div><strong>${esc(d.id)}</strong><div class="note">${esc(d.label)}</div></div><select id="${prefix}Status_${esc(d.id)}"><option>NOT_RUN</option><option>PASS</option><option>FAIL</option></select><input id="${prefix}Evidence_${esc(d.id)}" placeholder="evidence reference"></div>`).join('')}
function readTests(defs,prefix){const out={};for(const d of defs||[])out[d.id]={status:$(`${prefix}Status_${d.id}`).value,evidence:$(`${prefix}Evidence_${d.id}`).value};return out}
function referenceMetricsFromHistory(){for(const type of ['phase43_confirmation30_saved','phase42_stabilization_saved','phase39_confirmation30_saved','phase38_stabilization_saved','phase37_monthly_review_saved']){for(const row of rowsByType(type)){const m=row?.currentMetrics;if(m&&['answerAccuracy','processPassRate','recoveryRate','paceStability'].every(k=>Number.isFinite(Number(m[k]))))return m}}return null}
function setReferenceInputs(m){if(!m)return;for(const [id,k] of [['phase46RefAccuracy','answerAccuracy'],['phase46RefProcess','processPassRate'],['phase46RefRecovery','recoveryRate'],['phase46RefPace','paceStability']])if($(id)&&!$(id).value)$(id).value=Number(m[k])}
function getReferenceInputs(){return {answerAccuracy:Number($('phase46RefAccuracy').value),processPassRate:Number($('phase46RefProcess').value),recoveryRate:Number($('phase46RefRecovery').value),paceStability:Number($('phase46RefPace').value)}}
function render(){const v=state.verification||{status:'NOT_IMPORTED'},e=latest(state.executions)||{status:'V103_RELEASE_NOT_RUN'},s=latest(state.smokes)||{status:'V103_SMOKE_NOT_RUN'},z=latest(state.evaluations)||{status:'NOT_COLLECTED'},d=latest(state.decisions)||{status:'NOT_RECORDED'};for(const [id,val] of [['phase46InputBadge',v.status],['phase46RcBadge',v.rcGate?.status||'NOT_VERIFIED'],['phase46ReleaseBadge',e.status],['phase46SmokeBadge',s.status],['phase46StabilizationBadge',z.status],['phase46DecisionBadge',d.status]])if($(id)){ $(id).textContent=val;$(id).className=`status ${badgeClass(val)}` }
 if($('phase46SourceSha'))$('phase46SourceSha').textContent=v.bundleSha256||'-';if($('phase46PlanId'))$('phase46PlanId').textContent=v.rcGate?.planId||'-';if($('phase46StagingRunId'))$('phase46StagingRunId').textContent=v.candidateStaging?.runId||'-';if($('phase46CandidateIdentity'))$('phase46CandidateIdentity').textContent=v.candidateArtifactSha256||'-';if($('phase46ManifestIdentity'))$('phase46ManifestIdentity').textContent=v.assetManifestVersion?`${v.assetManifestVersion} / ${v.assetManifestSha256}`:'-';
 if(v.status==='PASS'){if($('phase46CandidateSha')&&!$('phase46CandidateSha').value)$('phase46CandidateSha').value=v.candidateArtifactSha256||'';if($('phase46ManifestVersion')&&!$('phase46ManifestVersion').value)$('phase46ManifestVersion').value=v.assetManifestVersion||'';if($('phase46ManifestSha')&&!$('phase46ManifestSha').value)$('phase46ManifestSha').value=v.assetManifestSha256||''}
 setReferenceInputs(referenceMetricsFromHistory());if($('phase46EvaluationResult'))$('phase46EvaluationResult').innerHTML=z?.evaluationId?`<div class="issue"><strong>${esc(z.status)}</strong><div class="note">learning ${esc(z.sufficientLearningDays||0)}d / ops ${esc(z.operationsDays||0)}d / P0·P1 ${esc(z.openP0P1||0)} / Daily regression ${esc(z.dailyStructureRegressionDays||0)} / content mismatch ${esc(z.contentMismatchDays||0)} / asset fail ${esc(z.assetIdentityFailureDays||0)} / ${esc(z.recommendation||'')}</div></div>`:'<div class="note">실제 v1.0.3 출시·스모크·14일 실사용 증거가 있어야 평가됩니다.</div>';
 if($('phase46History'))$('phase46History').innerHTML=[...state.executions.slice(0,2),...state.evaluations.slice(0,2),...state.decisions.slice(0,2)].map(x=>`<div class="decisionRow"><div><strong>${esc(x.status||x.action)}</strong><div class="note">${esc(x.targetUrl||x.recommendation||x.reason||'')}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status||x.action)}</span></div>`).join('')||'<div class="note">No Phase 46 external record.</div>';if($('phase46Export'))$('phase46Export').disabled=!state.importRecord;
}
async function load(){state.snapshot=JK_STORAGE.getSnapshot();state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase46_phase45_rc_audit_import_saved')[0]||null;state.verification=state.importRecord?.verification||null;state.executions=rowsByType('phase46_v103_release_execution_saved');state.smokes=rowsByType('phase46_post_release_smoke_saved');state.ops=rowsByType('phase46_ops_snapshot_saved');state.incidents=rowsByType('phase46_incident_saved');state.evaluations=rowsByType('phase46_stabilization_saved');state.decisions=rowsByType('phase46_followup_decision_saved');render()}
async function verifyBundle(){const file=$('phase46BundleFile').files?.[0];if(!file){$('phase46ImportMessage').textContent='Phase 45 audit JSON을 선택하세요.';return}try{const bundle=JSON.parse(await file.text()),sha=await hashFile(file),verification=JK_PHASE46.verifyPhase45RcAuditBundle(bundle,{computedSha256:sha,expectedSha256:$('phase46ExpectedSha').value}),record={format:'JK_ENG_PHASE46_PHASE45_RC_AUDIT_IMPORT',version:'46.0',importId:verification.verificationId,phase45Bundle:bundle,phase45BundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:sha,expectedSha256:JK_PHASE46.normalizeHash($('phase46ExpectedSha').value)||null},verification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase46_phase45_rc_audit_import_saved',entityId:record.importId,payload:record});$('phase46ImportMessage').textContent=verification.status==='PASS'?'RC_APPROVED + STAGING_PASS + ROLLBACK_REHEARSAL_PASS 검증 완료.':'검증 실패: '+verification.errors.join(', ');await load()}catch(e){$('phase46ImportMessage').textContent='Import failed: '+(e.message||e)}}
async function executeRelease(){const file=$('phase46ExecutionBundleFile').files?.[0];if(!file||!state.verification){$('phase46ReleaseMessage').textContent='검증된 Phase 45 감사 번들을 동일 파일로 다시 선택하세요.';return}const sha=await hashFile(file),rec=JK_PHASE46.createExternalReleaseExecution({rehashedSha256:sha,targetUrl:$('phase46TargetUrl').value,operator:$('phase46ReleaseOperator').value,evidence:$('phase46ReleaseEvidence').value,actualExternalContext:$('phase46ReleaseExternal').checked,confirmationPhrase:$('phase46ReleaseConfirm').value,deployedCandidateSha256:$('phase46CandidateSha').value,deployedAssetManifestVersion:$('phase46ManifestVersion').value,deployedAssetManifestSha256:$('phase46ManifestSha').value},state.verification);await JK_STORAGE.appendApprovalAudit({type:'phase46_v103_release_execution_saved',entityId:rec.executionId,payload:rec});$('phase46ReleaseMessage').textContent=`${rec.status}: ${(rec.errors||[]).join(', ')||'recorded'}`;await load()}
async function runSmoke(){const exec=latest(state.executions),cfg=JK_PHASE46_DATA.policy.externalRelease,rec=JK_PHASE46.evaluatePostReleaseSmoke({actualExternalContext:$('phase46SmokeExternal').checked,operator:$('phase46SmokeOperator').value,tests:readTests(cfg.smokeTests,'phase46Smoke')},exec||{},state.verification||{});await JK_STORAGE.appendApprovalAudit({type:'phase46_post_release_smoke_saved',entityId:rec.runId,payload:rec});$('phase46SmokeMessage').textContent=`${rec.status}: ${(rec.errors||[]).join(', ')||'all pass'}`;await load()}
async function saveOps(){const rec=JK_PHASE46.createOpsSnapshot({date:$('phase46OpsDate').value,syncStatus:$('phase46SyncStatus').value,backupStatus:$('phase46BackupStatus').value,recoveryStatus:$('phase46RecoveryStatus').value,contentIdentityStatus:$('phase46ContentIdentityStatus').value,assetIdentityStatus:$('phase46AssetIdentityStatus').value,dailyStructureStatus:$('phase46DailyStructureStatus').value,operator:$('phase46OpsOperator').value,evidence:$('phase46OpsEvidence').value,actualExternalContext:$('phase46OpsExternal').checked},latest(state.executions)||{});if(!rec.accepted){$('phase46OpsMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase46_ops_snapshot_saved',entityId:rec.snapshotId,payload:rec});$('phase46OpsMessage').textContent='운영 스냅샷 기록 완료.';await load()}
async function saveIncident(){const rec=JK_PHASE46.normalizeIncident({severity:$('phase46IncidentSeverity').value,status:$('phase46IncidentStatus').value,category:$('phase46IncidentCategory').value,title:$('phase46IncidentTitle').value,detail:$('phase46IncidentDetail').value,evidence:$('phase46IncidentEvidence').value,at:new Date().toISOString()});await JK_STORAGE.appendApprovalAudit({type:'phase46_incident_saved',entityId:rec.incidentId,payload:rec});$('phase46IncidentMessage').textContent='Incident recorded.';await load()}
async function evaluate14(){const rec=JK_PHASE46.evaluateStabilization14({execution:latest(state.executions)||{},smoke:latest(state.smokes)||{},asOf:$('phase46AsOf').value,actualLearnerDataUsed:$('phase46LearnerData').checked,dailyReports:Object.values(state.snapshot?.dailyReports||{}),opsSnapshots:state.ops,incidents:state.incidents,referenceMetrics:getReferenceInputs()});await JK_STORAGE.appendApprovalAudit({type:'phase46_stabilization_saved',entityId:rec.evaluationId,payload:rec});$('phase46EvaluationMessage').textContent=`${rec.status} / ${rec.recommendation}`;await load()}
async function decide(){const ev=latest(state.evaluations);if(!ev){$('phase46DecisionMessage').textContent='14-day evaluation is required.';return}const rec=JK_PHASE46.makeFollowupDecision({action:$('phase46DecisionAction').value,reviewer:$('phase46DecisionReviewer').value,reason:$('phase46DecisionReason').value,confirmationPhrase:$('phase46RollbackConfirm').value},ev);if(!rec.accepted){$('phase46DecisionMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase46_followup_decision_saved',entityId:rec.decisionId,payload:rec});$('phase46DecisionMessage').textContent=`${rec.status}. Automatic rollback was not performed.`;await load()}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE46.buildPhase46AuditBundle({phase45BundleMeta:state.importRecord?.phase45BundleMeta||null,phase45RcAuditVerification:state.verification,releaseExecutions:state.executions,smokeRuns:state.smokes,opsSnapshots:state.ops,incidents:state.incidents,stabilizationEvaluations:state.evaluations,followupDecisions:state.decisions}),`JK_ENG_Phase46_v103_Release_Stabilization_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();buildTestRows('phase46SmokeTests',JK_PHASE46_DATA.policy.externalRelease.smokeTests,'phase46Smoke');$('phase46OpsDate').value=new Date().toISOString().slice(0,10);$('phase46AsOf').value=new Date().toISOString().slice(0,10);$('phase46VerifyBundle').onclick=verifyBundle;$('phase46ExecuteRelease').onclick=executeRelease;$('phase46RunSmoke').onclick=runSmoke;$('phase46OpsSave').onclick=saveOps;$('phase46IncidentSave').onclick=saveIncident;$('phase46Evaluate14').onclick=evaluate14;$('phase46DecisionSave').onclick=decide;$('phase46Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase46ImportMessage');if(el)el.textContent=String(e.message||e)});
