(async function(){
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={audits:[],importRecord:null,verification:null,reviews:[],guardrails:[],plans:[],staging:[]};
const sorted=a=>(a||[]).slice().sort((x,y)=>Date.parse(y?.at||y?.payload?.testedAt||y?.payload?.approvedAt||y?.payload?.reviewedAt||0)-Date.parse(x?.at||x?.payload?.testedAt||x?.payload?.approvedAt||x?.payload?.reviewedAt||0));
const rowsByType=t=>state.audits.filter(x=>x?.type===t).map(x=>x.payload||x).filter(Boolean);
const latest=rows=>JK_PHASE40.latest(rows);
const hashFile=async f=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',await f.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');
function badgeClass(v){return ['PASS','AUTHORIZED','GUARDRAIL_PASS','PLAN_APPROVED','STAGING_PASS','MAINTENANCE_CLOSED','V102_CHANGE_WINDOW_OPEN'].includes(v)?'PASS':['FAIL','REJECTED','REVIEW_REJECTED','GUARDRAIL_BLOCKED','PLAN_BLOCKED','STAGING_FAIL'].includes(v)?'FAIL':'NOT_RUN'}
function render(){const v=state.verification||{status:'NOT_IMPORTED'},g=latest(state.guardrails)||{status:'NOT_RECORDED'},p=latest(state.plans)||{status:'NOT_RECORDED'},s=latest(state.staging)||{status:'NOT_RUN'};for(const [id,val] of [['phase40InputBadge',v.status],['phase40CloseoutBadge',v.maintenanceCloseout?.status||'NOT_VERIFIED'],['phase40WindowBadge',v.changeWindow?.status||'NOT_VERIFIED'],['phase40GuardrailBadge',g.status],['phase40PlanBadge',p.status],['phase40StagingBadge',s.status]])if($(id)){$(id).textContent=val;$(id).className=`status ${badgeClass(val)}`};if($('phase40SourceSha'))$('phase40SourceSha').textContent=v.bundleSha256||'-';if($('phase40RequestList'))$('phase40RequestList').innerHTML=(v.acceptedRequests||[]).map(r=>`<div class="decisionRow"><div><strong>${esc(r.requestId)}</strong><div class="note">${esc(r.type)} / ${esc(r.title)} / content approval ${esc(r.contentApprovalRef||'not required')}</div></div><span class="status ${badgeClass((state.reviews.find(x=>x.requestId===r.requestId)||{}).status||'NOT_RECORDED')}">${esc((state.reviews.find(x=>x.requestId===r.requestId)||{}).status||'NOT_RECORDED')}</span></div>`).join('')||'<div class="note">No verified Phase 39 requests.</div>';if($('phase40RequestId')){$('phase40RequestId').innerHTML='<option value="">Select request</option>'+(v.acceptedRequests||[]).map(r=>`<option value="${esc(r.requestId)}">${esc(r.requestId)} - ${esc(r.title)}</option>`).join('')};if($('phase40History'))$('phase40History').innerHTML=[...state.reviews.slice(0,3),...state.guardrails.slice(0,1),...state.plans.slice(0,1),...state.staging.slice(0,1)].map(x=>`<div class="decisionRow"><div><strong>${esc(x.status)}</strong><div class="note">${esc(x.requestId||x.planId||x.guardrailId||x.runId||'')}</div></div><span class="status ${badgeClass(x.status)}">${esc(x.status)}</span></div>`).join('')||'<div class="note">No Phase 40 records.</div>';if($('phase40Export'))$('phase40Export').disabled=!state.importRecord;}
async function load(){state.audits=sorted(await JK_STORAGE.listApprovalAudit());state.importRecord=rowsByType('phase40_phase39_audit_import_saved')[0]||null;state.verification=state.importRecord?.verification||null;state.reviews=rowsByType('phase40_request_review_saved');state.guardrails=rowsByType('phase40_guardrail_saved');state.plans=rowsByType('phase40_change_plan_saved');state.staging=rowsByType('phase40_staging_run_saved');render()}
async function verifyBundle(){const file=$('phase40BundleFile').files?.[0];if(!file){$('phase40ImportMessage').textContent='Select a Phase 39 audit JSON.';return}try{const bundle=JSON.parse(await file.text()),sha=await hashFile(file),verification=JK_PHASE40.verifyPhase39AuditBundle(bundle,{computedSha256:sha,expectedSha256:$('phase40ExpectedSha').value}),record={format:'JK_ENG_PHASE40_PHASE39_AUDIT_IMPORT',version:'40.0',importId:verification.verificationId,phase39Bundle:bundle,phase39BundleMeta:{name:file.name,size:file.size,lastModified:file.lastModified,sha256:sha,expectedSha256:JK_PHASE40.normalizeHash($('phase40ExpectedSha').value)||null},verification,importedAt:new Date().toISOString()};await JK_STORAGE.appendApprovalAudit({type:'phase40_phase39_audit_import_saved',entityId:record.importId,payload:record});$('phase40ImportMessage').textContent=verification.status==='PASS'?'Phase 39 maintenance closeout and v1.0.2 open window verified.':'Verification failed: '+verification.errors.join(', ');await load()}catch(e){$('phase40ImportMessage').textContent='Import failed: '+(e.message||e)}}
async function saveReview(){const rec=JK_PHASE40.reviewV102Request({requestId:$('phase40RequestId').value,decision:$('phase40ReviewDecision').value,riskLevel:$('phase40RiskLevel').value,reviewer:$('phase40Reviewer').value,scopeAssessment:$('phase40ScopeAssessment').value,riskAssessment:$('phase40RiskAssessment').value,rollbackPlan:$('phase40ReviewRollback').value,contentApprovalRef:$('phase40ContentApprovalRef').value,contentApprovalStatus:$('phase40ContentApprovalStatus').value,contentApprovalEvidence:$('phase40ContentApprovalEvidence').value},state.verification||{});if(!rec.accepted){$('phase40ReviewMessage').textContent='Rejected: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase40_request_review_saved',entityId:rec.reviewId,payload:rec});$('phase40ReviewMessage').textContent=`${rec.status}; no implementation was applied.`;await load()}
async function saveGuardrail(){const preservations={processScoringPreserved:$('phase40PreserveProcess').checked,textbookReturnLoopPreserved:$('phase40PreserveTextbook').checked,evidenceMarkingPreserved:$('phase40PreserveEvidence').checked,originalRetryPreserved:$('phase40PreserveRetry').checked,nonAnxietyPacingPreserved:$('phase40PreservePacing').checked};const impacts={numericCountdownVisible:$('phase40ImpactCountdown').checked,bypassProcessScoring:$('phase40ImpactProcessBypass').checked,bypassTextbookReturn:$('phase40ImpactTextbookBypass').checked,bypassEvidenceMarking:false,bypassOriginalRetry:false,automaticImplementation:false,automaticDeployment:false,automaticRollback:false,automaticPersonalizationThresholdChange:false,automaticContentApply:false};const rec=JK_PHASE40.assessLearnerImpact({reviewer:$('phase40GuardrailReviewer').value,evidence:$('phase40GuardrailEvidence').value,preservations,impacts},state.verification||{},state.reviews);await JK_STORAGE.appendApprovalAudit({type:'phase40_guardrail_saved',entityId:rec.guardrailId,payload:rec});$('phase40GuardrailMessage').textContent=`${rec.status}${rec.errors.length?': '+rec.errors.join(', '):''}`;await load()}
async function approvePlan(){const rec=JK_PHASE40.createControlledChangePlan({operator:$('phase40PlanOperator').value,owner:$('phase40PlanOwner').value,scopeSummary:$('phase40PlanScope').value,rollbackPlan:$('phase40PlanRollback').value,confirmationPhrase:$('phase40PlanConfirm').value},state.verification||{},state.reviews,latest(state.guardrails)||{});if(!rec.accepted){$('phase40PlanMessage').textContent='Blocked: '+rec.errors.join(', ');return}await JK_STORAGE.appendApprovalAudit({type:'phase40_change_plan_saved',entityId:rec.planId,payload:rec});$('phase40PlanMessage').textContent='Controlled plan approved. Deployment remains manual and separate.';await load()}
async function saveStaging(){const ids=['AUTH','DAILY_LOOP','MULTI_DEVICE_RESUME','OFFLINE_RECOVERY','ADMIN_RECOVERY','ASSET_INTEGRITY','ROLLBACK_READINESS'],cases=ids.map(id=>({id,status:$(`phase40Stage${id}Status`).value,evidence:$(`phase40Stage${id}Evidence`).value}));const rec=JK_PHASE40.createStagingValidation({actualStagingContext:$('phase40StagingActual').checked,stagingUrl:$('phase40StagingUrl').value,operator:$('phase40StagingOperator').value,cases},latest(state.plans)||{},latest(state.guardrails)||{});await JK_STORAGE.appendApprovalAudit({type:'phase40_staging_run_saved',entityId:rec.runId,payload:rec});$('phase40StagingMessage').textContent=`${rec.status}${rec.errors.length?': '+rec.errors.join(', '):''}. Production release is not authorized here.`;await load()}
function downloadJson(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){downloadJson(JK_PHASE40.buildPhase40AuditBundle({phase39BundleMeta:state.importRecord?.phase39BundleMeta||null,phase39AuditVerification:state.verification,requestReviews:state.reviews,learnerImpactGuardrails:state.guardrails,controlledChangePlans:state.plans,stagingValidations:state.staging}),`JK_ENG_Phase40_v102_ChangePlan_Staging_${new Date().toISOString().slice(0,10)}.json`)}
await JK_AUTH.requireRole('admin');await JK_STORAGE.init();$('phase40VerifyBundle').onclick=verifyBundle;$('phase40ReviewSave').onclick=saveReview;$('phase40GuardrailSave').onclick=saveGuardrail;$('phase40PlanApprove').onclick=approvePlan;$('phase40StagingSave').onclick=saveStaging;$('phase40Export').onclick=exportAudit;await load();
})().catch(e=>{console.error(e);const el=document.getElementById('phase40ImportMessage');if(el)el.textContent=String(e.message||e)});
