(async()=>{'use strict';
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 try{await window.JK_AUTH.requireRole('admin')}catch(e){console.warn(e);return}
 const D=window.JK_QUALITY_DATA||{},A=D.audit||{},S=A.summary||{},coverage=A.conceptCoverage||[],draftKey='jk_phase25_quality_approval_drafts';
 const drafts=JSON.parse(localStorage.getItem(draftKey)||'{}');
 $('metrics').innerHTML=[['전수감사',S.auditedCoreFamilies],['개념',A.scope?.conceptCount],['완전중복 묶음',S.exactDuplicateClusters],['근접중복 쌍',S.nearDuplicatePairs],['과소대표',S.underrepresentedConcepts],['과대표',S.overrepresentedConcepts],['계약 오류',S.contractFailures]].map(([l,v])=>`<div class="metric"><b>${Number(v||0).toLocaleString('ko-KR')}</b><span>${l}</span></div>`).join('');
 function curveSvg(){const seg=A.dayDifficultyCurve?.segments||[],w=720,h=230,pad=48;const x=r=>pad+r*(w-pad*2),y=v=>h-pad-(v-1)/2*(h-pad*2);let path='';const points=[];seg.forEach((s,i)=>{const a=[x(s.from),y(s.targetLevel)],b=[x(s.to),y(s.targetLevel)];if(!i){path+=`M${a[0]},${a[1]}`}else{path+=` L${a[0]},${a[1]}`}path+=` L${b[0]},${b[1]}`;points.push({...s,x1:a[0],x2:b[0],yy:a[1]})});const grid=[1,2,3].map(v=>`<line x1="${pad}" y1="${y(v)}" x2="${w-pad}" y2="${y(v)}" stroke="#e5e5ea"/><text x="${pad-12}" y="${y(v)+4}" text-anchor="end" font-size="12" fill="#6e6e73">${v}</text>`).join('');const labels=points.map(p=>`<text x="${(p.x1+p.x2)/2}" y="${h-16}" text-anchor="middle" font-size="11" font-weight="700" fill="#6e6e73">${p.id}</text>`).join('');return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Day 난이도 곡선">${grid}<path d="${path}" fill="none" stroke="#0071e3" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>${points.map(p=>`<circle cx="${p.x1}" cy="${p.yy}" r="5" fill="#fff" stroke="#0071e3" stroke-width="3"/>`).join('')}${labels}</svg>`}
 $('curve').innerHTML=curveSvg();
 const weights=A.difficultyFormula?.weights||{};$('formula').innerHTML=Object.entries(weights).map(([k,v])=>`<div><b>${Math.round(Number(v)*100)}%</b><small>${esc({authorDifficulty:'교재 난이도',wordCount:'문장 길이',decisionStepCount:'판단 단계',requiredBoundaryCount:'필수 경계',choiceComplexity:'선택지 복잡도',inkRequirement:'필기 요구'}[k]||k)}</small></div>`).join('');
 const parts=[...new Set(coverage.map(r=>r.part).filter(Boolean))].sort();$('part').innerHTML+parts.map(x=>`<option>${esc(x)}</option>`).join('');
 function selectedDifficulty(r){const d=r.difficultyCounts||{};return ['1','2','3'].sort((a,b)=>(d[b]||0)-(d[a]||0))[0]}
 function renderCoverage(){const q=$('search').value.toLowerCase().trim(),rep=$('representation').value,part=$('part').value,diff=$('difficulty').value;const rows=coverage.filter(r=>(!q||`${r.conceptId} ${r.conceptName}`.toLowerCase().includes(q))&&(!rep||r.representationStatus===rep)&&(!part||r.part===part)&&(!diff||selectedDifficulty(r)===diff));$('conceptRows').innerHTML=rows.map(r=>`<tr><td><b>${esc(r.conceptName)}</b><br><small>${esc(r.conceptId)}</small></td><td>${r.coreFamilyCount}</td><td><span class="pill ${r.representationStatus}">${{underrepresented:'과소대표',overrepresented:'과대표',balanced:'균형'}[r.representationStatus]}</span></td><td>${r.difficultyCounts['1']} / ${r.difficultyCounts['2']} / ${r.difficultyCounts['3']}</td><td>${r.averageWordCount}</td><td>${r.averageDecisionSteps}</td><td>${r.averageBoundaryCount}</td><td>${Math.round(r.averageTargetSeconds)}초</td><td>${r.duplicateRiskQuestions}</td><td>${r.proposalStatus==='pending_admin_approval'?`가중치 ${r.proposedSamplingWeight} · 승인 대기`:'유지'}</td></tr>`).join('')||'<tr><td class="empty" colspan="10">조건에 맞는 개념이 없습니다.</td></tr>'}
 ['search','representation','part','difficulty'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderCoverage));renderCoverage();
 const dups=[...(A.exactDuplicateClusters||[]),...(A.nearDuplicatePairs||[])];$('duplicates').innerHTML=dups.map(d=>`<article class="dup"><div class="dupTop"><div><span class="pill ${d.risk==='exact'?'overrepresented':'underrepresented'}">${d.risk==='exact'?'완전중복':'근접중복'}</span><h3>${esc(d.clusterId||d.pairId)} · ${(d.questionIds||[]).map(esc).join(' / ')}</h3></div><span class="pill">자동조치 없음</span></div>${d.stems?`<div class="stems">${d.stems.map(s=>`<div class="stem">${esc(s)}</div>`).join('')}</div>`:`<div class="stem">${esc(d.normalizedStem)}</div>`}<p>${esc(d.recommendedAction)}</p></article>`).join('')||'<div class="empty">중복 위험이 없습니다.</div>';
 const proposalRows=coverage.filter(r=>r.proposalStatus==='pending_admin_approval');function save(){localStorage.setItem(draftKey,JSON.stringify(drafts));$('draftStatus').textContent=`로컬 검토안 ${Object.keys(drafts).length}건 저장 · 학습자 출제에는 반영되지 않음`;}
 function renderProposals(){$('proposals').innerHTML=proposalRows.map(r=>{const d=drafts[r.conceptId]||{};return `<article class="proposal"><div class="proposalTop"><div><span class="pill ${r.representationStatus}">${r.representationStatus==='underrepresented'?'과소대표':'과대표'}</span><h3>${esc(r.conceptName)} · ${r.coreFamilyCount}가족</h3></div><select data-id="${esc(r.conceptId)}"><option value="pending" ${!d.status||d.status==='pending'?'selected':''}>승인 대기</option><option value="approved" ${d.status==='approved'?'selected':''}>제안 승인</option><option value="rejected" ${d.status==='rejected'?'selected':''}>제안 반려</option><option value="hold" ${d.status==='hold'?'selected':''}>보류</option></select></div><p>${esc(r.proposalRationale)} · 제안 가중치 ${r.proposedSamplingWeight}</p></article>`}).join('');document.querySelectorAll('.proposal select').forEach(el=>el.onchange=()=>{drafts[el.dataset.id]={conceptId:el.dataset.id,status:el.value,updatedAt:new Date().toISOString(),autoApplied:false};save()});save()};renderProposals();
 function download(obj,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 $('exportAll').onclick=()=>download({format:'JK_ENG_PHASE25_QUALITY_REVIEW',version:'25.0',createdAt:new Date().toISOString(),auditSummary:S,adminDrafts:drafts,automaticApplication:false,sourceAudit:A},`JK_ENG_Phase25_quality_review_${Date.now()}.json`);
})();
