(async()=>{'use strict';
 const $=id=>document.getElementById(id),state={tab:'learner',page:0,size:30,current:null};
 try{await window.JK_AUTH.requireRole('admin')}catch(e){console.warn(e);return}
 const M=window.JK_BANK.manifest,Q=window.JK_DATA.questions,C=Object.fromEntries(window.JK_DATA.concepts.map(c=>[c.id,c]));
 const candidates=window.JK_BANK.candidates||[],draftKey='jk_phase25_candidate_drafts',drafts=JSON.parse(localStorage.getItem(draftKey)||localStorage.getItem('jk_phase21_candidate_drafts')||'{}');
 const fmt=n=>typeof n==='number'?Number(n||0).toLocaleString('ko-KR'):String(n??''),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const stateLabels={extracted:'추출',visual_verified:'원문 확인',answer_verified:'정답 확인',pedagogy_mapped:'교육 매핑',approved:'승인',rejected:'반려'};
 const review=M.phase24Review||M.phase23Review||M.phase21Review||{},audit=M.phase25Audit||{};$('metrics').innerHTML=[['학습 문항',M.learnerQuestionRecordCount],['핵심 가족',M.coreFamilyCount],['품질 전수감사',audit.auditedCoreFamilies||0],['중복 위험 가족',audit.reviewRequiredFamilies||0],['과소대표 개념',audit.underrepresentedConcepts||0],['과대표 개념',audit.overrepresentedConcepts||0],['계약 오류',audit.contractFailures||0]].map(([l,v])=>`<div class="metric"><b>${fmt(v)}</b><span>${l}</span></div>`).join('');
 const parts=[...new Set(Q.map(q=>q.part).filter(Boolean))].sort(),variants=[...new Set(Q.map(q=>q.variantType).filter(Boolean))].sort();
 function resetFilters(){ $('part').innerHTML=state.tab==='learner'?'<option value="">전체 PART</option>'+parts.map(x=>`<option>${x}</option>`).join(''):'<option value="">전체 교재</option><option value="grammar">grammar</option><option value="reading">reading</option>'; $('variant').innerHTML='<option value="">전체 유형</option>'+variants.map(x=>`<option>${x}</option>`).join('');$('variant').disabled=state.tab!=='learner';$('tier').innerHTML='<option value="">전체 등급</option><option value="A">A</option><option value="B">B</option>'+(state.tab==='candidate'?'<option value="blocked">학습 차단</option>':'');$('workflow').innerHTML='<option value="">전체 상태</option>'+Object.entries(stateLabels).map(([v,l])=>`<option value="${v}">${l}</option>`).join('');$('workflow').disabled=state.tab==='learner';$('batch').innerHTML='<option value="">전체 검수 묶음</option><option value="phase21">문법 1차</option><option value="phase23-reading-batch-1">독해 1차</option><option value="phase24-reading-batch-2">독해 2차</option>';$('batch').disabled=state.tab==='learner'}
 function rows(){const s=$('search').value.trim().toLowerCase(),part=$('part').value,v=$('variant').value,t=$('tier').value,w=$('workflow').value,b=$('batch').value;if(state.tab==='learner')return Q.filter(q=>(!s||`${q.id} ${q.stem} ${C[q.conceptId]?.name||''}`.toLowerCase().includes(s))&&(!part||q.part===part)&&(!v||q.variantType===v)&&(!t||q.qualityTier===t));return candidates.filter(c=>(!s||`${c.candidateId} ${c.rawStem} ${c.correctedStem||''}`.toLowerCase().includes(s))&&(!part||c.book===part)&&(!w||c.workflowState===w)&&(!b||(b==='phase21'?String(c.workflowVersion||'').startsWith('21'):c.visualEvidence?.reviewBatch===b))&&(!t||t==='blocked'&&c.workflowState!=='approved'||t==='A'&&c.workflowState==='approved'))}
 function render(){const all=rows(),pages=Math.max(1,Math.ceil(all.length/state.size));state.page=Math.min(state.page,pages-1);const slice=all.slice(state.page*state.size,(state.page+1)*state.size);$('pageInfo').textContent=`${state.page+1} / ${pages} · ${fmt(all.length)}건`;$('prev').disabled=state.page===0;$('next').disabled=state.page>=pages-1;
  if(state.tab==='learner'){$('policy').className='notice';$('policy').textContent='A/B 등급만 학습자에게 노출됩니다. Phase 25는 1,140개 핵심 가족의 중복·개념 분포·초기 난이도를 전수감사했습니다. 개념별 보정안과 중복 조치는 관리자 승인 전 자동 적용하지 않습니다. 기존 표지 발견 → 경계 표시 → 중심 뼈대 → 연결의 4단계를 채점하며, 같은 가족은 하루에 한 변형만 출제됩니다.';$('list').innerHTML=slice.map(q=>`<article class="item"><div class="itemTop"><div class="chips"><span class="chip ${String(q.qualityTier).toLowerCase()}">${q.qualityTier}등급</span><span class="chip">${q.variantType}</span><span class="chip">${q.part||''}</span><span class="chip">${q.familyId}</span>${q.reviewWorkflow?.state==='approved'?'<span class="chip approved">PDF 검수</span>':''}</div><span class="chip">${q.reviewStatus}</span></div><h3>${esc(q.stem)}</h3><p>${esc(C[q.conceptId]?.name||q.conceptId)} · ${esc(q.id)}</p><div class="answer">선택지: ${q.choices.map(esc).join(' / ')} · <b>정답 ${esc(q.answer)}</b></div></article>`).join('')}
  else{$('policy').className='notice warn';$('policy').textContent='상태 흐름: 추출 → 원문 확인 → 정답 확인 → 교육 매핑 → 승인 또는 반려. 승인 전 후보와 로컬 검토 변경안은 학습 계획에 들어가지 않습니다. 승인 후에도 빌드·검증을 거쳐야 학습자에게 노출됩니다.';$('list').innerHTML=slice.map(c=>{const d=drafts[c.candidateId];return `<article class="item"><div class="itemTop"><div class="chips"><span class="chip ${c.workflowState}">${stateLabels[c.workflowState]||c.workflowState}</span><span class="chip">${c.book} PDF ${c.pdfPage}</span><span class="chip">${c.candidateType}</span>${c.duplicateOfExisting?'<span class="chip rejected">기존 중복</span>':''}${d?'<span class="chip visual_verified">로컬 변경안</span>':''}</div><button class="reviewBtn ${c.workflowState}" data-id="${c.candidateId}">상세 검수</button></div><h3>${esc(c.correctedStem||c.rawStem)}</h3><p>${esc(c.candidateId)} · ${esc(c.answerStatus)}</p>${c.choices?.length?`<div class="answer">선택지: ${c.choices.map(esc).join(' / ')}${c.answer?` · <b>정답 ${esc(c.answer)}</b>`:''}</div>`:''}${c.rejectionReason?`<p>반려 사유: ${esc(c.rejectionReason)}</p>`:''}</article>`}).join('');document.querySelectorAll('.reviewBtn').forEach(b=>b.onclick=()=>openModal(candidates.find(c=>c.candidateId===b.dataset.id)))}
  if(!slice.length)$('list').innerHTML='<div class="empty">조건에 맞는 항목이 없습니다.</div>';
 }
 function nextStates(c){const map={extracted:['extracted','visual_verified','rejected'],visual_verified:['visual_verified','answer_verified','rejected'],answer_verified:['answer_verified','pedagogy_mapped','rejected'],pedagogy_mapped:['pedagogy_mapped','approved','rejected'],approved:['approved'],rejected:['rejected','extracted']};return map[(drafts[c.candidateId]?.state)||c.workflowState]||['extracted']}
 function openModal(c){state.current=c;$('modalTitle').textContent=c.candidateId;$('modalMeta').textContent=`${c.book} PDF ${c.pdfPage} · ${stateLabels[c.workflowState]||c.workflowState}`;$('rawText').textContent=c.rawStem;$('correctedText').textContent=c.correctedStem||'아직 수정본 없음';$('answerText').textContent=c.choices?.length?`${c.choices.join(' / ')}${c.answer?` · 정답: ${c.answer}`:' · 정답 미확정'}`:'독해 문장 후보 · 저자식 경계·표지 좌표 미확정';$('mappingText').textContent=c.conceptId?`${C[c.conceptId]?.name||c.conceptId}\n${c.errorCode||''}\n교재 복귀: ${c.sourceRef||''}`:'교육 매핑 미완료';const img=$('evidenceImg');if(c.visualEvidence?.asset){img.src=c.visualEvidence.asset;img.style.display='block';$('evidenceMeta').textContent=`렌더 증거 · ${c.book} PDF ${c.pdfPage}쪽 · ${c.visualEvidence.verification}`}else{img.removeAttribute('src');img.style.display='none';$('evidenceMeta').textContent='렌더 증거 미연결'};$('history').innerHTML=(c.stateHistory||[]).map(h=>`<li><b>${stateLabels[h.state]||h.state}</b> · ${esc(h.at)}<br>${esc(h.note||'')}</li>`).join('')||'<li>이력 없음</li>';const d=drafts[c.candidateId]||{};$('draftState').innerHTML=nextStates(c).map(x=>`<option value="${x}" ${d.state===x?'selected':''}>${stateLabels[x]||x}</option>`).join('');$('draftNote').value=d.note||'';$('modalBack').classList.add('open')}
 $('saveDraft').onclick=()=>{const c=state.current;if(!c)return;drafts[c.candidateId]={state:$('draftState').value,note:$('draftNote').value.trim(),savedAt:new Date().toISOString(),baseState:c.workflowState};localStorage.setItem(draftKey,JSON.stringify(drafts));$('modalBack').classList.remove('open');render()};$('clearDraft').onclick=()=>{if(state.current){delete drafts[state.current.candidateId];localStorage.setItem(draftKey,JSON.stringify(drafts));$('modalBack').classList.remove('open');render()}};$('closeModal').onclick=()=> $('modalBack').classList.remove('open');$('modalBack').onclick=e=>{if(e.target===$('modalBack'))$('modalBack').classList.remove('open')};
 document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tab=b.dataset.tab;state.page=0;resetFilters();render()});
 for(const id of ['search','part','variant','tier','workflow','batch'])$(id).oninput=()=>{state.page=0;render()};$('prev').onclick=()=>{state.page--;render()};$('next').onclick=()=>{state.page++;render()};
 function download(name,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 $('exportBtn').onclick=()=>download('JK_ENG_Phase24_후보와검수이력.json',{manifest:M,candidates,reviewHistory:window.JK_BANK.reviewHistory});$('exportDraftBtn').onclick=()=>download('JK_ENG_Phase24_관리자검토변경안.json',{exportedAt:new Date().toISOString(),automaticApproval:false,drafts});resetFilters();render();
})();
