(() => {
  'use strict';
  const $ = id => document.getElementById(id), params = new URLSearchParams(location.search), replayId = params.get('replayId');
  const qMap = Object.fromEntries(JK_DATA.questions.map(q => [q.id, q])), cMap = Object.fromEntries(JK_DATA.concepts.map(c => [c.id, c]));
  let replay = null, question = null, canvas = null, ctx = null, time = 0, playing = false, raf = 0, lastFrame = 0, speed = 1, steps = [];
  const esc = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function tokenize(s) { return s.match(/[A-Za-z0-9]+(?:['’\-][A-Za-z0-9]+)*|[^\w\s]/g) || []; }
  function renderText() { const tokens = (question.annotationSpec && question.annotationSpec.tokens || []).map(x => x.text); const ts = tokens.length ? tokens : tokenize(question.stem); $('text').innerHTML = ''; ts.forEach((t,i) => { const span = document.createElement('span'); span.className='tok'; span.dataset.index=i; span.textContent=t; if(i && !/^[,.;:?!)]$/.test(t)) $('text').appendChild(document.createTextNode(' ')); $('text').appendChild(span); }); }
  function resize() { const r = $('paper').getBoundingClientRect(), dpr = Math.max(1, Math.min(3, devicePixelRatio || 1)); canvas.width = Math.round(r.width*dpr); canvas.height = Math.round(r.height*dpr); canvas.style.width = r.width+'px'; canvas.style.height = r.height+'px'; ctx.setTransform(dpr,0,0,dpr,0,0); draw(); }
  function tokenMetrics() { const pr=$('paper').getBoundingClientRect(); return [...document.querySelectorAll('.tok')].map((el,i)=>{const r=el.getBoundingClientRect();return{index:i,left:r.left-pr.left,top:r.top-pr.top,right:r.right-pr.left,bottom:r.bottom-pr.top,width:r.width,height:r.height,cx:(r.left+r.right)/2-pr.left,cy:(r.top+r.bottom)/2-pr.top}}); }
  function gapPoint(g) { const m=tokenMetrics(); if(!m.length)return{x:20,y:50}; const cur=m[Math.min(g,m.length-1)]; if(g<=0)return{x:Math.max(8,cur.left-10),y:cur.cy}; const prev=m[g-1]; return Math.abs(prev.cy-cur.cy)<Math.max(prev.height,cur.height)*.7 ? {x:(prev.right+cur.left)/2,y:(prev.cy+cur.cy)/2}:{x:Math.max(8,cur.left-10),y:cur.cy}; }
  function drawStroke(stroke, until) { const pts=(stroke.points||[]).filter(p=>Number(p.t)<=until); if(pts.length<2)return; const r=canvas.getBoundingClientRect(); ctx.save(); ctx.globalCompositeOperation=stroke.tool==='eraser'?'destination-out':'source-over'; ctx.strokeStyle=stroke.tool==='highlighter'?'#d7a900':'#4534b8'; ctx.globalAlpha=stroke.tool==='highlighter'?.25:1; ctx.lineWidth=stroke.tool==='highlighter'?18:3; ctx.lineCap='round'; ctx.lineJoin='round'; for(let i=1;i<pts.length;i++){ctx.beginPath();ctx.moveTo(pts[i-1].x*r.width,pts[i-1].y*r.height);ctx.lineTo(pts[i].x*r.width,pts[i].y*r.height);ctx.stroke()} ctx.restore(); }
  function drawMark(m, auto=false) { const mt=tokenMetrics(), col=auto?'#b44d00':'#4534b8'; ctx.save();ctx.strokeStyle=col;ctx.lineWidth=auto?2.5:3;ctx.setLineDash(auto?[7,5]:[]);ctx.lineCap='round';if(m.type==='slash'){const p=gapPoint(m.gap);ctx.beginPath();ctx.moveTo(p.x-7,p.y+14);ctx.lineTo(p.x+7,p.y-14);ctx.stroke()}else if(m.type==='circle'){const z=mt[m.token];if(z){ctx.beginPath();ctx.ellipse(z.cx,z.cy,z.width/2+6,z.height/2+5,0,0,Math.PI*2);ctx.stroke()}}else if(m.type==='underline'){const a=mt[m.start],b=mt[m.end??m.start];if(a&&b){if(Math.abs(a.cy-b.cy)<a.height){ctx.beginPath();ctx.moveTo(a.left,a.bottom+5);ctx.lineTo(b.right,b.bottom+5);ctx.stroke()}else for(let i=m.start;i<=m.end;i++){const z=mt[i];if(z){ctx.beginPath();ctx.moveTo(z.left,z.bottom+5);ctx.lineTo(z.right,z.bottom+5);ctx.stroke()}}}}ctx.restore(); }
  function uniqueDetected() { const committed=new Set((replay.committedMarks||[]).map(m=>m.type==='slash'?`s${m.gap}`:m.type==='circle'?`c${m.token}`:`u${m.start}-${m.end}`)); return (replay.detectedMarks||[]).filter(m=>!committed.has(m.type==='slash'?`s${m.gap}`:m.type==='circle'?`c${m.token}`:`u${m.start}-${m.end}`)); }
  function draw() { if(!ctx||!replay)return; const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);for(const s of replay.rawStrokes||[])drawStroke(s,time);for(const m of replay.committedMarks||[])if(Number(m.t||0)<=time)drawMark(m,false);for(const m of uniqueDetected())if(Number(m.t||replay.durationMs)<=time)drawMark(m,true);$('scrub').value=Math.min(time,replay.durationMs);$('clock').textContent=`${(time/1000).toFixed(1)} / ${(replay.durationMs/1000).toFixed(1)}초`; }
  function frame(ts) { if(!playing)return; if(!lastFrame)lastFrame=ts; time += (ts-lastFrame)*speed; lastFrame=ts;if(time>=replay.durationMs){time=replay.durationMs;playing=false;$('play').textContent='재생'}draw();if(playing)raf=requestAnimationFrame(frame); }
  function togglePlay(){playing=!playing;$('play').textContent=playing?'일시정지':'재생';lastFrame=0;if(playing){if(time>=replay.durationMs)time=0;raf=requestAnimationFrame(frame)}else cancelAnimationFrame(raf)}
  function buildSteps(){const values=[0];for(const s of replay.rawStrokes||[])for(const p of s.points||[])values.push(Number(p.t)||0);for(const m of [...(replay.committedMarks||[]),...(replay.detectedMarks||[])])values.push(Number(m.t)||0);values.push(replay.durationMs);steps=[...new Set(values.map(x=>Math.round(x)))].sort((a,b)=>a-b)}
  function step(dir){const candidates=dir>0?steps.filter(x=>x>time+1):steps.filter(x=>x<time-1);time=dir>0?(candidates[0]??replay.durationMs):(candidates[candidates.length-1]??0);playing=false;$('play').textContent='재생';draw()}
  function eventLabel(type){return({question_presented:'문항 제시',mark_confirmed:'표식 확정',final_answer:'최종 답안',grading_result:'채점 결과',textbook_return:'교재 복귀',decision_step_answered:'판단 단계',check_question_answered:'확인문제',original_retry:'원문 재도전',replay_saved:'리플레이 저장'}[type]||type)}
  async function boot(){await JK_STORAGE.init();if(!replayId)throw new Error('replayId가 없습니다.');replay=await JK_STORAGE.getReplay(replayId);if(!replay)throw new Error('리플레이를 찾을 수 없습니다.');question=qMap[replay.questionId];if(!question)throw new Error('문항 정보를 찾을 수 없습니다.');canvas=$('canvas');ctx=canvas.getContext('2d');renderText();$('scrub').max=Math.max(1,replay.durationMs);buildSteps();const concept=cMap[question.conceptId];$('meta').innerHTML=`<div><small>문항</small><b>${esc(question.id)}</b></div><div><small>개념</small><b>${esc((concept&&(concept.shortName||concept.name))||question.conceptId)}</b></div><div><small>시도</small><b>${replay.attemptNo}회차</b></div><div><small>과정 점수</small><b>${replay.assessment&&replay.assessment.total!=null?replay.assessment.total+'점':'-'}</b></div>`;$('status').textContent=`정규화 좌표 ${replay.coordinateSpace} · ${replay.rawStrokes.length}개 스트로크 · ${replay.detectedMarks.length}개 판정 표식`;const events=await JK_STORAGE.getEvents({sessionId:replay.sessionId,questionId:replay.questionId});$('timeline').innerHTML=events.map(e=>`<div class="event"><b>${eventLabel(e.type)}</b><small>${new Date(e.timestamp).toLocaleString()}${e.answerCorrect==null?'':` · 정답 ${e.answerCorrect?'O':'X'}`}${e.methodScore==null?'':` · 과정 ${e.methodScore}점`}${e.errorCode?` · ${esc(e.errorCode)}`:''}</small></div>`).join('')||'<div class="event">이력이 없습니다.</div>';resize();addEventListener('resize',resize);$('play').onclick=togglePlay;$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('speed').onchange=e=>speed=Number(e.target.value);$('scrub').oninput=e=>{time=Number(e.target.value);playing=false;$('play').textContent='재생';draw()};}
  boot().catch(e=>$('status').textContent=`불러오기 실패: ${e.message}`);
})();
