(async()=>{'use strict';
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const unwrap=x=>x?.payload||x||null,fmt=n=>Number(n||0).toFixed(1).replace(/\.0$/,''),today=()=>new Date().toISOString().slice(0,10);
 const metric=(label,value)=>`<div class="metric"><b>${esc(value)}</b><span>${esc(label)}</span></div>`;
 const label={NOT_COLLECTED:'실측 없음',APPROVED_NOT_APPLIED:'승인·미적용',ACTIVE_STABILIZING:'안정화 관찰 중',STABLE:'30일 안정',ROLLBACK_RECOMMENDED:'롤백 검토',ROLLED_BACK:'롤백 완료',PENDING:'대기',COMPLETE:'완료',INSUFFICIENT:'자료 부족'};
 try{await JK_AUTH.requireRole('admin')}catch(e){console.warn(e);return}
 await JK_STORAGE.init();
 let state={baseline:null,proposalSet:null,profiles:[],applications:[],observations:[],alerts:[],audits:[],bundle:null,activeProfile:null,activeApplication:null,latestObservation:null};
 function profilePayload(row){return unwrap(row)}
 function appPayload(row){return unwrap(row)}
 async function load(){
   const [baseline,proposalSets,profiles,applications,observations,alerts,audits,bundle]=await Promise.all([
     JK_STORAGE.getBaselineRun(),JK_STORAGE.listDifficultyProposalSets(),JK_STORAGE.listPersonalDifficultyProfiles(),JK_STORAGE.listDifficultyApplications(),JK_STORAGE.listStabilityObservations(),JK_STORAGE.listRegressionAlerts(),JK_STORAGE.listApprovalAudit(),JK_STORAGE.getDiagnosticBundle()
   ]);
   state.baseline=baseline;state.proposalSet=proposalSets.find(x=>unwrap(x)?.actualLearnerDataUsed&&Array.isArray(unwrap(x)?.proposals))||proposalSets[0]||null;
   state.profiles=profiles;state.applications=applications;state.observations=observations;state.alerts=alerts;state.audits=audits;state.bundle=bundle;
   state.activeProfile=profiles.map(x=>({row:x,p:profilePayload(x)})).find(x=>['ACTIVE_STABILIZING','STABLE'].includes(x.p?.status))||null;
   state.activeApplication=applications.map(x=>({row:x,p:appPayload(x)})).find(x=>['ACTIVE_STABILIZING','STABLE','ROLLBACK_RECOMMENDED'].includes(x.p?.status))||null;
   const aid=state.activeApplication?.p?.applicationId;state.latestObservation=observations.map(x=>unwrap(x)).filter(x=>!aid||x.applicationId===aid).sort((a,b)=>Date.parse(b.asOf||0)-Date.parse(a.asOf||0))[0]||null;
   render();
 }
 function approvedProposalCount(){return (unwrap(state.proposalSet)?.proposals||[]).filter(x=>x.status==='approved').length}
 function inferredStatus(){
   if(state.latestObservation?.rollbackRecommended)return 'ROLLBACK_RECOMMENDED';
   if(state.activeApplication)return state.latestObservation?.status||state.activeApplication.p.status;
   if(state.profiles.some(x=>profilePayload(x)?.status==='APPROVED_NOT_APPLIED'))return 'APPROVED_NOT_APPLIED';
   return JK_PHASE27.isApprovedActualBaseline(state.baseline)?'APPROVED_NOT_APPLIED':'NOT_COLLECTED';
 }
 function renderTop(){
   const status=inferredStatus(),b=unwrap(state.baseline),pCount=approvedProposalCount(),profile=state.activeProfile?.p,app=state.activeApplication?.p;
   $('stateBadge').textContent=status;$('stateBadge').className=`pill ${status==='STABLE'?'ok':status==='ROLLBACK_RECOMMENDED'?'bad':'warn'}`;
   $('stateSummary').textContent=status==='NOT_COLLECTED'?'실제 7일 기준선과 승인 제안이 아직 없어 초기 난이도를 유지합니다.':status==='ACTIVE_STABILIZING'?'승인된 개인 난이도를 적용하고 7·14·30일 변화를 관찰 중입니다.':status==='STABLE'?'30일 안정화 기준을 충족했습니다.':status==='ROLLBACK_RECOMMENDED'?'지표 악화가 감지되어 관리자 롤백 검토가 필요합니다.':'적용 가능한 승인 프로필이 준비되었습니다.';
   $('topMetrics').innerHTML=[metric('기준선',b?.status||'NOT_COLLECTED'),metric('충분한 Day',b?.sufficientDays||0),metric('승인 제안',pCount),metric('개인 프로필',state.profiles.length),metric('적용 상태',app?.status||'없음'),metric('실측 자료',b?.actualLearnerDataUsed?'있음':'없음')].join('');
   $('truthStatus').textContent=b?.actualLearnerDataUsed?'실제 학습 기록 기반입니다. 관리자의 명시적 승인 없이는 적용·롤백하지 않습니다.':'현재 실제 학습자 자료가 없습니다. 합성 검증 자료는 운영 상태나 난이도에 반영되지 않습니다.';
 }
 function renderGuardrails(){const g=JK_PHASE27.policy.cumulativeGuardrails||{};$('guardrails').innerHTML=[['1회 단축',`${Math.round(100*g.maximumTimeReductionPerApproval)}%`],['문항 누적',`${Math.round(100*g.maximumCumulativeQuestionReduction)}%`],['개념 누적',`${Math.round(100*g.maximumCumulativeConceptReduction)}%`],['30일 승인',`${g.maximumQuestionReductionApprovalsPer30Days}회`]].map(x=>`<div><b>${x[1]}</b><span class="note">${x[0]}</span></div>`).join('')}
 function renderProfile(){
   const candidate=state.profiles.map(x=>profilePayload(x)).find(x=>x.status==='APPROVED_NOT_APPLIED'),active=state.activeProfile?.p,p=candidate||active;
   $('createProfile').disabled=!(JK_PHASE27.isApprovedActualBaseline(state.baseline)&&approvedProposalCount()>0&&!candidate);
   $('profileStatus').textContent=candidate?'관리자 승인 프로필이 생성되었습니다. 적용 전 스냅샷을 만든 뒤 적용할 수 있습니다.':active?'현재 활성 프로필이 있으므로 새 프로필은 다음 승인 주기에서 생성합니다.':JK_PHASE27.isApprovedActualBaseline(state.baseline)?(approvedProposalCount()?'프로필을 생성할 수 있습니다.':'관리자 승인 난이도 제안이 없습니다.'):'APPROVED_PERSONAL 실제 7일 기준선이 필요합니다.';
   $('profileCard').innerHTML=p?`<div class="status"><b>${esc(p.profileId)}</b><br>상태 ${esc(p.status)} · 문항 ${p.itemCount||Object.keys(p.items||{}).length}개 · 실측 ${p.actualLearnerDataUsed?'예':'아니오'}<br><small>승인 ${esc((p.approvedAt||'').slice(0,16).replace('T',' '))}</small></div>`:'<div class="status warn">생성된 개인 난이도 프로필이 없습니다.</div>';
   $('applyProfile').disabled=!candidate||Boolean(active);
   $('applyStatus').textContent=active?`프로필 ${active.profileId}이 Daily 내부 목표에 적용 중입니다. 학습자에게 목표 초를 표시하지 않습니다.`:candidate?'자동 적용하지 않습니다. 관리자 버튼으로 적용하십시오.':'적용 대기 프로필이 없습니다.';
 }
 function change(v){if(v==null)return '-';const n=Number(v);return `${n>0?'+':''}${fmt(n)}%p`}
 function renderCheckpoints(){
   const app=state.activeApplication?.p,obs=state.latestObservation,cps=obs?.checkpoints||app?.checkpoints||JK_PHASE27.policy.checkpoints.map(x=>({...x,status:'PENDING'}));
   $('checkpoints').innerHTML=cps.map(cp=>{const c=cp.comparison?.changes||{},cls=cp.status==='COMPLETE'?(cp.comparison?.recommendRollback?'bad':'complete'):'';return `<div class="checkpoint ${cls}"><div class="itemTop"><h3>${cp.days}일</h3><span class="pill ${cp.status==='COMPLETE'?'ok':cp.status==='INSUFFICIENT'?'bad':'warn'}">${label[cp.status]||cp.status}</span></div><small>최소 충분 Day ${cp.minimumSufficientDays||'-'}일 · 기한 ${esc(cp.dueDate||'-')}</small><div class="delta"><div><b>${change(c.answerAccuracy)}</b><small>정확도</small></div><div><b>${change(c.processPassRate)}</b><small>과정</small></div><div><b>${change(c.paceOverrunRate)}</b><small>페이스 초과</small></div><div><b>${change(c.recoveryRate)}</b><small>회복</small></div></div></div>`}).join('');
   const next=app?JK_PHASE27.nextCheckpoint(app):null;$('nextCheckpoint').textContent=next?`${next.days}일 · ${next.dueDate}`:'체크포인트 없음';
   $('observationStatus').className=`status ${obs?.rollbackRecommended?'bad':''}`;$('observationStatus').textContent=!app?'적용 이력이 없어 안정화 관찰을 시작하지 않았습니다.':!obs?'적용 후 실제 학습 기록을 분석하면 체크포인트 결과가 생성됩니다.':obs.rollbackRecommended?`롤백 검토 사유: ${(obs.rollbackProposalReason||[]).join(', ')}`:`현재 상태 ${label[obs.status]||obs.status} · 자동 롤백 없음`;
 }
 function renderAlerts(){
   const pending=state.alerts.map(x=>({row:x,p:unwrap(x)})).filter(x=>x.p.status==='pending_admin');$('alertBadge').textContent=`알림 ${pending.length}`;$('alertBadge').className=`pill ${pending.length?'bad':''}`;
   $('alerts').innerHTML=pending.length?pending.map(x=>`<div class="status bad"><b>${esc(x.p.checkpointDays||'-')}일 체크포인트</b><br>${esc((x.p.reasons||[]).join(', '))}<br><small>${esc((x.p.createdAt||'').slice(0,16).replace('T',' '))}</small></div>`).join(''):'<div class="status">현재 관리자 검토 대기 회귀 알림이 없습니다.</div>';
   $('rollback').disabled=!pending.length||!state.activeApplication;
 }
 function renderContext(){
   const d=state.latestObservation?.contextDiagnostics;if(!d||!d.groups){$('contextDiagnostics').innerHTML='<div class="status">분류 가능한 실측 맥락 기록이 없습니다.</div>';return}
   const titles={medicationTiming:'약 복용 시간대',deviceCategory:'기기',interruptionBand:'학습 중단'};
   $('contextDiagnostics').innerHTML=Object.entries(d.groups).map(([group,rows])=>`<div class="contextBox"><b>${titles[group]||group}</b>${Object.values(rows).length?Object.values(rows).map(r=>`<div class="contextRow"><span>${esc(r.key)}</span><span>${r.days}일 · 정확도 ${fmt(r.answerAccuracy)}%</span></div>`).join(''):'<span class="note">기록 없음</span>'}</div>`).join('')||'<div class="status">기록 없음</div>';
 }
 function renderAudit(){
   const own=state.audits.filter(x=>String(x.type||'').includes('difficulty')||String(x.type||'').includes('stability')||String(x.type||'').includes('regression')||String(x.type||'').includes('learning_context')).slice(0,60);
   $('auditRows').innerHTML=own.length?own.map(x=>`<tr><td>${esc((x.at||x.createdAt||'').slice(0,16).replace('T',' '))}</td><td>${esc(x.type)}</td><td>${esc(x.entityId)}</td><td>${esc(JSON.stringify(x.payload||{}).slice(0,180))}</td></tr>`).join(''):'<tr><td colspan="4" class="note">Phase 27 감사 이력이 없습니다.</td></tr>';
 }
 function render(){renderTop();renderGuardrails();renderProfile();renderCheckpoints();renderAlerts();renderContext();renderAudit()}
 $('createProfile').onclick=async()=>{try{if(!confirm('실제 기준선과 승인 제안으로 개인 난이도 프로필을 생성합니까?'))return;const previous=state.activeProfile?.p||state.profiles.map(x=>profilePayload(x)).find(x=>x.status==='STABLE')||null;const history=state.applications.map(x=>appPayload(x)).flatMap(a=>Object.values(a?.changeHistory||{}));const profile=JK_PHASE27.createApprovedProfile({proposalSet:state.proposalSet,baseline:state.baseline,previousProfile:previous,applicationHistory:history,adminConfirmed:true});await JK_STORAGE.savePersonalDifficultyProfile(profile);await JK_STORAGE.appendApprovalAudit({type:'personal_difficulty_profile_created',entityId:profile.profileId,payload:{itemCount:profile.itemCount,actualLearnerDataUsed:true}});$('profileStatus').textContent='승인 프로필을 생성했습니다.';await load()}catch(e){$('profileStatus').textContent=e.message}}
 $('applyProfile').onclick=async()=>{try{const candidate=state.profiles.map(x=>profilePayload(x)).find(x=>x.status==='APPROVED_NOT_APPLIED');if(!candidate)throw new Error('적용 대기 프로필이 없습니다.');if(!confirm('적용 전 스냅샷을 만들고 개인 난이도를 Daily에 적용합니까?'))return;const previous=state.activeProfile?.p||null;const out=JK_PHASE27.activateProfile({profile:candidate,previousProfile:previous,baseline:state.baseline,adminConfirmed:true});await JK_STORAGE.saveBankSnapshot({snapshotId:out.snapshot.snapshotId,kind:'difficulty_pre_apply',payload:out.snapshot,createdAt:out.snapshot.createdAt});await JK_STORAGE.savePersonalDifficultyProfile(out.profile);await JK_STORAGE.saveDifficultyApplication(out.application);JK_PHASE27.saveActiveProfile(out.profile);await JK_STORAGE.updateSettings({activeDifficultyProfileId:out.profile.profileId,activeDifficultyApplicationId:out.application.applicationId});await JK_STORAGE.appendApprovalAudit({type:'personal_difficulty_applied',entityId:out.application.applicationId,payload:{profileId:out.profile.profileId,snapshotId:out.snapshot.snapshotId,automaticApplication:false}});$('applyStatus').textContent='관리자 승인 개인 난이도를 적용했습니다.';await load()}catch(e){$('applyStatus').textContent=e.message}}
 $('refreshObservation').onclick=async()=>{try{const app=state.activeApplication?.p;if(!app)throw new Error('활성 적용 이력이 없습니다.');const b=state.bundle,obs=JK_PHASE27.evaluateApplication({application:app,baseline:state.baseline,events:b.events,sessions:b.sessions,reports:b.dailyReports,questions:JK_DATA.questions,asOf:new Date().toISOString(),actualLearnerData:true});await JK_STORAGE.saveStabilityObservation(obs);const cpMap=Object.fromEntries((obs.checkpoints||[]).map(x=>[x.days,x]));const nextApp={...app,status:obs.status,checkpoints:(app.checkpoints||[]).map(x=>({...x,status:cpMap[x.days]?.status||x.status,observedAt:cpMap[x.days]?.status==='COMPLETE'?obs.asOf:x.observedAt})),updatedAt:new Date().toISOString()};await JK_STORAGE.saveDifficultyApplication(nextApp);if(obs.status==='STABLE'&&state.activeProfile?.p){const stable={...state.activeProfile.p,status:'STABLE',updatedAt:new Date().toISOString()};await JK_STORAGE.savePersonalDifficultyProfile(stable);JK_PHASE27.saveActiveProfile(stable)}if(obs.rollbackRecommended){const exists=state.alerts.some(x=>{const p=unwrap(x);return p.applicationId===app.applicationId&&p.status==='pending_admin'});if(!exists){const alert=JK_PHASE27.createRegressionAlert(obs);await JK_STORAGE.saveRegressionAlert(alert);await JK_STORAGE.appendApprovalAudit({type:'regression_rollback_proposed',entityId:alert.alertId,payload:{applicationId:app.applicationId,reasons:alert.reasons,automaticRollback:false}})}}await JK_STORAGE.appendApprovalAudit({type:'stability_checkpoint_saved',entityId:obs.observationId,payload:{applicationId:app.applicationId,status:obs.status,latestCheckpointDays:obs.latestCheckpointDays}});$('observationStatus').textContent='현재 실제 기록으로 안정화 상태를 재분석했습니다.';await load()}catch(e){$('observationStatus').textContent=e.message}}
 $('rollback').onclick=async()=>{try{const app=state.activeApplication?.p,pending=state.alerts.map(x=>({row:x,p:unwrap(x)})).find(x=>x.p.status==='pending_admin');if(!app||!pending)throw new Error('롤백 검토 대상이 없습니다.');if(!confirm('적용 전 스냅샷으로 롤백합니까? 이 작업은 자동으로 실행되지 않으며 관리자 확인을 기록합니다.'))return;const sw=await JK_STORAGE.getBankSnapshot(app.preApplicationSnapshotId),snap=unwrap(sw);const result=JK_PHASE27.rollbackApplication({application:app,snapshot:snap,adminConfirmed:true});if(state.activeProfile?.p){await JK_STORAGE.savePersonalDifficultyProfile({...state.activeProfile.p,status:'ROLLED_BACK',updatedAt:new Date().toISOString()})}if(result.restoredProfile)await JK_STORAGE.savePersonalDifficultyProfile(result.restoredProfile);await JK_STORAGE.saveDifficultyApplication(result.application);await JK_STORAGE.updateRegressionAlert(pending.p.alertId,'resolved_rolled_back','관리자 확인 롤백');await JK_STORAGE.updateSettings({activeDifficultyProfileId:result.restoredProfile?.profileId||null,activeDifficultyApplicationId:null});await JK_STORAGE.appendApprovalAudit({type:'personal_difficulty_rolled_back',entityId:app.applicationId,payload:{snapshotId:snap.snapshotId,restoredProfileId:result.restoredProfile?.profileId||null,automaticRollback:false}});$('rollbackStatus').textContent='관리자 확인으로 적용 전 상태를 복원했습니다.';await load()}catch(e){$('rollbackStatus').textContent=e.message}}
 $('saveContext').onclick=async()=>{try{const date=$('contextDate').value||today(),dayId=`DAY-${date}`,old=await JK_STORAGE.getDailyReport(dayId)||{dayId,date,learnerId:'single-learner'};const n=Math.max(0,Number($('interruptionCount').value||0)),band=n===0?'none':n<=1?'low':n<=3?'medium':'high';const report=await JK_STORAGE.saveDailyReport({...old,dayId,date,medicationTiming:$('medicationTiming').value,deviceCategory:$('deviceCategory').value,interruptionCount:n,interruptionBand:band,contextNote:$('contextNote').value.trim(),contextUpdatedAt:new Date().toISOString()});await JK_STORAGE.appendApprovalAudit({type:'learning_context_saved',entityId:dayId,payload:{medicationTiming:report.medicationTiming,deviceCategory:report.deviceCategory,interruptionBand:report.interruptionBand,usedForDifficultyDecision:false}});$('contextStatus').textContent='학습 맥락을 저장했습니다. 난이도 자동 결정에는 사용하지 않습니다.';await load()}catch(e){$('contextStatus').textContent=e.message}}
 $('contextDate').value=today();await load();
})();
