(async()=>{'use strict';const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let state,localDiag,localHealth,serverObs,serverTimeline=[],bundle,support={status:'NOT_CREATED'};
async function swInfo(){try{const r=await fetch('./sw.js',{cache:'no-store'}),t=await r.text(),m=/VERSION='([^']+)'/.exec(t);return{version:m?.[1]||'',matches:m?.[1]==='29.0'}}catch(_){return{version:'',matches:false}}}
async function collectLocal(){state=JK_STORAGE.getSnapshot();const queue=await JK_STORAGE.listSyncQueue();const d=await JK_STORAGE.diagnose();const sw=await swInfo();localDiag=JK_PHASE29.buildClientDiagnostic({snapshot:state,queue,cloudStatus:JK_CLOUD.getStatus(),serviceWorker:sw,storage:{mode:d.mode,indexedDbOk:d.readWrite&&d.mode==='indexeddb',quotaRatio:d.quota&&d.usage?d.usage/d.quota:0},navigatorLike:navigator,online:navigator.onLine});localHealth=JK_PHASE29.evaluateClientHealth(localDiag)}
async function loadServer(){serverObs=JK_PHASE29.normalizeObservability({});serverTimeline=[];try{serverObs=await JK_CLOUD.getObservability();const t=await JK_CLOUD.getSupportTimeline(200);serverTimeline=t.timeline||[]}catch(e){$('statusMessage').textContent=`서버 관측 미연결: ${e.message||e}`}}
function render(){const m=serverObs?.metrics||{};$('serverStatus').textContent=serverObs.status;$('serverStatus').className=serverObs.status;$('alertStatus').textContent=serverObs.alertDelivery?.status||'NOT_CONFIGURED';$('alertStatus').className=serverObs.alertDelivery?.status||'NOT_CONFIGURED';$('localSync').textContent=`${localDiag.syncQueue.queued} 대기`;$('swStatus').textContent=localDiag.serviceWorker.matches?'29.0':'불일치';$('mDb').textContent=m.databaseOk===true?'정상':m.databaseOk===false?'오류':'미연결';$('mBackup').textContent=m.backupAgeHours==null?'-':`${m.backupAgeHours.toFixed(1)}h`;$('mAuth').textContent=m.authFailures15m??'-';$('mLatency').textContent=m.syncP95Ms==null?'-':`${Math.round(m.syncP95Ms)}ms`;$('mQueue').textContent=m.syncQueueQueued??localDiag.syncQueue.queued;$('mLease').textContent=m.leaseConflicts15m??(localDiag.lease.conflict?1:0);$('mDevices').textContent=m.reportingDevices??'-';$('mSw').textContent=m.serviceWorkerMismatches??(localDiag.serviceWorker.matches?0:1);const alerts=[...(serverObs.alerts||[]),...(localHealth.alerts||[])];$('alerts').innerHTML=alerts.length?alerts.map(a=>`<div class="alert ${esc(a.severity)}"><b>${esc(a.code)}</b><div>${esc(a.message)}</div><small>제안: ${esc(a.recommendation)} · 자동조치 없음</small></div>`).join(''):'<div class="alert"><b>현재 감지된 경고 없음</b><small>서버 미연결 상태에서는 서버 지표가 평가되지 않습니다.</small></div>';$('supportCode').textContent=support.code||'NOT CREATED';$('codeMeta').textContent=support.expiresAt?`만료 ${new Date(support.expiresAt).toLocaleString()} · 일회성 · 세션 미발급`:'서버 연결과 관리자 인증 후 생성할 수 있습니다.';const p=bundle?.privacy||{containsPin:false,containsSessionToken:false,containsRawHandwriting:false,containsRawAnswerText:false,deviceIdsAliased:true};$('privacyGrid').innerHTML=Object.entries(p).filter(([k])=>k!=='excluded').map(([k,v])=>`<div><span>${esc(k)}</span><b class="${v===false||v===true&&k==='deviceIdsAliased'?'ok':'bad'}">${esc(v)}</b></div>`).join('');const localAudits=Object.values(state.approvalAudit||{}),tl=JK_PHASE29.mergeTimeline({localAudits,serverTimeline});$('timeline').innerHTML=tl.length?tl.map(x=>`<div class="event"><span>${esc(new Date(x.at).toLocaleString())}</span><b>${esc(x.category)}</b><span>${esc(x.action)} <small>(${esc(x.source)})</small></span></div>`).join(''):'<div class="note">기록된 지원 이벤트가 없습니다.</div>'}
async function refresh(){await collectLocal();await loadServer();bundle=JK_PHASE29.buildPrivacyBundle({local:{snapshot:state,queue:await JK_STORAGE.listSyncQueue(),cloudStatus:JK_CLOUD.getStatus(),serviceWorker:localDiag.serviceWorker,storage:localDiag.storage,navigatorLike:navigator},serverObservability:serverObs,localAudits:Object.values(state.approvalAudit||{}),serverTimeline});render()}
function download(name,data){const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function sendDiagnostic(){try{await JK_CLOUD.reportDeviceDiagnostic(localDiag);$('statusMessage').textContent='개인정보 최소화 기기 진단을 서버에 보고했습니다.';await refresh()}catch(e){$('statusMessage').textContent=`보고 실패: ${e.message||e}`}}
async function exportBundle(){try{let out=bundle;try{out=await JK_CLOUD.getDiagnosticBundle()}catch(_){}if(JK_PHASE29.containsForbidden(out))throw new Error('금지 필드 감지');download(`JK_ENG_Phase29_Diagnostic_${new Date().toISOString().slice(0,10)}.json`,out);$('statusMessage').textContent='개인정보 최소화 진단 번들을 내보냈습니다.'}catch(e){$('statusMessage').textContent=`번들 생성 실패: ${e.message||e}`}}
async function createCode(){try{support=JK_PHASE29.validateSupportCodeResult(await JK_CLOUD.createSupportCode(600));await JK_STORAGE.appendApprovalAudit({type:'support_code_created',entityId:support.supportId,payload:{expiresAt:support.expiresAt,diagnosticOnly:true,grantsSession:false}});render()}catch(e){$('statusMessage').textContent=`지원 코드 생성 실패: ${e.message||e}`}}
await JK_AUTH.requireRole('admin');state=await JK_STORAGE.init();$('refreshAll').onclick=refresh;$('sendDiagnostic').onclick=sendDiagnostic;$('exportBundle').onclick=exportBundle;$('createCode').onclick=createCode;$('copyCode').onclick=()=>support.code&&navigator.clipboard?.writeText(support.code);await refresh();})().catch(e=>{console.error(e);document.body.insertAdjacentHTML('beforeend',`<pre style="color:#b00;padding:20px">${String(e.message||e)}</pre>`)})
