const VERSION='maintenance-v1.2.0';
const CACHE='jk-maintenance-v1.2.0';
const PREVIOUS_CACHE='jk-maintenance-v1.0.0';
const CONTROL_CACHE='jk-release-control';
const CONTROL_KEY='./__jk_active_release__';
const MANIFEST='./asset-integrity-manifest-maintenance-v1.json';
const API_PATHS=['/__/' ,'/auth/','/devices/','/admin/','/sync','/snapshot','/lease','/health','/integrity','/diagnostics/','/support/'];
const hex=buffer=>[...new Uint8Array(buffer)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function verifiedFetch(url,expected){const response=await fetch(url,{cache:'reload'});if(!response.ok)throw new Error(`asset fetch failed ${response.status}: ${url}`);if(expected){const digest=hex(await crypto.subtle.digest('SHA-256',await response.clone().arrayBuffer()));if(digest!==expected)throw new Error(`asset integrity mismatch: ${url}`)}return response}
async function setActive(cacheName){const c=await caches.open(CONTROL_CACHE);await c.put(CONTROL_KEY,new Response(cacheName,{headers:{'Content-Type':'text/plain'}}))}
async function getActive(){const c=await caches.open(CONTROL_CACHE),r=await c.match(CONTROL_KEY);const name=r?await r.text():CACHE;return (await caches.has(name))?name:CACHE}
async function installAssets(){const manifestResponse=await fetch(MANIFEST,{cache:'no-store'});if(!manifestResponse.ok)throw new Error('asset integrity manifest unavailable');const manifest=await manifestResponse.clone().json();if(manifest.format!=='JK_ENG_ASSET_INTEGRITY'||manifest.version!==VERSION)throw new Error('asset integrity manifest version mismatch');const cache=await caches.open(CACHE);await cache.put(MANIFEST,manifestResponse);const assets=(manifest.assets||[]).filter(item=>item.critical);for(let i=0;i<assets.length;i+=10){await Promise.all(assets.slice(i,i+10).map(async item=>{const url=`./${item.path}`;const response=await verifiedFetch(url,item.critical?item.sha256:null);await cache.put(url,response)}))}}
self.addEventListener('install',event=>event.waitUntil(installAssets().then(async()=>{const clients=await self.clients.matchAll({includeUncontrolled:true});clients.forEach(c=>c.postMessage({type:'JK_SW_UPDATE_READY',version:VERSION}));self.skipWaiting()})));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>(k.startsWith('jk-phase')||k.startsWith('jk-maintenance'))&&![CACHE,PREVIOUS_CACHE].includes(k)).map(k=>caches.delete(k)));await setActive(CACHE);await self.clients.claim();const previousCacheRetained=await caches.has(PREVIOUS_CACHE);const clients=await self.clients.matchAll({includeUncontrolled:true});clients.forEach(c=>c.postMessage({type:'JK_SW_ACTIVATED',version:VERSION,previousCacheRetained}))})()));
self.addEventListener('message',event=>event.waitUntil((async()=>{const d=event.data||{};if(d.type==='SKIP_WAITING')return self.skipWaiting();if(d.type==='ROLLBACK_TO_PREVIOUS'){const ok=await caches.has(PREVIOUS_CACHE);if(ok)await setActive(PREVIOUS_CACHE);event.source?.postMessage({type:'JK_SW_ROLLBACK_RESULT',ok,version:ok?'maintenance-v1.0.0':VERSION});return}if(d.type==='RESTORE_CURRENT'){const ok=await caches.has(CACHE);if(ok)await setActive(CACHE);event.source?.postMessage({type:'JK_SW_ROLLBACK_RESULT',ok,version:VERSION})}})()));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;if(API_PATHS.some(path=>url.pathname===path||url.pathname.startsWith(path)))return;event.respondWith((async()=>{const active=await getActive(),cache=await caches.open(active);if(event.request.mode==='navigate'&&active===PREVIOUS_CACHE){return (await cache.match(event.request))||(await cache.match('./index.html'))||fetch(event.request)}if(event.request.mode==='navigate'){try{const response=await fetch(event.request);if(response.ok)cache.put(event.request,response.clone());return response}catch(_){return (await cache.match(event.request))||(await cache.match('./index.html'))}}const cached=await cache.match(event.request);if(cached)return cached;try{const response=await fetch(event.request);if(response.ok)cache.put(event.request,response.clone());return response}catch(_){return new Response('offline',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}})}})())});
